[package]
name = "zeroship-worker"
version = "0.1.0"
edition = "2021"
description = "zeroship data plane — V8 compute worker"

[[bin]]
name = "zeroship-worker"
path = "src/main.rs"

[dependencies]
zeroship-core = { workspace = true }
zeroship-bundle = { workspace = true }
zeroship-runtime = { workspace = true }
zeroship-plugin-db = { workspace = true }
ntex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
compio = { workspace = true }
futures = { workspace = true }
mimalloc = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
url = { workspace = true }
base64 = { workspace = true }
cyper = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
