ALTER TABLE zeroship.gateway_sessions DROP CONSTRAINT gateway_sessions_app_id_fkey;
DROP TRIGGER IF EXISTS authz_decisions_block_truncate ON zeroship.authz_decisions;
DROP TRIGGER IF EXISTS authz_decisions_block_delete ON zeroship.authz_decisions;
DROP TRIGGER IF EXISTS authz_decisions_block_update ON zeroship.authz_decisions;
DROP FUNCTION IF EXISTS zeroship.authz_decisions_block_tamper();
DROP TABLE zeroship.authz_decisions;
DROP TABLE zeroship.oauth_grants;
DROP TABLE zeroship.oauth_clients;
DROP TABLE zeroship.platform_policies;
DROP TABLE zeroship.permission_tokens;
DROP TABLE zeroship.app_members;
DROP TRIGGER IF EXISTS app_audit_block_truncate ON zeroship.app_audit;
DROP TRIGGER IF EXISTS app_audit_block_delete ON zeroship.app_audit;
DROP TRIGGER IF EXISTS app_audit_block_update ON zeroship.app_audit;
DROP FUNCTION IF EXISTS zeroship.app_audit_block_tamper();
DROP TABLE zeroship.app_audit;
DROP TABLE zeroship.payouts;
DROP TABLE zeroship.creator_account_history;
DROP TABLE zeroship.creator_accounts;
DROP TABLE zeroship.app_env_expose;
DROP TABLE zeroship.app_secrets;
DROP TABLE zeroship.app_vars;
DROP TABLE zeroship.app_usage_history;
DROP TABLE zeroship.app_usage;
DROP TABLE zeroship.apps;
