DO $rb$ BEGIN IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='zeroship_control') THEN EXECUTE 'REVOKE ALL ON zeroship.payout_failures FROM zeroship_control'; EXECUTE 'REVOKE ALL ON zeroship.connect_checkout_failures FROM zeroship_control'; END IF; END $rb$;
ALTER DOMAIN zeroship.billing_notification_kind DROP CONSTRAINT billing_notification_kind_check;
ALTER DOMAIN zeroship.billing_notification_kind ADD CONSTRAINT billing_notification_kind_check CHECK (VALUE IN ('payment_failed','past_due','suspended','recovered','invoice_finalized','refunded','disputed','spend_warn','spend_degrade','spend_block'));
DROP TRIGGER IF EXISTS connect_checkout_failures_immutable_trg ON zeroship.connect_checkout_failures;
DROP FUNCTION IF EXISTS zeroship.connect_checkout_failures_immutable();
DROP INDEX IF EXISTS zeroship.connect_checkout_failures_creator_idx;
DROP TABLE zeroship.connect_checkout_failures;
DROP TRIGGER IF EXISTS payout_failures_immutable_trg ON zeroship.payout_failures;
DROP FUNCTION IF EXISTS zeroship.payout_failures_immutable();
DROP INDEX IF EXISTS zeroship.payout_failures_creator_idx;
DROP TABLE zeroship.payout_failures;
DROP INDEX IF EXISTS zeroship.credit_ledger_refund_clawback_note_idx;
ALTER TABLE zeroship.credit_ledger DROP CONSTRAINT credit_ledger_grant_ref;
ALTER TABLE zeroship.credit_ledger ADD CONSTRAINT credit_ledger_grant_ref CHECK ((kind IN ('consumed','void_reversal') AND consumed_from_grant_id IS NOT NULL) OR (kind NOT IN ('consumed','void_reversal') AND consumed_from_grant_id IS NULL));
ALTER TABLE zeroship.credit_ledger DROP CONSTRAINT credit_ledger_kind_sign;
ALTER TABLE zeroship.credit_ledger ADD CONSTRAINT credit_ledger_kind_sign CHECK ((kind = 'consumed' AND amount_cents < 0) OR (kind <> 'consumed' AND amount_cents > 0));
ALTER DOMAIN zeroship.credit_entry_kind DROP CONSTRAINT credit_entry_kind_check;
ALTER DOMAIN zeroship.credit_entry_kind ADD CONSTRAINT credit_entry_kind_check CHECK (VALUE IN ('grant','promo','goodwill','refund_to_credit','consumed','void_reversal'));
DROP FUNCTION IF EXISTS zeroship.refunds_no_over_refund() CASCADE;
DROP FUNCTION IF EXISTS zeroship.refunds_immutable() CASCADE;
SELECT 1;
ALTER TABLE zeroship.refunds DROP COLUMN failed_at;
ALTER DOMAIN zeroship.refund_status DROP CONSTRAINT refund_status_check;
ALTER DOMAIN zeroship.refund_status ADD CONSTRAINT refund_status_check CHECK (VALUE IN ('pending','issued'));
