[package]
name = "zeroship-auth"
version = "0.1.0"
edition = "2021"
description = "zeroship auth service — user management, OAuth2, consent"

[[bin]]
name = "zeroship-auth"
path = "src/main.rs"

[dependencies]
zeroship-core = { workspace = true }
zeroship-pg = { workspace = true }
ntex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
bcrypt = { workspace = true }
jsonwebtoken = { workspace = true }
mimalloc = { workspace = true }

[lints]
workspace = true
