[package]
name = "appbase-compiler"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "appbase-compile"
path = "src/main.rs"

[lib]
name = "appbase_compiler"
path = "src/lib.rs"

[dependencies]
swc_core = { version = ">=59.0.1", features = [
    "ecma_parser",
    "ecma_ast",
    "ecma_visit",
    "ecma_codegen",
    "ecma_transforms_react",
    "common",
] }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
