[package]
name = "zeroship-gateway"
version = "0.1.0"
edition = "2021"
description = "zeroship gateway — auth, rate limit, proxy to workers"

[[bin]]
name = "zeroship-gate"
path = "src/main.rs"

[dependencies]
zeroship-core = { workspace = true }
ntex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
compio = { workspace = true }
url = { workspace = true }
xxhash-rust = { version = "0.8", features = ["xxh3"] }
httparse = { workspace = true }
mimalloc = { workspace = true }

[lints]
workspace = true
