[workspace]
members = [
    "crates/common",
    "crates/bundle",
    "crates/runtime",
    "crates/runtime-macros",
    "crates/compiler",
    "crates/platform",
    "crates/cli",
    "crates/pg",
    "crates/control",
    "crates/worker",
    "crates/gateway",
]
resolver = "3"
exclude = ["crates/runtime/benches/ntex-bench"]

[workspace.lints.rust]
unsafe_code = "deny"
unused_must_use = "deny"
missing_debug_implementations = "warn"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
