// A `uuidV4()` default is generated BY THE DATABASE, and the deprecated
// `genRandomUuid()` alias is checksum-identical to it.
//
// `writing-migrations.md` makes two claims worth separating:
//
//   "Use `now()`, `uuidV4()`, and (on PostgreSQL 18+) `uuidV7()` when the database
//    should choose the value at apply time."
//   "`genRandomUuid()` remains as a deprecated source alias for `uuidV4()` and
//    records the same exact expression."
//
// The first is a data-correctness property with the F631 failure shape: if the
// helper were SAMPLED at authoring time rather than recorded as an expression, the
// DDL would carry one baked literal and every row would receive the SAME uuid. That
// migration applies cleanly and the damage appears later as a unique-violation, or
// as rows that silently alias each other. So the assertion is DISTINCTNESS across
// inserted rows, plus the stored default being a call rather than a literal.
//
// The second is an operational promise about UPGRADING OFF the deprecated alias. A
// team doing that edits an already-applied migration file, and the only question
// that matters is whether the edit trips checksum drift and blocks every subsequent
// deploy. "Records the same exact expression" is precisely the claim that it does
// not.
//
// THE THIRD TEST IS WHAT MAKES THE SECOND MEAN ANYTHING. `skipped` on re-apply is
// also what a journal that ignored checksums entirely would print. So a substantive
// edit to the same applied migration must be REFUSED with checksum drift — proving
// the check is live and that the alias swap passing it is a real result rather than
// an absent check.
//
// GATE: `ZERO_MIGRATE_TEST_PG_URL`. Database-generated uuid defaults are
// PostgreSQL-only here.

import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

import { pgUrl } from "./live-db.js";

// The host suite's addon is resolved and freshness-checked in one place.
import "./addon.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const CLI_BIN = resolve(HERE, "../../src/cli-bin.ts");
const ABI = process.platform === "linux" ? "-gnu" : "";
const ADDON_PATH = resolve(
  HERE,
  `../../../../crates/zero-migrate-node/zero-migrate-node.${process.platform}-${process.arch}${ABI}.node`,
);

const OWNER_APP = "app_uuiddefault";
const TABLE = "uu_t";

function uniqueNamespace(prefix: string): string {
  return `${prefix}_${Date.now().toString(36)}_${Math.floor(Math.random() * 1e6).toString(36)}`;
}

function scaffold(): string {
  const work = mkdtempSync(join(HERE, "uuiddef-"));
  mkdirSync(join(work, "migrations"));
  writeFileSync(
    join(work, "policy.toml"),
    `policy_version = 1

[[grant]]
key = "schema.cross_schema"
value = true
scope = "all"

[[grant]]
key = "schema.create_table"
value = true
scope = "all"
`,
  );
  writeFileSync(join(work, "registry.json"), JSON.stringify({ [TABLE]: OWNER_APP }));
  return work;
}

/** Rewrites the ONE migration file, so a later call simulates an author editing a
 *  migration that has already been applied. */
function writeMigration(work: string, helper: string, extraColumn = false): void {
  writeFileSync(
    join(work, "migrations", "20260101000000_a.ts"),
    `import { table, t, ${helper} } from "zero-migrate";
export const name = "a";
export default {
  schema() {
    table("${TABLE}").create({
      columns: {
        id: t.int().notNull(),
        u: t.uuid().notNull().default(${helper}()),${extraColumn ? "\n        extra: t.int()," : ""}
      },
      primaryKey: ["id"],
    });
  },
};
`,
  );
}

function apply(work: string, namespace: string): { code: number | null; text: string } {
  const result = spawnSync(
    process.execPath,
    [
      "--import", "tsx", CLI_BIN, "apply", "--approve",
      "--dir", join(work, "migrations"),
      "--database-url", pgUrl(),
      "--policy", join(work, "policy.toml"),
      "--registry", join(work, "registry.json"),
      "--schema", namespace,
      "--owner-app", OWNER_APP,
    ],
    {
      cwd: work,
      encoding: "utf8",
      env: { ...process.env, ZERO_MIGRATE_ADDON_PATH: ADDON_PATH, DATABASE_URL: "" },
    },
  );
  return {
    code: result.status,
    text: `${result.stdout ?? ""}\n${result.stderr ?? ""}`.replace(/^WARNING.*$/gm, "").trim(),
  };
}

test("a uuidV4 default is generated per row by the database", async (ctx) => {
  if (!process.env.ZERO_MIGRATE_TEST_PG_URL) {
    ctx.skip("ZERO_MIGRATE_TEST_PG_URL unset");
    return;
  }
  const pg = await import("pg");
  const client = new pg.Client({ connectionString: pgUrl() });
  await client.connect();
  const namespace = uniqueNamespace("uuiddef");
  const work = scaffold();
  try {
    writeMigration(work, "uuidV4");
    await client.query(`CREATE SCHEMA "${namespace}"`);
    const applied = apply(work, namespace);
    assert.equal(applied.code, 0, `the migration must apply; ${applied.text}`);

    // A CALL, not a literal. A sampled uuid would appear here as a quoted constant.
    const stored = (
      await client.query(
        `SELECT column_default FROM information_schema.columns
          WHERE table_schema = $1 AND table_name = $2 AND column_name = 'u'`,
        [namespace, TABLE],
      )
    ).rows[0].column_default;
    assert.match(
      String(stored),
      /gen_random_uuid\(\)/,
      `the default must be a database call; got ${JSON.stringify(stored)}`,
    );

    for (let id = 1; id <= 5; id += 1) {
      await client.query(`INSERT INTO "${namespace}"."${TABLE}" (id) VALUES ($1)`, [id]);
    }
    const values = (
      await client.query(`SELECT u::text AS u FROM "${namespace}"."${TABLE}"`)
    ).rows.map((row: { u: string }) => row.u);

    assert.equal(
      new Set(values).size,
      5,
      "each row must get its own uuid -- a helper sampled at authoring time would " +
        "bake one literal into the DDL and give every row the same value, which " +
        "applies cleanly and surfaces much later",
    );
  } finally {
    await client
      .query(
        `DROP SCHEMA IF EXISTS "${namespace}" CASCADE;
         DROP SCHEMA IF EXISTS "${namespace}_migrations" CASCADE`,
      )
      .catch(() => {});
    await client.end().catch(() => {});
    rmSync(work, { recursive: true, force: true });
  }
});

test("swapping the deprecated genRandomUuid alias for uuidV4 does not drift", async (ctx) => {
  if (!process.env.ZERO_MIGRATE_TEST_PG_URL) {
    ctx.skip("ZERO_MIGRATE_TEST_PG_URL unset");
    return;
  }
  const pg = await import("pg");
  const client = new pg.Client({ connectionString: pgUrl() });
  await client.connect();
  const namespace = uniqueNamespace("uuidalias");
  const work = scaffold();
  try {
    writeMigration(work, "genRandomUuid");
    await client.query(`CREATE SCHEMA "${namespace}"`);
    assert.equal(apply(work, namespace).code, 0, "the deprecated alias must apply");

    // The upgrade an author actually performs: edit the applied migration in place.
    writeMigration(work, "uuidV4");
    const rerun = apply(work, namespace);
    assert.equal(
      rerun.code,
      0,
      `swapping the alias must not block later deploys; ${rerun.text}`,
    );
    assert.match(
      rerun.text,
      /"skipped":\[/,
      `and the migration must be skipped as already applied; ${rerun.text}`,
    );
    assert.doesNotMatch(rerun.text, /checksum drift/, "no drift may be reported");
  } finally {
    await client
      .query(
        `DROP SCHEMA IF EXISTS "${namespace}" CASCADE;
         DROP SCHEMA IF EXISTS "${namespace}_migrations" CASCADE`,
      )
      .catch(() => {});
    await client.end().catch(() => {});
    rmSync(work, { recursive: true, force: true });
  }
});

/** Without this, the test above is equally consistent with a journal that never
 *  compares checksums at all. */
test("CONTROL: a substantive edit to the same applied migration IS refused", async (ctx) => {
  if (!process.env.ZERO_MIGRATE_TEST_PG_URL) {
    ctx.skip("ZERO_MIGRATE_TEST_PG_URL unset");
    return;
  }
  const pg = await import("pg");
  const client = new pg.Client({ connectionString: pgUrl() });
  await client.connect();
  const namespace = uniqueNamespace("uuiddrift");
  const work = scaffold();
  try {
    writeMigration(work, "uuidV4");
    await client.query(`CREATE SCHEMA "${namespace}"`);
    assert.equal(apply(work, namespace).code, 0, "the first apply must succeed");

    // Same file, same helper, one added column.
    writeMigration(work, "uuidV4", true);
    const rerun = apply(work, namespace);
    assert.equal(rerun.code, 1, `a real edit must be refused; ${rerun.text}`);
    assert.match(
      rerun.text,
      /checksum drift/,
      `and refused BY THE CHECKSUM, which is what proves the check is live; ${rerun.text}`,
    );
  } finally {
    await client
      .query(
        `DROP SCHEMA IF EXISTS "${namespace}" CASCADE;
         DROP SCHEMA IF EXISTS "${namespace}_migrations" CASCADE`,
      )
      .catch(() => {});
    await client.end().catch(() => {});
    rmSync(work, { recursive: true, force: true });
  }
});
