/**
 * gen-types orchestrator — the in-process schema-artifact emitter the
 * vite-plugin links (no CLI subprocess).
 *
 * Two sources, one Rust renderer (the `zeroship-migrate-node` `genArtifacts` verb):
 *  - MANUAL — {@link genTypesFromSchemaFile}: evaluate a committed `schema.ts`
 *    (`@zeroship/db` builders) → `CollectionDescriptorDto[]` → `genArtifacts`.
 *  - GENERATED — {@link genTypesFromMigrations}: record `op.*` migrations →
 *    IR envelopes → `genArtifacts`.
 *
 * Both write `schema.runtime.json` (the v2 RuntimeSchemaDescriptor packed into
 * the `.zship`). They differ only in `env.db.ts`:
 *  - GENERATED renders an inline `const schema = { ... } as const` literal of
 *    `@zeroship/db` builder calls from that descriptor (migrations are the
 *    source of truth, so there is no `schema.ts` to point at).
 *  - MANUAL writes an AUGMENTATION over the author's `schema.ts`: the author
 *    owns `schema.ts`; `env.db.ts` just re-exports its typing.
 *
 * Neither uses the engine's own `envDbTs`: that string round-trips the folded IR
 * back into the *migration authoring* DSL (`from "@zeroship/migrate"`), which is the
 * engine's artifact, not a creator app's type surface.
 *
 * `--check` (`{ check: true }`) regenerates in memory and diffs against the
 * committed artifacts — a HARD drift gate, no write. There is no CLI to be
 * absent, so drift is always caught.
 */

import { promises as fs } from "node:fs";
import { dirname, relative, resolve } from "node:path";

import { loadMigrateAddon, type GenArtifactsReply } from "./addon.js";
import { CONFINED_SCHEMA_EMIT_CEILING_TOML } from "./confined-ceiling.js";
import { discoverMigrations, recordMigration } from "./recorder.js";
import { evaluateSchemaModule, schemaModuleToDescriptors } from "./manual.js";
import {
  GENERATED_ENV_DB_BANNER,
  renderEnvAugmentation,
  renderGeneratedEnvDb,
  type GeneratedDatabase,
  type RuntimeDescriptor,
} from "./render-env-db.js";

/** The two committed artifact filenames gen-types emits. */
export const RUNTIME_DESCRIPTOR_FILE = "schema.runtime.json";
/** The generated `env.db` typings module. A real `.ts` (NOT a `.d.ts`): the
 *  generated variant carries `const schema = <builder calls> as const`, which is
 *  illegal in a `.d.ts` ambient context. */
export const ENV_DB_FILE = "env.db.ts";

/** The banner every MANUAL `env.db.ts` carries (the GENERATED variant's banner is
 *  rendered by the Rust verb). */
const MANUAL_ENV_DB_BANNER =
  "// GENERATED by @zeroship/vite-plugin gen-types (manual schema source) — DO NOT EDIT.\n" +
  "//\n" +
  "// The typed `env.db` surface, augmented over the author's `schema.ts`.\n" +
  "// `schema.ts` is the source of truth; this file re-exports its typing so the\n" +
  "// worker's `env.db` is `Db<typeof schema>`. Re-run gen-types after schema\n" +
  "// changes; the gen-types --check CI gate fails if this file drifts.\n";

/**
 * The tag a `MigrationSourceError` carries. A STRING on the instance rather
 * than an `instanceof` check: the dev server, the build and the CLI each load
 * this module through a different entry, and a duplicated module instance would
 * silently make `instanceof` false — which fails in the direction that looks
 * safe (a creator's typo classified as a platform fault, killing dev).
 */
const MIGRATION_SOURCE_FAULT = "migration-source";

/**
 * A fault in the CREATOR's migration source: their `.ts` failed to build, or
 * the engine rejected the schema it declares. Distinguished from every other
 * throw out of gen-types, all of which are OUR bug or their environment's:
 * a missing native addon, an engine panic, an unparseable descriptor, an
 * unwritable output dir.
 *
 * The distinction has to be CARRIED, not derived. An engine-rejected migration
 * and an esbuild failure both arrive as a plain `Error` with `code ===
 * undefined`, and so do `addonLoadError`, the missing-`runtimeJson` arm, and
 * `parseRuntimeDescriptor`. `code` therefore separates neither class from the
 * other; only two producers set one at all, and both are ours or the
 * environment's: `EACCES` from the write, and `ERR_MODULE_NOT_FOUND`-class
 * codes from the recorder.
 *
 * AN ENGINE PANIC IS NOT IN THAT CLASS. At our vendored pin a panic never
 * reaches this catch at all -- it aborts the process, because the
 * `zeroship-migrate-node` export carries no `catch_unwind` and a Rust panic
 * crossing an `extern "C"` shim aborts rather than becoming a catchable Error.
 * So the loud arm below is REAL for every fault that arrives as a JS Error --
 * a missing addon, an unparseable descriptor, an unwritable dir, a caller-shape
 * bug -- and INERT for a panic, which kills the process before any of our code
 * runs. A core dump is arguably loud enough; what it is not is our code
 * deciding.
 *
 * WHERE THIS TAG STOPS, and it is a boundary not a guarantee. The tag covers
 * the SYNC verb, `genArtifacts`, because every creator-content fault comes back
 * through its soft `{ ok:false }` arm and `unwrap` converts it here. That soft
 * return is a GUARDED CONTRACT upstream, not a lucky sample: the export's own
 * doc comment promises `ok=false` + `error` "on a malformed/incoherent source
 * ... (never a throw)", so it is safe to build an allow-list on. A change that
 * made a malformed source throw would fail that upstream contract test instead
 * of silently reaching us.
 *
 * The ASYNC verb, `applyIr`, does NOT behave that way. It rejects at the
 * napi boundary, and `Error::from_reason` hardcodes `Status::GenericFailure`,
 * so a CREATOR's invalid migration arrives from the engine indistinguishable
 * from an engine panic and carrying no tag of ours.
 *
 * That costs nothing TODAY because the only caller of `applyIr` from here is
 * `cli/migrate-dev.ts`, which has no try/catch, so both classes propagate
 * equally loudly. It stops being free the moment the apply is chained into the
 * dev server. Under this allow-list, a creator's own bad migration would
 * then land in the LOUD arm and refuse to boot. Whoever wires that up owes
 * either a tag at that boundary or a deliberate decision that refusing to boot
 * on an invalid migration is the behaviour they want.
 */
export class MigrationSourceError extends Error {
  readonly zsFaultClass = MIGRATION_SOURCE_FAULT;
  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = "MigrationSourceError";
  }
}

/** Is `e` a creator-migration fault (as opposed to a platform/environment one)? */
export function isMigrationSourceError(e: unknown): boolean {
  return (
    typeof e === "object" &&
    e !== null &&
    (e as { zsFaultClass?: unknown }).zsFaultClass === MIGRATION_SOURCE_FAULT
  );
}

/**
 * What both sources need to know beyond where the schema comes from.
 *
 * `label` and `primary` are REQUIRED and carry no default. They are not
 * recoverable from the schema - a fold says what the collections are and
 * nothing about which of an app's databases holds them - and the emitted
 * module keys `EnvDatabases` on the label, so a guess here is `env.databases`
 * typed under the wrong name. Every caller reads them from the same place,
 * `zeroship.jsonc` through `project-config`.
 */
export interface GenTypesOptions extends GeneratedDatabase {
  /** Regenerate in memory and diff against the committed artifacts, never
   *  writing: the hard drift gate. */
  check?: boolean;
}

/** Options common to both sources. */
export interface GenTypesResult {
  /** `"written"` (regenerated) or `"checked"` (drift gate passed, no write). */
  status: "written" | "checked";
  /**
   * The artifact filenames relative to the out dir, in emit order.
   *
   * The two schema artifacts, whichever source produced them. The recorded
   * migration set is NOT among them: it is built in memory by
   * {@link recordApplyRequest} when `zeroship migrate` asks for it, and is
   * never written to disk.
   */
  files: readonly string[];
}

/**
 * MANUAL source. Evaluate `schemaTsPath` → descriptors → `genArtifacts`, then
 * write (or `--check`) `schema.runtime.json` + an augmentation `env.db.ts`.
 */
export async function genTypesFromSchemaFile(
  schemaTsPath: string,
  outDir: string,
  opts: GenTypesOptions,
): Promise<GenTypesResult> {
  const declared = await evaluateSchemaModule(schemaTsPath);
  const descriptors = schemaModuleToDescriptors(declared);

  const reply = loadMigrateAddon().genArtifacts({
    descriptors,
    projectSchema: "public",
    // The engine is preset-free: the CALLER supplies the confined injection shape
    // (the 7 system columns + [id] PK + system indexes). The SAME ceiling on both
    // sources keeps the descriptor + envelope outputs byte-identical.
    charterLayers: [CONFINED_SCHEMA_EMIT_CEILING_TOML],
    // `postgres` is the platform tier; the SQLite dev tier consumes the same
    // descriptor for typing only. Required by the engine.
    //
    // THIS CONSTANT IS SAFE BY A CONDITION, NOT BY CONSTRUCTION. The descriptor
    // is NOT dialect-neutral: the dialect does not change how a column RENDERS
    // here, but it changes WHICH COLUMNS EXIST, before rendering, because the
    // fold selects `Op::Dialectal` legs. A history authored with
    // `dialect({ pg, mysql })` yields a different column set per target, and the
    // descriptor lists columns.
    //
    // The condition: NO migration in this repo authors a dialectal leg. Re-check
    // with a grep for BOTH spellings over every migration `.ts` in the tree -
    // `dialect(` (the engine's own) and `emitDialectal` (ours) - because grepping
    // only the engine's spelling would miss every leg a creator could author
    // through our surface. Run it under `bash -c`: an unquoted multi-root scope
    // does not word-split in zsh, so the whole sweep collapses to one bogus path
    // and reports a confident zero.
    //
    // That grep is the whole check; the other routes a leg could take are
    // closed:
    //   - OUR recorder cannot accept a hand-written envelope. `discoverMigrations`
    //     gates on `MIGRATION_TS_RE`, so a committed `.json` beside the migrations
    //     is silently skipped; envelopes exist only as in-memory values built from
    //     a `.ts`, and nothing in gen-types reads one from disk.
    //   - THE DESCRIPTOR LANE cannot carry one at all: there is no `Dialectal` in
    //     the engine's `render/declarative.rs` at our pin.
    //   - NOTHING UPSTREAM CONSTRUCTS ONE outside tests.
    // So a future reader re-checking this only has to re-run the migration grep
    // above.
    //
    // Nothing enforces it. `emitDialectal` is exposed on our own op surface
    // (packages/zero-migrate/src/ops.ts), so the first migration to use it makes
    // this constant silently wrong for the SQLite dev tier - a column set that
    // the dev database does not have. If you are adding a dialectal leg, this
    // line is the thing that breaks, and it will not tell you.
    dialect: "postgres",
  });
  const runtimeJson = unwrap(reply, "manual schema source");

  const envDbTs = renderManualEnvDb(outDir, schemaTsPath, opts);
  return emit(outDir, envDbTs, runtimeJson, opts.check ?? false);
}

/** One recorded migration, named the way the migration service journals it. */
export interface RecordedDocument {
  /** `<stem>.ir.json`, from the migration's own filename. */
  filename: string;
  /** The recorded IR envelope (`{ ir_version, name, ops }`). */
  body: Awaited<ReturnType<typeof recordMigration>>;
}

/** One fold of one migrations directory: the documents and the descriptor the
 *  SAME `genArtifacts` call rendered from them. */
export interface FoldedMigrations {
  documents: RecordedDocument[];
  /** The v2 RuntimeSchemaDescriptor, as the bytes that reach the packer. */
  runtimeJson: string;
}

/**
 * Record every `.ts` migration under `migrationsDir` and render the runtime
 * descriptor from them, in ONE `genArtifacts` call.
 *
 * The single call is the ordering anchor. Both consumers — the artifact emitter
 * below and {@link recordApplyRequest}, which builds the migration service's
 * apply body — read the documents and the descriptor out of this one reply, so
 * a descriptor hash taken here always names exactly this document set.
 */
export async function foldMigrations(migrationsDir: string): Promise<FoldedMigrations> {
  // Recording EVALUATES the creator's `.ts`, so everything that throws here is
  // their source: an unresolvable import, a syntax error, a DSL guard. Tagged
  // so the dev server can keep serving through it — see `MigrationSourceError`.
  let envelopes;
  // Recorded with their filename stems, not through `recordMigrationsDir`: the
  // apply request identifies each document by `<stem>.ir.json`, and the stem is
  // what the migration service journals a version under. Dropping it here would
  // mean re-deriving it later from something that is not the filename.
  let documents: RecordedDocument[];
  try {
    const discovered = await discoverMigrations(migrationsDir);
    documents = [];
    for (const m of discovered) {
      documents.push({ filename: `${m.stem}.ir.json`, body: await recordMigration(m.path) });
    }
    envelopes = documents.map((d) => d.body);
  } catch (cause) {
    throw new MigrationSourceError(
      `gen-types: a migration under ${migrationsDir} failed to load — ${(cause as Error)?.message ?? String(cause)}`,
      { cause },
    );
  }

  const reply = loadMigrateAddon().genArtifacts({
    envelopes,
    projectSchema: "public",
    // The engine is preset-free: the CALLER supplies the confined injection shape.
    // The pure-JS recorder emits RAW author-only ops; this ceiling injects the 7
    // system columns + [id] PK + system indexes at resolve time, matching the
    // descriptor path so both sources stay byte-identical.
    charterLayers: [CONFINED_SCHEMA_EMIT_CEILING_TOML],
    // Must match the MANUAL call above: the two sources are required to produce
    // byte-identical output, so a dialect skew between them would break that
    // contract silently rather than loudly.
    dialect: "postgres",
  });
  return { documents, runtimeJson: unwrap(reply, "generated migration source") };
}

/**
 * GENERATED source. Fold every `.ts` migration under `migrationsDir`, then write
 * (or `--check`) BOTH the inline `env.db.ts` literal + `schema.runtime.json`.
 * No subprocess.
 */
export async function genTypesFromMigrations(
  migrationsDir: string,
  outDir: string,
  opts: GenTypesOptions,
): Promise<GenTypesResult> {
  const { runtimeJson } = await foldMigrations(migrationsDir);
  // The typed surface is rendered HERE, off the runtime descriptor - the engine's
  // own `envDbTs` re-authors the fold in the migration DSL, which a deployed app
  // neither depends on nor gets `env.db` typing from.
  const envDbTs = renderGeneratedEnvDb(parseRuntimeDescriptor(runtimeJson), opts);
  return emit(outDir, envDbTs, runtimeJson, opts.check ?? false);
}

/** Unwrap a `genArtifacts` reply, turning the soft `{ ok:false, error }` arm into
 *  a thrown build error and asserting `runtimeJson` is present. */
function unwrap(reply: GenArtifactsReply, source: string): string {
  if (!reply.ok) {
    // The engine REJECTED what the creator declared (a duplicate column, an
    // unknown table, a facet the charter forbids). Their fault, so tagged.
    throw new MigrationSourceError(
      `gen-types: ${source} failed to render — ${reply.error ?? "unknown error"}`,
    );
  }
  if (reply.runtimeJson === undefined) {
    // Deliberately NOT tagged: `ok` with no payload is an emitter bug, ours.
    throw new Error(`gen-types: ${source} produced no schema.runtime.json`);
  }
  return reply.runtimeJson;
}

/** Parse the emitted `schema.runtime.json` back into the descriptor the
 *  `env.db.ts` renderer reads. A parse failure here is an emitter bug, so it
 *  surfaces as a build error rather than a silently empty schema. */
function parseRuntimeDescriptor(runtimeJson: string): RuntimeDescriptor {
  let parsed: unknown;
  try {
    parsed = JSON.parse(runtimeJson);
  } catch (cause) {
    throw new Error(
      `gen-types: the generated source emitted an unparseable ${RUNTIME_DESCRIPTOR_FILE}`,
      { cause },
    );
  }
  if (parsed === null || typeof parsed !== "object") {
    throw new Error(
      `gen-types: the generated source emitted a non-object ${RUNTIME_DESCRIPTOR_FILE}`,
    );
  }
  return parsed as RuntimeDescriptor;
}

/**
 * Render the MANUAL `env.db.ts` augmentation: import the author's `schema` and
 * declare this database's entry on `EnvDatabases` (plus `Env.db` when it is
 * the primary). The import path is relative from the out dir to `schema.ts`,
 * extension-stripped, always `./`-anchored and POSIX-slashed for a stable,
 * cross-platform module specifier.
 *
 * The augmentation block itself comes from `renderEnvAugmentation`, the same
 * producer the generated source uses: the two schema sources differ in where
 * `schema` comes from and in nothing else.
 */
function renderManualEnvDb(
  outDir: string,
  schemaTsPath: string,
  database: GeneratedDatabase,
): string {
  let rel = relative(resolve(outDir), resolve(schemaTsPath));
  rel = rel.replace(/\.ts$/, "");
  rel = rel.split(/[\\/]/).join("/");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return (
    MANUAL_ENV_DB_BANNER +
    `import { type Db } from "@zeroship/db";\n` +
    `import { schema } from "${rel}";\n\n` +
    renderEnvAugmentation(database, "Db<typeof schema>") +
    `export {};\n`
  );
}

/**
 * Emit or check the two artifacts. When `check`, regenerate in memory and diff
 * against the committed files — a hard error naming the first drifted file.
 * Otherwise write both (creating the out dir).
 */
async function emit(
  outDir: string,
  envDbTs: string,
  runtimeJson: string,
  check: boolean,
): Promise<GenTypesResult> {
  const envPath = resolve(outDir, ENV_DB_FILE);
  const jsonPath = resolve(outDir, RUNTIME_DESCRIPTOR_FILE);
  const files = [ENV_DB_FILE, RUNTIME_DESCRIPTOR_FILE];

  if (check) {
    await assertNoDrift(envPath, envDbTs, ENV_DB_FILE);
    await assertNoDrift(jsonPath, runtimeJson, RUNTIME_DESCRIPTOR_FILE);
    return { status: "checked", files };
  }

  const targets: Array<[string, string]> = [
    [envPath, ENV_DB_FILE],
    [jsonPath, RUNTIME_DESCRIPTOR_FILE],
  ];
  for (const [path, file] of targets) {
    await assertGeneratedArtifactMayBeReplaced(path, file);
  }

  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(envPath, envDbTs, "utf8");
  await fs.writeFile(jsonPath, runtimeJson, "utf8");
  return { status: "written", files };
}

async function assertGeneratedArtifactMayBeReplaced(path: string, file: string): Promise<void> {
  // Concurrent HMR folds can expose a briefly truncated generated file. Retry
  // only while its bytes are changing; a stable unknown owner is still refused.
  let previous: string | undefined;
  let stableReads = 0;
  for (let attempt = 0; attempt < 6; attempt += 1) {
    let stat;
    try {
      stat = await fs.lstat(path);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
      throw error;
    }
    if (stat.isSymbolicLink() || !stat.isFile()) {
      throw new Error(`gen-types: refusing to overwrite non-generated ${file} at ${path}`);
    }

    const existing = await fs.readFile(path, "utf8");
    if (isGeneratedArtifact(file, existing)) return;
    stableReads = existing === previous ? stableReads + 1 : 0;
    if (stableReads >= 2 || attempt === 5) break;
    previous = existing;
    await new Promise((done) => setTimeout(done, 10));
  }
  throw new Error(`gen-types: refusing to overwrite creator-owned ${file} at ${path}`);
}

function isGeneratedArtifact(file: string, existing: string): boolean {
  if (file === ENV_DB_FILE) {
    return existing.startsWith(MANUAL_ENV_DB_BANNER) ||
      existing.startsWith(GENERATED_ENV_DB_BANNER);
  }
  return file === RUNTIME_DESCRIPTOR_FILE && isRuntimeDescriptorArtifact(existing);
}

/**
 * Is this file one WE wrote, as opposed to something a creator hand-authored?
 *
 * Deliberately version-AGNOSTIC: any numeric `version` over a `collections` record is
 * ours. Pinning this to the current version looks tighter and is actively wrong, because
 * the recogniser gates OVERWRITING - so a version bump would make every committed
 * artifact unrecognisable, and `gen-types` would refuse to regenerate the very files the
 * bump had just made stale.
 *
 * "Is this file ours" and "is this file CURRENT" are different questions. The second one
 * belongs to the drift gate (`--check`), which compares bytes and has a fresh render to
 * compare against; this one only has the file.
 */
function isRuntimeDescriptorArtifact(text: string): boolean {
  const parsed = parseObject(text);
  return typeof parsed?.version === "number" && isRecord(parsed.collections);
}

function parseObject(text: string): Record<string, unknown> | null {
  try {
    const parsed: unknown = JSON.parse(text);
    return isRecord(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value != null && typeof value === "object" && !Array.isArray(value);
}

/** Assert the committed artifact byte-matches the freshly-generated one. */
async function assertNoDrift(
  path: string,
  fresh: string,
  file: string,
): Promise<void> {
  let committed: string;
  try {
    committed = await fs.readFile(path, "utf8");
  } catch {
    throw new Error(
      `gen-types --check: ${file} is missing at ${path} — run gen-types to generate it`,
    );
  }
  if (committed !== fresh) {
    throw new Error(
      `gen-types --check: ${file} is STALE — regenerate it (the committed artifact ` +
        `drifted from the schema source).\n${firstDivergence(committed, fresh)}`,
    );
  }
}

/** A short human-readable preview of the first line that diverges. */
function firstDivergence(a: string, b: string): string {
  const al = a.split("\n");
  const bl = b.split("\n");
  const n = Math.max(al.length, bl.length);
  for (let i = 0; i < n; i++) {
    if (al[i] !== bl[i]) {
      return (
        `  first divergence at line ${i + 1}:\n` +
        `  - committed: ${JSON.stringify(al[i] ?? "<missing>")}\n` +
        `  + fresh:     ${JSON.stringify(bl[i] ?? "<missing>")}`
      );
    }
  }
  return "  (files differ in trailing content)";
}

export { dirname as _dirname };
