/**
 * gen-types orchestrator — the in-process schema-artifact emitter the
 * vite-plugin links (no CLI subprocess).
 *
 * Two sources, one Rust renderer (the `zeroship-migrate-node` `genArtifacts` verb):
 *  - MANUAL — {@link genTypesFromSchemaFile}: evaluate a committed `schema.ts`
 *    (`@zeroship/db` builders) → `CollectionDescriptorDto[]` → `genArtifacts`.
 *  - GENERATED — {@link genTypesFromMigrations}: record `op.*` migrations →
 *    IR envelopes → `genArtifacts`.
 *
 * Both write `schema.runtime.json` (the v2 RuntimeSchemaDescriptor packed into
 * the `.zship`). They differ only in `env.db.ts`:
 *  - GENERATED renders an inline `const schema = { ... } as const` literal of
 *    `@zeroship/db` builder calls from that descriptor (migrations are the
 *    source of truth, so there is no `schema.ts` to point at).
 *  - MANUAL writes an AUGMENTATION over the author's `schema.ts`: the author
 *    owns `schema.ts`; `env.db.ts` just re-exports its typing.
 *
 * Neither uses the engine's own `envDbTs`: that string round-trips the folded IR
 * back into the *migration authoring* DSL (`from "@zeroship/migrate"`), which is the
 * engine's artifact, not a creator app's type surface.
 *
 * `--check` (`{ check: true }`) regenerates in memory and diffs against the
 * committed artifacts — a HARD drift gate, no write. There is no CLI to be
 * absent, so drift is always caught.
 */

import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import { dirname, relative, resolve } from "node:path";

import { loadMigrateAddon, type GenArtifactsReply } from "./addon.js";
import { CONFINED_SCHEMA_EMIT_CEILING_TOML } from "./confined-ceiling.js";
import { discoverMigrations, recordMigration } from "./recorder.js";
import { evaluateSchemaModule, schemaModuleToDescriptors } from "./manual.js";
import {
  GENERATED_ENV_DB_BANNER,
  renderGeneratedEnvDb,
  type RuntimeDescriptor,
} from "./render-env-db.js";

/** The two committed artifact filenames gen-types emits. */
export const RUNTIME_DESCRIPTOR_FILE = "schema.runtime.json";
/**
 * The recorded migration set, as the migration service's apply-request body.
 *
 * Emitted ONLY by the generated (migrations-authored) source - a manual
 * `schema.ts` app has no migrations to record. `zeroship migrate` posts this
 * file verbatim; keeping the whole envelope (`{ kind, documents }`) rather than
 * a bare array means the CLI never has to know the wire shape, so a change to
 * `ApplyMigrationsRequest` moves this emitter and nothing else.
 *
 * It is emitted here, beside the other two, rather than into `dist/`, because
 * all three are the SAME fold of the SAME `migrations/*.ts`. Splitting them
 * across two output dirs is how they drift.
 */
export const MIGRATIONS_IR_FILE = "migrations.ir.json";
/** The generated `env.db` typings module. A real `.ts` (NOT a `.d.ts`): the
 *  generated variant carries `const schema = <builder calls> as const`, which is
 *  illegal in a `.d.ts` ambient context. */
export const ENV_DB_FILE = "env.db.ts";

/** The banner every MANUAL `env.db.ts` carries (the GENERATED variant's banner is
 *  rendered by the Rust verb). */
const MANUAL_ENV_DB_BANNER =
  "// GENERATED by @zeroship/vite-plugin gen-types (manual schema source) — DO NOT EDIT.\n" +
  "//\n" +
  "// The typed `env.db` surface, augmented over the author's `schema.ts`.\n" +
  "// `schema.ts` is the source of truth; this file re-exports its typing so the\n" +
  "// worker's `env.db` is `Db<typeof schema>`. Re-run gen-types after schema\n" +
  "// changes; the gen-types --check CI gate fails if this file drifts.\n";

/**
 * The tag a `MigrationSourceError` carries. A STRING on the instance rather
 * than an `instanceof` check: the dev server, the build and the CLI each load
 * this module through a different entry, and a duplicated module instance would
 * silently make `instanceof` false — which fails in the direction that looks
 * safe (a creator's typo classified as a platform fault, killing dev).
 */
const MIGRATION_SOURCE_FAULT = "migration-source";

/**
 * A fault in the CREATOR's migration source: their `.ts` failed to build, or
 * the engine rejected the schema it declares. Distinguished from every other
 * throw out of gen-types, all of which are OUR bug or their environment's:
 * a missing native addon, an engine panic, an unparseable descriptor, an
 * unwritable output dir.
 *
 * The distinction has to be CARRIED, not derived. Measured 2026-08-11 across
 * four fault classes: an engine-rejected migration and an esbuild failure both
 * arrive as a plain `Error` with `code === undefined`, and so — by reading —
 * do `addonLoadError`, the missing-`runtimeJson` arm below, and
 * `parseRuntimeDescriptor`. `code` therefore separates neither class from the
 * other; only two of the eight producers set one at all, and both are ours or
 * the environment's: `EACCES` from the write, and `ERR_MODULE_NOT_FOUND`-class
 * codes from the recorder. See task #269.
 *
 * AN ENGINE PANIC IS NOT IN THAT TABLE, and an earlier version of this comment
 * wrongly put it there with `GenericFailure`. At OUR PIN a panic never reaches
 * this catch at all -- it aborts the process. Verified in our own
 * `third_party/zero-migrate` @ cb1bcb59: `catch_unwind` appears ZERO times in
 * the whole `zeroship-migrate-node` crate src, and the export is a bare
 * `#[napi(js_name = "genArtifacts")]` (bridge.rs:132; that same grep returning
 * line 132 is the positive control that the file was read). Without
 * `catch_unwind` a Rust panic crossing an `extern "C"` shim aborts rather than
 * becoming a catchable Error.
 *
 * The upstream fix (`bc4d1c9b`, "a panicking export throws instead of killing
 * the Node process") is NOT in our object store and NOT an ancestor of our pin
 * -- checked, not assumed. It postdates cb1bcb59 by about ten hours on the same
 * day, which is exactly the window where "they fixed it" and "we have it" come
 * apart; task #29 records the same shape. Whether to bump the pin is an
 * operator call (see task #271); the range is unaudited.
 *
 * So the loud arm below is REAL for every fault that arrives as a JS Error --
 * a missing addon, an unparseable descriptor, an unwritable dir, a caller-shape
 * bug -- and INERT for a panic, which kills the process before any of our code
 * runs. A core dump is arguably loud enough; what it is not is our code
 * deciding.
 *
 * WHERE THIS TAG STOPS, and it is a boundary not a guarantee. The tag covers
 * the SYNC verb, `genArtifacts`, because every creator-content fault comes back
 * through its soft `{ ok:false }` arm and `unwrap` converts it here. Measured
 * 2026-08-11 at the decode boundary itself, which is the arm most likely to
 * reject rather than return: a non-object envelope, an unknown op token, a
 * missing-field envelope and a malformed JSON string ALL returned
 * `ok:false, error:"envelope[N] is not a valid IR document: ..."`. None threw.
 *
 * That soft return is a GUARDED CONTRACT upstream, not four lucky samples,
 * which is what makes it safe to build an allow-list on. Checked at OUR OWN
 * vendored pin (`third_party/zero-migrate` @ cb1bcb59) rather than taken on
 * report, because an upstream guarantee is only worth what the pin we compile
 * against actually contains: `bridge.rs:129-131`, the doc comment ON the
 * `genArtifacts` export, promises `ok=false` + `error` "on a malformed/incoherent
 * source ... (never a throw)", and `api.rs:452`
 * `gen_artifacts_from_a_malformed_envelope_fails_soft` asserts `!reply.ok` for an
 * envelope whose `ops` is not an array. A change that made a malformed source
 * throw fails that test upstream instead of silently reaching us.
 *
 * (zero-migrate reported this as ZERO-MIGRATE-2026-08-11-011, citing different
 * line numbers and different prose -- their tree is AHEAD of this pin. Grepping
 * for their sentence here returns nothing while the contract is plainly present
 * under other words, so re-check this by concept, not by their quote.)
 *
 * The ASYNC verb, `applyIrSqlite`, does NOT behave that way. It rejects at the
 * napi boundary, and `Error::from_reason` hardcodes `Status::GenericFailure`,
 * so a CREATOR's invalid migration arrives from the engine indistinguishable
 * from an engine panic and carrying no tag of ours. (Established by
 * zero-migrate, ZERO-MIGRATE-2026-08-11-010, with a live rejection.)
 *
 * That costs nothing TODAY because the only caller of `applyIrSqlite` is
 * `cli/migrate-dev.ts`, which has no try/catch, so both classes propagate
 * equally loudly. It stops being free the moment the apply is chained into the
 * dev server -- which `docs/proposals/2026-08-09-dev-sqlite-migration-apply-ahead-of-runtime.md`
 * proposes doing. Under this allow-list, a creator's own bad migration would
 * then land in the LOUD arm and refuse to boot. Whoever wires that up owes
 * either a tag at that boundary or a deliberate decision that refusing to boot
 * on an invalid migration is the behaviour they want.
 */
export class MigrationSourceError extends Error {
  readonly zsFaultClass = MIGRATION_SOURCE_FAULT;
  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = "MigrationSourceError";
  }
}

/** Is `e` a creator-migration fault (as opposed to a platform/environment one)? */
export function isMigrationSourceError(e: unknown): boolean {
  return (
    typeof e === "object" &&
    e !== null &&
    (e as { zsFaultClass?: unknown }).zsFaultClass === MIGRATION_SOURCE_FAULT
  );
}

/** Options common to both sources. */
export interface GenTypesResult {
  /** `"written"` (regenerated) or `"checked"` (drift gate passed, no write). */
  status: "written" | "checked";
  /**
   * The artifact filenames relative to the out dir, in emit order.
   *
   * Always the two schema artifacts; plus `migrations.ir.json` when the source
   * was migrations (the manual `schema.ts` source has none to record), which is
   * why this is no longer a fixed-length tuple.
   */
  files: readonly string[];
}

/**
 * MANUAL source. Evaluate `schemaTsPath` → descriptors → `genArtifacts`, then
 * write (or `--check`) `schema.runtime.json` + an augmentation `env.db.ts`.
 */
export async function genTypesFromSchemaFile(
  schemaTsPath: string,
  outDir: string,
  opts: { check?: boolean } = {},
): Promise<GenTypesResult> {
  const declared = await evaluateSchemaModule(schemaTsPath);
  const descriptors = schemaModuleToDescriptors(declared);

  const reply = loadMigrateAddon().genArtifacts({
    descriptors,
    projectSchema: "public",
    // The engine is preset-free: the CALLER supplies the confined injection shape
    // (the 7 system columns + [id] PK + system indexes). The SAME ceiling on both
    // sources keeps the descriptor + envelope outputs byte-identical.
    charterLayers: [CONFINED_SCHEMA_EMIT_CEILING_TOML],
    // `postgres` is the platform tier; the SQLite dev tier consumes the same
    // descriptor for typing only. Required by the engine since the vendored pin
    // moved.
    //
    // THIS CONSTANT IS SAFE BY A CONDITION, NOT BY CONSTRUCTION, and the comment
    // that used to sit here got that wrong. It claimed the descriptor is
    // "dialect-neutral - it carries types, idPrefix and mask facets, never DDL".
    // The second half is true; the first half does not follow from it and is
    // false in general. The dialect does not change how a column RENDERS here -
    // it changes WHICH COLUMNS EXIST, before rendering, because the fold selects
    // `Op::Dialectal` legs. A history authored with `dialect({ pg, mysql })`
    // yields a different column set per target, and the descriptor lists columns.
    // (Established by zero-migrate, ZERO-MIGRATE-2026-08-10-192, citing the
    // `dialect` field contract and two live tests that fold one history under two
    // dialects and match each against that database's real catalog.)
    //
    // The condition: NO migration in this repo authors a dialectal leg.
    // Re-measured 2026-08-11 across ALL 17 migration `.ts` files in the live
    // tree - db/migrations-ts/, the four examples/*/migrations/, and
    // packages/create-zeroship-app/template/migrations/, which the previous
    // 16-file scope omitted. Zero hits for BOTH spellings: `dialect(` (the
    // engine's own) and `emitDialectal` (ours, ops.ts:525). Grepping only the
    // engine's spelling would miss every leg a creator could actually author
    // through our surface, which is the one that matters here. Positive
    // control: `table(` in the same scope, same tool, 456 hits.
    //
    // Run under `bash -c`, not this shell: an unquoted multi-root $SCOPE does
    // not word-split in zsh, so the whole sweep collapses to one bogus path and
    // reports a confident zero. The first attempt did exactly that and reported
    // "0 files in scope" alongside its zeros, which is the only reason it was
    // caught.
    //
    // While that holds, folding through `postgres` is exactly right.
    //
    // AND THAT GREP IS THE WHOLE CHECK - there is no second door, which is what
    // makes re-verifying this cheap. Three independent facts close the other
    // routes a leg could take in:
    //   - OUR recorder cannot accept a hand-written envelope. `discoverMigrations`
    //     gates on `MIGRATION_TS_RE` (recorder.ts:37), so a committed `.json`
    //     beside the migrations is silently skipped; envelopes exist only as
    //     in-memory values built from a `.ts`, and nothing in gen-types reads one
    //     from disk. Verified by me.
    //   - THE DESCRIPTOR LANE cannot carry one at all: zero `Dialectal` in the
    //     engine's `render/declarative.rs` at our pin cb1bcb59 (positive control:
    //     316 `fn ` in the same file). Verified by me, at OUR pin rather than
    //     upstream's.
    //   - NOTHING UPSTREAM CONSTRUCTS ONE outside tests: 61 `Op::Dialectal` sites
    //     in `crates/`, 3 construction-shaped, all 3 inside `#[cfg(test)]`
    //     modules. Reported by zero-migrate (ZERO-MIGRATE-2026-08-11-015) with
    //     counts and line numbers, after they corrected their OWN earlier
    //     "verified" on it, which had been inferred from directory names. Taken
    //     from them, not re-read by me.
    // So a future reader re-checking this only has to re-run the migration grep
    // above. They do not have to wonder about generated artifacts or the other
    // `genArtifacts` source.
    //
    // Nothing enforces it. `emitDialectal` is exposed on our own op surface
    // (packages/zero-migrate/src/ops.ts), so the first migration to use it makes this
    // constant silently wrong for the SQLite dev tier - a column set that the dev
    // database does not have. If you are adding a dialectal leg, this line is the
    // thing that breaks, and it will not tell you.
    dialect: "postgres",
  });
  const runtimeJson = unwrap(reply, "manual schema source");

  const envDbTs = renderManualEnvDb(outDir, schemaTsPath);
  return emit(outDir, envDbTs, runtimeJson, opts.check ?? false);
}

/**
 * GENERATED source. Record every `.ts` migration under `migrationsDir` →
 * envelopes → `genArtifacts`, then write (or `--check`) BOTH the inline
 * `env.db.ts` literal + `schema.runtime.json`. No subprocess.
 */
export async function genTypesFromMigrations(
  migrationsDir: string,
  outDir: string,
  opts: { check?: boolean } = {},
): Promise<GenTypesResult> {
  // Recording EVALUATES the creator's `.ts`, so everything that throws here is
  // their source: an unresolvable import, a syntax error, a DSL guard. Tagged
  // so the dev server can keep serving through it — see `MigrationSourceError`.
  let envelopes;
  // Recorded with their filename stems, not through `recordMigrationsDir`: the
  // apply request identifies each document by `<stem>.ir.json`, and the stem is
  // what the migration service journals a version under. Dropping it here would
  // mean re-deriving it later from something that is not the filename.
  let documents: Array<{
    filename: string;
    body: Awaited<ReturnType<typeof recordMigration>>;
  }>;
  try {
    const discovered = await discoverMigrations(migrationsDir);
    documents = [];
    for (const m of discovered) {
      documents.push({ filename: `${m.stem}.ir.json`, body: await recordMigration(m.path) });
    }
    envelopes = documents.map((d) => d.body);
  } catch (cause) {
    throw new MigrationSourceError(
      `gen-types: a migration under ${migrationsDir} failed to load — ${(cause as Error)?.message ?? String(cause)}`,
      { cause },
    );
  }

  const reply = loadMigrateAddon().genArtifacts({
    envelopes,
    projectSchema: "public",
    // The engine is preset-free: the CALLER supplies the confined injection shape.
    // The pure-JS recorder emits RAW author-only ops; this ceiling injects the 7
    // system columns + [id] PK + system indexes at resolve time, matching the
    // descriptor path so both sources stay byte-identical.
    charterLayers: [CONFINED_SCHEMA_EMIT_CEILING_TOML],
    // Must match the MANUAL call above: the two sources are required to produce
    // byte-identical output, so a dialect skew between them would break that
    // contract silently rather than loudly.
    dialect: "postgres",
  });
  const runtimeJson = unwrap(reply, "generated migration source");
  // The typed surface is rendered HERE, off the runtime descriptor - the engine's
  // own `envDbTs` re-authors the fold in the migration DSL, which a deployed app
  // neither depends on nor gets `env.db` typing from.
  const envDbTs = renderGeneratedEnvDb(parseRuntimeDescriptor(runtimeJson));
  // THE ORDERING ANCHOR. `genArtifacts` ran ONCE above and both artifacts come
  // out of that single reply, so this hash names the descriptor that belongs to
  // exactly these documents. `migrated` records it on the ledger row for the
  // apply request; the control plane refuses a deploy whose
  // `manifest.runtime_descriptor.hash` is not the hash on the newest applied
  // row.
  //
  // IT MUST BE THE HASH OF THE BYTES THAT REACH THE PACKER, not of some
  // re-serialisation of the same value. `emit` writes `runtimeJson` verbatim
  // with `fs.writeFile(..., "utf8")`, and `zship.ts` hashes the file it reads
  // back (`sha256Hex(descriptorBytes)`), so hashing the string here as utf8
  // yields the same digest. A pretty-print, a re-`JSON.stringify`, or a
  // trailing newline added on either side would produce two hashes that can
  // never agree, and the failure would look like the guard misfiring.
  const descriptorSha256 = createHash("sha256").update(runtimeJson, "utf8").digest("hex");
  // Two-space JSON, trailing newline: this file is committed and reviewed, and
  // a one-line 200 KB blob is not.
  const migrationsIr = `${JSON.stringify(
    { kind: "ir", descriptor_sha256: descriptorSha256, documents },
    null,
    2,
  )}\n`;
  return emit(outDir, envDbTs, runtimeJson, opts.check ?? false, migrationsIr);
}

/** Unwrap a `genArtifacts` reply, turning the soft `{ ok:false, error }` arm into
 *  a thrown build error and asserting `runtimeJson` is present. */
function unwrap(reply: GenArtifactsReply, source: string): string {
  if (!reply.ok) {
    // The engine REJECTED what the creator declared (a duplicate column, an
    // unknown table, a facet the charter forbids). Their fault, so tagged.
    throw new MigrationSourceError(
      `gen-types: ${source} failed to render — ${reply.error ?? "unknown error"}`,
    );
  }
  if (reply.runtimeJson === undefined) {
    // Deliberately NOT tagged: `ok` with no payload is an emitter bug, ours.
    throw new Error(`gen-types: ${source} produced no schema.runtime.json`);
  }
  return reply.runtimeJson;
}

/** Parse the emitted `schema.runtime.json` back into the descriptor the
 *  `env.db.ts` renderer reads. A parse failure here is an emitter bug, so it
 *  surfaces as a build error rather than a silently empty schema. */
function parseRuntimeDescriptor(runtimeJson: string): RuntimeDescriptor {
  let parsed: unknown;
  try {
    parsed = JSON.parse(runtimeJson);
  } catch (cause) {
    throw new Error(
      `gen-types: the generated source emitted an unparseable ${RUNTIME_DESCRIPTOR_FILE}`,
      { cause },
    );
  }
  if (parsed === null || typeof parsed !== "object") {
    throw new Error(
      `gen-types: the generated source emitted a non-object ${RUNTIME_DESCRIPTOR_FILE}`,
    );
  }
  return parsed as RuntimeDescriptor;
}

/**
 * Render the MANUAL `env.db.ts` augmentation: import the author's
 * `schema` and declare `Env.db = Db<typeof schema>`. The import path is relative
 * from the out dir to `schema.ts`, extension-stripped, always `./`-anchored and
 * POSIX-slashed for a stable, cross-platform module specifier.
 */
function renderManualEnvDb(outDir: string, schemaTsPath: string): string {
  let rel = relative(resolve(outDir), resolve(schemaTsPath));
  rel = rel.replace(/\.ts$/, "");
  rel = rel.split(/[\\/]/).join("/");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return (
    MANUAL_ENV_DB_BANNER +
    `import { type Db } from "@zeroship/db";\n` +
    `import { schema } from "${rel}";\n\n` +
    `declare module "zeroship" {\n` +
    `  interface Env {\n` +
    `    db: Db<typeof schema>;\n` +
    `  }\n` +
    `}\n\n` +
    `export {};\n`
  );
}

/**
 * Emit or check the two artifacts. When `check`, regenerate in memory and diff
 * against the committed files — a hard error naming the first drifted file.
 * Otherwise write both (creating the out dir).
 */
async function emit(
  outDir: string,
  envDbTs: string,
  runtimeJson: string,
  check: boolean,
  // Absent on the MANUAL source, which has no migrations to record. It is
  // optional rather than an empty string so a manual app does not emit an
  // apply body with zero documents - the migration service rejects that
  // outright ("at least one .ir.json document is required"), and shipping a
  // file that can only ever 422 is worse than shipping none.
  migrationsIr?: string,
): Promise<GenTypesResult> {
  const envPath = resolve(outDir, ENV_DB_FILE);
  const jsonPath = resolve(outDir, RUNTIME_DESCRIPTOR_FILE);
  const irPath = resolve(outDir, MIGRATIONS_IR_FILE);
  const files = [ENV_DB_FILE, RUNTIME_DESCRIPTOR_FILE];
  if (migrationsIr !== undefined) files.push(MIGRATIONS_IR_FILE);

  if (check) {
    await assertNoDrift(envPath, envDbTs, ENV_DB_FILE);
    await assertNoDrift(jsonPath, runtimeJson, RUNTIME_DESCRIPTOR_FILE);
    if (migrationsIr !== undefined) {
      await assertNoDrift(irPath, migrationsIr, MIGRATIONS_IR_FILE);
    }
    return { status: "checked", files };
  }

  const targets: Array<[string, string]> = [
    [envPath, ENV_DB_FILE],
    [jsonPath, RUNTIME_DESCRIPTOR_FILE],
  ];
  if (migrationsIr !== undefined) targets.push([irPath, MIGRATIONS_IR_FILE]);
  for (const [path, file] of targets) {
    await assertGeneratedArtifactMayBeReplaced(path, file);
  }

  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(envPath, envDbTs, "utf8");
  await fs.writeFile(jsonPath, runtimeJson, "utf8");
  if (migrationsIr !== undefined) {
    await fs.writeFile(irPath, migrationsIr, "utf8");
  }
  return { status: "written", files };
}

async function assertGeneratedArtifactMayBeReplaced(path: string, file: string): Promise<void> {
  // Concurrent HMR folds can expose a briefly truncated generated file. Retry
  // only while its bytes are changing; a stable unknown owner is still refused.
  let previous: string | undefined;
  let stableReads = 0;
  for (let attempt = 0; attempt < 6; attempt += 1) {
    let stat;
    try {
      stat = await fs.lstat(path);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") return;
      throw error;
    }
    if (stat.isSymbolicLink() || !stat.isFile()) {
      throw new Error(`gen-types: refusing to overwrite non-generated ${file} at ${path}`);
    }

    const existing = await fs.readFile(path, "utf8");
    if (isGeneratedArtifact(file, existing)) return;
    stableReads = existing === previous ? stableReads + 1 : 0;
    if (stableReads >= 2 || attempt === 5) break;
    previous = existing;
    await new Promise((done) => setTimeout(done, 10));
  }
  throw new Error(`gen-types: refusing to overwrite creator-owned ${file} at ${path}`);
}

function isGeneratedArtifact(file: string, existing: string): boolean {
  if (file === ENV_DB_FILE) {
    return existing.startsWith(MANUAL_ENV_DB_BANNER) ||
      existing.startsWith(GENERATED_ENV_DB_BANNER);
  }
  if (file === RUNTIME_DESCRIPTOR_FILE) return isRuntimeDescriptorArtifact(existing);
  return file === MIGRATIONS_IR_FILE && isMigrationsIrArtifact(existing);
}

/**
 * Is this file one WE wrote, as opposed to something a creator hand-authored?
 *
 * Deliberately version-AGNOSTIC: any numeric `version` over a `collections` record is
 * ours. Pinning this to the current version looks tighter and is actively wrong, because
 * the recogniser gates OVERWRITING - so a version bump would make every committed
 * artifact unrecognisable, and `gen-types` would refuse to regenerate the very files the
 * bump had just made stale. Measured: pinning it to 2 refused all 8 loadable committed
 * artifacts with "refusing to overwrite creator-owned schema.runtime.json", and the only
 * way out was to hand-edit each file to the new version first.
 *
 * "Is this file ours" and "is this file CURRENT" are different questions. The second one
 * belongs to the drift gate (`--check`), which compares bytes and has a fresh render to
 * compare against; this one only has the file.
 */
function isRuntimeDescriptorArtifact(text: string): boolean {
  const parsed = parseObject(text);
  return typeof parsed?.version === "number" && isRecord(parsed.collections);
}

function isMigrationsIrArtifact(text: string): boolean {
  const parsed = parseObject(text);
  return parsed?.kind === "ir" && Array.isArray(parsed.documents);
}

function parseObject(text: string): Record<string, unknown> | null {
  try {
    const parsed: unknown = JSON.parse(text);
    return isRecord(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value != null && typeof value === "object" && !Array.isArray(value);
}

/** Assert the committed artifact byte-matches the freshly-generated one. */
async function assertNoDrift(
  path: string,
  fresh: string,
  file: string,
): Promise<void> {
  let committed: string;
  try {
    committed = await fs.readFile(path, "utf8");
  } catch {
    throw new Error(
      `gen-types --check: ${file} is missing at ${path} — run gen-types to generate it`,
    );
  }
  if (committed !== fresh) {
    throw new Error(
      `gen-types --check: ${file} is STALE — regenerate it (the committed artifact ` +
        `drifted from the schema source).\n${firstDivergence(committed, fresh)}`,
    );
  }
}

/** A short human-readable preview of the first line that diverges. */
function firstDivergence(a: string, b: string): string {
  const al = a.split("\n");
  const bl = b.split("\n");
  const n = Math.max(al.length, bl.length);
  for (let i = 0; i < n; i++) {
    if (al[i] !== bl[i]) {
      return (
        `  first divergence at line ${i + 1}:\n` +
        `  - committed: ${JSON.stringify(al[i] ?? "<missing>")}\n` +
        `  + fresh:     ${JSON.stringify(bl[i] ?? "<missing>")}`
      );
    }
  }
  return "  (files differ in trailing content)";
}

export { dirname as _dirname };
