-- Generated by schema/generate.mjs through the migration compiler.
DROP TABLE "__zeroship_workflow_advance_publications";

DROP TABLE "__zeroship_workflow_fanout_publications";

DROP TABLE "__zeroship_workflow_propagation_publications";
