/**
 * `installSchema` — framework-internal helper behind the
 * `export default { schema }` convention. The synthetic SSR entry
 * generated by `@zeroship/vite-plugin` (and the dev-bootstrap) calls
 * this once at module-init to register every collection in the schema
 * map AND install typed Collection wrappers (plus the `transaction` /
 * `live` helpers) as own properties on `env.db`. From handlers, user
 * code writes `env.db.users.find(...)` and
 * `env.db.transaction(tx => ...)` — no factory call required.
 *
 * Usage in user code (typical):
 *   import { t, schema } from "@zeroship/db";
 *   import { env } from "zeroship";
 *
 *   export default {
 *     schema: {
 *       users: {
 *         email: t.string().required().unique(),
 *         name:  t.string().required().max(100),
 *       },
 *       todos: {
 *         userId: t.ref("users").required(),
 *         title:  t.string().required().min(1).max(200),
 *         done:   t.boolean().default(false),
 *       },
 *     },
 *   };
 *
 *   // Inside any procedure handler:
 *   const { data: user } = await env.db.users.insert({
 *     email: "alice@example.com",
 *     name:  "Alice",
 *   });
 *
 *   // Transactions — tx mirrors db, throws on error:
 *   const { data, error } = await env.db.transaction(async (tx) => {
 *     const u = await tx.users.insert({ email: "...", name: "..." });
 *     await tx.todos.insert({ userId: u.id, title: "buy milk" });
 *     return u;
 *   });
 *
 * Returns Result vs throws (worth knowing):
 * - `env.db.x.*` outside a transaction → `Promise<Result<T>>`.
 * - `tx.x.*` inside `env.db.transaction(tx => ...)` → `Promise<T>`, throws on error.
 * - `env.db.transaction(fn)` itself → `Promise<Result<R>>` — never throws.
 *
 * The function is exported as `installSchema` (framework-internal but
 * stable across the platform / SDK boundary). User modules MUST NOT
 * call it directly — the convention is `export default { schema }` and
 * the platform installs it.
 */

import { model } from "./model.js";
import { Collection, type NativeDb } from "./collection.js";
import { Query } from "./query.js";
import { createLive, type LiveOptions, type LiveQuery } from "./live.js";
import { normalizeSchema, validateRefTargets } from "./schema.js";
import { type PlainObject, type Result, type Row, type RowInput, type UpdateExpression, type Filter, type IsolationLevel, type NamingStrategy, type WithSpec, type WithRelations, SchemaBuilder, TypeBuilder, naming, ok, err } from "./types.js";

/**
 * Topologically sort schema names so parents precede children. A child
 * is a collection with `t.ref(parent)` somewhere in its field set.
 * Used by `installSchema` to chain `registerModel` calls in dependency
 * order. Cycles (mutual refs) fall back to declaration order — they're
 * resolved by `DEFERRABLE INITIALLY DEFERRED` at the SQL layer.
 */
function topoSortByRefs(schemas: Record<string, unknown>): string[] {
  const names = Object.keys(schemas);
  const deps = new Map<string, Set<string>>();
  for (const name of names) {
    deps.set(name, new Set());
    const raw = schemas[name];
    const fields = (raw instanceof SchemaBuilder ? raw.fields : raw) as Record<string, unknown> | unknown;
    if (!fields || typeof fields !== "object") continue;
    for (const fd of Object.values(fields as Record<string, unknown>)) {
      const def = fd instanceof TypeBuilder ? fd.toFieldDef() : (fd as { type?: string; refTarget?: string });
      if (def && (def as { type?: string }).type === "ref") {
        const target = (def as { refTarget?: string }).refTarget;
        if (target && target !== name && names.includes(target)) {
          deps.get(name)!.add(target);
        }
      }
    }
  }
  const visited = new Set<string>();
  const onStack = new Set<string>();
  const out: string[] = [];
  function visit(n: string): void {
    if (visited.has(n)) return;
    if (onStack.has(n)) return; // cycle — break; DEFERRABLE handles it
    onStack.add(n);
    for (const d of deps.get(n)!) visit(d);
    onStack.delete(n);
    visited.add(n);
    out.push(n);
  }
  for (const n of names) visit(n);
  return out;
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Schema definition — plain fields, schema() builder with options, or
 * a top-level `t.union(...)` whose row shape is a discriminated union
 * (proposal §C2). The TypeBuilder form is type-erased to
 * `TypeBuilder<unknown, any>` here so the conditional in `UnwrapSchema`
 * can distribute over the union.
 */
type SchemaInput =
  | Record<string, unknown>
  | SchemaBuilder<Record<string, unknown>>
  | TypeBuilder<unknown, any>;

/**
 * Schema-shape validator (R3 IMPORTANT-5). When a user writes
 * `{ name: "string" }` instead of `{ name: t.string() }`, the bare
 * value is structurally compatible with `Record<string, unknown>` so
 * the constraint passes silently, leaving the runtime path
 * (`normalizeSchema`) as the only feedback channel.
 *
 * `ValidateSchemaShape<T>` walks each collection's field map: if any
 * field value is not a `TypeBuilder` (or a `SchemaBuilder` / top-level
 * `TypeBuilder` for the whole collection), it returns a string-literal
 * error type that surfaces in the assignability message — TS quotes
 * the literal, so users see exactly which field is the offender and
 * what to do.
 *
 * If the shape is valid the validator returns `T` unchanged, preserving
 * inference for the rest of the type machinery.
 */
type IsValidSchemaField<F> = F extends TypeBuilder<unknown, boolean> ? true : false;

type ValidateSchemaShape<T> = {
  [K in keyof T]:
    T[K] extends SchemaBuilder<Record<string, unknown>>
      ? T[K]
      : T[K] extends TypeBuilder<unknown, boolean>
        ? T[K]
        : T[K] extends Record<string, unknown>
          ? {
              [F in keyof T[K]]:
                IsValidSchemaField<T[K][F]> extends true
                  ? T[K][F]
                  : `Field "${F & string}" on "${K & string}" must be a t.* builder (e.g. t.string(), t.number(), t.ref("users")) — got a bare value.`;
            }
          : `Schema "${K & string}" must be a field map of t.* builders, a schema(...) builder, or a top-level t.union(...).`;
};

/**
 * A typed collection inside a transaction — same API as Collection but throws
 * on error instead of returning Result. Generic over schema shape S.
 *
 * `AllSchemas` mirrors `Collection<S, N, AllSchemas>` — `installSchema`
 * passes the full schema map so `tx.x.find({...}, { with: { fk: true } })`
 * resolves the joined field to the target collection's `Row<...>` at the
 * type layer. Default `Record<string, unknown>` keeps direct `TxCollection`
 * consumers compiling (joined fields degrade to `PlainObject`).
 */
export type TxCollection<S = PlainObject, AllSchemas extends Record<string, unknown> = Record<string, unknown>> = {
  insert(row: RowInput<S>): Promise<Row<S>>;
  insertMany(rows: RowInput<S>[]): Promise<Row<S>[]>;
  get<K extends string & keyof Row<S>>(
    idOrFilter: number | Filter<S>,
    opts: { select: K[]; orderBy?: Record<string, 1 | -1> },
  ): Promise<Pick<Row<S>, K> | null>;
  get<W extends WithSpec>(
    idOrFilter: number | Filter<S>,
    opts: { with: W; orderBy?: Record<string, 1 | -1> },
  ): Promise<(Row<S> & WithRelations<S, W, AllSchemas>) | null>;
  get(
    idOrFilter: number | Filter<S>,
    opts?: { orderBy?: Record<string, 1 | -1> },
  ): Promise<Row<S> | null>;
  exists(filter: Filter<S>): Promise<boolean>;
  find<W extends WithSpec>(filter: Filter<S>, opts: { with: W }): TxQuery<S, Row<S> & WithRelations<S, W, AllSchemas>, AllSchemas>;
  find(filter?: Filter<S>): TxQuery<S, Row<S>, AllSchemas>;
  upsert(row: RowInput<S>, options: { conflictFields: (string & keyof Row<S>)[] }): Promise<Row<S>>;
  update(idOrFilter: number | Filter<S>, patch: UpdateExpression<S>): Promise<Row<S> | null>;
  updateMany(filter: Filter<S>, patch: UpdateExpression<S>): Promise<{ count: number }>;
  delete(idOrFilter: number | Filter<S>, opts?: { hard?: boolean }): Promise<Row<S> | null>;
  deleteMany(filter: Filter<S>, opts?: { hard?: boolean }): Promise<{ deletedCount: number }>;
  count(filter?: Filter<S>): Promise<number>;
  distinct(field: string & keyof Row<S>, filter?: Filter<S>): Promise<(string | number | boolean | null)[]>;
  aggregate(pipeline: ZeroshipDbAggregateStage[]): Promise<PlainObject[]>;
};

/** Query inside a transaction — same chainable API but resolves to data directly */
export type TxQuery<
  S = PlainObject,
  P = Row<S>,
  AllSchemas extends Record<string, unknown> = Record<string, unknown>,
> = {
  sort(s: Record<string, number> | string): TxQuery<S, P, AllSchemas>;
  limit(n: number): TxQuery<S, P, AllSchemas>;
  skip(n: number): TxQuery<S, P, AllSchemas>;
  select<K extends keyof Row<S> & string>(fields: K[]): TxQuery<S, Pick<Row<S>, K>, AllSchemas>;
  select(s: string | string[] | Record<string, number | boolean>): TxQuery<S, P, AllSchemas>;
  after(id: number): TxQuery<S, P, AllSchemas>;
  with<W extends WithSpec>(spec: W): TxQuery<S, P & WithRelations<S, W, AllSchemas>, AllSchemas>;
  then<TResult1 = P[], TResult2 = never>(
    resolve?: ((value: P[]) => TResult1 | PromiseLike<TResult1>) | null,
    reject?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null
  ): Promise<TResult1 | TResult2>;
};

/** Options for the transaction method. */
export interface TransactionOptions {
  /** PostgreSQL transaction isolation level. Defaults to the database default (read committed). */
  isolationLevel?: IsolationLevel;
}

/**
 * Unwrap SchemaBuilder / TypeBuilder at the type level so the collection
 * receives the underlying field record (or, for a top-level
 * `t.union(...)`, the inferred union shape — see proposal §C2).
 *
 * - `schema({...})` wraps a `Record<string, unknown>` and we strip it.
 * - `t.union(...)` produces `TypeBuilder<UnionShape>`; we extract
 *   `UnionShape` so the collection is `Collection<UnionShape>` and a
 *   `find()` returns `Row<UnionShape>` whose discriminator key
 *   narrows correctly under control flow analysis.
 */
type UnwrapSchema<T> =
  T extends SchemaBuilder<infer S> ? S :
  T extends TypeBuilder<infer U, any> ? U :
  T;

/**
 * The typed Collection map produced by `installSchema`. Indexed by
 * collection name; values are fully typed `Collection<...>` instances
 * carrying both the per-row shape (`UnwrapSchema<T[K]>`) and the full
 * schema map (`T`) so brand types and joined-relation types resolve
 * without extra casts at the call site.
 */
export type Collections<T extends Record<string, SchemaInput>> = {
  [K in keyof T]: Collection<UnwrapSchema<T[K]>, K & string, T>;
};

/**
 * The shape `installSchema` plants on `env.db` (the native handle) on
 * top of the per-collection wrappers — `transaction` and `live` are
 * SDK-level helpers that wrap the native `beginTransaction` /
 * subscription primitives.
 */
export type DbExtensions<T extends Record<string, SchemaInput>> = {
  transaction: <R>(fn: (tx: { [K in keyof T]: TxCollection<UnwrapSchema<T[K]>, T> }) => Promise<R>, options?: TransactionOptions) => Promise<Result<R>>;
  /**
   * Reactive query layer. Runs `queryFn`, yields the initial result,
   * then re-runs and yields a fresh result on every change to any
   * table the `queryFn` reads.
   *
   * v1 is coarse-grained: every change to a watched table fires a
   * rerun (no row-level filter narrowing). The tables are auto-detected
   * by observing which `Collection.find/findOne/get/...` methods the
   * `queryFn` calls during its first execution. Pass `{ tables: [...] }`
   * to bypass auto-detection (e.g. when the queryFn doesn't go through
   * a Collection).
   *
   * Throws `code = "live_in_transaction"` if called inside
   * `db.transaction(tx => ...)`. Returns an AsyncIterableIterator with
   * an explicit `close()` method for teardown.
   */
  live: <R>(queryFn: () => Promise<R[]> | { then(onFulfilled: (value: unknown) => unknown, onRejected?: (reason: unknown) => unknown): unknown }, options?: LiveOptions) => LiveQuery<R>;
};

/**
 * Legacy `Db<T>` shape — `Collections<T> & DbExtensions<T>`. Kept as a
 * convenience alias so call sites that want the combined surface
 * (collections + transaction/live) have a single name. The SDK no
 * longer materialises an object of this exact shape (everything is
 * planted on `env.db`); the type still describes the union users
 * observe when they read off `env.db`.
 */
export type Db<T extends Record<string, SchemaInput>> = Collections<T> & DbExtensions<T>;

// ---------------------------------------------------------------------------
// TxCollection — wraps a Collection, throws on error
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// installSchema — module-local chain serialization (replaces the prior
// `globalThis.__zeroshipPlatformReady` global). Each call's `ready`
// promise becomes the new `_prevChain`; the next call's chain is built
// on top so HMR re-installs serialise. A previous-chain rejection is
// swallowed via `prev.catch(() => undefined)` so a stale failure
// doesn't poison fresh re-installs, but THIS call's chain still
// rejects on its own DDL failure.
//
// Module-local lives once per V8 isolate; each app has its own isolate
// in the runtime, so concurrent isolates can't observe each other's
// chain.
// ---------------------------------------------------------------------------
let _prevChain: Promise<void> | null = null;

/** Extracts data from Result, throws on error. Shared across all TxCollections. */
async function unwrap<T>(result: Result<T>): Promise<T> {
  if (result.error) throw result.error;
  return result.data as T;
}

/**
 * Wraps the outer Collection so its CRUD methods return the bare value
 * and throw on error (vs Result<T>). The tx adapter does NOT re-route
 * the call to a different native handle — every call goes through the
 * same `Collection.{insert,update,...}` you'd use outside the tx, and
 * routing onto the transaction's Postgres connection happens in Rust
 * via the `TX_CONN` thread-local (`crates/plugin-db/src/callbacks.rs`
 * around the dispatch site). Two consequences worth knowing:
 *
 * - `db.users` and `tx.users` are the SAME Collection instance; the
 *   only difference is the surface adapter that strips Result.
 * - There is no `Collection<tx>` vs `Collection<db>` split in JS.
 *   Schema validation, naming, and the soft-delete / versioning
 *   plumbing all live on one object.
 */
function createTxCollection<S>(collection: Collection<S>): TxCollection<S> {

  // The TxCollection.get signature is two overloads (with/without
  // select); the runtime impl is a single function that delegates to
  // the underlying Collection — the overload-aware return type comes
  // from the TxCollection type, not the impl signature.
  async function getImpl(
    idOrFilter: number | Filter<S>,
    opts?: { select?: (string & keyof Row<S>)[]; orderBy?: Record<string, 1 | -1> },
  ): Promise<unknown> {
    const colAny = collection as unknown as {
      get(
        idOrFilter: number | Filter<S>,
        opts?: { select?: (string & keyof Row<S>)[]; orderBy?: Record<string, 1 | -1> },
      ): Promise<Result<Row<S> | null>>;
    };
    return unwrap(await colAny.get(idOrFilter, opts));
  }

  const tx: TxCollection<S> = {
    async insert(row: RowInput<S>) {
      return unwrap(await collection.insert(row));
    },
    async insertMany(rows: RowInput<S>[]) {
      return unwrap(await collection.insertMany(rows));
    },
    get: getImpl as TxCollection<S>["get"],
    async exists(filter: Filter<S>) {
      return unwrap(await collection.exists(filter));
    },
    find: ((filter: Filter<S> = {} as Filter<S>, opts?: { with?: WithSpec }): TxQuery<S, Row<S>> => {
      const query = (opts?.with !== undefined
        ? (collection as unknown as {
            find(f: Filter<S>, o: { with: WithSpec }): Query<S, Row<S>>;
          }).find(filter, { with: opts.with })
        : collection.find(filter));
      return createTxQuery<S>(query);
    }) as TxCollection<S>["find"],
    async upsert(row: RowInput<S>, options: { conflictFields: (string & keyof Row<S>)[] }) {
      return unwrap(await collection.upsert(row, options));
    },
    async update(idOrFilter: number | Filter<S>, patch: UpdateExpression<S>) {
      return unwrap(await collection.update(idOrFilter, patch));
    },
    async updateMany(filter: Filter<S>, patch: UpdateExpression<S>) {
      return unwrap(await collection.updateMany(filter, patch));
    },
    async delete(idOrFilter: number | Filter<S>, opts?: { hard?: boolean }) {
      return unwrap(await collection.delete(idOrFilter, opts));
    },
    async deleteMany(filter: Filter<S>, opts?: { hard?: boolean }) {
      return unwrap(await collection.deleteMany(filter, opts));
    },
    async count(filter: Filter<S> = {} as Filter<S>) {
      return unwrap(await collection.count(filter));
    },
    async distinct(field: string & keyof Row<S>, filter: Filter<S> = {} as Filter<S>) {
      return unwrap(await collection.distinct(field, filter));
    },
    async aggregate(pipeline: ZeroshipDbAggregateStage[]) {
      return unwrap(await collection.aggregate(pipeline));
    },
  };
  return tx;
}

/** Wrap a Query to throw on error. The `select` overloads mirror the
 *  underlying `Query.select` so a typed-fields call narrows the result
 *  to `Pick<Row<S>, K>` — the runtime path stays untyped, but the
 *  generic signatures preserve the narrowing across the wrapper. */
function createTxQuery<S>(query: Query<S, Row<S>>): TxQuery<S, Row<S>> {
  function selectImpl(
    s: string | string[] | Record<string, number | boolean>,
  ): unknown {
    (query.select as (arg: unknown) => unknown)(s);
    // Both overloads return the same wrapper instance; only the type
    // narrows at the call boundary via the TxQuery type's signatures.
    return wrapped;
  }
  const wrapped: TxQuery<S, Row<S>> = {
    sort(s: Record<string, number> | string) { query.sort(s); return wrapped; },
    limit(n: number) { query.limit(n); return wrapped; },
    skip(n: number) { query.skip(n); return wrapped; },
    // The overloads on TxQuery.select carry the K[] narrowing; the
    // runtime implementation is a single function that delegates to
    // the underlying Query — the cast is local to the call site.
    select: selectImpl as TxQuery<S, Row<S>>["select"],
    after(id: number) { query.after(id); return wrapped; },
    with: ((spec: WithSpec) => {
      (query as unknown as { with(s: WithSpec): unknown }).with(spec);
      return wrapped;
    }) as TxQuery<S, Row<S>>["with"],
    then<TResult1 = Row<S>[], TResult2 = never>(
      resolve?: ((value: Row<S>[]) => TResult1 | PromiseLike<TResult1>) | null,
      reject?: ((reason: unknown) => TResult2 | PromiseLike<TResult2>) | null,
    ): Promise<TResult1 | TResult2> {
      return query.then(
        (result: Result<Row<S>[]>) => {
          if (result.error) throw result.error;
          return resolve ? resolve(result.data as Row<S>[]) : (result.data as unknown as TResult1);
        },
        reject,
      ) as Promise<TResult1 | TResult2>;
    },
  };
  return wrapped;
}

// ---------------------------------------------------------------------------
// installSchema
// ---------------------------------------------------------------------------

/**
 * Options for `installSchema`. Framework-internal — not part of the
 * public surface. `env` (the second positional arg) carries the native
 * driver; this struct just bundles ancillary knobs.
 */
export interface InstallSchemaOptions {
  /** Column naming strategy. Default: `naming.snakeCase`. */
  naming?: NamingStrategy;
}

/**
 * Names on the `env.db` v8_class instance that the SDK MUST NOT
 * overwrite when installing Collection wrappers. Mirrors the public
 * method surface of `ZeroshipDb` in `sdks/types/db.d.ts` — schema
 * authors who pick one of these names for a collection get a thrown
 * `Error` at boot, not a silent shadowing of the native method.
 *
 * `transaction` and `live` are SDK-level extension methods installed
 * by `installSchema`; reserving them prevents a schema collection
 * named `transaction` (or `live`) from clobbering the helper.
 */
const RESERVED_ENV_DB_NAMES = new Set<string>([
  "collection",
  "migrations",
  "replication",
  "beginTransaction",
  "openSubscription",
  "registerModel",
  "startReplicationConsumer",
  "transaction",
  "live",
]);

/**
 * Re-entrancy guard for `installSchema`. HMR storms (multiple
 * concurrent reloads racing through `getRunner().then(...)`) can
 * interleave two installs that both read `__zeroshipDbInstalledNames`
 * before either writes back, leaving stale own-properties bound to
 * orphaned Collection wrappers. The dev-bootstrap's `schemaRegistered`
 * latch is the real serializer; this guard makes a programming-error
 * concurrent call surface as `install_in_flight` instead of corrupting
 * `env.db` silently.
 */
let _installInFlight = false;

/**
 * Framework-internal helper that backs the `export default { schema }`
 * convention. Walks the schema map, runs `registerModel` in topological
 * order so parent tables (referenced via `t.ref(...)`) are created
 * before child tables, and unconditionally defines typed Collection
 * wrappers (plus the `transaction` / `live` extension methods) as own
 * properties on the supplied `env` (the native `ZeroshipDb` handle —
 * `env.db` in production, a mock in tests). After this returns,
 * `env.<collection>.find(...)` and `env.transaction(tx => ...)` are
 * live.
 *
 * Returns:
 *   - `collections` — the typed Collection map, keyed by schema name.
 *     Convenient for code that already has a reference to the return
 *     value (tests, helpers); production callers usually just keep
 *     reading off `env.db.<name>`.
 *   - `ready` — a Promise that resolves once the chained `registerModel`
 *     DDL has settled. Callers MUST await this before opening any
 *     auto-tx — the auto-tx dispatcher receives the promise via
 *     closure capture in the runtime bootstrap (`db_init.js`) and
 *     dev-bootstrap (the module-local `_schemaReady`).
 *
 * Re-entrant: a second call with overlapping names re-installs the
 * Collection wrappers (the `defineProperty` descriptor is
 * `configurable: true`), but throws on a name colliding with a
 * reserved native method (see `RESERVED_ENV_DB_NAMES`).
 *
 * User code must NOT call this directly. The synthetic SSR entry
 * (`@zeroship/vite-plugin`'s production build) and the dev-bootstrap
 * call it from their schema-discovery IIFE; everything else flows
 * through `env.db.<collection>` once the install has settled.
 */
export function installSchema<const T extends Record<string, SchemaInput>>(
  schemas: ValidateSchemaShape<T>,
  env: NativeDb,
  options?: InstallSchemaOptions,
): { collections: Collections<T>; ready: Promise<void> } {
  // Re-entrancy guard. `installSchema` is documented as single-threaded
  // (the dev-bootstrap's `schemaRegistered` latch enforces this for HMR
  // reloads). If a caller violates the contract we throw a typed error
  // rather than risk a stale `__zeroshipDbInstalledNames` overwrite
  // orphaning Collection wrappers on `env.db`.
  if (_installInFlight) {
    throw Object.assign(
      new Error(
        "@zeroship/db: installSchema called while a previous install is in flight — " +
          "this helper must run from a single-threaded scope (the dev-bootstrap and " +
          "production synthetic SSR entry both serialize).",
      ),
      { code: "install_in_flight" as const },
    );
  }
  _installInFlight = true;
  try {
    return _installSchemaInner(schemas as unknown as T, env, options);
  } catch (e) {
    // Surface this install's failure on the module-local prev-chain so
    // the next caller (HMR re-install) sees the rejected handle on
    // `prev` and clears it via `prev.catch(() => undefined)`. The
    // throw still propagates synchronously to the caller; this just
    // keeps the chain coherent for any later awaiter that already
    // captured a stale handle.
    const prev = _prevChain ?? Promise.resolve();
    const reason = e instanceof Error ? e : new Error(String(e));
    const published = prev.catch(() => undefined).then(() => Promise.reject(reason));
    // Silence unhandled-rejection on the published handle — actual
    // awaiters still see the rejection because `.catch` returns a
    // new promise without mutating the original.
    published.catch(() => undefined);
    _prevChain = published;
    throw e;
  } finally {
    _installInFlight = false;
  }
}

function _installSchemaInner<const T extends Record<string, SchemaInput>>(
  schemas: T,
  env: NativeDb,
  options?: InstallSchemaOptions,
): { collections: Collections<T>; ready: Promise<void> } {
  // Guard against `installSchema(schema, undefined)`. Production
  // callers (the runtime bootstrap `db_init.js`, the dev-bootstrap)
  // pass the live `env.db` handle resolved off the runtime's
  // composite env; if that lookup yielded `undefined`, the DbPlugin
  // is misconfigured and there's no point planting on `undefined`.
  // Test mocks pass a stub handle — they hit this guard only when
  // they intentionally elide it.
  if (env == null || typeof env !== "object") {
    throw Object.assign(
      new Error(
        "@zeroship/db: installSchema requires a native env.db handle as " +
          "the second argument — got " + (env === undefined ? "undefined" : env === null ? "null" : typeof env) + ".",
      ),
      { code: "native_db_unavailable" as const },
    );
  }
  const native = env;
  const namingStrategy = options?.naming ?? naming.snakeCase;
  // Carry both the name (`K & string`) AND the full schema map (`T`) on
  // every collection so brand types (`db.users.Id` → `Id<"users">`) and
  // joined-relation types (`find({...}, { with })`) resolve without the
  // type-erasing cast that used to live at the return site. The internal
  // alias keeps the per-key shape narrow; the cast on line ~469 only
  // widens to `Collection<unknown, string, T>` for the loop that iterates
  // a heterogeneous map.
  const collections = {} as { [K in keyof T]: Collection<UnwrapSchema<T[K]>, K & string, T> };

  // B2 — validate that every `t.ref("...")` target is a declared
  // collection in this same schema map. The TS `Tables<S>` constraint
  // catches the canonical case at compile-time; this runtime check is
  // the safety net for `t.ref("x" as any)` escapes and ensures we never
  // emit DDL that references a non-existent table (which would otherwise
  // fail later with a confusing Postgres error).
  validateRefTargets(schemas);

  // B2 — pass `skipRegister=true` so `model()` doesn't eagerly fire
  // `registerModel` itself. `installSchema` runs the registrations in
  // topological order below, so parent tables (referenced via
  // `t.ref(...)`) get created before child tables. We can't strip
  // `registerModel` by wrapping `native` because env.db is a
  // `#[v8_class]` instance whose other methods (`.collection`,
  // `.beginTransaction`, …) need the original `this` binding —
  // `Object.create(env.db)` would lose internal-field access and
  // method calls would throw "Illegal invocation".
  for (const [name, rawSchema] of Object.entries(schemas)) {
    // Unwrap SchemaBuilder to extract per-collection options. A top-level
    // `t.union(...)` (C2) is also a valid schema input — `model()` ->
    // `normalizeSchema` recognises a TypeBuilder and expands the union
    // into flat columns; we pass it through unchanged.
    const isBuilder = rawSchema instanceof SchemaBuilder;
    const fields = isBuilder ? rawSchema.fields : rawSchema;
    const softDelete = isBuilder ? rawSchema.options.softDelete : false;
    const versioning = isBuilder ? rawSchema.options.versioning : false;
    const declaredIndexes = isBuilder ? rawSchema.indexes : [];
    (collections as Record<string, Collection<unknown, string, T>>)[name] =
      model(
        name,
        // `model()` -> `normalizeSchema` accepts SchemaBuilder fields,
        // bare Mongoose-style records, and a TypeBuilder (union). The
        // single cast keeps the heterogeneous map's loop tractable.
        fields as Record<string, unknown>,
        native,
        namingStrategy,
        softDelete,
        versioning,
        /* skipRegister */ true,
        declaredIndexes,
      ) as Collection<unknown, string, T>;
  }

  // Chain registerModel calls in topological order so parent tables
  // (referenced via `t.ref(...)`) are created before child tables. The
  // native orchestrator's advisory lock makes concurrent calls safe
  // but not deterministic: whichever orchestrator acquires the lock
  // first runs first, and a child running before its parent fails
  // inline-FK CREATE TABLE. Sequencing in JS removes the race
  // entirely.
  //
  // The chain is later returned as the `ready` field so the bootstrap
  // (production: `db_init.js`'s top-level await; dev: dev-bootstrap's
  // `dispatchRpc` await on `_schemaReady`) can gate request dispatch
  // on it BEFORE opening the request-scope auto-tx. pglite-socket's
  // TCP proxy serializes pglite queries per-connection-in-tx, so
  // opening an auto-tx connection while the orchestrator's
  // registerModel connection holds `pg_advisory_lock` deadlocks.
  // Awaiting the chain pre-tx keeps the two off the same socket
  // window.
  const refOrder = topoSortByRefs(schemas as Record<string, unknown>);
  let chain: Promise<void> = Promise.resolve();
  for (const name of refOrder) {
    const col = (collections as Record<string, Collection<unknown, string, T>>)[name];
    if (!col) continue;
    const rawSchema = schemas[name as keyof T];
    const fields =
      rawSchema instanceof SchemaBuilder ? rawSchema.fields : rawSchema;
    // Same normalisation `model()` does — TypeBuilder → plain field
    // defs (carries `type: "ref"` + `refTarget`), Mongoose-style →
    // field defs, union expansion. The Rust orchestrator expects this
    // shape.
    const normalized = normalizeSchema(fields as Parameters<typeof normalizeSchema>[0]);
    const dbSchema: ZeroshipDbSchema = {};
    for (const [key, def] of Object.entries(normalized)) {
      dbSchema[namingStrategy.toColumn(key)] = def as ZeroshipDbFieldDef;
    }
    const declaredIndexes =
      rawSchema instanceof SchemaBuilder ? rawSchema.indexes : [];
    const wireIndexes: ZeroshipDbNamedIndex[] = declaredIndexes.map((idx) => ({
      name: idx.name,
      fields: idx.fields.map((f) => namingStrategy.toColumn(f)),
      ...(idx.unique ? { unique: true } : {}),
    }));
    // Sequencing in JS removes the parent-before-child race, but the
    // chain MUST surface registerModel failures: a broken DDL for table
    // X means every CRUD call against X is doomed, and silently
    // skipping past the rejection (`.catch(() => undefined)`) just
    // pushes the failure into a confusing later-stage Postgres error.
    // Each iteration's `then(...)` runs only on fulfilment, so a
    // rejected chain short-circuits the remaining registrations; the
    // promise the Collection stores via `_setReady` then rejects on
    // first CRUD and `_run` converts that to `result.error`.
    chain = chain.then(() => {
      if (!native.registerModel) return Promise.resolve();
      return (native.registerModel as unknown as (
        this: typeof native,
        collection: string,
        schema: ZeroshipDbSchema,
        indexes?: ZeroshipDbNamedIndex[],
      ) => Promise<void>).call(native, name, dbSchema, wireIndexes);
    });
    (col as unknown as { _setReady(p: Promise<void> | null): void })._setReady(chain);
  }

  // Plant the sibling-collection lookup on every Collection so the
  // `with: { fk: true }` option can resolve `refTarget` → target
  // Collection at query time without a per-call closure.
  const resolveCollection = (n: string): Collection<unknown> | undefined =>
    (collections as Record<string, Collection<unknown>>)[n];
  for (const col of Object.values(collections)) {
    (col as unknown as {
      _setResolveCollection(fn: (name: string) => Collection<unknown> | undefined): void;
    })._setResolveCollection(resolveCollection);
  }

  // Pre-cache TxCollection wrappers — stateless, reusable across transactions.
  // Mirror the outer `Collections<T>`'s `UnwrapSchema<T[K]>` normalisation so
  // `tx.x.insert(...)` infers identically to `env.db.x.insert(...)`. The third
  // generic `T` threads the parent db's full schema map through TxCollection
  // → TxQuery so `tx.x.find({...}, { with: { userId: true } })` resolves the
  // joined field to `Row<TargetSchema>`.
  const txCollections = {} as { [K in keyof T]: TxCollection<UnwrapSchema<T[K]>, T> };
  for (const [name, col] of Object.entries(collections)) {
    (txCollections as Record<string, TxCollection<unknown>>)[name] =
      createTxCollection(col as Collection<unknown>);
  }

  // `live` and `transaction` are SDK-level extension methods we plant
  // on `env.db` next to the per-collection wrappers. They close over
  // `collections` and `txCollections` (the schema-specific state) so
  // each install scope gets its own pair — a second install for a
  // different schema set re-plants both with bindings against the new
  // collections.
  function liveImpl<R>(
    queryFn: () => Promise<R[]> | { then(onFulfilled: (value: unknown) => unknown, onRejected?: (reason: unknown) => unknown): unknown },
    liveOptions?: LiveOptions,
  ): LiveQuery<R> {
    // `createLive` reads the per-collection access tracker off the
    // collection set; `collections` is passed as the host for table
    // detection (mirrors the pre-Stage-6 layout where `db` was the
    // same shape).
    return createLive<R>(collections as Record<string, unknown>, queryFn, liveOptions);
  }

  async function transactionImpl<R>(
    fn: (tx: { [K in keyof T]: TxCollection<UnwrapSchema<T[K]>, T> }) => Promise<R>,
    txOptions?: TransactionOptions,
  ): Promise<Result<R>> {
    // BEGIN — the native runtime returns a Transaction wrapper
    // (v8_class) whose .commit() / .rollback() are explicit methods.
    // The JS body below ALWAYS calls one of them (rollback on body
    // throw or commit failure, commit on success); the native Drop
    // auto-rollback exists only as defence-in-depth if the JS layer
    // is killed mid-call (e.g. isolate shutdown).
    const nativeAny = native as unknown as {
      beginTransaction?: (opts?: { isolationLevel?: string }) => Promise<{
        commit(): Promise<void>;
        rollback(): Promise<void>;
      }>;
    };
    if (typeof nativeAny.beginTransaction !== "function") {
      return err(
        Object.assign(
          new Error(
            "@zeroship/db: env.db.beginTransaction not available — " +
              "runtime is missing the Transaction v8_class surface.",
          ),
          { code: "native_transaction_unavailable" as const },
        ),
      );
    }
    // DRAIN BEFORE BEGIN — pending non-tx batched reads must complete
    // against the non-tx connection. `beginTransaction` plants TX_CONN
    // synchronously on resolution; any deferred batch that runs after
    // BEGIN would route its `find(...)` onto the tx connection, mixing
    // its results into the wrong scope. Drain awaits the underlying
    // batched fetches before we open the tx.
    //
    // The IdLoader scheduling discipline ("flush on next microtask")
    // means a `get(id)` queued in the same turn as `env.db.transaction(...)`
    // would otherwise lose this race: the BEGIN promise and the flush
    // microtask interleave nondeterministically. Awaiting drain forces
    // a happens-before edge.
    const collectionList = Object.values(collections).map(
      (c) => c as unknown as {
        _txDepth: number;
        _idLoader: { _drain(): Promise<void> } | null;
      },
    );
    // `transaction` is documented to return `Promise<Result<R>>` — it
    // must NEVER throw, even on a drain rejection that fires before
    // any begin/body/commit. Wrap the drain await in a try/catch so a
    // drained-batch failure surfaces as `err(drainErr)` instead of
    // leaking a rejected promise up to the caller's
    // `const { data, error } = ...` destructure.
    try {
      await Promise.all(
        collectionList
          .map((c) => c._idLoader?._drain())
          .filter((p): p is Promise<void> => p !== undefined),
      );
    } catch (drainErr) {
      const wrapped = Object.assign(
        new Error(
          `pre-transaction drain failed: ${
            drainErr instanceof Error ? drainErr.message : String(drainErr)
          }`,
          { cause: drainErr instanceof Error ? drainErr : undefined },
        ),
        { code: "tx_drain_failed" as const },
      );
      return err(wrapped);
    }

    // Bump `_txDepth` BEFORE awaiting `beginTransaction` so any
    // `get(id)` enqueued between drain resolution and BEGIN settling
    // sees `_txDepth > 0` at the synchronous call boundary and
    // bypasses the loader path. The loader's tx-race rejection
    // catches the residual case where an entry was enqueued at
    // snapshot 0 and a tx opened before flush — but the snapshot is
    // taken inside `Collection.get()` AFTER the drain await, so
    // without the synchronous bump, a `get(id)` racing this turn
    // would still snapshot 0 and route through the loader onto the
    // tx connection. Roll back the increment if begin itself throws.
    for (const c of collectionList) {
      c._txDepth += 1;
    }
    let tx: { commit(): Promise<void>; rollback(): Promise<void> };
    try {
      tx = await nativeAny.beginTransaction(
        txOptions?.isolationLevel ? { isolationLevel: txOptions.isolationLevel } : undefined,
      );
    } catch (beginErr) {
      for (const c of collectionList) c._txDepth -= 1;
      // Preserve a native `.code` if the underlying runtime stamped
      // one (e.g. pglite connection errors); otherwise stamp
      // `begin_failed` so callers branching on `error.code` can
      // distinguish a begin failure from a body/commit failure.
      const baseErr =
        beginErr instanceof Error ? beginErr : new Error(String(beginErr));
      const finalErr =
        typeof (baseErr as Error & { code?: unknown }).code === "string"
          ? baseErr
          : Object.assign(baseErr, { code: "begin_failed" as const });
      return err(finalErr);
    }

    // Two failure modes carry different post-conditions:
    //
    // 1. The transaction body threw — nothing was committed; we
    //    rollback and surface the body's error. Side-effects already
    //    flushed inside the tx (writes against TX_CONN) are reverted
    //    on rollback.
    //
    // 2. The body completed but `tx.commit()` itself threw — the
    //    SQL `COMMIT` was attempted, and depending on where it
    //    failed (network drop after server-side commit, deadlock at
    //    commit, prepared-tx ambiguity, ...) the database state is
    //    indeterminate. Callers cannot safely treat this as "rolled
    //    back". Tag the error with `.code = "commit_failed_indeterminate"`
    //    so a higher layer can decide whether to retry, prompt the
    //    user, or fail the request.
    let bodyResult: R;
    try {
      bodyResult = await fn(txCollections);
    } catch (bodyErr) {
      // Explicit rollback is the primary teardown; the rollback
      // call may throw if the connection already dropped, in which
      // case the native Drop will catch up.
      try { await tx.rollback(); } catch { /* rollback failure tolerated */ }
      for (const c of collectionList) c._txDepth -= 1;
      return err(bodyErr instanceof Error ? bodyErr : new Error(String(bodyErr)));
    }
    try {
      await tx.commit();
    } catch (commitErr) {
      try { await tx.rollback(); } catch { /* commit-half may make rollback a no-op */ }
      for (const c of collectionList) c._txDepth -= 1;
      const msg = commitErr instanceof Error ? commitErr.message : String(commitErr);
      const wrapped = Object.assign(
        new Error(`commit failed — transaction state indeterminate: ${msg}`, {
          cause: commitErr instanceof Error ? commitErr : undefined,
        }),
        { code: "commit_failed_indeterminate" as const },
      );
      return err(wrapped);
    }
    for (const c of collectionList) c._txDepth -= 1;
    return ok(bodyResult);
  }

  // Install typed Collection wrappers AND the `transaction` / `live`
  // extension methods as own properties on the supplied `env` (the
  // native `ZeroshipDb` v8_class instance) so user code can write
  // `env.db.<collection>.find(...)` and `env.db.transaction(tx => ...)`.
  //
  // Why `Object.defineProperty` with `configurable: true,
  // enumerable: true, writable: false`:
  // - `writable: false` keeps app code from rebinding `env.db.users`,
  //   matching how the native methods feel.
  // - `configurable: true` lets a second `installSchema` call
  //   redefine the same names without throwing (HMR, multi-bundle
  //   composition).
  //
  // Reserved names that overlap the native v8_class method surface
  // throw — silently shadowing `env.db.collection` (the native mint)
  // or `env.db.beginTransaction` is worse than failing fast at boot.
  //
  // Re-install hygiene: snapshot the previously-installed collection
  // names on a hidden sigil (`__zeroshipDbInstalledNames`) and DELETE
  // any old name that the new schema map doesn't redeclare before
  // defining this round's properties. Without this, a first install
  // `{users, todos}` followed by a second install `{posts}` would
  // leave stale `env.db.users` / `env.db.todos` pointing at the OLD
  // (HMR-detached) collections — silently mixing schemas at request
  // time.
  {
    const target = native as unknown as Record<string, unknown> & {
      __zeroshipDbInstalledNames?: string[];
    };
    const newNames = Object.keys(collections);
    const newNameSet = new Set(newNames);
    const prevNames = Array.isArray(target.__zeroshipDbInstalledNames)
      ? target.__zeroshipDbInstalledNames
      : [];
    // Drop every previously-installed own-property whose key is NOT
    // redefined in this install. Overlapping names fall through to the
    // `defineProperty` below (which re-binds to the new Collection
    // because the descriptor was `configurable: true`).
    for (const stale of prevNames) {
      if (newNameSet.has(stale)) continue;
      if (RESERVED_ENV_DB_NAMES.has(stale)) continue;
      try {
        delete target[stale];
      } catch {
        // Native v8_class may refuse the delete on a sealed prototype;
        // best-effort cleanup, the writable:false defineProperty below
        // for overlapping names still wins for active collections.
      }
    }
    for (const [name, col] of Object.entries(collections)) {
      if (RESERVED_ENV_DB_NAMES.has(name)) {
        throw Object.assign(
          new Error(
            `@zeroship/db: schema name "${name}" collides with a native env.db method — ` +
              `rename the collection. Reserved: ${[...RESERVED_ENV_DB_NAMES].join(", ")}.`,
          ),
          { code: "reserved_env_db_name" as const },
        );
      }
      Object.defineProperty(target, name, {
        value: col,
        configurable: true,
        enumerable: true,
        writable: false,
      });
    }
    // Plant the SDK-level extension methods. They're re-defined on
    // every install so they close over the current `collections` /
    // `txCollections`. `writable: false` matches the per-collection
    // properties; `configurable: true` keeps re-installs idempotent.
    Object.defineProperty(target, "transaction", {
      value: transactionImpl,
      configurable: true,
      enumerable: true,
      writable: false,
    });
    Object.defineProperty(target, "live", {
      value: liveImpl,
      configurable: true,
      enumerable: true,
      writable: false,
    });
    // Stash the new key set on a hidden, non-enumerable sigil so the
    // next re-install can scrub anything we own that this install
    // dropped. `configurable: true` so a third install can replace it.
    Object.defineProperty(target, "__zeroshipDbInstalledNames", {
      value: newNames,
      configurable: true,
      enumerable: false,
      writable: true,
    });
  }

  // Serialise this install behind the module-local prev-chain so HMR
  // re-installs in the same isolate happen in order. A prior install's
  // rejection is swallowed via `prev.catch(() => undefined)` so the
  // dispatcher doesn't reject on a stale failure, but THIS round's
  // registerModel rejection still propagates through `ready` so its
  // own failures surface.
  //
  // Consumers (runtime bootstrap `db_init.js`, dev-bootstrap) capture
  // the `ready` promise returned to them and await it before opening
  // any auto-tx — pglite-socket's per-connection-in-tx serialisation
  // would deadlock against the orchestrator's `pg_advisory_lock`
  // otherwise.
  const prev = _prevChain ?? Promise.resolve();
  const ready = prev.catch(() => undefined).then(() => chain);
  _prevChain = ready;
  // Silence unhandled-rejection on the published handle — actual
  // awaiters still see the rejection because `.catch` returns a new
  // promise without mutating the original.
  ready.catch(() => undefined);

  return { collections: collections as Collections<T>, ready };
}
