//! Live PostgreSQL coverage for import-time identity synchronization.
//!
//! Gated behind `ZERO_MIGRATE_TEST_PG_URL`; DB-free runs skip cleanly. These
//! tests drive the shipped generic `PostgresBackend<PgDevSession>` seam.

mod support;

use std::sync::atomic::{AtomicU64, Ordering};

use support::PgDevSession;
use zero_migrate::driver::SqlSession;
use zero_migrate::{
    ApplyError, Checksum, ChecksumInput, ExecutorConfig, Migration, MigrationBackend,
    MigrationFlags, MigrationId, PostgresBackend, SynchronizeIdentityStep,
};

fn token() -> String {
    static NEXT: AtomicU64 = AtomicU64::new(0);
    let sequence = NEXT.fetch_add(1, Ordering::SeqCst);
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("clock after epoch")
        .as_nanos();
    format!("{}_{}_{}", std::process::id(), nanos, sequence)
}

fn cfg_for(token: &str) -> ExecutorConfig {
    let mut cfg = ExecutorConfig::new(
        format!("identity_project_{token}"),
        format!("identity_app_{token}"),
    );
    cfg.pg.meta_schema = format!("identity_meta_{token}");
    cfg
}

async fn setup(session: &PgDevSession, cfg: &ExecutorConfig) {
    session
        .batch(&format!("CREATE SCHEMA \"{}\"", cfg.project_schema))
        .await
        .expect("create identity test schema");
    PostgresBackend::new_generic(session)
        .ensure_journal(cfg)
        .await
        .expect("create identity test journal");
}

async fn cleanup(session: &PgDevSession, cfg: &ExecutorConfig) {
    let _ = session
        .batch(&format!(
            "DROP SCHEMA IF EXISTS \"{}\" CASCADE; \
             DROP SCHEMA IF EXISTS \"{}\" CASCADE",
            cfg.project_schema, cfg.pg.meta_schema
        ))
        .await;
}

fn step(table: &str) -> SynchronizeIdentityStep {
    let flags = MigrationFlags::default();
    let up = format!("-- structured PostgreSQL identity synchronization for {table}.id");
    let checksum = Checksum::of(&ChecksumInput {
        up: &up,
        down: None,
        flags: &flags,
        owner_app: "app_test",
        depends_on: &[],
        supersedes: &[],
        preconditions: &[],
    });
    SynchronizeIdentityStep {
        migration: Migration {
            version: MigrationId::generate(),
            name: format!("synchronize identity {table}.id"),
            checksum,
            up,
            down: None,
            flags,
            owner_app: "app_test".into(),
            depends_on: Vec::new(),
            supersedes: Vec::new(),
            preconditions: Vec::new(),
            existence_guard: None,
        },
        schema: String::new(), // filled from ExecutorConfig by `run`
        table: table.into(),
        column: "id".into(),
        writes_quiesced: "live_pg_import_window".into(),
    }
}

async fn run(
    session: &PgDevSession,
    cfg: &ExecutorConfig,
    mut step: SynchronizeIdentityStep,
) -> Result<bool, ApplyError> {
    step.schema.clone_from(&cfg.project_schema);
    let backend = PostgresBackend::new_generic(session);
    backend.acquire_project_lock(cfg).await?;
    let result = backend
        .synchronize_identity(cfg, &step, "pg-identity-test")
        .await;
    backend.release_project_lock(cfg).await?;
    result
}

async fn next_value(session: &PgDevSession, schema: &str, table: &str, column: &str) -> i64 {
    session
        .query_one(
            "SELECT nextval(pg_get_serial_sequence(
                 format('%I.%I', $1::text, $2::text), $3::text
             )) AS value",
            &[schema.into(), table.into(), column.into()],
        )
        .await
        .expect("read next owned-sequence value")
        .try_get("value")
        .expect("decode next owned-sequence value")
}

async fn set_sequence(session: &PgDevSession, schema: &str, table: &str, value: i64) {
    session
        .query_one(
            "SELECT setval(
                 pg_get_serial_sequence(format('%I.%I', $1::text, $2::text), 'id'),
                 $3::bigint,
                 true
             ) AS value",
            &[schema.into(), table.into(), value.into()],
        )
        .await
        .expect("set owned-sequence value");
}

#[compio::test]
async fn advances_an_uncalled_identity_sequence_by_its_non_unit_increment() {
    let url = skip_if_no_pg!();
    let session = PgDevSession::connect(&url);
    let cfg = cfg_for(&token());
    setup(&session, &cfg).await;
    session
        .batch(&format!(
            "CREATE TABLE \"{}\".items (
               id bigint GENERATED BY DEFAULT AS IDENTITY
                 (START WITH 1 INCREMENT BY 5) PRIMARY KEY,
               payload text
             );
             INSERT INTO \"{}\".items (id, payload) VALUES (21, 'imported')",
            cfg.project_schema, cfg.project_schema
        ))
        .await
        .expect("create behind identity fixture");

    assert!(run(&session, &cfg, step("items"))
        .await
        .expect("synchronize behind identity"));
    assert_eq!(
        next_value(&session, &cfg.project_schema, "items", "id").await,
        26
    );
    cleanup(&session, &cfg).await;
}

#[compio::test]
async fn never_moves_an_already_ahead_sequence_backward() {
    let url = skip_if_no_pg!();
    let session = PgDevSession::connect(&url);
    let cfg = cfg_for(&token());
    setup(&session, &cfg).await;
    session
        .batch(&format!(
            "CREATE TABLE \"{}\".items (
               id bigint GENERATED BY DEFAULT AS IDENTITY
                 (START WITH 1 INCREMENT BY 5) PRIMARY KEY
             );
             INSERT INTO \"{}\".items (id) VALUES (21)",
            cfg.project_schema, cfg.project_schema
        ))
        .await
        .expect("create ahead identity fixture");
    set_sequence(&session, &cfg.project_schema, "items", 101).await;

    assert!(run(&session, &cfg, step("items"))
        .await
        .expect("journal monotonic identity no-op"));
    assert_eq!(
        next_value(&session, &cfg.project_schema, "items", "id").await,
        106
    );
    cleanup(&session, &cfg).await;
}

#[compio::test]
async fn already_ahead_out_of_bounds_imports_are_noops_in_both_directions() {
    let url = skip_if_no_pg!();
    let session = PgDevSession::connect(&url);
    let cfg = cfg_for(&token());
    setup(&session, &cfg).await;
    session
        .batch(&format!(
            "CREATE TABLE \"{}\".ascending_items (
               id bigint GENERATED BY DEFAULT AS IDENTITY
                 (START WITH 100 INCREMENT BY 5 MINVALUE 100) PRIMARY KEY
             );
             INSERT INTO \"{}\".ascending_items (id) VALUES (50);
             CREATE TABLE \"{}\".descending_items (
               id bigint GENERATED BY DEFAULT AS IDENTITY
                 (START WITH -100 INCREMENT BY -5 MAXVALUE -100) PRIMARY KEY
             );
             INSERT INTO \"{}\".descending_items (id) VALUES (-50)",
            cfg.project_schema, cfg.project_schema, cfg.project_schema, cfg.project_schema
        ))
        .await
        .expect("create bounded ahead identity fixtures");

    assert!(run(&session, &cfg, step("ascending_items"))
        .await
        .expect("ascending out-of-bounds import is already safe"));
    assert_eq!(
        next_value(&session, &cfg.project_schema, "ascending_items", "id").await,
        100
    );

    assert!(run(&session, &cfg, step("descending_items"))
        .await
        .expect("descending out-of-bounds import is already safe"));
    assert_eq!(
        next_value(&session, &cfg.project_schema, "descending_items", "id").await,
        -100
    );
    cleanup(&session, &cfg).await;
}

#[compio::test]
async fn respects_a_descending_owned_sequence() {
    let url = skip_if_no_pg!();
    let session = PgDevSession::connect(&url);
    let cfg = cfg_for(&token());
    setup(&session, &cfg).await;
    session
        .batch(&format!(
            "CREATE TABLE \"{}\".descending_items (
               id bigint GENERATED BY DEFAULT AS IDENTITY
                 (START WITH -1 INCREMENT BY -5 MINVALUE -9223372036854775807 MAXVALUE -1)
                 PRIMARY KEY
             );
             INSERT INTO \"{}\".descending_items (id) VALUES (-21)",
            cfg.project_schema, cfg.project_schema
        ))
        .await
        .expect("create descending identity fixture");

    assert!(run(&session, &cfg, step("descending_items"))
        .await
        .expect("synchronize descending identity"));
    assert_eq!(
        next_value(&session, &cfg.project_schema, "descending_items", "id").await,
        -26
    );
    cleanup(&session, &cfg).await;
}

#[compio::test]
async fn supports_serial_and_rejects_a_column_without_an_owned_sequence() {
    let url = skip_if_no_pg!();
    let session = PgDevSession::connect(&url);
    let cfg = cfg_for(&token());
    setup(&session, &cfg).await;
    session
        .batch(&format!(
            "CREATE TABLE \"{}\".serial_items (id bigserial PRIMARY KEY);
             INSERT INTO \"{}\".serial_items (id) VALUES (41);
             CREATE TABLE \"{}\".plain_items (id bigint PRIMARY KEY)",
            cfg.project_schema, cfg.project_schema, cfg.project_schema
        ))
        .await
        .expect("create serial and unowned fixtures");

    assert!(run(&session, &cfg, step("serial_items"))
        .await
        .expect("synchronize serial sequence"));
    assert_eq!(
        next_value(&session, &cfg.project_schema, "serial_items", "id").await,
        42
    );

    let error = run(&session, &cfg, step("plain_items"))
        .await
        .expect_err("plain bigint must be rejected");
    assert!(error
        .to_string()
        .contains("no owned PostgreSQL identity/serial sequence"));
    cleanup(&session, &cfg).await;
}
