/**
 * @zeroship/ui — public surface.
 *
 * Mid-rebuild. The exports below are intentionally narrow: theme primitives
 * plus the styled components that have landed so far, plus temporary
 * native-HTML placeholders for the names other packages still import.
 *
 * As styled components land they replace the corresponding placeholder
 * exports in this file.
 */
import "./styles.css";

export {
  DEFAULT_THEME,
  THEME_STORAGE_KEY,
  ThemeProvider,
  isThemeName,
  themeLabels,
  themes,
  useTheme,
  type ThemeName,
  type ThemeProviderProps,
} from "./theme";

// Real, styled components.
export {
  Button,
  type ButtonProps,
  type ButtonIntent,
  type ButtonSize,
  type ButtonVariant,
  Field,
  useFieldVisualSize,
  useFieldDisabledContext,
  type FieldProps,
  type FieldOrientation,
  type FieldSize,
  type FieldRequiredProps,
  Input,
  type InputProps,
  type InputSize,
  type InputVariant,
  Card,
  type CardProps,
  type CardVariant,
  type CardSize,
  type CardMediaSide,
  type CardMediaProps,
  type CardFooterAlign,
  type CardFooterDivider,
  type CardFooterProps,
  type CardHeaderProps,
  type CardTitleProps,
  type CardDescriptionProps,
  type CardActionProps,
  type CardContentProps,
  Dialog,
  createDialogHandle,
  type DialogProps,
  type DialogSize,
  type DialogPlacement,
  type DialogBackdropTint,
  type DialogBackdropProps,
  type DialogPopupProps,
  type DialogHeaderProps,
  type DialogTitleProps,
  type DialogDescriptionProps,
  type DialogBodyProps,
  type DialogFooterProps,
  type DialogCloseProps,
  type DialogTriggerProps,
  type DialogPortalProps,
  type DialogViewportProps,
  Checkbox,
  type CheckboxProps,
  type CheckboxSize,
  type CheckboxVariant,
  CheckboxGroup,
  type CheckboxGroupProps,
  type CheckboxGroupOrientation,
  type CheckboxGroupValue,
  Switch,
  type SwitchProps,
  type SwitchSize,
  Radio,
  RadioGroup,
  type RadioProps,
  type RadioGroupProps,
  type RadioSize,
  type RadioOrientation,
  Toggle,
  ToggleGroup,
  type ToggleProps,
  type ToggleGroupProps,
  type ToggleSize,
  type ToggleVariant,
  type ToggleOrientation,
  Select,
  type SelectProps,
  type SelectSingleProps,
  type SelectMultipleProps,
  type SelectItemProps,
  type SelectGroupProps,
  type SelectGroupLabelProps,
  type SelectSeparatorProps,
  type SelectSize,
  type SelectVariant,
  type SelectAlign,
  type SelectPlacement,
  Combobox,
  type ComboboxProps,
  type ComboboxSingleProps,
  type ComboboxMultipleProps,
  type ComboboxItemProps,
  type ComboboxEmptyProps,
  type ComboboxChipProps,
  type ComboboxSize,
  type ComboboxVariant,
  type ComboboxAlign,
  type ComboboxPlacement,
  Autocomplete,
  type AutocompleteProps,
  type AutocompleteItemProps,
  type AutocompleteSize,
  type AutocompleteVariant,
  type AutocompleteAlign,
  type AutocompletePlacement,
  NumberField,
  type NumberFieldProps,
  type NumberFieldSize,
  type NumberFieldVariant,
  Slider,
  type SliderProps,
  type SliderSingleProps,
  type SliderRangeProps,
  type SliderRangeUncontrolledProps,
  type SliderSize,
  type SliderVariant,
  type SliderOrientation,
  Form,
  type FormActions,
  type FormProps,
  type FormVariant,
  Fieldset,
  useFieldsetDisabledContext,
  type FieldsetLegendProps,
  type FieldsetProps,
  type FieldsetSize,
  AlertDialog,
  type AlertDialogProps,
  type AlertDialogSize,
  type AlertDialogActionTone,
  type AlertDialogTriggerProps,
  type AlertDialogPortalProps,
  type AlertDialogBackdropProps,
  type AlertDialogPopupProps,
  type AlertDialogHeaderProps,
  type AlertDialogTitleProps,
  type AlertDialogDescriptionProps,
  type AlertDialogBodyProps,
  type AlertDialogFooterProps,
  type AlertDialogCancelProps,
  type AlertDialogActionProps,
  Popover,
  createPopoverHandle,
  type PopoverProps,
  type PopoverSide,
  type PopoverAlign,
  type PopoverTriggerProps,
  type PopoverPortalProps,
  type PopoverBackdropProps,
  type PopoverPopupProps,
  type PopoverTitleProps,
  type PopoverDescriptionProps,
  type PopoverArrowProps,
  type PopoverCloseProps,
  type PopoverComponent,
  Tooltip,
  createTooltipHandle,
  type TooltipProps,
  type TooltipSide,
  type TooltipAlign,
  type TooltipProviderProps,
  type TooltipTriggerProps,
  type TooltipPortalProps,
  type TooltipPopupProps,
  type TooltipArrowProps,
  type TooltipComponent,
  OtpField,
  type OtpFieldProps,
  type OtpFieldSize,
  type OtpFieldVariant,
  type OtpFieldInputProps,
  Meter,
  meterStatus,
  type MeterProps,
  type MeterSize,
  type MeterIntent,
  Progress,
  type ProgressProps,
  type ProgressSize,
  Avatar,
  AvatarRoot,
  AvatarImage,
  AvatarFallback,
  type AvatarProps,
  type AvatarRootProps,
  type AvatarImageProps,
  type AvatarFallbackProps,
  type AvatarSize,
  type AvatarShape,
  Separator,
  type SeparatorProps,
  type SeparatorOrientation,
  type SeparatorVariant,
  PreviewCard,
  createPreviewCardHandle,
  type PreviewCardProps,
  type PreviewCardSide,
  type PreviewCardAlign,
  type PreviewCardSize,
  type PreviewCardTriggerProps,
  type PreviewCardPortalProps,
  type PreviewCardBackdropProps,
  type PreviewCardPositionerProps,
  type PreviewCardPopupProps,
  type PreviewCardArrowProps,
  type PreviewCardComponent,
  type PreviewCardHandle,
  Menu,
  createMenuHandle,
  type MenuProps,
  type MenuSide,
  type MenuAlign,
  type MenuTriggerProps,
  type MenuPortalProps,
  type MenuBackdropProps,
  type MenuPopupProps,
  type MenuItemProps,
  type MenuGroupProps,
  type MenuGroupLabelProps,
  type MenuSeparatorProps,
  type MenuCheckboxItemProps,
  type MenuRadioGroupProps,
  type MenuRadioItemProps,
  type MenuLinkItemProps,
  type MenuSubmenuProps,
  type MenuArrowProps,
  type MenuComponent,
  ContextMenu,
  type ContextMenuProps,
  type ContextMenuTriggerProps,
  type ContextMenuComponent,
  Tabs,
  type TabsProps,
  type TabsListProps,
  type TabsTabProps,
  type TabsPanelProps,
  type TabsIndicatorProps,
  type TabsSize,
  type TabsVariant,
  type TabsOrientation,
  Menubar,
  type MenubarProps,
  type MenubarOrientation,
  Toolbar,
  type ToolbarProps,
  type ToolbarOrientation,
  type ToolbarButtonProps,
  type ToolbarLinkProps,
  type ToolbarInputProps,
  type ToolbarSeparatorProps,
  type ToolbarComponent,
  Drawer,
  type DrawerProps,
  type DrawerSide,
  type DrawerSize,
  type DrawerTriggerProps,
  type DrawerPortalProps,
  type DrawerBackdropProps,
  type DrawerContentProps,
  type DrawerHeaderProps,
  type DrawerTitleProps,
  type DrawerDescriptionProps,
  type DrawerBodyProps,
  type DrawerFooterProps,
  type DrawerCloseProps,
  NavigationMenu,
  type NavigationMenuProps,
  type NavigationMenuComponent,
  type NavMenuSide,
  type NavMenuAlign,
  type NavMenuOrientation,
  type NavMenuListProps,
  type NavMenuItemProps,
  type NavMenuTriggerProps,
  type NavMenuContentProps,
  type NavMenuLinkProps,
  type NavMenuPortalProps,
  type NavMenuPositionerProps,
  type NavMenuPopupProps,
  type NavMenuViewportProps,
  type NavMenuArrowProps,
  type NavMenuIconProps,
  Accordion,
  AccordionItem,
  AccordionHeader,
  AccordionTrigger,
  AccordionPanel,
  type AccordionRootProps,
  type AccordionItemProps,
  type AccordionHeaderProps,
  type AccordionTriggerProps,
  type AccordionPanelProps,
  type AccordionOrientation,
  Collapsible,
  CollapsibleRoot,
  CollapsibleTrigger,
  CollapsiblePanel,
  type CollapsibleRootProps,
  type CollapsibleTriggerProps,
  type CollapsiblePanelProps,
  Toast,
  useToast,
  useToastManager,
  type ToastComponent,
  type ToastPayload,
  type ToastProviderProps,
  type ToastViewportProps,
  type ToastPortalProps,
  type ToastRootProps,
  type ToastTitleProps,
  type ToastDescriptionProps,
  type ToastActionProps,
  type ToastCloseProps,
  type ToastVariant,
  type ToastPosition,
  type ToastSwipeDirection,
  type UseToastReturn,
  type ToastEmitter,
  type ToastOptions,
  ScrollArea,
  type ScrollAreaProps,
  type ScrollAreaType,
  type ScrollAreaOrientation,
  type ScrollAreaRootProps,
  type ScrollAreaViewportProps,
  type ScrollAreaContentProps,
  type ScrollAreaScrollbarProps,
  type ScrollAreaThumbProps,
  type ScrollAreaCornerProps,
} from "./components";

// Temporary placeholders — see ./placeholders.tsx for migration tracking.
export {
  Badge,
  type BadgeProps,
} from "./placeholders";
