#!/usr/bin/env bash
# ============================================================================
# Regenerate (or verify) deploy/ops/caddy-claimed-hosts.json - the record of
# every hostname the edge config claims, as answered by CADDY ITSELF.
#
# WHY THIS EXISTS. crates/control/src/reserved_names.rs must know which
# hostname labels under {$ZEROSHIP_DOMAIN} the edge already claims, so
# RESERVED_APP_NAMES can refuse them to creators. It used to answer that by
# parsing deploy/ops/Caddyfile with a hand-written text parser, and that parser
# had a silent hole every time it met a spelling it had not been taught:
#
#   MEASURED 2026-08-20 against the parser as it stood. Each of these routes a
#   host away from creator apps, and each returned a set with NO new label:
#     @status host status.{$ZEROSHIP_DOMAIN} + handle @status   -> Ok, unchanged
#     @h header Host h.{$ZEROSHIP_DOMAIN}    + handle @h        -> Ok([])
#     @b { host b.{$ZEROSHIP_DOMAIN} }       + handle @b        -> Ok([])
#     import sites/*.caddy  (a whole site block in another file) -> Ok([])
#
# The fix is not a better parser. Caddyfile is Caddy's language, it grows
# matcher modules we do not control, and `@x expression {host}.startsWith(...)`
# is not statically decidable at all. So we stop parsing it: `caddy adapt`
# lowers the Caddyfile to Caddy's JSON config, in which EVERY host claim -
# site block, named matcher, header matcher, imported file - is a concrete
# `match` entry. Verified 2026-08-20: adapt resolves `{$ENV:default}`, resolves
# `import`, and emits the matcher host as a nested `match[].host[]`.
#
# The adapted config is committed so the Rust gate needs no Caddy, no docker
# and no network to run - it is an `include_str!` like the Caddyfile was. What
# keeps it honest is the `caddyfile_sha256` field: the Rust gate recomputes it
# over the Caddyfile's bytes and REFUSES if they differ, so editing the edge
# without regenerating goes red instead of quietly leaving the gate asserting
# about a config the edge no longer has.
#
# WHAT THIS SCRIPT DOES NOT PROVE. `--check` re-derives the artifact from the
# repo's Caddyfile. It says nothing about the Caddyfile deployed on a host;
# that is deploy/scripts/deploy-remote.sh's scp, which overwrites the host copy
# from this repo on every roll.
#
# USAGE
#   deploy/ops/caddy-claimed-hosts.sh --write   # regenerate the artifact
#   deploy/ops/caddy-claimed-hosts.sh --check   # fail if it is stale or edited
#
#   # regenerate a TEST FIXTURE from some other Caddyfile:
#   deploy/ops/caddy-claimed-hosts.sh --write \
#     --caddyfile crates/control/testdata/edge_matcher_claim.Caddyfile \
#     --out       crates/control/testdata/edge_matcher_claim.json
#
# The fixtures under crates/control/testdata/ are generated by this same
# script on purpose. A hand-written "adapted config" would be a fixture that
# proves the extractor handles a shape CADDY DOES NOT PRODUCE, which is worth
# nothing; these are Caddy's real output for a real Caddyfile.
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CADDYFILE="$ROOT/deploy/ops/Caddyfile"
ARTIFACT="$ROOT/deploy/ops/caddy-claimed-hosts.json"

# The domain the Caddyfile is adapted against. `.invalid` is reserved by
# RFC 2606 and can never be a real deployment domain, so a host in the adapted
# config that does NOT end in it is a literal domain baked into the edge -
# which the Caddyfile's own header forbids, and which the Rust gate refuses.
SENTINEL="zsdomain.invalid"

MODE=""
EXPLICIT_TARGET=""
while [ $# -gt 0 ]; do
  case "$1" in
    --write) MODE=write; shift ;;
    --check) MODE=check; shift ;;
    --caddyfile) CADDYFILE="$2"; EXPLICIT_TARGET=1; shift 2 ;;
    --out) ARTIFACT="$2"; EXPLICIT_TARGET=1; shift 2 ;;
    *)
      echo "usage: $0 --write|--check [--caddyfile PATH] [--out PATH]" >&2
      exit 2
      ;;
  esac
done
if [ -z "$MODE" ]; then
  echo "usage: $0 --write|--check [--caddyfile PATH] [--out PATH]" >&2
  exit 2
fi

[ -f "$CADDYFILE" ] || { echo "REFUSED: $CADDYFILE not found." >&2; exit 1; }

# THE CADDY THAT ANSWERS MUST BE THE CADDY THAT RUNS. Adapting is a question
# about a specific Caddy's behaviour, so asking a different build than the edge
# is a wrong answer that still looks like an answer. The image is therefore read
# out of the compose file that runs the edge, not written here - bumping the
# edge bumps the adapter, in one place.
COMPOSE="$ROOT/deploy/compose/docker-compose.yml"
CADDY_IMAGE="$(
  awk '
    /^  caddy:[[:space:]]*$/ { in_svc = 1; next }
    /^  [a-z]/               { in_svc = 0 }
    in_svc && /^    image:/  { print $2; exit }
  ' "$COMPOSE" 2>/dev/null
)"
if [ -z "$CADDY_IMAGE" ]; then
  echo "REFUSED: no image found for the 'caddy' service in $COMPOSE, so there is" >&2
  echo "         no way to know which Caddy the edge runs. Adapting with some" >&2
  echo "         other build would answer a question about a different Caddy." >&2
  exit 1
fi

# Docker with the pinned image FIRST, a local binary only as a fallback: a
# developer's `caddy` is whatever version they happen to have, and would
# generate an artifact CI then disagrees with. REFUSE rather than skip if
# neither is there - a gate that silently does nothing when its tool is missing
# prints the same green as a gate that ran and passed.
CADDY_HOW=""
if command -v docker >/dev/null 2>&1; then
  CADDY_HOW=docker
elif command -v caddy >/dev/null 2>&1; then
  CADDY_HOW=local
  echo "warn: docker is unavailable, so this is using the local caddy binary" >&2
  echo "      rather than the edge's pinned $CADDY_IMAGE. If they differ, the" >&2
  echo "      artifact may not describe the Caddy that actually runs." >&2
else
  echo "REFUSED: neither 'docker' nor a 'caddy' binary is available, so the edge" >&2
  echo "         config cannot be adapted. This check cannot be skipped:" >&2
  echo "         make docker able to run $CADDY_IMAGE, or install caddy." >&2
  exit 1
fi

adapt() {
  if [ "$CADDY_HOW" = docker ]; then
    # Mount the Caddyfile's own directory, so `import ./sibling` resolves the
    # same way it would for the caddy binary. An import reaching OUTSIDE that
    # directory fails to adapt, which is an error here rather than a config
    # this cannot see.
    docker run --rm -i \
      -e ZEROSHIP_DOMAIN="$SENTINEL" \
      -v "$(cd "$(dirname "$CADDYFILE")" && pwd):/w:ro" -w /w \
      "$CADDY_IMAGE" \
      caddy adapt --config "$(basename "$CADDYFILE")" --adapter caddyfile --pretty
  else
    ZEROSHIP_DOMAIN="$SENTINEL" caddy adapt \
      --config "$CADDYFILE" --adapter caddyfile --pretty
  fi
}

caddy_version() {
  if [ "$CADDY_HOW" = docker ]; then
    docker run --rm "$CADDY_IMAGE" caddy version 2>/dev/null | head -1
  else
    caddy version 2>/dev/null | head -1
  fi
}

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
VERSION="$(caddy_version)"
RC=0

# Build the provenance-wrapped artifact for $CADDYFILE into $1.
build_artifact() {
  local out="$1" sha
  sha="$(sha256sum "$CADDYFILE" | cut -d' ' -f1)"
  # `caddy adapt` writes warnings to stderr and the config to stdout. Let
  # stderr through so an adapt warning is visible rather than swallowed.
  adapt > "$TMP/config.json"
  # The adapted config is nested under `config` alongside the provenance
  # fields, so the Rust gate reads one file and can tell whether it describes
  # the Caddyfile in front of it.
  jq -n \
    --arg sha "$sha" \
    --arg sentinel "$SENTINEL" \
    --arg version "$VERSION" \
    --slurpfile config "$TMP/config.json" \
    '{
       _comment: "GENERATED by deploy/ops/caddy-claimed-hosts.sh --write. Do not hand-edit: crates/control/src/reserved_names.rs reads it as the authority on which hostnames the edge claims.",
       caddyfile_sha256: $sha,
       sentinel_domain: $sentinel,
       caddy_version: $version,
       config: $config[0]
     }' > "$out"
}

# `caddy_version` is provenance, not a claim about the edge, and it moves every
# time the image is bumped. Compare everything else.
strip_version() { jq 'del(.caddy_version)' "$1"; }

# Write or verify ONE (Caddyfile -> artifact) pair, per $MODE.
emit() {
  local label="$1"
  build_artifact "$TMP/artifact.json"

  if [ "$MODE" = write ]; then
    mv "$TMP/artifact.json" "$ARTIFACT"
    echo "ok  wrote ${ARTIFACT#"$ROOT/"}  ($label)"
    return 0
  fi

  if [ ! -f "$ARTIFACT" ]; then
    echo "FAIL ${ARTIFACT#"$ROOT/"} does not exist. Run: $0 --write" >&2
    RC=1
    return 0
  fi
  if diff -u <(strip_version "$ARTIFACT") <(strip_version "$TMP/artifact.json") \
       > "$TMP/diff" 2>&1; then
    echo "ok  ${ARTIFACT#"$ROOT/"} matches ${CADDYFILE#"$ROOT/"} as Caddy adapts it"
    return 0
  fi
  echo "FAIL ${ARTIFACT#"$ROOT/"} does NOT match what Caddy makes of ${CADDYFILE#"$ROOT/"}." >&2
  echo "     Either the Caddyfile changed without regenerating, or the artifact" >&2
  echo "     was hand-edited. Run: $0 --write" >&2
  echo >&2
  sed -n '1,60p' "$TMP/diff" >&2
  RC=1
}

# Explicit single-target mode: do exactly what was asked and nothing else.
if [ -n "$EXPLICIT_TARGET" ]; then
  emit "explicit target"
  exit "$RC"
fi

# ---------------------------------------------------------------------------
# Default: the live edge AND the fixtures that pin the gate's behaviour.
#
# The fixtures are regenerated here rather than by hand because they are only
# meaningful as a MATCHED PAIR against the live Caddyfile: `edge_control` must
# BE the current edge (so the passing arm is the real thing) and
# `edge_matcher_claim` must be that same file plus one matcher and nothing
# else (so the failing arm differs in one variable). Kept by hand, one
# Caddyfile edit silently makes the control arm a fixture of a config that no
# longer ships.
# ---------------------------------------------------------------------------
FIXTURES="$ROOT/crates/control/testdata"

emit "the live edge"

# The control arm: byte-identical to the live edge.
if [ "$MODE" = write ]; then
  cp "$CADDYFILE" "$FIXTURES/edge_control.Caddyfile"
else
  diff -q "$CADDYFILE" "$FIXTURES/edge_control.Caddyfile" > /dev/null 2>&1 || {
    echo "FAIL crates/control/testdata/edge_control.Caddyfile is not the live edge config." >&2
    echo "     The gate's passing arm must be what actually ships. Run: $0 --write" >&2
    RC=1
  }
fi

# The failing arm: the same file plus a host claimed by a MATCHER rather than a
# site block - the shape the text parser this replaced could not see.
mutate_add_matcher() {
  awk '
    /^http:\/\/\*\./ {
      print
      print "\t@status host status.{$ZEROSHIP_DOMAIN:zeroship.localhost}"
      print "\thandle @status {"
      print "\t\treverse_proxy status:9099"
      print "\t}"
      next
    }
    { print }
  ' "$CADDYFILE"
}
mutate_add_matcher > "$TMP/edge_matcher_claim.Caddyfile"
# The mutation must have APPLIED. If the wildcard block is ever rewritten so
# the awk rule stops matching, an unmutated fixture would regenerate as a copy
# of the control and the gate's failing arm would silently become a second
# passing arm - green, and proving nothing.
grep -q '@status host status\.' "$TMP/edge_matcher_claim.Caddyfile" || {
  echo "REFUSED: the matcher mutation did not apply to $CADDYFILE." >&2
  echo "         The wildcard site block no longer matches the awk rule, so the" >&2
  echo "         gate's failing arm would be a copy of its passing arm." >&2
  exit 1
}

if [ "$MODE" = write ]; then
  cp "$TMP/edge_matcher_claim.Caddyfile" "$FIXTURES/edge_matcher_claim.Caddyfile"
elif ! diff -q "$TMP/edge_matcher_claim.Caddyfile" \
       "$FIXTURES/edge_matcher_claim.Caddyfile" > /dev/null 2>&1; then
  echo "FAIL crates/control/testdata/edge_matcher_claim.Caddyfile is not the live" >&2
  echo "     edge plus the matcher. Run: $0 --write" >&2
  RC=1
fi

for name in edge_control edge_matcher_claim; do
  CADDYFILE="$FIXTURES/$name.Caddyfile"
  ARTIFACT="$FIXTURES/$name.json"
  emit "gate fixture"
done

exit "$RC"
