-- ops/postgres-init.sql - runs ONCE on a fresh postgres data dir
-- (mounted into /docker-entrypoint-initdb.d/).
--
-- The whole platform shares ONE database, and `zeroship` is the schema holding
-- platform state. It is not the only system schema: `service_authn` holds the
-- service-assertion replay store, which is deliberately outside `zeroship` and
-- deliberately NOT on any role's search_path, since every statement against it
-- is qualified. Most queries here are fully qualified
-- (`zeroship.apps`), but a few reference objects UNQUALIFIED (e.g.
-- `crates/control/src/admin_handlers.rs` `UPDATE apps ...`), so every connection
-- needs `zeroship` on its search_path. Postgres's default role search_path
-- ("$user", public) omits it, which makes those queries fail with
-- `relation "apps" does not exist`.
--
-- Setting the role default here (it's allowed to list a schema that doesn't
-- exist yet - it's created by the platform migration runner on first
-- boot) gives every connection the right resolution order.
--
-- This covers `postgres` only - the role the `migrate` service connects as. The
-- per-service login roles (zeroship_{auth,control,gateway}; sandbox_{app,
-- audit,gdpr}) get their OWN `ALTER ROLE ... SET search_path = zeroship, public`
-- inside migrations V0025/V0026, since those roles do not exist yet at
-- initdb time (the platform migration runner creates them on first boot).
ALTER ROLE postgres SET search_path = zeroship, public;
