/**
 * gen-types orchestrator — the in-process schema-artifact emitter the
 * vite-plugin links (no CLI subprocess).
 *
 * Two sources, one Rust renderer (the `zero-migrate-node` `genArtifacts` verb):
 *  - MANUAL — {@link genTypesFromSchemaFile}: evaluate a committed `schema.ts`
 *    (`@zeroship/db` builders) → `CollectionDescriptorDto[]` → `genArtifacts`.
 *  - GENERATED — {@link genTypesFromMigrations}: record `op.*` migrations →
 *    IR envelopes → `genArtifacts`.
 *
 * Both write `schema.runtime.json` (the v1 RuntimeSchemaDescriptor packed into
 * the `.zship`). They differ only in `env.db.ts`:
 *  - GENERATED writes the inline `const schema = { … } as const` literal
 *    `genArtifacts` emits (migrations are the source of truth).
 *  - MANUAL writes an AUGMENTATION over the author's `schema.ts` (§11.3): the
 *    author owns `schema.ts`; `env.db.ts` just re-exports its typing.
 *
 * `--check` (`{ check: true }`) regenerates in memory and diffs against the
 * committed artifacts — a HARD drift gate, no write. There is no CLI to be
 * absent, so drift is always caught.
 */

import { promises as fs } from "node:fs";
import { dirname, relative, resolve } from "node:path";

import { loadMigrateAddon, type GenArtifactsReply } from "./addon.js";
import { recordMigrationsDir } from "./recorder.js";
import { evaluateSchemaModule, schemaModuleToDescriptors } from "./manual.js";

/** The two committed artifact filenames gen-types emits. */
export const RUNTIME_DESCRIPTOR_FILE = "schema.runtime.json";
/** The generated `env.db` typings module. A real `.ts` (NOT a `.d.ts`): the
 *  generated variant carries `const schema = <builder calls> as const`, which is
 *  illegal in a `.d.ts` ambient context. */
export const ENV_DB_FILE = "env.db.ts";

/** The default gen-types output dir (relative to root). COMMITTED (not the
 *  gitignored `.zeroship/`) so apps include its `env.db.ts` in tsconfig. */
export const GEN_TYPES_OUT_DEFAULT = "generated/zeroship";

/** The banner every MANUAL `env.db.ts` carries (the GENERATED variant's banner is
 *  rendered by the Rust verb). */
const MANUAL_ENV_DB_BANNER =
  "// GENERATED by @zeroship/vite-plugin gen-types (manual schema source) — DO NOT EDIT.\n" +
  "//\n" +
  "// The typed `env.db` surface, augmented over the author's `schema.ts`.\n" +
  "// `schema.ts` is the source of truth; this file re-exports its typing so the\n" +
  "// worker's `env.db` is `Db<typeof schema>`. Re-run gen-types after schema\n" +
  "// changes; the gen-types --check CI gate fails if this file drifts.\n";

/** Options common to both sources. */
export interface GenTypesResult {
  /** `"written"` (regenerated) or `"checked"` (drift gate passed, no write). */
  status: "written" | "checked";
  /** The two artifact filenames relative to the out dir. */
  files: readonly [typeof ENV_DB_FILE, typeof RUNTIME_DESCRIPTOR_FILE];
}

/**
 * MANUAL source. Evaluate `schemaTsPath` → descriptors → `genArtifacts`, then
 * write (or `--check`) `schema.runtime.json` + an augmentation `env.db.ts`.
 */
export async function genTypesFromSchemaFile(
  schemaTsPath: string,
  outDir: string,
  opts: { check?: boolean } = {},
): Promise<GenTypesResult> {
  const declared = await evaluateSchemaModule(schemaTsPath);
  const descriptors = schemaModuleToDescriptors(declared);

  const reply = loadMigrateAddon().genArtifacts({
    descriptors,
    projectSchema: "public",
  });
  const runtimeJson = unwrap(reply, "manual schema source");

  const envDbTs = renderManualEnvDb(outDir, schemaTsPath);
  return emit(outDir, envDbTs, runtimeJson, opts.check ?? false);
}

/**
 * GENERATED source. Record every `.ts` migration under `migrationsDir` →
 * envelopes → `genArtifacts`, then write (or `--check`) BOTH the inline
 * `env.db.ts` literal + `schema.runtime.json`. No subprocess.
 */
export async function genTypesFromMigrations(
  migrationsDir: string,
  outDir: string,
  opts: { check?: boolean } = {},
): Promise<GenTypesResult> {
  const envelopes = await recordMigrationsDir(migrationsDir);

  const reply = loadMigrateAddon().genArtifacts({
    envelopes,
    projectSchema: "public",
  });
  const runtimeJson = unwrap(reply, "generated migration source");
  const envDbTs = reply.envDbTs;
  if (envDbTs === undefined) {
    throw new Error(
      "gen-types: the generated source produced no env.db.ts (genArtifacts.envDbTs was empty)",
    );
  }
  return emit(outDir, envDbTs, runtimeJson, opts.check ?? false);
}

/** Unwrap a `genArtifacts` reply, turning the soft `{ ok:false, error }` arm into
 *  a thrown build error and asserting `runtimeJson` is present. */
function unwrap(reply: GenArtifactsReply, source: string): string {
  if (!reply.ok) {
    throw new Error(`gen-types: ${source} failed to render — ${reply.error ?? "unknown error"}`);
  }
  if (reply.runtimeJson === undefined) {
    throw new Error(`gen-types: ${source} produced no schema.runtime.json`);
  }
  return reply.runtimeJson;
}

/**
 * Render the MANUAL `env.db.ts` augmentation (§11.3): import the author's
 * `schema` and declare `Env.db = Db<typeof schema>`. The import path is relative
 * from the out dir to `schema.ts`, extension-stripped, always `./`-anchored and
 * POSIX-slashed for a stable, cross-platform module specifier.
 */
function renderManualEnvDb(outDir: string, schemaTsPath: string): string {
  let rel = relative(resolve(outDir), resolve(schemaTsPath));
  rel = rel.replace(/\.ts$/, "");
  rel = rel.split(/[\\/]/).join("/");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return (
    MANUAL_ENV_DB_BANNER +
    `import { type Db } from "@zeroship/db";\n` +
    `import { schema } from "${rel}";\n\n` +
    `declare module "zeroship" {\n` +
    `  interface Env {\n` +
    `    db: Db<typeof schema>;\n` +
    `  }\n` +
    `}\n\n` +
    `export {};\n`
  );
}

/**
 * Emit or check the two artifacts. When `check`, regenerate in memory and diff
 * against the committed files — a hard error naming the first drifted file.
 * Otherwise write both (creating the out dir).
 */
async function emit(
  outDir: string,
  envDbTs: string,
  runtimeJson: string,
  check: boolean,
): Promise<GenTypesResult> {
  const envPath = resolve(outDir, ENV_DB_FILE);
  const jsonPath = resolve(outDir, RUNTIME_DESCRIPTOR_FILE);

  if (check) {
    await assertNoDrift(envPath, envDbTs, ENV_DB_FILE);
    await assertNoDrift(jsonPath, runtimeJson, RUNTIME_DESCRIPTOR_FILE);
    return { status: "checked", files: [ENV_DB_FILE, RUNTIME_DESCRIPTOR_FILE] };
  }

  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(envPath, envDbTs, "utf8");
  await fs.writeFile(jsonPath, runtimeJson, "utf8");
  return { status: "written", files: [ENV_DB_FILE, RUNTIME_DESCRIPTOR_FILE] };
}

/** Assert the committed artifact byte-matches the freshly-generated one. */
async function assertNoDrift(
  path: string,
  fresh: string,
  file: string,
): Promise<void> {
  let committed: string;
  try {
    committed = await fs.readFile(path, "utf8");
  } catch {
    throw new Error(
      `gen-types --check: ${file} is missing at ${path} — run gen-types to generate it`,
    );
  }
  if (committed !== fresh) {
    throw new Error(
      `gen-types --check: ${file} is STALE — regenerate it (the committed artifact ` +
        `drifted from the schema source).\n${firstDivergence(committed, fresh)}`,
    );
  }
}

/** A short human-readable preview of the first line that diverges. */
function firstDivergence(a: string, b: string): string {
  const al = a.split("\n");
  const bl = b.split("\n");
  const n = Math.max(al.length, bl.length);
  for (let i = 0; i < n; i++) {
    if (al[i] !== bl[i]) {
      return (
        `  first divergence at line ${i + 1}:\n` +
        `  - committed: ${JSON.stringify(al[i] ?? "<missing>")}\n` +
        `  + fresh:     ${JSON.stringify(bl[i] ?? "<missing>")}`
      );
    }
  }
  return "  (files differ in trailing content)";
}

export { dirname as _dirname };
