/**
 * The generated-source `env.db.ts` renderer.
 *
 * The schema engine's own `envDbTs` is a round-trip of the folded IR back into
 * the *migration authoring* DSL (`import ... from "@zeroship/migrate"`,
 * `t.text().primaryKey()`). That is the engine's artifact, not ours: a deployed
 * app depends on `@zeroship/db`, never on the migration engine, and the whole
 * point of this file is to type `env.db`. So gen-types renders its own module
 * from the runtime descriptor instead.
 *
 * The emitted module reconstructs `const schema = { ... } as const` out of
 * `@zeroship/db` `t.*()` builder CALLS - not a hand-rolled interface - because
 * the SDK's type inference keys only off `TypeBuilder`, so the same
 * `InferSchema`/`Row`/`Collections`/`Db` chain a declared schema flows through
 * also applies here. It is a real `.ts` module (never a `.d.ts`): `const x =
 * <call expr>` is illegal in an ambient declaration context.
 */

/** One column's wire `FieldDef`, as carried by `schema.runtime.json`. */
export interface RuntimeFieldDef {
  type?: string;
  required?: boolean;
  unique?: boolean;
  min?: number;
  max?: number;
  enum?: unknown[];
  mask?: { kind?: string; classification?: string };
  default?: unknown;
  encrypted?: { keyId?: string; wraps?: string };
  idPrefix?: string;
  refTarget?: string;
  onDelete?: string;
  onUpdate?: string;
  deferrable?: boolean;
  vectorDims?: number;
  vectorMetric?: string;
  [key: string]: unknown;
}

/** Runtime-visible collection options. */
export interface RuntimeOptions {
  softDelete?: boolean;
  versioning?: boolean;
  strictness?: string;
}

/** One runtime-visible plain/unique index. */
export interface RuntimeIndex {
  name: string;
  fields: string[];
  unique?: boolean;
}

/** One collection of the v2 RuntimeSchemaDescriptor. */
export interface RuntimeCollection {
  fields?: Record<string, RuntimeFieldDef>;
  options?: RuntimeOptions;
  indexes?: RuntimeIndex[];
}

/** The v2 RuntimeSchemaDescriptor (`schema.runtime.json`). */
export interface RuntimeDescriptor {
  version?: number;
  collections?: Record<string, RuntimeCollection>;
}

/**
 * The 7 platform-injected system columns. They live in `schema.runtime.json`
 * (the runtime installs them), but they are elided from the `env.db.ts` literal
 * because `@zeroship/db` already infers them onto every row - re-declaring them
 * would let a hand edit disagree with the platform.
 */
const SYSTEM_FIELDS: ReadonlySet<string> = new Set([
  "id",
  "created_at",
  "updated_at",
  "created_by",
  "updated_by",
  "version",
  "deleted_at",
]);

/**
 * The banner both schema sources carry. It names the toolchain, not a source,
 * so the two artifacts read identically to a creator.
 */
export const GENERATED_ENV_DB_BANNER =
  "// GENERATED by the schema toolchain (gen-types) — DO NOT EDIT.\n" +
  "//\n" +
  "// The typed `env.db` surface, reconstructed from the schema source (the\n" +
  "// op.* migration set or a declared schema — the source is the ground truth,\n" +
  "// types are generated from the fold). Re-run gen-types after schema changes;\n" +
  "// the gen-types --check CI gate fails if this file drifts from the source.\n" +
  "//\n" +
  "// The schema below is a reconstruction of `@zeroship/db` `t.*()` builder\n" +
  "// calls — NOT a hand-rolled interface — so it flows through the SAME\n" +
  "// `InferSchema`/`Row`/`Collections`/`Db`/`Id<>`/`MaskedValue<>` inference\n" +
  "// chain a declared schema would.\n" +
  "//\n" +
  "// That equivalence is about TYPES, not about DDL, and the difference is not\n" +
  "// cosmetic: feeding this file back in as a declared schema would NOT\n" +
  "// reproduce the columns the migrations built. `int`, `integer`, `bigInt`,\n" +
  "// `number` and `float` all render as `t.number()`, because `@zeroship/db`\n" +
  "// has no integer builder — so an `int` column that the migration created as\n" +
  "// INTEGER would come back as DOUBLE PRECISION.\n" +
  "//\n" +
  "// Read `t.number()` here as \"some numeric column\", not as the column's\n" +
  "// type. The schema source above remains the ground truth for DDL.\n";

/**
 * Render the generated `env.db.ts` from a parsed v2 runtime descriptor.
 *
 * Collection and field order follow the descriptor's key order, which the
 * emitter produces deterministically - so the output is stable and the
 * `--check` drift gate is meaningful.
 */
export function renderGeneratedEnvDb(descriptor: RuntimeDescriptor): string {
  let body = GENERATED_ENV_DB_BANNER;
  body += 'import { t, schema as defineSchema, type Db } from "@zeroship/db";\n\n';

  body += "const schema = {\n";
  for (const [collection, coll] of Object.entries(descriptor.collections ?? {})) {
    const options = coll.options ?? {};
    const indexes = coll.indexes ?? [];
    const needsBuilder = collectionNeedsSchemaBuilder(options, indexes);

    body += `  ${jsKey(collection)}: ${needsBuilder ? "defineSchema({" : "{"}\n`;
    for (const [column, def] of Object.entries(coll.fields ?? {})) {
      if (SYSTEM_FIELDS.has(column)) continue;
      body += `    ${jsKey(column)}: ${renderBuilderChain(def)},\n`;
    }
    body += needsBuilder ? `  })${renderCollectionChains(options, indexes)}` : "  }";
    body += ",\n";
  }
  body += "} as const;\n\n";

  body +=
    'declare module "zeroship" {\n  interface Env {\n    db: Db<typeof schema>;\n  }\n}\n\n' +
    "export {};\n";
  return body;
}

/**
 * Whether the collection carries runtime metadata that only the SDK `schema()`
 * builder can express. A bare object literal is the cleaner output when it does
 * not (and infers identically).
 */
function collectionNeedsSchemaBuilder(
  options: RuntimeOptions,
  indexes: RuntimeIndex[],
): boolean {
  return (
    options.softDelete === true ||
    options.versioning === true ||
    (options.strictness !== undefined && options.strictness !== "strict") ||
    indexes.length > 0
  );
}

/** The `.softDelete()`/`.withVersioning()`/`.strictness()`/`.index()` suffix chain. */
function renderCollectionChains(options: RuntimeOptions, indexes: RuntimeIndex[]): string {
  let out = "";
  if (options.softDelete === true) out += ".softDelete()";
  if (options.versioning === true) out += ".withVersioning()";
  if (options.strictness === "lenient") out += '.strictness("lenient")';
  else if (options.strictness === "off") out += '.strictness("off")';
  for (const idx of indexes) {
    const method = idx.unique === true ? "uniqueIndex" : "index";
    out += `.${method}(${jsStr(idx.name)}, ${JSON.stringify(idx.fields)})`;
  }
  return out;
}

/**
 * Reconstruct ONE column's `@zeroship/db` builder chain from its wire
 * `FieldDef`. The base call comes from `type` (plus the
 * `encrypted`/`id`/`ref`/`vector` facets); modifiers chain off it in a fixed
 * order so the output is byte-stable.
 */
function renderBuilderChain(def: RuntimeFieldDef): string {
  if (def === null || typeof def !== "object") return "t.json()";
  const hasEncrypted = def.encrypted !== undefined;

  let chain: string;
  if (hasEncrypted) {
    chain = renderEncryptedBase(def.encrypted);
  } else if (typeof def.refTarget === "string" && def.refTarget.length > 0) {
    // A relation is identified by its relation METADATA, not by the `type`
    // token, which describes storage. This mirrors the same decision already
    // made in the runtime's `loadRelations`.
    //
    // The migration-first pipeline is the platform's only schema path, and a
    // committed migration declares a foreign key as
    // `t.text().references("users", "id")` - the vendored engine DSL has no
    // `t.ref()`. The engine reports that honestly as
    // `{ type: "string", refTarget: "users" }`, and dispatching on
    // `type === "ref"` alone rendered it as a bare `t.string()`. The runtime
    // then eager-loaded the relation happily while `ExtractRefTarget` resolved
    // to `never` and typed the joined field as `null`: the type layer denying
    // a relation that works.
    //
    // It must render `t.ref(...)` specifically. `ExtractRefTarget` matches only
    // a `TypeBuilder<Id<T>>` or a literal `{ type: "ref"; refTarget }`; a
    // string field carrying `refTarget` resolves to `never` however the
    // metadata is attached, so emitting the token is the fix, not decorating
    // the string.
    //
    // This also repairs two sites downstream that key on `type === "ref"` and
    // silently skipped migration FKs: missing-ref-target validation and FK
    // topological ordering in `install-schema.ts`.
    chain = renderRefBase(def);
  } else {
    switch (def.type) {
      case "string":
        chain = "t.string()";
        break;
      // Preserve the wide integer contract in generated SDK declarations.
      case "bigInt":
        chain = "t.bigInt()";
        break;
      case "int":
      case "integer":
      case "number":
      case "float":
        chain = "t.number()";
        break;
      case "boolean":
        chain = "t.boolean()";
        break;
      case "json":
      case "object":
      case "array":
        chain = "t.json()";
        break;
      case "date":
      case "timestamp":
        chain = "t.timestamp()";
        break;
      case "bytes":
        chain = "t.bytes()";
        break;
      case "geoPoint":
        chain = "t.geoPoint()";
        break;
      case "calendarDate":
        chain = "t.calendarDate()";
        break;
      case "id":
        chain = renderIdBase(def);
        break;
      case "ref":
        chain = renderRefBase(def);
        break;
      case "vector":
        chain = renderVectorBase(def);
        break;
      // An unknown token degrades to `t.json()` rather than throwing: the column
      // still types (loosely), and gen-types never silently DROPS a column.
      default:
        chain = "t.json()";
        break;
    }
  }

  if (def.required === true) chain += ".required()";
  if (def.unique === true) chain += ".unique()";
  if (typeof def.min === "number") chain += `.min(${renderNumber(def.min)})`;
  if (typeof def.max === "number") chain += `.max(${renderNumber(def.max)})`;
  if (Array.isArray(def.enum)) {
    // The `as const` at the schema root narrows these to a literal union in
    // `Row<S>`. A non-scalar member is dropped rather than rendered as an
    // un-typecheckable `.enum(true)`; if none survive, the `.enum(...)` is
    // omitted entirely and the column types as its base scalar.
    const members = def.enum.map(renderEnumMember).filter((m): m is string => m !== null);
    if (members.length > 0) chain += `.enum(${members.join(", ")})`;
  }
  if (def.mask !== undefined && def.mask !== null && typeof def.mask === "object") {
    const kind = typeof def.mask.kind === "string" ? def.mask.kind : "full";
    const classification =
      typeof def.mask.classification === "string" ? def.mask.classification : "pii";
    // `t.encrypted()` stamps the fail-safe `{ full, pii }` auto-mask at builder
    // time, so re-emitting exactly that on an encrypted column is redundant
    // noise. An OVERRIDING mask on an encrypted column is still rendered.
    const isEncryptedAutoMask = hasEncrypted && kind === "full" && classification === "pii";
    if (!isEncryptedAutoMask) {
      chain += `.mask({ kind: ${jsStr(kind)}, classification: ${jsStr(classification)} })`;
    }
  }
  if (def.default !== undefined) chain += `.default(${renderDefaultValue(def.default)})`;

  return chain;
}

/**
 * `t.encrypted({ keyId?, wraps? })`.
 *
 * The kernel-default triple (`randomised` / `default` / `string`) is what a bare
 * `t.encrypted()` stamps, so it collapses back to the bare form: the two
 * spellings produce the same `TypeBuilder`, and the full facet is preserved in
 * `schema.runtime.json` regardless. Only a non-default facet renders opts.
 */
function renderEncryptedBase(enc: RuntimeFieldDef["encrypted"]): string {
  if (enc === null || typeof enc !== "object") return "t.encrypted()";
  const keyId = typeof enc.keyId === "string" ? enc.keyId : undefined;
  const wraps = typeof enc.wraps === "string" ? enc.wraps : undefined;
  if (
    (keyId === undefined || keyId === "default") &&
    (wraps === undefined || wraps === "string")
  ) {
    return "t.encrypted()";
  }
  const opts: string[] = [];
  if (keyId !== undefined) opts.push(`keyId: ${jsStr(keyId)}`);
  if (wraps !== undefined) {
    // `wraps` is a TypeBuilder argument in the SDK, reconstructed from the
    // inner-type token.
    const wrapsBuilder =
      wraps === "number" ? "t.number()" : wraps === "bytes" ? "t.bytes()" : "t.string()";
    opts.push(`wraps: ${wrapsBuilder}`);
  }
  return opts.length === 0 ? "t.encrypted()" : `t.encrypted({ ${opts.join(", ")} })`;
}

/** `t.id(prefix?)` - the typed-id base, threading the recovered `idPrefix`. */
function renderIdBase(def: RuntimeFieldDef): string {
  return typeof def.idPrefix === "string" ? `t.id(${jsStr(def.idPrefix)})` : "t.id()";
}

/** `t.ref(target, { onDelete?, onUpdate?, deferrable? })` - the FK base. */
function renderRefBase(def: RuntimeFieldDef): string {
  const target = typeof def.refTarget === "string" ? def.refTarget : "";
  const opts: string[] = [];
  if (typeof def.onDelete === "string") opts.push(`onDelete: ${jsStr(def.onDelete)}`);
  if (typeof def.onUpdate === "string") opts.push(`onUpdate: ${jsStr(def.onUpdate)}`);
  if (typeof def.deferrable === "boolean") opts.push(`deferrable: ${def.deferrable}`);
  return opts.length === 0
    ? `t.ref(${jsStr(target)})`
    : `t.ref(${jsStr(target)}, { ${opts.join(", ")} })`;
}

/** `t.vector(dims, { metric? })` - the vector base. */
function renderVectorBase(def: RuntimeFieldDef): string {
  const dims = typeof def.vectorDims === "number" ? def.vectorDims : 0;
  return typeof def.vectorMetric === "string"
    ? `t.vector(${dims}, { metric: ${jsStr(def.vectorMetric)} })`
    : `t.vector(${dims})`;
}

/** A numeric bound as a TS number literal. */
function renderNumber(n: number): string {
  return String(n);
}

/**
 * An `enum` member as a TS literal - STRING or NUMBER only.
 *
 * The SDK's `.enum<Values extends readonly (T & (string | number))[]>` forbids
 * boolean and non-scalar members. The CHECK-lift only ever carries
 * strings/numbers today, but render fail-closed (drop) so a hand-crafted
 * descriptor can never make the renderer emit something tsc would reject.
 */
function renderEnumMember(v: unknown): string | null {
  if (typeof v === "string") return jsStr(v);
  if (typeof v === "number") return String(v);
  return null;
}

/** A `default` value as a TS literal for `.default(...)`. */
function renderDefaultValue(v: unknown): string {
  if (typeof v === "string") return jsStr(v);
  if (typeof v === "boolean" || typeof v === "number") return String(v);
  if (v === null) return "null";
  return JSON.stringify(v);
}

/** A double-quoted, minimally-escaped TS string literal. */
function jsStr(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/** An object key: a bare identifier when safe, else a quoted string literal. */
function jsKey(s: string): string {
  const isIdent = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s);
  return isIdent ? s : jsStr(s);
}
