//! Dev-tier auth identity injection for `zeroship serve` (dev runtime only).
//!
//! ## Why this exists
//!
//! In production the **gateway** is the BFF: it owns the `__Host-zeroship_app_session`
//! cookie, resolves the authenticated user, and HMAC-signs that identity into
//! the request-bound `ZeroShip-User` header (`crates/core/src/auth.rs`,
//! `crates/gateway/src/oidc_rp.rs`). The worker verifies + decodes that header
//! and threads the resulting `user_json` into
//! [`Runtime::call_fetch_handler_with_user`], which feeds BOTH the
//! `env.auth.getUser()` per-request state (`crate::auth::set_request_user`) and
//! the `currentUser()` RPC ctx (`mint_rpc_ctx(user_json)`).
//!
//! In **self-contained dev** (`pnpm dev` → the Vite plugin spawns
//! `zeroship serve`) there is no gateway and no Hydra. The dev-tier auth
//! provider lives in JS (`@zeroship/bootstrap/dev` — `dev-auth.ts`): it serves
//! `/__zeroship/auth/{authorize,popup-callback,session,signout}` and mints a LOCAL
//! signed session cookie `__zeroship_dev_session`. That cookie is the dev equivalent
//! of the gateway's `__Host-zeroship_app_session` cookie — but the JS layer runs
//! *inside* the same `call_fetch_handler` invocation that needs the identity,
//! so it cannot retroactively populate the native per-request user state.
//!
//! This module is the one small Rust hook that closes the loop: the dev serve
//! path (`serve.rs::handle_request`) calls [`resolve_dev_user_json`] BEFORE
//! dispatch. It reads the `__zeroship_dev_session` cookie, verifies the dev HMAC
//! (shared secret `ZEROSHIP_DEV_AUTH_SECRET`, generated by the Vite plugin and
//! passed to the child), and returns the decoded identity JSON — the exact same
//! `user_json` shape the gateway produces. The identity then flows through the
//! identical `call_fetch_handler_with_user` path prod uses. Contract parity:
//! same wire shape, same native plumbing, same `env.auth` / `currentUser`
//! surfaces — only the *producer* of the cookie differs (dev JS vs gateway).
//!
//! ## Dev-only by construction
//!
//! [`resolve_dev_user_json`] is a no-op unless `ZEROSHIP_DEV=1` (the Vite
//! plugin sets it on the spawned child; see
//! `sdks/vite-plugin/src/constants.ts` `ENV_DEV`). The cookie format is NOT the
//! production `__Host-zeroship_app_session` cookie, carries a dev-only HMAC, and is
//! never read by the gateway. There is no untrusted gateway in front of the dev
//! runtime — the only client is the developer's own browser via the Vite proxy
//! — so a dev-trusted, dev-secret-signed cookie is the faithful dev-tier
//! credential (mirrors how `env.db` → SQLite is a real impl of the contract,
//! not a fake Postgres).

use base64::Engine as _;

/// Cookie name carrying the dev session identity. Distinct from the prod
/// `__Host-zeroship_app_session` cookie so the two can never be confused, and so a
/// stray prod cookie is ignored by the dev decoder (and vice-versa).
pub const DEV_SESSION_COOKIE: &str = "__zeroship_dev_session";

/// Env var the Vite plugin sets to `1` on the spawned dev runtime child.
/// Mirrors `ENV_DEV` in `sdks/vite-plugin/src/constants.ts`.
const ENV_DEV: &str = "ZEROSHIP_DEV";

/// Env var carrying the per-dev-server HMAC secret the JS dev-auth layer uses
/// to sign the `__zeroship_dev_session` cookie. Generated fresh by the Vite plugin
/// for each dev server and passed to the child via the spawn env.
const ENV_DEV_AUTH_SECRET: &str = "ZEROSHIP_DEV_AUTH_SECRET";

/// Resolve the dev user identity JSON for a request from its `Cookie` header.
///
/// Returns `Some(user_json)` only when:
///   1. `ZEROSHIP_DEV=1` (the dev runtime; structurally absent otherwise), and
///   2. `ZEROSHIP_DEV_AUTH_SECRET` is set (the Vite plugin provisioned it), and
///   3. a `__zeroship_dev_session` cookie is present and its dev HMAC verifies.
///
/// The returned string is the canonical `ZeroShip-User` JSON body
/// (`{id,email,name,avatar?,email_verified,scopes}`) — handed verbatim to
/// [`Runtime::call_fetch_handler_with_user`], exactly as the worker hands the
/// gateway-verified header body in production.
#[must_use]
pub fn resolve_dev_user_json(request_headers: &[(String, String)]) -> Option<String> {
    if std::env::var(ENV_DEV).is_err() {
        return None;
    }
    let secret = std::env::var(ENV_DEV_AUTH_SECRET).ok()?;
    if secret.is_empty() {
        return None;
    }
    let cookie_header = request_headers
        .iter()
        .find(|(name, _)| name.eq_ignore_ascii_case("cookie"))
        .map(|(_, value)| value.as_str())?;
    let token = extract_cookie(cookie_header, DEV_SESSION_COOKIE)?;
    verify_dev_session(secret.as_bytes(), token)
}

/// Extract a single cookie value from a `Cookie:` header. Returns the raw
/// (still percent-/base64-encoded) cookie value, trimmed of surrounding
/// whitespace. `None` if the named cookie is absent.
fn extract_cookie<'a>(cookie_header: &'a str, name: &str) -> Option<&'a str> {
    cookie_header.split(';').find_map(|pair| {
        let pair = pair.trim();
        let (k, v) = pair.split_once('=')?;
        if k.trim() == name {
            Some(v.trim())
        } else {
            None
        }
    })
}

/// Verify and decode a dev session token of the form
/// `<base64url(user_json)>.<hex-hmac>`, where the HMAC covers the base64url
/// payload segment. Returns the decoded `user_json` on success.
///
/// This is a deliberately tiny, dev-only HMAC envelope — NOT the
/// request-bound, time-bound prod `ZeroShip-User` format
/// (`crates/core/src/auth.rs`). It only needs to bind the cookie to the
/// per-dev-server secret so an unrelated process cannot forge an identity into
/// the dev runtime; there is no replay surface worth time-binding in
/// single-developer dev.
#[must_use]
fn verify_dev_session(secret: &[u8], token: &str) -> Option<String> {
    let (payload_b64, mac) = token.split_once('.')?;
    if payload_b64.is_empty() || mac.is_empty() {
        return None;
    }
    if !zeroship_core::auth::verify_hmac_sha256_hex(secret, payload_b64.as_bytes(), mac) {
        return None;
    }
    let json = base64::engine::general_purpose::URL_SAFE_NO_PAD
        .decode(payload_b64)
        .ok()?;
    String::from_utf8(json).ok()
}

/// Sign a dev session token for a given identity JSON. Mirrors the JS
/// `signDevSession` in `@zeroship/bootstrap/dev` (`dev-auth.ts`) so the two
/// stay byte-compatible; exposed for the faithful integration test.
#[must_use]
pub fn sign_dev_session(secret: &[u8], user_json: &str) -> String {
    let payload_b64 = base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(user_json.as_bytes());
    let mac = zeroship_core::auth::hmac_sha256_hex(secret, payload_b64.as_bytes());
    format!("{payload_b64}.{mac}")
}

#[cfg(test)]
mod tests {
    use super::*;

    const SECRET: &[u8] = b"dev-secret-abc";
    const USER_JSON: &str =
        r#"{"id":"pws_dev0000000000000000","email":"dev@localhost","name":"Dev User","email_verified":true,"scopes":["openid","profile","email"]}"#;

    /// Round-trip: a token signed with the secret verifies and decodes back to
    /// the original identity JSON.
    #[test]
    fn sign_verify_roundtrip() {
        let token = sign_dev_session(SECRET, USER_JSON);
        assert_eq!(verify_dev_session(SECRET, &token).as_deref(), Some(USER_JSON));
    }

    /// A token signed with a DIFFERENT secret is rejected (forgery guard).
    #[test]
    fn wrong_secret_rejected() {
        let token = sign_dev_session(SECRET, USER_JSON);
        assert_eq!(verify_dev_session(b"other-secret", &token), None);
    }

    /// A tampered payload (re-encoded different JSON, original MAC) is rejected.
    #[test]
    fn tampered_payload_rejected() {
        let token = sign_dev_session(SECRET, USER_JSON);
        let (_, mac) = token.split_once('.').unwrap();
        let forged_payload = base64::engine::general_purpose::URL_SAFE_NO_PAD
            .encode(br#"{"id":"pws_attacker","scopes":["admin"]}"#);
        let forged = format!("{forged_payload}.{mac}");
        assert_eq!(verify_dev_session(SECRET, &forged), None);
    }

    /// Malformed tokens (missing the `.` separator, empty halves) are rejected.
    #[test]
    fn malformed_tokens_rejected() {
        assert_eq!(verify_dev_session(SECRET, "nodot"), None);
        assert_eq!(verify_dev_session(SECRET, ".deadbeef"), None);
        assert_eq!(verify_dev_session(SECRET, "payload."), None);
    }

    /// `extract_cookie` finds the named cookie among several and trims space.
    #[test]
    fn extract_cookie_picks_named() {
        let header = "other=1; __zeroship_dev_session=abc.def ; foo=bar";
        assert_eq!(
            extract_cookie(header, DEV_SESSION_COOKIE),
            Some("abc.def")
        );
        assert_eq!(extract_cookie("only=here", DEV_SESSION_COOKIE), None);
    }

    /// `resolve_dev_user_json` is a no-op when `ZEROSHIP_DEV` is unset —
    /// dev-only-by-construction even if a cookie + secret somehow appear.
    /// (Serial-ish: mutates process env; restores afterward.)
    #[test]
    fn resolve_is_noop_without_dev_flag() {
        let prev_dev = std::env::var_os(ENV_DEV);
        let prev_secret = std::env::var_os(ENV_DEV_AUTH_SECRET);
        unsafe {
            std::env::remove_var(ENV_DEV);
            std::env::set_var(ENV_DEV_AUTH_SECRET, "dev-secret-abc");
        }
        let token = sign_dev_session(SECRET, USER_JSON);
        let headers = vec![(
            "Cookie".to_string(),
            format!("{DEV_SESSION_COOKIE}={token}"),
        )];
        assert_eq!(resolve_dev_user_json(&headers), None);
        unsafe {
            match prev_dev {
                Some(v) => std::env::set_var(ENV_DEV, v),
                None => std::env::remove_var(ENV_DEV),
            }
            match prev_secret {
                Some(v) => std::env::set_var(ENV_DEV_AUTH_SECRET, v),
                None => std::env::remove_var(ENV_DEV_AUTH_SECRET),
            }
        }
    }
}
