//! Constructor callback codegen.
//!
//! Hosts:
//!
//! - `gen_constructor_callback` — user-defined `#[v8_constructor]`
//! - `gen_default_constructor_callback` — `<State as Default>::default()`
//! - `gen_must_new_prologue` — WebIDL §3.7.1 must-new guard
//! - `gen_install_state`: hands the instance to `<Class>::__zs_install`

use proc_macro2::TokenStream as TokenStream2;
use quote::{format_ident, quote};

use super::super::helpers::{
    gen_param_extractions, outer_ident, parse_params_skipping_self,
};
use super::super::shared::class_config::ClassConfig;
use super::super::ClassMethod;
use crate::gen_throw_op_error_arms;

/// WebIDL §3.7.1: every interface constructor MUST be called with `new`.
/// Returns the `if !args.is_construct_call() { throw TypeError; return; }`
/// prologue unless the class opts out via `#[v8_constructor(callable_no_new)]`.
///
/// # Deliberate-uniformity choice on the error message
///
/// The thrown TypeError uses Chromium's verbatim phrasing
/// (`"Failed to construct 'X': Please use the 'new' operator, this
/// DOM object constructor cannot be called as a function."`) for two
/// reasons:
///
///   1. **WPT compatibility.** A handful of tests in
///      `wpt/dom/`, `wpt/url/`, and `wpt/fetch/` assert against the
///      exact diagnostic string (substring or full equality).
///      Diverging here means snapshot drift in the W3C suite that
///      we don't control.
///   2. **Predictable signal across a creator-built app surface.**
///      Apps generated by the AI builder land hundreds of WebIDL
///      classes; consistent diagnostics let LLM reviewers and human
///      operators recognise the failure mode without per-class
///      training.
///
/// The macro therefore parameterises ONLY the class name (the
/// `'X'` in the message). Custom error styles
/// (`#[v8_constructor(error_kind = ...)]`) deliberately do NOT
/// influence this prologue — they apply to errors thrown from
/// inside the user's constructor body, not the must-new guard.
/// Applying them here would re-introduce the WPT drift and the
/// per-class diagnostic divergence the choice avoids.
///
/// Class-name interpolation lets WPT diagnose mistakes per-class
/// (`"Failed to construct 'Headers': ..."` vs the generic form).
/// The `is_construct_call` flag is V8-native — it differentiates
/// `new Foo()` (true) from `Foo()` and `Foo.call(...)` (false)
/// without a runtime thunk in the user code.
fn gen_must_new_prologue(class_ty: &syn::Ident, opt_out: bool) -> TokenStream2 {
    if opt_out {
        return quote! {};
    }
    let class_name_str = class_ty.to_string();
    let msg = format!(
        "Failed to construct '{class_name_str}': Please use the 'new' operator, this DOM object constructor cannot be called as a function."
    );
    quote! {
        if !args.is_construct_call() {
            let __msg = v8::String::new(scope, #msg).unwrap();
            let __exc = v8::Exception::type_error(scope, __msg);
            scope.throw_exception(__exc);
            return;
        }
    }
}

/// User-defined constructor callback. Parses JS args, invokes the
/// user's `#[v8_constructor]` fn, materialises a `Box<State>`, and
/// installs it in internal field 0 with a guaranteed finalizer.
/// An optional `post_init` hook fires after install.
pub(crate) fn gen_constructor_callback(cfg: &ClassConfig, c: &ClassMethod) -> TokenStream2 {
    let class_ty = cfg.class_ty;
    let state_ty = cfg.state_ty;
    let ctor_name = &c.func.sig.ident;
    let callback_ident = format_ident!("__{}_constructor_callback", class_ty);

    // Constructors have no `self` receiver; the skipping-self helper
    // works uniformly here since it just collects typed args.
    let params = parse_params_skipping_self(c.func);
    // Per-method extracts are pre-parsed by the analyze phase.
    let extractions = gen_param_extractions(&params, &c.reject_shared_names);
    let call_args: Vec<&syn::Ident> = params.iter().map(|p| &p.name).collect();

    let is_result = matches!(
        outer_ident(&c.func.sig.output).as_deref(),
        Some("Result")
    );

    let make_instance = if is_result {
        // Routed through the shared `gen_throw_op_error_arms` helper —
        // single source of truth for the 6-variant OpErrorKind dispatch
        // (TypeError, RangeError, DomException, NodeError, Error,
        // JsValue passthrough). The helper throws via
        // `scope.throw_exception(...)` in both the JsValue and the
        // typed-error branches; the macro emits `return;` after to
        // unwind the V8 callback.
        let throw = gen_throw_op_error_arms(&quote! { scope }, &quote! { __err });
        quote! {
            let __instance: #state_ty = match <#state_ty>::#ctor_name(#(#call_args),*) {
                Ok(__v) => __v,
                Err(__err) => {
                    #throw
                    return;
                }
            };
        }
    } else {
        quote! {
            let __instance: #state_ty = <#state_ty>::#ctor_name(#(#call_args),*);
        }
    };

    let store = gen_install_state(class_ty);
    let must_new = gen_must_new_prologue(class_ty, c.callable_no_new);

    // post_init dispatch runs after box install and before the
    // callback returns to V8. Hook signature is
    // `fn(&mut PinScope, Local<Object>) -> Result<(), OpError>`.
    //
    // Behaviour matrix:
    //   - must_new + post_init: must-new throws early, post_init never
    //     runs. No special case in this code — must-new returns first.
    //   - callable_no_new + post_init: hook only fires for `new Foo()`
    //     (is_construct_call() == true). Bare `Foo()` skips the hook
    //     to avoid writing private symbols on globalThis.
    //   - #[v8_inherit]: derived's hook runs; base's does NOT auto-chain
    //     (V8's existing constructor semantics — derived is responsible
    //     for invoking base setup explicitly).
    //
    // Box reclamation under failure: when the hook returns Err, the macro
    // throws a JS exception and returns. The box stays installed in field
    // 0 until the V8 weak finalizer reclaims the wrapper on the next GC
    // sweep. Drop is lazy; the user-visible contract: `Self::Drop`
    // side-effects from a failed post_init may be delayed by up to one
    // GC cycle.
    let post_init = match c.post_init.as_ref() {
        None => quote! {},
        Some(hook_ident) => {
            // Routed through the shared `gen_throw_op_error_arms` helper
            // — same 6-variant OpErrorKind dispatch as the make_instance
            // Result arm above. Adding a 7th variant means editing one
            // match in one helper.
            let throw = gen_throw_op_error_arms(&quote! { scope }, &quote! { __err });
            quote! {
                if args.is_construct_call() {
                    match <#class_ty>::#hook_ident(scope, __this) {
                        Ok(()) => {},
                        Err(__err) => {
                            #throw
                            return;
                        }
                    }
                }
            }
        }
    };

    let body = quote! {
            #must_new
            let __this = args.this();

            #(#extractions)*
            #make_instance

            #store
            #post_init
        };

    quote! {
        #[allow(non_snake_case, unused_variables, unused_mut, clippy::needless_borrow)]
        pub(crate) fn #callback_ident(
            scope: &mut v8::PinScope,
            args: v8::FunctionCallbackArguments,
            _rv: v8::ReturnValue,
        ) {
            #body
        }
    }
}

/// Default-derived constructor callback — emitted when the user impl
/// has no `#[v8_constructor]` attribute. Allocates a `<State as
/// Default>::default()`, boxes it, and installs the finalizer.
/// Always must-new (no opt-out path for default-derived constructors).
pub(crate) fn gen_default_constructor_callback(cfg: &ClassConfig) -> TokenStream2 {
    let class_ty = cfg.class_ty;
    let state_ty = cfg.state_ty;
    let callback_ident = format_ident!("__{}_constructor_callback", class_ty);
    let store = gen_install_state(class_ty);
    // No method-level attrs to read — the Default-derived constructor
    // is always must-new. The opt-out attribute requires a user-written
    // `#[v8_constructor]`, by definition.
    let must_new = gen_must_new_prologue(class_ty, false);

    let body = quote! {
            #must_new
            let __this = args.this();
            let __instance: #state_ty = <#state_ty as ::core::default::Default>::default();

            #store
        };

    quote! {
        #[allow(non_snake_case, unused_variables, unused_mut, clippy::needless_borrow)]
        pub(crate) fn #callback_ident(
            scope: &mut v8::PinScope,
            args: v8::FunctionCallbackArguments,
            _rv: v8::ReturnValue,
        ) {
            #body
        }
    }
}

/// Hand the new instance to `<Class>::__zs_install`, which boxes it into
/// the wrapper's internal fields, brands the wrapper and registers the
/// finalizer. It refuses a receiver that is not a fresh wrapper of the
/// class (a constructor opted out of must-new, called on another object),
/// and the callback throws instead of writing that object's fields.
fn gen_install_state(class_ty: &syn::Ident) -> TokenStream2 {
    quote! {
        if <#class_ty>::__zs_install(scope, __this, __instance).is_none() {
            let __msg = v8::String::new(scope, "Illegal invocation").unwrap();
            let __exc = v8::Exception::type_error(scope, __msg);
            scope.throw_exception(__exc);
            return;
        }
    }
}
