import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { workflowSchema } from "./schema.ts";
import { workflowPlatformPolicy } from "./platform-policy.ts";
import { buildEnvelope } from "../../../packages/zero-migrate/dist/internal/recorder.js";
import { currentIrVersion, previewSql } from "../../../packages/zero-migrate-cli/dist/index.js";

const check = process.argv.includes("--check");
const fingerprints = {};
const outputs = [];
for (const dialect of ["postgres", "sqlite"]) {
  const namespace = dialect === "postgres" ? "workflow" : "main";
  const envelope = buildEnvelope({ name: "workflow_service", schema: () => workflowSchema(namespace) }, { irVersion: currentIrVersion() });
  if (!envelope.ops.length) throw new Error("workflow schema recorder is empty");
  const charter = `policy_version = 1
[[grant]]
key = "schema.create_table"
value = true
scope = { include = ["${namespace}"] }
[[grant]]
key = "schema.cross_schema"
value = true
scope = { include = ["${namespace}"] }
`;
  const statements = previewSql({ envelopes: [JSON.stringify(envelope)], dialect, defaultSchema: namespace, ownerApp: "workflow", charterLayers: [charter] });
  const emitted = statements.join("\n");
  if (emitted.includes("[runtime-resolved]")) throw new Error("workflow schema must lower completely");
  // Preview annotations contain measured tallies; shipped SQL retains statements.
  const sql = emitted.split("\n").filter(line => !line.startsWith("--")).join("\n").trim();
  const fingerprint = createHash("sha256").update(sql).digest("hex");
  fingerprints[dialect] = fingerprint;
  const content = `-- Generated by schema/generate.mjs through the migration compiler.\n${sql}\nINSERT INTO ${namespace}.schema_version (id, fingerprint) VALUES ('workflow', '${fingerprint}');\n`;
  const path = new URL(`./${dialect}.sql`, import.meta.url);
  outputs.push({ path, content });
}

const policyEnvelope = buildEnvelope({ name: "workflow_platform_policy", schema: workflowPlatformPolicy }, { irVersion: currentIrVersion() });
const policyCharter = await readFile(new URL("../../../policies/platform.policy.toml", import.meta.url), "utf8");
const policyStatements = previewSql({ envelopes: [JSON.stringify(policyEnvelope)], dialect: "postgres", defaultSchema: "zeroship", ownerApp: "zeroship_platform", charterLayers: [policyCharter] });
const policyRendered = policyStatements.join("\n");
if (policyRendered.includes("[runtime-resolved]")) throw new Error("workflow policy must lower completely");
const policySql = policyRendered.split("\n").filter(line => !line.startsWith("--")).join("\n").trim();
fingerprints.platform_policy = createHash("sha256").update(policySql).digest("hex");
outputs.push({ path: new URL("./platform-policy.sql", import.meta.url), content: `-- Generated by schema/generate.mjs through the migration compiler.\n${policySql}\nINSERT INTO workflow.schema_version (id, fingerprint) VALUES ('platform_policy', '${fingerprints.platform_policy}');\n` });
outputs.push({ path: new URL("./fingerprints.json", import.meta.url), content: JSON.stringify(fingerprints, null, 2) + "\n" });
// Finish compiling every dialect before changing any generated artifact.
for (const { path, content } of outputs) {
  if (check) {
    if (await readFile(path, "utf8") !== content) throw new Error(`stale workflow schema ${path.pathname}; run node crates/zeroship-workflow/schema/generate.mjs`);
  } else {
    await writeFile(path, content);
  }
}
