import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { workflowSchema } from "./schema.ts";
import { buildEnvelope } from "../../../packages/zero-migrate/dist/internal/recorder.js";
import { currentIrVersion, previewSql } from "../../../packages/zero-migrate-cli/dist/index.js";

const check = process.argv.includes("--check");
const fingerprints = {};
for (const dialect of ["postgres", "sqlite"]) {
  const namespace = dialect === "postgres" ? "workflow" : "main";
  const envelope = buildEnvelope({ name: "workflow_service", schema: () => workflowSchema(namespace) }, { irVersion: currentIrVersion() });
  if (!envelope.ops.length) throw new Error("workflow schema recorder is empty");
  const charter = `policy_version = 1
[[grant]]
key = "schema.create_table"
value = true
scope = { include = ["${namespace}"] }
[[grant]]
key = "schema.cross_schema"
value = true
scope = { include = ["${namespace}"] }
`;
  const statements = previewSql({ envelopes: [JSON.stringify(envelope)], dialect, defaultSchema: namespace, ownerApp: "workflow", charterLayers: [charter] });
  const emitted = statements.join("\n");
  if (emitted.includes("[runtime-resolved]")) throw new Error("workflow schema must lower completely");
  // Preview annotations contain measured tallies; shipped SQL retains statements.
  const sql = emitted.split("\n").filter(line => !line.startsWith("--")).join("\n").trim();
  const fingerprint = createHash("sha256").update(sql).digest("hex");
  fingerprints[dialect] = fingerprint;
  const content = `-- Generated by schema/generate.mjs through the migration compiler.\n${sql}\nINSERT INTO ${namespace}.schema_version (id, fingerprint) VALUES ('workflow', '${fingerprint}');\n`;
  const path = new URL(`./${dialect}.sql`, import.meta.url);
  if (check) {
    if (await readFile(path, "utf8") !== content) throw new Error(`stale workflow ${dialect} schema; run node crates/zeroship-workflow/schema/generate.mjs`);
  } else {
    await writeFile(path, content);
  }
}

const fingerprintsPath = new URL("./fingerprints.json", import.meta.url);
const encoded = JSON.stringify(fingerprints, null, 2) + "\n";
if (check) {
  if (await readFile(fingerprintsPath, "utf8") !== encoded) throw new Error("stale workflow schema fingerprints");
} else {
  await writeFile(fingerprintsPath, encoded);
}
