-- Generated by schema/generate.mjs through the migration compiler.
CREATE TABLE "zeroship"."workflow_deploy_notifications" ("app_id" uuid PRIMARY KEY NOT NULL, "revision" bigint NOT NULL);

ALTER TABLE zeroship.workflow_deploy_notifications ADD CONSTRAINT workflow_deploy_notification_app FOREIGN KEY (app_id) REFERENCES zeroship.apps(id) ON DELETE CASCADE;

GRANT SELECT, INSERT, UPDATE, DELETE ON "zeroship"."workflow_deploy_notifications" TO "zeroship_control";

CREATE FUNCTION "zeroship"."workflow_policy_lock"("resource_kind" text, "resource_id" text, "exclusive_lock" boolean) RETURNS void LANGUAGE plpgsql AS $zsfn$
DECLARE lock_key bigint;
BEGIN
  IF resource_kind NOT IN ('app', 'plan', 'organization', 'spend', 'rollout')
     OR resource_kind IS NULL OR resource_id IS NULL OR resource_id = ''
     OR exclusive_lock IS NULL THEN
    RAISE EXCEPTION 'invalid workflow policy lock resource';
  END IF;
  lock_key := pg_catalog.hashtextextended('workflow-policy:' || resource_kind || ':' || resource_id, 0);
  IF exclusive_lock THEN
    PERFORM pg_catalog.pg_advisory_xact_lock(lock_key);
  ELSE
    PERFORM pg_catalog.pg_advisory_xact_lock_shared(lock_key);
  END IF;
END;
$zsfn$;

REVOKE ALL ON FUNCTION zeroship.workflow_policy_lock(text,text,boolean) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION zeroship.workflow_policy_lock(text,text,boolean) TO zeroship_control, zeroship_workflow;

CREATE FUNCTION "zeroship"."workflow_policy_fence_app"() RETURNS trigger LANGUAGE plpgsql AS $zsfn$
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.id IS DISTINCT FROM OLD.id THEN
    RAISE EXCEPTION 'workflow policy resource identity is immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    PERFORM zeroship.workflow_policy_lock('app', OLD.id::text, true);
    RETURN OLD;
  END IF;
  PERFORM zeroship.workflow_policy_lock('app', NEW.id::text, true);
  RETURN NEW;
END;
$zsfn$;

REVOKE ALL ON FUNCTION zeroship.workflow_policy_fence_app() FROM PUBLIC;

CREATE TRIGGER "workflow_policy_fence_app" BEFORE INSERT OR UPDATE OR DELETE ON "zeroship"."apps" FOR EACH ROW EXECUTE FUNCTION "zeroship"."workflow_policy_fence_app"();

CREATE FUNCTION "zeroship"."workflow_policy_fence_plan"() RETURNS trigger LANGUAGE plpgsql AS $zsfn$
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.id IS DISTINCT FROM OLD.id THEN
    RAISE EXCEPTION 'workflow policy resource identity is immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    PERFORM zeroship.workflow_policy_lock('plan', OLD.id::text, true);
    RETURN OLD;
  END IF;
  PERFORM zeroship.workflow_policy_lock('plan', NEW.id::text, true);
  RETURN NEW;
END;
$zsfn$;

REVOKE ALL ON FUNCTION zeroship.workflow_policy_fence_plan() FROM PUBLIC;

CREATE TRIGGER "workflow_policy_fence_plan" BEFORE INSERT OR UPDATE OR DELETE ON "zeroship"."plans" FOR EACH ROW EXECUTE FUNCTION "zeroship"."workflow_policy_fence_plan"();

CREATE FUNCTION "zeroship"."workflow_policy_fence_organization"() RETURNS trigger LANGUAGE plpgsql AS $zsfn$
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.organization_id IS DISTINCT FROM OLD.organization_id THEN
    RAISE EXCEPTION 'workflow policy resource identity is immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    PERFORM zeroship.workflow_policy_lock('organization', OLD.organization_id::text, true);
    RETURN OLD;
  END IF;
  PERFORM zeroship.workflow_policy_lock('organization', NEW.organization_id::text, true);
  RETURN NEW;
END;
$zsfn$;

REVOKE ALL ON FUNCTION zeroship.workflow_policy_fence_organization() FROM PUBLIC;

CREATE TRIGGER "workflow_policy_fence_organization" BEFORE INSERT OR UPDATE OR DELETE ON "zeroship"."organization_billing_status" FOR EACH ROW EXECUTE FUNCTION "zeroship"."workflow_policy_fence_organization"();

CREATE FUNCTION "zeroship"."workflow_policy_fence_spend"() RETURNS trigger LANGUAGE plpgsql AS $zsfn$
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.app_id IS DISTINCT FROM OLD.app_id THEN
    RAISE EXCEPTION 'workflow policy resource identity is immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    PERFORM zeroship.workflow_policy_lock('spend', OLD.app_id::text, true);
    RETURN OLD;
  END IF;
  PERFORM zeroship.workflow_policy_lock('spend', NEW.app_id::text, true);
  RETURN NEW;
END;
$zsfn$;

REVOKE ALL ON FUNCTION zeroship.workflow_policy_fence_spend() FROM PUBLIC;

CREATE TRIGGER "workflow_policy_fence_spend" BEFORE INSERT OR UPDATE OR DELETE ON "zeroship"."app_spend_state" FOR EACH ROW EXECUTE FUNCTION "zeroship"."workflow_policy_fence_spend"();

CREATE FUNCTION "zeroship"."workflow_policy_fence_rollout"() RETURNS trigger LANGUAGE plpgsql AS $zsfn$
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.id IS DISTINCT FROM OLD.id THEN
    RAISE EXCEPTION 'workflow policy resource identity is immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    PERFORM zeroship.workflow_policy_lock('rollout', OLD.id::text, true);
    RETURN OLD;
  END IF;
  PERFORM zeroship.workflow_policy_lock('rollout', NEW.id::text, true);
  RETURN NEW;
END;
$zsfn$;

REVOKE ALL ON FUNCTION zeroship.workflow_policy_fence_rollout() FROM PUBLIC;

CREATE TRIGGER "workflow_policy_fence_rollout" BEFORE INSERT OR UPDATE OR DELETE ON "zeroship"."workflow_rollout_config" FOR EACH ROW EXECUTE FUNCTION "zeroship"."workflow_policy_fence_rollout"();

CREATE FUNCTION "zeroship"."workflow_policy_fence_notification"() RETURNS trigger LANGUAGE plpgsql AS $zsfn$
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.app_id IS DISTINCT FROM OLD.app_id THEN
    RAISE EXCEPTION 'workflow policy resource identity is immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    PERFORM zeroship.workflow_policy_lock('app', OLD.app_id::text, true);
    RETURN OLD;
  END IF;
  PERFORM zeroship.workflow_policy_lock('app', NEW.app_id::text, true);
  RETURN NEW;
END;
$zsfn$;

REVOKE ALL ON FUNCTION zeroship.workflow_policy_fence_notification() FROM PUBLIC;

CREATE TRIGGER "workflow_policy_fence_notification" BEFORE INSERT OR UPDATE OR DELETE ON "zeroship"."workflow_deploy_notifications" FOR EACH ROW EXECUTE FUNCTION "zeroship"."workflow_policy_fence_notification"();

CREATE FUNCTION "zeroship"."workflow_policy_fence_deploy"() RETURNS trigger LANGUAGE plpgsql AS $zsfn$
BEGIN
  IF TG_OP = 'UPDATE' AND (
      NEW.id IS DISTINCT FROM OLD.id OR NEW.app_id IS DISTINCT FROM OLD.app_id
      OR NEW.deploy_hash IS DISTINCT FROM OLD.deploy_hash
      OR NEW.manifest_json IS DISTINCT FROM OLD.manifest_json) THEN
    RAISE EXCEPTION 'workflow deployment snapshot is immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN
    PERFORM zeroship.workflow_policy_lock('app', OLD.app_id::text, true);
    RETURN OLD;
  END IF;
  PERFORM zeroship.workflow_policy_lock('app', NEW.app_id::text, true);
  RETURN NEW;
END;
$zsfn$;

REVOKE ALL ON FUNCTION zeroship.workflow_policy_fence_deploy() FROM PUBLIC;

CREATE TRIGGER "workflow_policy_fence_deploy" BEFORE INSERT OR UPDATE OR DELETE ON "zeroship"."app_deploys" FOR EACH ROW EXECUTE FUNCTION "zeroship"."workflow_policy_fence_deploy"();

CREATE FUNCTION "zeroship"."workflow_deploy_notify"() RETURNS trigger LANGUAGE plpgsql AS $zsfn$
BEGIN
  IF TG_OP = 'INSERT' AND NEW.deploy_hash IS NULL THEN RETURN NEW; END IF;
  IF TG_OP = 'UPDATE' AND NEW.deploy_hash IS NOT DISTINCT FROM OLD.deploy_hash
     AND NEW.manifest_json IS NOT DISTINCT FROM OLD.manifest_json THEN RETURN NEW; END IF;
  INSERT INTO zeroship.workflow_deploy_notifications (app_id, revision) VALUES (NEW.id, 1)
    ON CONFLICT (app_id) DO UPDATE SET revision=zeroship.workflow_deploy_notifications.revision + 1;
  RETURN NEW;
END;
$zsfn$;

REVOKE ALL ON FUNCTION zeroship.workflow_deploy_notify() FROM PUBLIC;

CREATE TRIGGER "workflow_deploy_notify" AFTER INSERT OR UPDATE ON "zeroship"."apps" FOR EACH ROW EXECUTE FUNCTION "zeroship"."workflow_deploy_notify"();

INSERT INTO zeroship.workflow_rollout_config (id,dispatch_paused,ingress_disabled) VALUES ('global',false,false) ON CONFLICT (id) DO NOTHING;

GRANT USAGE ON SCHEMA "zeroship" TO "zeroship_workflow";

GRANT SELECT (id,plan_id,organization_id,workflows_enabled,archived_at,deleted_at,deploy_hash,manifest_json) ON zeroship.apps TO zeroship_workflow;

GRANT SELECT (id,app_id,deploy_hash,manifest_json,activated_at) ON zeroship.app_deploys TO zeroship_workflow;

GRANT SELECT (app_id,revision) ON zeroship.workflow_deploy_notifications TO zeroship_workflow;

GRANT SELECT (id,workflows_allowed,archived,runtime_limits_json) ON zeroship.plans TO zeroship_workflow;

GRANT SELECT (organization_id,state) ON zeroship.organization_billing_status TO zeroship_workflow;

GRANT SELECT (app_id,state) ON zeroship.app_spend_state TO zeroship_workflow;

GRANT SELECT (id,dispatch_paused,ingress_disabled) ON zeroship.workflow_rollout_config TO zeroship_workflow;

GRANT SELECT (id,status,public_key) ON zeroship.worker_instances TO zeroship_workflow;
INSERT INTO workflow.schema_version (id, fingerprint) VALUES ('platform_policy', 'bfaaa0b0df43e7077b281e34505dff534804a47d157e58c7f7549693aebb06c1');
