-- Generated by schema/generate.mjs through the migration compiler.
CREATE TABLE "schema_version" ("id" TEXT PRIMARY KEY NOT NULL, "fingerprint" TEXT NOT NULL);

CREATE TABLE "apps" ("app_id" TEXT PRIMARY KEY NOT NULL, "revision" INTEGER NOT NULL, "policy" TEXT, "signal_epoch" INTEGER NOT NULL, "last_polled_at" INTEGER NOT NULL DEFAULT 0, "subscription_sequence" INTEGER NOT NULL DEFAULT 0);

CREATE TABLE "deploys" ("app_id" TEXT NOT NULL, "id" TEXT NOT NULL, "hash" TEXT NOT NULL, "manifest" TEXT NOT NULL, "created_at" INTEGER NOT NULL, "active" INTEGER NOT NULL, "state" TEXT NOT NULL, CONSTRAINT "deploys_app" FOREIGN KEY (app_id) REFERENCES apps(app_id) ON DELETE RESTRICT, CONSTRAINT "deploys_pkey" PRIMARY KEY (app_id, id));

CREATE UNIQUE INDEX IF NOT EXISTS "deploy_hash_identity" ON "deploys" ("app_id", "hash");

CREATE TABLE "schedules" ("app_id" TEXT NOT NULL, "id" TEXT NOT NULL, "name" TEXT NOT NULL, "workflow_name" TEXT NOT NULL, "deploy_id" TEXT NOT NULL, "definition" TEXT NOT NULL, "next_at" INTEGER, "revision" INTEGER NOT NULL, "anchor_at" INTEGER NOT NULL, "last_checked_at" INTEGER NOT NULL, CONSTRAINT "schedule_deploy" FOREIGN KEY (app_id, deploy_id) REFERENCES deploys(app_id, id) ON DELETE RESTRICT, CONSTRAINT "schedules_app" FOREIGN KEY (app_id) REFERENCES apps(app_id) ON DELETE RESTRICT, CONSTRAINT "schedules_pkey" PRIMARY KEY (app_id, id));

CREATE INDEX IF NOT EXISTS "schedule_deploy_idx" ON "schedules" ("app_id", "deploy_id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_name" ON "schedules" ("app_id", "name");

CREATE INDEX IF NOT EXISTS "schedules_due_idx" ON "schedules" ("next_at", "app_id", "id");

CREATE TABLE "runs" ("app_id" TEXT NOT NULL, "id" TEXT NOT NULL, "workflow_name" TEXT NOT NULL, "deploy_id" TEXT NOT NULL, "generation" INTEGER NOT NULL, "state" TEXT NOT NULL, "control" TEXT NOT NULL, "due_at" INTEGER, "task_id" TEXT, "lease_epoch" INTEGER NOT NULL, "key" TEXT, "parent_id" TEXT, "parent_generation" INTEGER, "parent_ordinal" INTEGER, "cascade" INTEGER NOT NULL, "depth" INTEGER NOT NULL, "created_at" INTEGER NOT NULL, "terminal_at" INTEGER, "signal_epoch" INTEGER NOT NULL, "compensation_target" TEXT, "schedule_id" TEXT, "continued_from_id" TEXT, "continued_to_id" TEXT, CONSTRAINT "run_continued_from" FOREIGN KEY (app_id, continued_from_id) REFERENCES runs(app_id, id) ON DELETE RESTRICT, CONSTRAINT "run_continued_to" FOREIGN KEY (app_id, continued_to_id) REFERENCES runs(app_id, id) ON DELETE RESTRICT, CONSTRAINT "run_deploy" FOREIGN KEY (app_id, deploy_id) REFERENCES deploys(app_id, id) ON DELETE RESTRICT, CONSTRAINT "run_parent" FOREIGN KEY (app_id, parent_id) REFERENCES runs(app_id, id) ON DELETE RESTRICT, CONSTRAINT "run_schedule" FOREIGN KEY (app_id, schedule_id) REFERENCES schedules(app_id, id) ON DELETE RESTRICT, CONSTRAINT "runs_app" FOREIGN KEY (app_id) REFERENCES apps(app_id) ON DELETE RESTRICT, CONSTRAINT "runs_pkey" PRIMARY KEY (app_id, id));

CREATE INDEX IF NOT EXISTS "run_continued_from_idx" ON "runs" ("app_id", "continued_from_id");

CREATE INDEX IF NOT EXISTS "run_continued_to_idx" ON "runs" ("app_id", "continued_to_id");

CREATE INDEX IF NOT EXISTS "run_deploy_idx" ON "runs" ("app_id", "deploy_id");

CREATE INDEX IF NOT EXISTS "run_parent_idx" ON "runs" ("app_id", "parent_id");

CREATE INDEX IF NOT EXISTS "run_schedule_idx" ON "runs" ("app_id", "schedule_id");

CREATE UNIQUE INDEX IF NOT EXISTS "live_workflow_key" ON "runs" ("app_id", "workflow_name", "key");

CREATE INDEX IF NOT EXISTS "runs_due_idx" ON "runs" ("due_at", "app_id", "id");

CREATE INDEX IF NOT EXISTS "runs_parent_idx" ON "runs" ("app_id", "parent_id", "parent_generation");

CREATE TABLE "generations" ("app_id" TEXT NOT NULL, "run_id" TEXT NOT NULL, "generation" INTEGER NOT NULL, "deploy_id" TEXT NOT NULL, "input" TEXT NOT NULL, "input_ref" TEXT, "output" TEXT, "output_ref" TEXT, "error" TEXT, "state" TEXT NOT NULL, "started_at" INTEGER NOT NULL, "terminal_at" INTEGER, CONSTRAINT "generation_deploy" FOREIGN KEY (app_id, deploy_id) REFERENCES deploys(app_id, id) ON DELETE RESTRICT, CONSTRAINT "generations_pkey" PRIMARY KEY (app_id, run_id, generation), CONSTRAINT "generations_run" FOREIGN KEY (app_id, run_id) REFERENCES runs(app_id, id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "generation_deploy_idx" ON "generations" ("app_id", "deploy_id");

CREATE TABLE "steps" ("app_id" TEXT NOT NULL, "run_id" TEXT NOT NULL, "generation" INTEGER NOT NULL, "ordinal" INTEGER NOT NULL, "name" TEXT NOT NULL, "occurrence" INTEGER NOT NULL, "origin_generation" INTEGER NOT NULL, "kind" TEXT NOT NULL, "state" TEXT NOT NULL, "record" TEXT NOT NULL, "compensation_attempts" INTEGER NOT NULL DEFAULT 0, "compensation_due_at" INTEGER, "compensation_error" TEXT, "compensation_retry_ms" INTEGER NOT NULL DEFAULT 1000, CONSTRAINT "steps_generation" FOREIGN KEY (app_id, run_id, generation) REFERENCES generations(app_id, run_id, generation) ON DELETE RESTRICT, CONSTRAINT "steps_pkey" PRIMARY KEY (app_id, run_id, generation, ordinal));

CREATE UNIQUE INDEX IF NOT EXISTS "step_name_occurrence" ON "steps" ("app_id", "run_id", "generation", "name", "occurrence");

CREATE TABLE "tasks" ("app_id" TEXT NOT NULL, "run_id" TEXT NOT NULL, "generation" INTEGER NOT NULL, "id" TEXT PRIMARY KEY NOT NULL, "worker" TEXT NOT NULL, "epoch" INTEGER NOT NULL, "token_hash" TEXT NOT NULL, "deadline" INTEGER NOT NULL, "state" TEXT NOT NULL, "completion_digest" TEXT, "receipt" TEXT, "created_at" INTEGER NOT NULL, "finished_at" INTEGER, CONSTRAINT "tasks_generation" FOREIGN KEY (app_id, run_id, generation) REFERENCES generations(app_id, run_id, generation) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "tasks_generation_idx" ON "tasks" ("app_id", "run_id", "generation");

CREATE UNIQUE INDEX IF NOT EXISTS "task_scope_identity" ON "tasks" ("app_id", "run_id", "generation", "id");

CREATE UNIQUE INDEX IF NOT EXISTS "task_fence_identity" ON "tasks" ("app_id", "run_id", "generation", "epoch");

CREATE INDEX IF NOT EXISTS "tasks_admission_idx" ON "tasks" ("app_id", "state", "deadline");

CREATE TABLE "waits" ("app_id" TEXT NOT NULL, "run_id" TEXT NOT NULL, "generation" INTEGER NOT NULL, "ordinal" INTEGER NOT NULL, "kind" TEXT NOT NULL, "signal_type" TEXT, "topic" TEXT, "max_signal_age" INTEGER, "due_at" INTEGER, "child_id" TEXT, CONSTRAINT "wait_child" FOREIGN KEY (app_id, child_id) REFERENCES runs(app_id, id) ON DELETE RESTRICT, CONSTRAINT "wait_step" FOREIGN KEY (app_id, run_id, generation, ordinal) REFERENCES steps(app_id, run_id, generation, ordinal) ON DELETE RESTRICT, CONSTRAINT "waits_pkey" PRIMARY KEY (app_id, run_id, generation, ordinal));

CREATE INDEX IF NOT EXISTS "wait_child_idx" ON "waits" ("app_id", "child_id");

CREATE TABLE "topics" ("app_id" TEXT NOT NULL, "topic" TEXT NOT NULL, "signal_epoch" INTEGER NOT NULL, CONSTRAINT "topics_app" FOREIGN KEY (app_id) REFERENCES apps(app_id) ON DELETE RESTRICT, CONSTRAINT "topics_pkey" PRIMARY KEY (app_id, topic));

CREATE TABLE "broadcasts" ("app_id" TEXT NOT NULL, "id" TEXT NOT NULL, "topic" TEXT NOT NULL, "signal_type" TEXT NOT NULL, "payload" TEXT NOT NULL, "created_at" INTEGER NOT NULL, "cursor" INTEGER NOT NULL, "cutoff_sequence" INTEGER NOT NULL, "origin" TEXT NOT NULL, "finished" INTEGER NOT NULL, CONSTRAINT "broadcasts_app" FOREIGN KEY (app_id) REFERENCES apps(app_id) ON DELETE RESTRICT, CONSTRAINT "broadcasts_pkey" PRIMARY KEY (app_id, id));

CREATE TABLE "signals" ("app_id" TEXT NOT NULL, "run_id" TEXT NOT NULL, "id" TEXT NOT NULL, "signal_type" TEXT NOT NULL, "payload" TEXT NOT NULL, "created_at" INTEGER NOT NULL, "consumed_generation" INTEGER, "consumed_ordinal" INTEGER, "broadcast_id" TEXT, "origin" TEXT NOT NULL DEFAULT 'app', "delivery" TEXT NOT NULL DEFAULT 'direct', "topic" TEXT, "target_generation" INTEGER, "target_ordinal" INTEGER, CONSTRAINT "signal_broadcast" FOREIGN KEY (app_id, broadcast_id) REFERENCES broadcasts(app_id, id) ON DELETE RESTRICT, CONSTRAINT "signal_consumption" FOREIGN KEY (app_id, run_id, consumed_generation, consumed_ordinal) REFERENCES steps(app_id, run_id, generation, ordinal) ON DELETE RESTRICT, CONSTRAINT "signal_target" FOREIGN KEY (app_id, run_id, target_generation, target_ordinal) REFERENCES steps(app_id, run_id, generation, ordinal) ON DELETE RESTRICT, CONSTRAINT "signals_pkey" PRIMARY KEY (app_id, id), CONSTRAINT "signals_run" FOREIGN KEY (app_id, run_id) REFERENCES runs(app_id, id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "signal_broadcast_idx" ON "signals" ("app_id", "broadcast_id");

CREATE INDEX IF NOT EXISTS "signal_consumption_idx" ON "signals" ("app_id", "run_id", "consumed_generation", "consumed_ordinal");

CREATE INDEX IF NOT EXISTS "signal_target_idx" ON "signals" ("app_id", "run_id", "target_generation", "target_ordinal");

CREATE INDEX IF NOT EXISTS "signals_run_idx" ON "signals" ("app_id", "run_id");

CREATE UNIQUE INDEX IF NOT EXISTS "broadcast_delivery" ON "signals" ("app_id", "broadcast_id", "run_id");

CREATE INDEX IF NOT EXISTS "signals_mailbox_idx" ON "signals" ("app_id", "run_id", "signal_type", "consumed_generation", "created_at");

CREATE TABLE "subscriptions" ("app_id" TEXT NOT NULL, "run_id" TEXT NOT NULL, "generation" INTEGER NOT NULL, "ordinal" INTEGER NOT NULL, "id" TEXT NOT NULL, "topic" TEXT NOT NULL, "created_at" INTEGER NOT NULL, "sequence" INTEGER NOT NULL, CONSTRAINT "subscription_step" FOREIGN KEY (app_id, run_id, generation, ordinal) REFERENCES steps(app_id, run_id, generation, ordinal) ON DELETE RESTRICT, CONSTRAINT "subscriptions_pkey" PRIMARY KEY (app_id, run_id, generation, ordinal));

CREATE UNIQUE INDEX IF NOT EXISTS "subscription_identity" ON "subscriptions" ("app_id", "id");

CREATE UNIQUE INDEX IF NOT EXISTS "subscription_sequence" ON "subscriptions" ("app_id", "sequence");

CREATE INDEX IF NOT EXISTS "subscriptions_topic_idx" ON "subscriptions" ("app_id", "topic", "id");

CREATE TABLE "requests" ("app_id" TEXT NOT NULL, "id" TEXT NOT NULL, "operation" TEXT NOT NULL, "digest" TEXT NOT NULL, "result" TEXT NOT NULL, "expires_at" INTEGER NOT NULL, CONSTRAINT "requests_app" FOREIGN KEY (app_id) REFERENCES apps(app_id) ON DELETE RESTRICT, CONSTRAINT "requests_pkey" PRIMARY KEY (app_id, id));

CREATE INDEX IF NOT EXISTS "requests_expiry_idx" ON "requests" ("expires_at");

CREATE TABLE "occurrences" ("app_id" TEXT NOT NULL, "schedule_id" TEXT NOT NULL, "at" INTEGER NOT NULL, "run_id" TEXT, CONSTRAINT "occurrence_run" FOREIGN KEY (app_id, run_id) REFERENCES runs(app_id, id) ON DELETE RESTRICT, CONSTRAINT "occurrence_schedule" FOREIGN KEY (app_id, schedule_id) REFERENCES schedules(app_id, id) ON DELETE RESTRICT, CONSTRAINT "occurrences_pkey" PRIMARY KEY (app_id, schedule_id, at));

CREATE INDEX IF NOT EXISTS "occurrence_run_idx" ON "occurrences" ("app_id", "run_id");

CREATE TABLE "payloads" ("app_id" TEXT NOT NULL, "run_id" TEXT NOT NULL, "generation" INTEGER NOT NULL, "id" TEXT NOT NULL, "task_id" TEXT NOT NULL, "request_id" TEXT NOT NULL, "hash" TEXT NOT NULL, "size" INTEGER NOT NULL, "content_type" TEXT, "state" TEXT NOT NULL, "created_at" INTEGER NOT NULL, "expires_at" INTEGER NOT NULL, CONSTRAINT "payload_task" FOREIGN KEY (app_id, run_id, generation, task_id) REFERENCES tasks(app_id, run_id, generation, id) ON DELETE RESTRICT, CONSTRAINT "payloads_generation" FOREIGN KEY (app_id, run_id, generation) REFERENCES generations(app_id, run_id, generation) ON DELETE RESTRICT, CONSTRAINT "payloads_pkey" PRIMARY KEY (app_id, id));

CREATE INDEX IF NOT EXISTS "payload_task_idx" ON "payloads" ("app_id", "run_id", "generation", "task_id");

CREATE INDEX IF NOT EXISTS "payloads_generation_idx" ON "payloads" ("app_id", "run_id", "generation");

CREATE UNIQUE INDEX IF NOT EXISTS "payload_upload_request" ON "payloads" ("app_id", "task_id", "request_id");

CREATE INDEX IF NOT EXISTS "payloads_expiry_idx" ON "payloads" ("state", "expires_at");

CREATE TABLE "payload_refs" ("app_id" TEXT NOT NULL, "run_id" TEXT NOT NULL, "generation" INTEGER NOT NULL, "slot" TEXT NOT NULL, "ordinal" INTEGER NOT NULL, "payload_id" TEXT NOT NULL, CONSTRAINT "payload_ref" FOREIGN KEY (app_id, payload_id) REFERENCES payloads(app_id, id) ON DELETE RESTRICT, CONSTRAINT "payload_refs_generation" FOREIGN KEY (app_id, run_id, generation) REFERENCES generations(app_id, run_id, generation) ON DELETE RESTRICT, CONSTRAINT "payload_refs_pkey" PRIMARY KEY (app_id, run_id, generation, slot, ordinal));

CREATE INDEX IF NOT EXISTS "payload_ref_idx" ON "payload_refs" ("app_id", "payload_id");

CREATE TABLE "outbox" ("app_id" TEXT NOT NULL, "id" TEXT NOT NULL, "kind" TEXT NOT NULL, "payload" TEXT NOT NULL, "created_at" INTEGER NOT NULL, "delivered_at" INTEGER, CONSTRAINT "outbox_app" FOREIGN KEY (app_id) REFERENCES apps(app_id) ON DELETE RESTRICT, CONSTRAINT "outbox_pkey" PRIMARY KEY (app_id, id));

CREATE INDEX IF NOT EXISTS "outbox_delivery_idx" ON "outbox" ("delivered_at", "created_at");
INSERT INTO main.schema_version (id, fingerprint) VALUES ('workflow', '8c55591d94ad0d6a1ac979178cf6743239426b3ff77a79e0964887df95d6e69a');
