/**
 * GENERATED by schema/codegen.mjs from schema/project-v1.json -- DO NOT EDIT.
 *
 * Regenerate with `node schema/codegen.mjs`; `tests/project_config_gate.sh`
 * fails the build when this file drifts from the schema.
 *
 * The plugin applies every default when there is no file. For a present file,
 * optional non-CLI defaults are also generated into Rust so the readers agree.
 * Defaults for CLI-read facts never reach Rust: silence there is an error.
 */

export const CONFIG_FILENAME = "zeroship.jsonc";
export const CONFIG_ENV_VAR = "ZEROSHIP_CONFIG";
export const SCHEMA_ID = "https://zeroship.ai/schema/project-v1.json";

/** Fields the Rust CLI also reads. The `config` escape hatch may not touch these. */
export const CLI_READ_FIELDS: readonly string[] = ["name","app","control","runtime_date","build.output","migrations.dir","migrations.out"];

/** Key names that must never appear anywhere in the file. */
export const FORBIDDEN_KEY_NAMES: readonly string[] = ["password","token","secret","key","apiKey","credentials"];

export const ROOT_KNOWN_KEYS: readonly string[] = ["$schema","name","app","control","runtime_date","build","migrations","secrets","environments"];
export const ROOT_REQUIRED_KEYS: readonly string[] = ["name","control","runtime_date","build","migrations"];
export const BUILD_KNOWN_KEYS: readonly string[] = ["mode","serverEntry","dist","output"];
export const BUILD_REQUIRED_KEYS: readonly string[] = ["mode","dist","output"];
export const MIGRATIONS_KNOWN_KEYS: readonly string[] = ["dir","out"];
export const MIGRATIONS_REQUIRED_KEYS: readonly string[] = ["dir","out"];
export const ENVIRONMENT_KNOWN_KEYS: readonly string[] = ["app","control","protected","build","migrations","secrets"];
export const ENVIRONMENT_REQUIRED_KEYS: readonly string[] = ["app","control"];

/** Every string field carrying a `pattern` or an `enum`, for validation. */
export const FIELD_RULES: readonly {
  path: string; type: "string" | "boolean" | "string[]";
  enum?: readonly string[]; pattern?: string; itemPattern?: string;
}[] = [{"path":"$schema","type":"string"},{"path":"name","type":"string","pattern":"^[a-z0-9][a-z0-9-]{0,62}$"},{"path":"app","type":"string"},{"path":"control","type":"string"},{"path":"runtime_date","type":"string","pattern":"^[0-9]{4}-[0-9]{2}-[0-9]{2}$"},{"path":"build.mode","type":"string","enum":["full","static"]},{"path":"build.serverEntry","type":"string"},{"path":"build.dist","type":"string","pattern":"^(?!\\.{1,2}$).+$"},{"path":"build.output","type":"string"},{"path":"migrations.dir","type":"string"},{"path":"migrations.out","type":"string"},{"path":"secrets","type":"string[]","itemPattern":"^[A-Z][A-Z0-9_]{0,63}$"},{"path":"protected","type":"boolean"}];

/** Every schema `default`, by dotted path. The ONLY copy in the TS tree. */
export const DEFAULTS: Readonly<Record<string, unknown>> = {
  "build.mode": "full",
  "build.dist": "dist",
  "build.output": "dist/app.zship",
  "migrations.dir": "migrations",
  "migrations.out": "generated/zeroship",
  "secrets": [],
};

/** The shape a fully-resolved config takes. */
export interface ResolvedProjectConfig {
  name: string;
  app?: string;
  control: string;
  runtime_date: string;
  build: { mode: "full" | "static"; serverEntry?: string; dist: string; output: string };
  migrations: { dir: string; out: string };
  secrets: string[];
  protected?: boolean;
}
