import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { coordinatorIdentityColumns, workflowCoordinatorSchema } from "./schema.ts";
import { buildEnvelope } from "../../../packages/zero-migrate/dist/internal/recorder.js";
import { currentIrVersion, previewSql } from "../../../packages/zero-migrate-cli/dist/index.js";

const envelope = buildEnvelope({ name: "workflow_coordination", schema: workflowCoordinatorSchema }, { irVersion: currentIrVersion() });
if (!envelope.ops.length) throw new Error("coordinator schema recorder is empty");
const charter = await readFile(new URL("../../../policies/platform.policy.toml", import.meta.url), "utf8");
const emitted = previewSql({ envelopes: [JSON.stringify(envelope)], dialect: "postgres", defaultSchema: "workflow_coordination", ownerApp: "zeroship_platform", charterLayers: [charter] }).join("\n");
if (emitted.includes("[runtime-resolved]")) throw new Error("coordinator schema must lower completely");
// Preview annotations contain measured tallies; shipped SQL retains statements.
const sql = emitted.split("\n").filter(line => !line.startsWith("--")).join("\n").trim();
const fingerprint = createHash("sha256").update(sql).digest("hex");
const outputs = [
  ["postgres.sql", `-- Generated by schema/generate.mjs through the migration compiler.\n${sql}\nINSERT INTO workflow_coordination.schema_version (id, fingerprint) VALUES ('coordination', '${fingerprint}');\n`],
  ["fingerprint.txt", `${fingerprint}\n`],
  ["identity-columns.json", `${JSON.stringify(coordinatorIdentityColumns, null, 2)}\n`],
];
for (const [name, content] of outputs) {
  const path = new URL(name, import.meta.url);
  if (process.argv.includes("--check")) {
    if (await readFile(path, "utf8") !== content) throw new Error(`stale coordinator schema ${name}; run node crates/zeroship-workflow-server/schema/generate.mjs`);
  } else {
    await writeFile(path, content);
  }
}
