-- Generated by schema/generate.mjs through the migration compiler.
CREATE TABLE "workflow_coordination"."schema_version" ("id" text PRIMARY KEY NOT NULL, "fingerprint" text NOT NULL);

CREATE TABLE "workflow_coordination"."workers" ("worker_id" text PRIMARY KEY NOT NULL, "capacity" bigint NOT NULL, "state" text NOT NULL, "expires_at" bigint NOT NULL);

CREATE TABLE "workflow_coordination"."scopes" ("app_id" text PRIMARY KEY NOT NULL);

CREATE TABLE "workflow_coordination"."assignments" ("app_id" text NOT NULL, "worker_id" text NOT NULL, "revision" bigint NOT NULL, "expires_at" bigint NOT NULL, "released" boolean NOT NULL, "wake_revision" bigint, "next_due_at" bigint, CONSTRAINT "assignment_scope" FOREIGN KEY ("app_id") REFERENCES "workflow_coordination"."scopes" ("app_id") ON DELETE RESTRICT, CONSTRAINT "assignment_worker" FOREIGN KEY ("worker_id") REFERENCES "workflow_coordination"."workers" ("worker_id") ON DELETE RESTRICT, CONSTRAINT "assignments_pkey" PRIMARY KEY (app_id, worker_id));

CREATE INDEX IF NOT EXISTS "assignment_worker_idx" ON "workflow_coordination"."assignments" ("worker_id");

CREATE INDEX IF NOT EXISTS "assignments_worker_idx" ON "workflow_coordination"."assignments" ("worker_id", "app_id");

CREATE INDEX IF NOT EXISTS "assignments_expiry_idx" ON "workflow_coordination"."assignments" ("expires_at", "app_id");

CREATE TABLE "workflow_coordination"."placement_receipts" ("app_id" text NOT NULL, "request_id" text NOT NULL, "operation" text NOT NULL, "worker_id" text NOT NULL, "expected_revision" bigint, "wake_revision" bigint, "result_revision" bigint NOT NULL, "result_expires_at" bigint NOT NULL, CONSTRAINT "receipt_scope" FOREIGN KEY ("app_id") REFERENCES "workflow_coordination"."scopes" ("app_id") ON DELETE RESTRICT, CONSTRAINT "placement_receipts_pkey" PRIMARY KEY (app_id, request_id));

CREATE TABLE "workflow_coordination"."management" ("app_id" text NOT NULL, "request_id" text NOT NULL, "run_id" text NOT NULL, "actor" text NOT NULL, "operation" text NOT NULL, "restart_name" text, "restart_occurrence" bigint, "restart_deploy" text, "created_at" bigint NOT NULL, "outcome" text, "run_state" text, "ack_worker_id" text, "ack_revision" bigint, CONSTRAINT "management_scope" FOREIGN KEY ("app_id") REFERENCES "workflow_coordination"."scopes" ("app_id") ON DELETE RESTRICT, CONSTRAINT "management_pkey" PRIMARY KEY (app_id, request_id));

CREATE INDEX IF NOT EXISTS "management_pending_idx" ON "workflow_coordination"."management" ("app_id", "outcome", "created_at", "request_id");

ALTER TABLE workflow_coordination."workers" ALTER COLUMN "worker_id" TYPE text COLLATE "C";

ALTER TABLE workflow_coordination."scopes" ALTER COLUMN "app_id" TYPE text COLLATE "C";

ALTER TABLE workflow_coordination."assignments" ALTER COLUMN "app_id" TYPE text COLLATE "C", ALTER COLUMN "worker_id" TYPE text COLLATE "C";

ALTER TABLE workflow_coordination."placement_receipts" ALTER COLUMN "app_id" TYPE text COLLATE "C", ALTER COLUMN "request_id" TYPE text COLLATE "C", ALTER COLUMN "worker_id" TYPE text COLLATE "C";

ALTER TABLE workflow_coordination."management" ALTER COLUMN "app_id" TYPE text COLLATE "C", ALTER COLUMN "request_id" TYPE text COLLATE "C", ALTER COLUMN "run_id" TYPE text COLLATE "C", ALTER COLUMN "ack_worker_id" TYPE text COLLATE "C";
INSERT INTO workflow_coordination.schema_version (id, fingerprint) VALUES ('coordination', '9289c6c05c79aefa1960f8eee81fda7f812fc433c80ecd221d4cd059062a83e1');
