import { readFile, writeFile } from "node:fs/promises";
import { isDeepStrictEqual } from "node:util";
import { genArtifacts } from "../../../../crates/zeroship-migrate-node/index.js";
import { buildEnvelope } from "../../../../packages/zero-migrate/dist/internal/recorder.js";
import { currentIrVersion, previewSql } from "../../../../packages/zero-migrate-cli/dist/index.js";
import { deploymentSchema } from "./schema.ts";

const check = process.argv.includes("--check");
const outputs = [];
let runtime;
for (const dialect of ["postgres", "sqlite"]) {
  const namespace = dialect === "postgres" ? "zeroship" : "main";
  const envelope = buildEnvelope({ name: "app_deployments", schema: () => deploymentSchema(namespace) }, { irVersion: currentIrVersion() });
  if (!envelope.ops.length) throw new Error("deployment schema recorder is empty");
  const charter = `policy_version = 1
[[grant]]
key = "schema.create_table"
value = true
scope = { include = ["${namespace}"] }
[[grant]]
key = "schema.cross_schema"
value = true
scope = { include = ["${namespace}"] }
`;
  const args = { dialect, projectSchema: namespace, charterLayers: [charter] };
  const artifacts = genArtifacts({ ...args, envelopes: [envelope] });
  if (!artifacts.ok) throw new Error(artifacts.error);
  const descriptor = JSON.parse(artifacts.runtimeJson);
  if (!descriptor.collections.app_deploys || !descriptor.collections.app_deploy_holds) throw new Error("deployment descriptor is incomplete");
  if (runtime && !isDeepStrictEqual(runtime, descriptor)) throw new Error("deployment metadata differs by dialect");
  runtime = descriptor;
  const statements = previewSql({ ...args, envelopes: [JSON.stringify(envelope)], defaultSchema: namespace, ownerApp: "deployments" });
  const sql = statements.join("\n").split("\n").filter(line => !line.startsWith("--")).join("\n").trim();
  if (sql.includes("[runtime-resolved]")) throw new Error("deployment schema must lower completely");
  outputs.push({ name: `${dialect}.sql`, content: `-- Generated by schema/deployments/generate.mjs through the migration compiler.\n${sql}\n` });
}
outputs.push({ name: "schema.runtime.json", content: JSON.stringify(runtime, null, 2) + "\n" });
for (const { name, content } of outputs) {
  const path = new URL(name, import.meta.url);
  if (check) {
    if (await readFile(path, "utf8") !== content) throw new Error(`stale deployment schema: ${name}`);
  } else {
    await writeFile(path, content);
  }
}
