use deno_core::*;
use rusqlite::Connection;
use std::borrow::Cow;
use std::cell::RefCell;
use std::rc::Rc;
use std::sync::Arc;

use crate::ops;

#[derive(Debug)]
pub struct RpcResult(pub RefCell<String>);

#[op2(fast)]
pub fn op_set_rpc_result(state: &mut OpState, #[string] result: &str) {
    let rpc = state.borrow::<Rc<RpcResult>>();
    *rpc.0.borrow_mut() = result.to_string();
}

static RUNTIME_JS: &str = include_str!("embed/runtime.js");

fn ops_list() -> Vec<OpDecl> {
    vec![
        ops::op_db_ensure_table(),
        ops::op_db_insert(),
        ops::op_db_find(),
        ops::op_db_update(),
        ops::op_db_delete(),
        op_set_rpc_result(),
    ]
}

/// Build extension with ops + ESM (for first-time/non-snapshot mode)
fn build_extension_full() -> Extension {
    let runtime_code: Arc<str> = Arc::from(RUNTIME_JS);
    let runtime_js = ExtensionFileSource::new_computed("ext:appbase/runtime.js", runtime_code);

    Extension {
        name: "appbase",
        ops: Cow::Owned(ops_list()),
        esm_files: Cow::Owned(vec![runtime_js]),
        esm_entry_point: Some("ext:appbase/runtime.js"),
        ..Default::default()
    }
}

/// Build extension with ops only (for snapshot mode — JS already baked in)
fn build_extension_ops_only() -> Extension {
    Extension {
        name: "appbase",
        ops: Cow::Owned(ops_list()),
        ..Default::default()
    }
}

// Snapshot — loaded at runtime from file (not embedded at compile time)
// This avoids the chicken-and-egg problem of build.rs needing the library

/// Create the snapshot at build time. Called from build.rs.
#[cfg(feature = "snapshot")]
pub fn create_snapshot() -> Box<[u8]> {
    let mut runtime = JsRuntimeForSnapshot::new(RuntimeOptions {
        extensions: vec![build_extension_full()],
        ..Default::default()
    });
    runtime.snapshot()
}

pub fn create_v8_runtime(db_path: &str) -> Result<(JsRuntime, Rc<RpcResult>), String> {
    create_v8_runtime_inner(db_path, None)
}

/// Create a V8 runtime using a pre-built snapshot for faster startup.
/// The snapshot must be generated by `appbase-snapshot` binary.
pub fn create_v8_runtime_with_snapshot(
    db_path: &str,
    snapshot: &'static [u8],
) -> Result<(JsRuntime, Rc<RpcResult>), String> {
    create_v8_runtime_inner(db_path, Some(snapshot))
}

fn create_v8_runtime_inner(
    db_path: &str,
    snapshot: Option<&'static [u8]>,
) -> Result<(JsRuntime, Rc<RpcResult>), String> {
    let conn = Rc::new(Connection::open(db_path).map_err(|e| e.to_string())?);
    conn.execute_batch("PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;")
        .map_err(|e| e.to_string())?;

    let runtime = if let Some(snapshot_data) = snapshot {
        JsRuntime::new(RuntimeOptions {
            startup_snapshot: Some(snapshot_data),
            extensions: vec![build_extension_ops_only()],
            ..Default::default()
        })
    } else {
        JsRuntime::new(RuntimeOptions {
            extensions: vec![build_extension_full()],
            ..Default::default()
        })
    };

    let rpc_result = Rc::new(RpcResult(RefCell::new(String::new())));
    {
        let op_state = runtime.op_state();
        let mut state = op_state.borrow_mut();
        state.put(conn);
        state.put(rpc_result.clone());
    }

    Ok((runtime, rpc_result))
}

/// Result of an RPC call including CPU time consumed.
#[derive(Debug)]
pub struct RpcResponse {
    pub json: String,
    pub cpu_time: std::time::Duration,
}

pub async fn handle_rpc(
    runtime: &mut JsRuntime,
    rpc_result: &Rc<RpcResult>,
    request_json: &str,
    cpu_limits: &crate::cpu_timer::CpuLimits,
) -> Result<RpcResponse, deno_error::JsErrorBox> {
    fn err(e: impl std::fmt::Display) -> deno_error::JsErrorBox {
        deno_error::JsErrorBox::generic(e.to_string())
    }

    let escaped = request_json.replace('\\', "\\\\").replace('`', "\\`");

    let script = format!(
        r#"(async () => {{
            const result = await globalThis.__handleRpc(`{escaped}`);
            Deno.core.ops.op_set_rpc_result(result);
        }})()"#
    );

    // Measure CPU time (only counts actual CPU cycles, not I/O wait)
    let cpu_before = crate::cpu_timer::thread_cpu_time();

    runtime.execute_script("<rpc>", script).map_err(err)?;
    runtime
        .run_event_loop(Default::default())
        .await
        .map_err(err)?;

    let cpu_after = crate::cpu_timer::thread_cpu_time();
    let cpu_time = cpu_after.saturating_sub(cpu_before);

    // Check per-request CPU limit
    if let Some(max) = cpu_limits.max_cpu_per_request {
        if cpu_time > max {
            return Err(deno_error::JsErrorBox::generic(format!(
                "CPU time limit exceeded: {:.1}ms used, {:.1}ms allowed",
                cpu_time.as_secs_f64() * 1000.0,
                max.as_secs_f64() * 1000.0,
            )));
        }
    }

    Ok(RpcResponse {
        json: rpc_result.0.borrow().clone(),
        cpu_time,
    })
}
