//! GENERATED by schema/codegen.mjs from schema/project-v1.json -- DO NOT EDIT.
//!
//! Regenerate with `node schema/codegen.mjs`; `tests/project_config_gate.sh`
//! fails the build when this file drifts from the schema.
//!
//! CLI-read defaults are absent unless the schema explicitly marks them safe.
//! Optional defaults generated below keep both readers byte-identical without
//! inventing a cross-tool scalar fact.

pub const CONFIG_FILENAME: &str = "zeroship.jsonc";
pub const CONFIG_ENV_VAR: &str = "ZEROSHIP_CONFIG";
pub const SCHEMA_ID: &str = "https://zeroship.ai/schema/project-v1.json";

/// Fields the CLI reads. The Vite `config` escape hatch may not touch these.
pub const CLI_READ_FIELDS: &[&str] = &["name", "app", "control", "runtime_date", "build.output", "migrations.dir", "migrations.out", "secrets", "protected"];

/// Key names that must never appear anywhere in the file.
pub const FORBIDDEN_KEY_NAMES: &[&str] = &["password", "token", "secret", "key", "apiKey", "credentials"];

pub const ROOT_KNOWN_KEYS: &[&str] = &["$schema", "name", "app", "control", "runtime_date", "build", "migrations", "secrets", "environments"];
pub const ROOT_REQUIRED_KEYS: &[&str] = &["name", "control", "runtime_date", "build", "migrations"];
pub const BUILD_KNOWN_KEYS: &[&str] = &["mode", "serverEntry", "dist", "output"];
pub const BUILD_REQUIRED_KEYS: &[&str] = &["mode", "dist", "output"];
pub const MIGRATIONS_KNOWN_KEYS: &[&str] = &["dir", "out"];
pub const MIGRATIONS_REQUIRED_KEYS: &[&str] = &["dir", "out"];
pub const ENVIRONMENT_KNOWN_KEYS: &[&str] = &["app", "control", "protected", "build", "migrations", "secrets"];
pub const ENVIRONMENT_REQUIRED_KEYS: &[&str] = &["app", "control"];

/// `(dotted path, regex-free validator tag)` for every constrained string.
///
/// The tag is matched in `super::validate`, which hand-writes each check: the
/// CLI has no regex crate and adding one for six patterns is not proportionate.
pub const FIELD_PATTERNS: &[(&str, &str)] = &[
    ("name", "^[a-z0-9][a-z0-9-]{0,62}$"),
    ("runtime_date", "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"),
    ("build.dist", "^(?!\\.{1,2}$).+$"),
    ("secrets[]", "^[A-Z][A-Z0-9_]{0,63}$"),
];

/// `(dotted path, allowed values)` for every enum-constrained string.
pub const FIELD_ENUMS: &[(&str, &[&str])] = &[
    ("build.mode", &["full", "static"]),
];

/// Every dotted path carrying a schema default.
///
/// Named rather than merely absent so the gate can assert the list is the exact
/// complete schema `default` set -- an omission here would read as "no default
/// exists" instead of a deliberate resolution rule.
pub const SCHEMA_DEFAULTED_FIELDS: &[&str] = &["build.mode", "build.dist", "build.output", "migrations.dir", "migrations.out", "secrets"];

/// Optional defaults explicitly safe for a present file's resolved view.
/// Values are JSON so arrays and future object defaults stay schema-generated.
pub const RESOLVED_OPTIONAL_DEFAULTS_JSON: &[(&str, &str)] = &[("secrets", "[]")];
