//! GENERATED by schema/codegen.mjs from schema/project-v1.json -- DO NOT EDIT.
//!
//! Regenerate with `node schema/codegen.mjs`; `tests/project_config_gate.sh`
//! fails the build when this file drifts from the schema.
//!
//! THERE ARE NO DEFAULTS IN THIS FILE, and that is the point (proposal 7.3).
//! Every default lives in `schema/project-v1.json` and reaches exactly one
//! reader, the TypeScript one. A key the CLI reads and the file omits is an
//! error naming the key -- so the two readers cannot hold different values for
//! the same fact, which is the bug `zeroship.jsonc` exists to remove.
//!
//! `tests/project_config_gate.sh` asserts the absence: a `default` literal
//! appearing here fails the gate.

pub const CONFIG_FILENAME: &str = "zeroship.jsonc";
pub const CONFIG_ENV_VAR: &str = "ZEROSHIP_CONFIG";
pub const SCHEMA_ID: &str = "https://zeroship.ai/schema/project-v1.json";

/// Fields the CLI reads. The Vite `config` escape hatch may not touch these.
pub const CLI_READ_FIELDS: &[&str] = &["name", "app", "control", "runtime_date", "build.output", "migrations.dir", "migrations.out"];

/// Key names that must never appear anywhere in the file (proposal 8.4).
pub const FORBIDDEN_KEY_NAMES: &[&str] = &["password", "token", "secret", "key", "apiKey", "credentials"];

pub const ROOT_KNOWN_KEYS: &[&str] = &["$schema", "name", "app", "control", "runtime_date", "build", "migrations", "secrets", "environments"];
pub const ROOT_REQUIRED_KEYS: &[&str] = &["name", "control", "runtime_date", "build", "migrations"];
pub const BUILD_KNOWN_KEYS: &[&str] = &["mode", "serverEntry", "dist", "output"];
pub const BUILD_REQUIRED_KEYS: &[&str] = &["mode", "dist", "output"];
pub const MIGRATIONS_KNOWN_KEYS: &[&str] = &["dir", "out"];
pub const MIGRATIONS_REQUIRED_KEYS: &[&str] = &["dir", "out"];
pub const ENVIRONMENT_KNOWN_KEYS: &[&str] = &["app", "control", "protected", "build", "migrations", "secrets"];
pub const ENVIRONMENT_REQUIRED_KEYS: &[&str] = &["app", "control"];

/// `(dotted path, regex-free validator tag)` for every constrained string.
///
/// The tag is matched in `super::validate`, which hand-writes each check: the
/// CLI has no regex crate and adding one for six patterns is not proportionate.
pub const FIELD_PATTERNS: &[(&str, &str)] = &[
    ("name", "^[a-z0-9][a-z0-9-]{0,62}$"),
    ("runtime_date", "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"),
    ("secrets[]", "^[A-Z][A-Z0-9_]{0,63}$"),
];

/// `(dotted path, allowed values)` for every enum-constrained string.
pub const FIELD_ENUMS: &[(&str, &[&str])] = &[
    ("build.mode", &["full", "static"]),
];

/// Dotted paths the schema gives a default and this reader deliberately does NOT.
///
/// Named rather than merely absent so the gate can assert the list is the exact
/// complement of the schema's `default` set -- an omission here would read as
/// "no default exists" instead of "we chose not to have one".
pub const SCHEMA_DEFAULTED_FIELDS: &[&str] = &["build.mode", "build.dist", "build.output", "migrations.dir", "migrations.out", "secrets"];
