// sdks/vite-plugin/src/rpc-registry.ts
//
// Synthetic SSR entry generator (ZS-standard, descriptor-only cutover).
//
// The plugin emits one virtual module — `virtual:zeroship/_server-entry`
// — that imports the user's entry and normalises its exports into the
// `default = { schema?, fetch?, rpc? }` shape consumed by the runtime.
//
// `default.rpc` is a PLAIN OBJECT (dict-shape: `{ wireId: handler }`).
// Dispatch (input validation, capability frame, stream framing,
// dev-only output validation) is owned by `@zeroship/bootstrap`'s
// `__zsDispatch` + `createFetchHandler`. The plugin only wires the
// generated module to those shared runtime helpers; it does not inline
// dispatcher source.
//
// Two code paths:
//   - Namespace-walk (default): the entry walks `_zsUser`'s keys at
//     module-init time and rolls every callable non-`default`/`fetch`
//     export into `_zsRpc`, keyed by `fn.config.id ?? exportName`.
//     User's own `default.rpc` (if a plain object) merges in first;
//     named-export procedures take precedence on key conflict.
//   - Phase-2 (binding-fed): the reference-graph walk hands us a
//     `Map<string, ServerBinding>`. We emit one namespace import per
//     target file and a static dict literal mapping wireId → handler
//     reference (or an async arrow that does a dynamic import for
//     lazy bindings).

import type { Plugin } from "vite";
import type { TransformState } from "./transform.js";
import type { ServerBinding } from "./server-graph.js";

// ── Public IDs ─────────────────────────────────────────────────────────────

/** Public specifier for the synthetic server entry. */
export const SERVER_ENTRY_VIRTUAL_ID = "virtual:zeroship/_server-entry";
/** Internal (\0-prefixed) id Vite uses for the synthetic entry. */
export const SERVER_ENTRY_RESOLVED_ID = "\0" + SERVER_ENTRY_VIRTUAL_ID;

// ── Synthetic entry source ─────────────────────────────────────────────────

/**
 * Pick the wireId for a procedure. Mirrors `pickWireId()` in manifest.ts:
 * explicit `fn.config.id` (when string and non-empty) wins; default is
 * the bare export name. Kept in sync because the synthetic entry's
 * dispatch table must use the same key the manifest emitter advertises.
 */
export function pickEntryWireId(p: {
  exportName: string;
  config?: Record<string, unknown>;
}): string {
  const explicit = p.config?.id;
  if (typeof explicit === "string" && explicit.length > 0) return explicit;
  return p.exportName;
}

/**
 * Build the source of the synthetic server entry.
 *
 * Emits a normaliser that imports the user module and re-exports its
 * `default.{fetch, rpc}` after rolling callable non-`default` exports
 * into the dict-shape `rpc`. RPC fall-through is delegated to
 * `@zeroship/bootstrap` so input validation, capability frames, and
 * stream framing stay shared with dev/runtime.
 *
 * @param opts.userEntryRel  Specifier the synthetic entry should use to
 *                           import the user module.
 * @param opts.bindings      Optional pre-computed server-binding map.
 *                           When provided, switches to the Phase-2
 *                           static-dispatch shape (see below).
 */
export function buildServerEntrySource(opts: {
  userEntryRel: string;
  /** Explicit server-binding map. When provided, the synthetic entry
   *  emits per-target imports and a static `_zsRpc` dict literal.
   *  Falls back to namespace-walk normalisation when omitted or empty. */
  bindings?: Map<string, ServerBinding>;
}): string {
  const userImport = JSON.stringify(opts.userEntryRel);

  if (opts.bindings && opts.bindings.size > 0) {
    return buildPhase2Entry(userImport, opts.bindings);
  }

  // Namespace-walk normaliser. Static glue only: build the dict-shape
  // `default.rpc`, then hand `/__zeroship/v1/*` fall-through to the shared
  // bootstrap fetch handler so stream RPCs work in production too.
  return `// virtual:zeroship/_server-entry — auto-generated by @zeroship/vite-plugin
//
// Wire shape — \`default\`:
//   fetch    The user's own \`default.fetch\` (or a top-level \`fetch\`
//            export when no \`default\` object), wrapped by the bootstrap
//            fetch handler.
//   rpc      Dict-shape: { wireId: handler }. Dispatch is owned by the
//            bootstrap dispatcher. The plugin only normalises —
//            capability/Zod/stream framing live in shared runtime helpers.

// Side-effect import: forces the bundler to include the framework-
// internal bootstrap package so the runtime can dynamically resolve
// \`@zeroship/bootstrap/install-schema\` at module-eval time.
import "@zeroship/bootstrap";
import { createFetchHandler } from "@zeroship/bootstrap/fetch-handler";

import * as _zsUser from ${userImport};

const _zsUserDefaultExport = Reflect.get(_zsUser, "default");
const _zsUserDefault = (_zsUserDefaultExport && typeof _zsUserDefaultExport === "object")
  ? _zsUserDefaultExport
  : {};
const _zsUserDefaultThis = (_zsUserDefaultExport && typeof _zsUserDefaultExport === "object")
  ? _zsUserDefaultExport
  : null;

// Build the rpc dict from:
//   1. user.default.rpc (if it's a plain object — passed through verbatim
//      so users can declare procedures inline).
//   2. user.<name> for every callable non-\`default\`/\`fetch\` export
//      (rolled in; named-export procedures take precedence on key
//      conflict — they're the canonical source-level declaration).
const _zsRpc = (typeof _zsUserDefault.rpc === "object" && _zsUserDefault.rpc != null)
  ? { ..._zsUserDefault.rpc }
  : {};
for (const _zsName of Object.keys(_zsUser)) {
  if (_zsName === "default" || _zsName === "fetch") continue;
  const _zsFn = _zsUser[_zsName];
  if (typeof _zsFn !== "function") continue;
  const _zsId = (_zsFn.config && typeof _zsFn.config.id === "string" && _zsFn.config.id) || _zsName;
  _zsRpc[_zsId] = _zsFn;
}

// Pick user's default.fetch, with fall-through to a top-level export.
const _zsTopLevelFetch = Reflect.get(_zsUser, "fetch");
const _zsFetch = (typeof _zsUserDefault.fetch === "function")
  ? _zsUserDefault.fetch
  : (typeof _zsTopLevelFetch === "function" ? _zsTopLevelFetch : undefined);

const _zsFetchHandler = createFetchHandler(async () => ({
  fetch: _zsFetch,
  rpc: _zsRpc,
  userDefault: _zsUserDefaultThis,
}));

export default {
  fetch: _zsFetchHandler,
  rpc: _zsRpc,
};
`;
}

// ── Server-Binding Synthetic Entry (Phase-2) ──────────────────────────────
//
// When the plugin has run the reference-graph walk it hands the generator
// a `ServerBinding` map keyed by `<sourceFile>::<exportName>`. We emit
// one ESM import per target file (deduplicated) and a static `_zsRpc`
// literal keyed by wireId. The user's own `default.rpc` (when present)
// merges with the binding-derived entries — bindings win on key conflict
// because they're the explicit registration surface.

function buildPhase2Entry(
  userImport: string,
  bindings: Map<string, ServerBinding>,
): string {
  // Group bindings by source file so we emit ONE namespace import per
  // target. A file with both eager AND lazy exports lands in BOTH
  // columns: the namespace import for the eager ones, the dynamic-import
  // wrapper for the lazy ones. V8 de-dupes the module — the dynamic
  // import resolves to the same namespace the static import already
  // evaluated (Wave #187 host callback cache). The lazy wrapper is then
  // a Map lookup on the second call.
  const byFile = new Map<string, ServerBinding[]>();
  for (const b of bindings.values()) {
    const arr = byFile.get(b.sourceFile);
    if (arr) arr.push(b);
    else byFile.set(b.sourceFile, [b]);
  }

  // Files needing a static namespace import — those with at least one
  // EAGER binding. Lazy-only files get no static import.
  const eagerFiles = [...byFile.keys()]
    .filter((f) => byFile.get(f)!.some((b) => !b.lazy))
    .sort();
  const aliasOf = new Map<string, string>();
  eagerFiles.forEach((file, idx) => aliasOf.set(file, `_user_TARGET_${idx}_`));

  const importLines = eagerFiles
    .map((file) => `import * as ${aliasOf.get(file)} from ${JSON.stringify(file)};`)
    .join("\n");

  // Dict entries — eager bindings reference the static namespace alias,
  // lazy bindings emit an async arrow that dynamic-imports the target
  // and forwards (Wave #188).
  const tableEntries: string[] = [];
  const allFiles = [...byFile.keys()].sort();
  for (const file of allFiles) {
    for (const b of byFile.get(file)!) {
      if (b.lazy) {
        tableEntries.push(
          `  ${JSON.stringify(b.wireId)}: async (input, ctx) => ` +
            `(await import(${JSON.stringify(file)})).${b.exportName}(input, ctx),`,
        );
      } else {
        tableEntries.push(
          `  ${JSON.stringify(b.wireId)}: ${aliasOf.get(file)}.${b.exportName},`,
        );
      }
    }
  }

  return `// virtual:zeroship/_server-entry — auto-generated by @zeroship/vite-plugin
//
// Phase-2 (binding-fed) shape. The dispatch dict is statically derived
// from the reference-graph walk. Each entry maps a wireId to a per-target
// namespace member (eager) or to an async dynamic-import wrapper (lazy).
// User code never reaches this module; the resolveId hook keeps it
// behind a \\0-prefix. Dispatch lives in bootstrap's shared dispatcher
// and fetch handler — this file is glue, not a dispatcher fork.

// Side-effect imports: force the bundler to include the exact modules
// the runtime-entry resolves dynamically during isolate boot. Bundle
// inclusion matters even though the synthetic entry never calls them
// directly: the V8 module loader can only resolve dynamic imports
// against bundle-resident modules.
import "@zeroship/bootstrap/install-schema";
import "@zeroship/db/internal";
import { createFetchHandler } from "@zeroship/bootstrap/fetch-handler";

import * as _zsUser from ${userImport};
${importLines}

const _zsUserDefaultExport = Reflect.get(_zsUser, "default");
const _zsUserDefault = (_zsUserDefaultExport && typeof _zsUserDefaultExport === "object")
  ? _zsUserDefaultExport
  : {};
const _zsUserDefaultThis = (_zsUserDefaultExport && typeof _zsUserDefaultExport === "object")
  ? _zsUserDefaultExport
  : null;

// Build the rpc dict from:
//   1. user.default.rpc (if a plain object — merged first).
//   2. The binding-derived static map (wins on key conflict; bindings
//      are the explicit registration surface).
const _zsRpc = (typeof _zsUserDefault.rpc === "object" && _zsUserDefault.rpc != null)
  ? { ..._zsUserDefault.rpc }
  : {};
Object.assign(_zsRpc, {
${tableEntries.join("\n")}
});

const _zsTopLevelFetch = Reflect.get(_zsUser, "fetch");
const _zsFetch = (typeof _zsUserDefault.fetch === "function")
  ? _zsUserDefault.fetch
  : (typeof _zsTopLevelFetch === "function" ? _zsTopLevelFetch : undefined);

const _zsFetchHandler = createFetchHandler(async () => ({
  fetch: _zsFetch,
  rpc: _zsRpc,
  userDefault: _zsUserDefaultThis,
}));

export default {
  fetch: _zsFetchHandler,
  rpc: _zsRpc,
};
`;
}

// ── Vite plugin ────────────────────────────────────────────────────────────

/**
 * Vite plugin that resolves and loads the synthetic SSR entry.
 *
 * `enforce: "pre"` — runs before user-installed plugins so the virtual id
 * never leaks to the file resolver. The plugin owns this specifier in
 * full: any `virtual:zeroship/_server-entry` import in the graph routes
 * through `load` here.
 *
 * @param opts.userEntryRel  Path the synthetic entry should import from.
 * @param opts.state         TransformState (unused; kept so call sites
 *                           can pass shared state without a refactor).
 * @param opts.getBindings   Optional accessor for a pre-computed server-
 *                           binding map. When it returns a non-empty map,
 *                           the generator emits the Phase-2 static dict.
 */
export function rpcRegistryPlugin(opts: {
  root?: string;
  userEntryRel: string;
  state?: TransformState;
  getBindings?: () => Map<string, ServerBinding> | undefined;
}): Plugin {
  return {
    name: "zeroship:server-entry",
    enforce: "pre",
    resolveId(id: string) {
      if (id === SERVER_ENTRY_VIRTUAL_ID) return SERVER_ENTRY_RESOLVED_ID;
      return null;
    },
    load(id: string) {
      if (id !== SERVER_ENTRY_RESOLVED_ID) return null;
      const bindings = opts.getBindings?.();
      return buildServerEntrySource({
        userEntryRel: opts.userEntryRel,
        bindings,
      });
    },
  };
}
