/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * `applyIr` — the HOST-AUTHORING apply entry: take a pure-JS IR envelope
 * ENVELOPE (`{ ir_version, name, ops }`) as a typed [`ApplyRequest`], run the
 * fail-closed LOAD GATE + LOWER **in Rust** (stamping `owner_app` + folding the
 * authoritative `Checksum::of_ir` — the checksum is NEVER computed in JS), then
 * drive the complete ordered plan over the host driver. The envelope must NOT carry
 * `owner_app`; it is stamped from `req.owner_app` (provenance).
 *
 * This is the entry the `zero-migrate-cli` facade's `apply` calls: the pure-JS
 * recorder produces the envelope, this addon owns the checksum.
 * Resolves to a typed [`ApplyReply`].
 */
export declare function applyIr(hostDriver: (args: [request: JsRequest, done: (err: JsError | null, reply: JsReply | null) => void]) => void, req: ApplyRequest): Promise<ApplyReply>

/**
 * `applyIrSqlite` — deploy an ordered migration-IR sequence through the bundled
 * in-process SQLite backend. There is no host-driver callback: the hardened app
 * and journal connections are opened on the engine worker thread, and the same
 * high-level library deploy loop used by Rust callers owns lowering, idempotent
 * journal skips, apply, and live-schema threading.
 */
export declare function applyIrSqlite(appPath: string, journalPath: string, req: ApplyIrSqliteRequest): Promise<ApplyReply>

/**
 * The typed request for the in-process SQLite `applyIrSqlite` verb.
 *
 * Unlike [`ApplyRequest`], this carries the complete ordered envelope sequence:
 * SQLite opens its bundled-rusqlite backend in the addon and deploys every
 * pending envelope in one engine call, without a host-driver callback.
 */
export interface ApplyIrSqliteRequest {
  /** The deploying app id (`app_…`) stamped onto every lowered migration. */
  ownerApp: string
  /** The logical project/schema name used by lowering and executor confinement. */
  projectSchema: string
  /** The project's `{ table: owner_app }` ownership registry. */
  registry: Record<string, string>
  /** Ordered policy charter documents (TOML), starting with the root bound. */
  charterLayers: Array<string>
  /** Whether destructive changes are pre-approved. */
  approved: boolean
  /** Ordered authored migration IR envelopes as real JavaScript values. */
  envelopes: Array<JsonValue>
}

/** One outstanding online-rename contract returned after apply. */
export interface ApplyPendingContractDto {
  /** Table whose old and new columns currently coexist. */
  table: string
  /** Original column retained until the contract is completed. */
  fromColumn: string
  /** Destination column populated by the online expansion. */
  toColumn: string
  /** Stable key accepted by `resolvePending` and `resolve-pending`. */
  pendingVersion: string
}

/**
 * The typed reply for `applyIr` (the projected [`ApplyOutcome`]).
 *
 * [`ApplyOutcome`]: zero_migrate::apply::executor::ApplyOutcome
 */
export interface ApplyReply {
  /** Versions applied this run, in apply order. */
  applied: Array<string>
  /** Versions already applied (skipped). Informational. */
  skipped: Array<string>
  /** Versions recovered via the non-txn recovery path this run. */
  recovered: Array<string>
  /** Outstanding PostgreSQL online-rename contracts after this operation. */
  pendingContracts: Array<ApplyPendingContractDto>
}

/**
 * The typed request for the host-authoring `applyIr` verb.
 *
 * The `envelope` (`{ ir_version, name, ops }`) crosses as a REAL JS value
 * ([`JsonValue`]) — the recorder builds a JS object, no JSON string round-trip. The
 * envelope MUST NOT carry `owner_app` (it is stamped from `owner_app` here —
 * provenance).
 */
export interface ApplyRequest {
  /**
   * The deploying app id (`app_…`) — stamped as `owner_app` + folded into the
   * authoritative `Checksum::of_ir` in Rust.
   */
  ownerApp: string
  /** The confined project schema the lower pins ops to. */
  projectSchema: string
  /** The migrator role to `SET ROLE` under (least-privilege apply). Optional. */
  migratorRole?: string
  /** `"postgres" | "mysql"` — selects the dialect backend (`SQLite` is in-process). */
  dialect: string
  /**
   * The project's `{ table: owner_app }` ownership registry. Empty on a
   * fresh single-app project.
   */
  registry: Record<string, string>
  /** The pure-JS IR envelope `{ ir_version, name, ops }` as a JS value. */
  envelope: JsonValue
  /**
   * Ordered authored envelopes that precede `envelope` in the project migration
   * set. Apply uses them only to reconstruct declared logical column contracts,
   * and accepts that metadata only after the corresponding plans are proven
   * fully applied in the journal.
   */
  priorEnvelopes?: Array<JsonValue>
  /**
   * The **policy input**: an ordered list of policy charter documents (TOML).
   * The first document is the root bound; each subsequent document narrows it.
   */
  charterLayers: Array<string>
  /** Whether destructive changes are pre-approved. */
  approved: boolean
  /** The audit `applied_by` label recorded in the journal. */
  appliedBy: string
}

/** One plan blocked by an outstanding dependency contract. */
export interface BlockedPlanDto {
  /** Logical id of the blocked plan. */
  blocked: string
  /** Logical id of the dependency plan. */
  dependency: string
  /** Outstanding obligation key on the dependency. */
  pendingVersion: string
}

/** One declared collection (table) — the MANUAL-source `CollectionDescriptor` mirror. */
export interface CollectionDescriptorDto {
  /** The collection (table) name. */
  name: string
  /** The declaring app id (`app_…`). The migrate producer stamps ownership from it. */
  ownerApp: string
  /**
   * The author-declared fields. Columns owned by the active policy are supplied
   * by the producer's explicit policy-resolution pass.
   */
  fields: Array<FieldDescriptorDto>
  /** The declared named indexes. */
  indexes?: Array<IndexDescriptorDto>
  /** Per-collection runtime options (`softDelete`/`versioning`/`strictness`). */
  runtimeOptions?: RuntimeOptionsDto
}

/**
 * One declared field of a collection — the MANUAL-source `FieldDescriptor` mirror.
 *
 * Mirrors the `@zeroship/db` wire `FieldDef` shape the manual evaluator produces.
 * The common facets are typed scalars; the rich sub-object facets (`encrypted`,
 * `mask`, `generated`, `identity`) cross as REAL JS values ([`JsonValue`]) and
 * deserialize into the engine `FieldDescriptor` verbatim.
 */
export interface FieldDescriptorDto {
  /** The field (column) name. */
  name: string
  /**
   * The DSL type token (`string` | `number` | `boolean` | `date` |
   * `calendarDate` | `json` | `ref` | `bytes` | `id` | `vector` | …).
   */
  type: string
  /** `true` ⇒ `NOT NULL`. */
  required?: boolean
  /** `true` ⇒ a unique index over this column. */
  unique?: boolean
  /** For a `ref` field, the referenced collection (FK target table). */
  references?: string
  /** `ref` ON DELETE policy (`cascade`|`restrict`|`setNull`|`setDefault`|`noAction`). */
  onDelete?: string
  /** `ref` ON UPDATE policy. */
  onUpdate?: string
  /** Whether the FK is `DEFERRABLE INITIALLY DEFERRED`. */
  deferrable?: boolean
  /** Column `DEFAULT` value. */
  default?: JsonValue
  /** Numeric `min` bound (lifts a CHECK). */
  min?: number
  /** Numeric `max` bound (lifts a CHECK). */
  max?: number
  /** Enum membership (string or numeric members). */
  enum?: Array<JsonValue>
  /** A legacy internal `<prefix>_<22 base62 UUIDv7>` platform-ID prefix. */
  idPrefix?: string
  /** A `t.vector(dims, …)` dimensionality. */
  vectorDims?: number
  /** A `t.vector(_, { metric })` distance metric (`cosine`|`l2`|`innerProduct`). */
  vectorMetric?: string
  /** `t.string({ caseSensitive: false })` — only `Some(false)` is meaningful. */
  caseSensitive?: boolean
  /** The `t.encrypted({ mode, keyId, wraps })` sub-object (verbatim). */
  encrypted?: JsonValue
  /** The `.mask({ kind, classification })` sub-object (verbatim). */
  mask?: JsonValue
  /** `t.string().fts(language?)` participation flag. */
  fts?: boolean
  /** The FTS tsvector configuration token. */
  ftsLanguage?: string
  /** A generated/computed column facet (structured IR, never raw SQL). */
  generated?: JsonValue
  /** A SQL identity column facet. */
  identity?: JsonValue
}

/**
 * `genArtifacts` — the sync, DB-free schema-artifact emitter. Fold a schema SOURCE
 * (EITHER a set of IR envelopes — the generated source — OR a declared
 * `CollectionDescriptor` set — the manual source) into the two co-emitted
 * artifacts `{ envDbTs, runtimeJson }`. Both sources funnel through the SAME Rust
 * renderer, so their output is byte-identical for equivalent schemas — PROVIDED the
 * same ordered `charterLayers` stack drives both (the confined system-shape injection is
 * policy-driven, not a baked-in engine preset; the caller supplies the confined
 * charter).
 *
 * Runs inline on the napi call thread (no DB, no host driver). Returns a typed
 * [`GenArtifactsReply`]; `ok=false` + `error` on a malformed/incoherent source or a
 * malformed policy charter (never a throw). Exactly one of `envelopes`/`descriptors`
 * must be populated.
 */
export declare function genArtifacts(source: GenArtifactsSource): GenArtifactsReply

/**
 * The typed reply for `genArtifacts`: the two CO-EMITTED artifact strings.
 *
 * napi-neutral (plain string/option fields) so [`crate::api`] builds it on the
 * napi-free test path too. `ok=false` + `error` on a fold/produce failure (never a
 * throw).
 */
export interface GenArtifactsReply {
  /** `true` iff both artifacts rendered cleanly. */
  ok: boolean
  /**
   * The generated `env.db.ts` source: a passive schema map built with the
   * current `zero-migrate` authoring API and checked as `CreateTableArgs`.
   * `None` on failure.
   */
  envDbTs?: string
  /**
   * The `schema.runtime.json` bytes (the v1 `RuntimeSchemaDescriptor`, pretty +
   * trailing newline). `None` on failure.
   */
  runtimeJson?: string
  /** A human-readable error when `ok == false`. */
  error?: string
}

/**
 * The tagged SOURCE for `genArtifacts` — EITHER IR envelopes (the generated
 * source) OR a declared descriptor set (the manual source). A `#[napi(object)]`
 * cannot be a Rust enum with data, so the two arms are optional fields; exactly one
 * must be populated. Both arms funnel through the SAME Rust renderer, so their
 * output is byte-identical for equivalent schemas.
 */
export interface GenArtifactsSource {
  /**
   * The GENERATED source: a set of IR envelopes (`{ ir_version, name, ops }`), in
   * version order. Their `ops` are concatenated and folded. Mutually exclusive
   * with `descriptors`.
   */
  envelopes?: Array<JsonValue>
  /**
   * The MANUAL source: a declared `CollectionDescriptor` set. Turned into
   * `createTable` ops via the producer, then folded through the same tail.
   * Mutually exclusive with `envelopes`.
   */
  descriptors?: Array<CollectionDescriptorDto>
  /**
   * The project schema the fold threads (FK `definition`s embed it). Optional;
   * defaults to `"public"`.
   */
  projectSchema?: string
  /**
   * The **policy input**: ordered charter documents (TOML) that drive the
   * confined system-shape injection. The first document is the root bound and
   * each subsequent document is an untrusted narrowing layer. The composed
   * policy is applied identically on the envelope and descriptor sides.
   */
  charterLayers: Array<string>
}

/**
 * `history` — the generic `ops::status::history` over the host driver.
 * Resolves to a typed [`HistoryReply`].
 */
export declare function history(hostDriver: (args: [request: JsRequest, done: (err: JsError | null, reply: JsReply | null) => void]) => void, req: HistoryRequest): Promise<HistoryReply>

/** One event in the typed `history` audit trail. */
export interface HistoryEventDto {
  /**
   * The shared monotonic sequence number — an `int8` audit key, so it crosses as
   * a JS `bigint` (napi6) to survive a large sequence without float rounding.
   */
  eventSeq: bigint
  /** The migration version (`mig_…`). */
  version: string
  /** The migration name recorded on the event. */
  name: string
  /** `"applied" | "rolled_back"` — the projected `HistoryKind`. */
  kind: string
  /** The event timestamp (RFC-3339 / ISO-8601). */
  at: string
  /** The actor who performed the event. */
  appliedBy: string
  /** The checksum recorded on the event. */
  checksum: string
}

/** The typed reply for `history` (the projected `Vec<HistoryEvent>`). */
export interface HistoryReply {
  /** The audit events, in `event_seq` order. */
  events: Array<HistoryEventDto>
}

/** The typed request for the `history` verb. */
export interface HistoryRequest {
  /** The project id the `ExecutorConfig` carries. */
  projectId: string
  /** The confined project schema. */
  projectSchema: string
  /**
   * Ordered policy charter documents (TOML), starting with the root bound and
   * used by the executor's guard.
   */
  charterLayers: Array<string>
}

/** One declared named index of a collection (the `_indexes` array entry). */
export interface IndexDescriptorDto {
  /** The index name (already collision-stable from the SDK). */
  name: string
  /** The columns the index covers, in order. */
  columns: Array<string>
  /** `true` ⇒ a unique index. */
  unique?: boolean
}

/** The IR-format version this addon was built against (fail-closed floor). */
export declare function irVersion(): number

/**
 * The kind tag of a driver-neutral scalar cell — mirrors the engine `Value`'s
 * variants.
 *
 * A `#[napi(object)]` cannot be a Rust enum with data, so a cell crosses as a
 * tagged struct: `kind` selects the arm, and the matching payload field carries
 * the value (all others `None`/default). This keeps the union explicit on both
 * sides without a fragile positional encoding.
 */
export interface JsCell {
  /** `"null" | "text" | "int" | "bool" | "textArray"`. */
  kind: string
  /** Payload for `kind == "text"`. */
  text?: string
  /** Payload for `kind == "int"` when the value fits a JS `number` safely. */
  int?: number
  /**
   * Payload for `kind == "int"` carried as a decimal string (int8/numeric that a
   * `pg` type-parser stringified). Preferred over `int` when present.
   */
  intStr?: string
  /** Payload for `kind == "bool"`. */
  bool?: boolean
  /** Payload for `kind == "textArray"`; a JS `null` element is `None`. */
  textArray?: Array<string | undefined | null>
}

/** A driver-neutral error crossing the boundary: message + optional SQLSTATE. */
export interface JsError {
  /** Human-readable message (`err.message` from node-pg). */
  message: string
  /** SQLSTATE if the driver surfaced one (`err.code` from node-pg). */
  code?: string
}

/**
 * A successful verb reply crossing the boundary: the returned rows (empty for a
 * pure DML `execute`/`executeTextParams`) plus the driver's affected-/returned-row
 * count (`result.rowCount` from node-pg). The engine's `execute` verbs read the
 * count; `query`/`queryOne` read the rows.
 */
export interface JsReply {
  /** Rows for `query`/`queryOne` (empty for pure DML). */
  rows: Array<JsRow>
  /**
   * `result.rowCount` — affected/returned rows. An honest [`i64`] (a JS `number`);
   * `None` when the driver reports no count (e.g. `batch`). A count is an integer,
   * not a float.
   */
  rowCount?: number
}

/**
 * A single verb request the engine hands to the host driver.
 *
 * `kind` selects the verb (`batch | execute | executeTextParams | query |
 * queryOne`); `sql` is the statement; `binds` carries the neutral params for
 * `execute`/`query`/`queryOne`; `textParams` carries the `&[Option<String>]`
 * text-format params for `executeTextParams` (text-format, server-inferred
 * OID). Exactly one of `binds`/`textParams` is populated per verb kind.
 */
export interface JsRequest {
  /** The verb: `"batch" | "execute" | "executeTextParams" | "query" | "queryOne"`. */
  kind: string
  /** The SQL statement. */
  sql: string
  /** Neutral binds for `execute`/`query`/`queryOne` (as [`JsCell`]s). */
  binds: Array<JsCell>
  /** Text-format params for `executeTextParams` (`None` element → SQL NULL bind). */
  textParams: Array<string | undefined | null>
}

/** A driver-neutral row crossing the boundary: parallel column-name / cell vectors. */
export interface JsRow {
  /** Column names, positionally aligned with `cells`. */
  columns: Array<string>
  /** One [`JsCell`] per column. */
  cells: Array<JsCell>
}

/**
 * Load + verify an IR document (the sync, DB-free deploy gate). Returns a
 * typed [`LoadVerifyReply`]; never throws for a malformed document.
 */
export declare function loadVerify(envelopeJson: string, deployingApp: string, dialect: string, registry: Record<string, string>, projectSchema: string): LoadVerifyReply

/**
 * The typed reply for the sync, DB-free `loadVerify` gate. Never throws for a
 * malformed document; `ok=false` + a message.
 *
 * napi-neutral (plain scalar fields) so [`crate::api`] builds it on the napi-free
 * test path too.
 */
export interface LoadVerifyReply {
  /** `true` iff the IR document loaded + validated cleanly. */
  ok: boolean
  /** The document's `ir_version` (when it deserialized far enough to read it). */
  irVersion?: number
  /** The number of `op.*` operations in the document (when loaded). */
  opCount?: number
  /** A human-readable error when `ok == false` (the first fail-closed rejection). */
  error?: string
}

/** One outstanding online-contract obligation in a status reply. */
export interface PendingContractStatusDto {
  /** Table whose deferred contract remains outstanding. */
  table: string
  /** Stable obligation key used by operator resolution. */
  pendingVersion: string
  /** Whether the supplying plan is absent from the current manifest set. */
  orphaned: boolean
}

/** One plan in a plan-aware status reply. */
export interface PlanStatusDto {
  /** Stable logical plan id. */
  version: string
  /** Authored migration name. */
  name: string
  /** `applied | pending | partial | drifted | blocked | unknownDependency`. */
  state: string
  /** Ordered journal-visible steps. */
  steps: Array<PlanStatusStepDto>
  /** Dependencies omitted from the supplied plan set. */
  missingDependencies: Array<string>
}

/** One executable step in a plan-aware status reply. */
export interface PlanStatusStepDto {
  /** Stable step journal id. */
  version: string
  /** Human-readable operation label. */
  name: string
  /**
   * `ddl | dml | backfill | synchronizeIdentity | onlineExpand |
   * onlineContract | sqliteRebuild`.
   */
  kind: string
  /** `pending | inflight | applied | drifted`. */
  state: string
  /** `guardUpdates | externalInvariant` for resumable backfills. */
  cursorStabilityMode?: string
  /** The explicitly approved invariant name for `externalInvariant`. */
  cursorStabilityInvariant?: string
  /** Named assertion that identity-allocating writes are quiesced. */
  writesQuiesced?: string
}

/** Complete or abort one outstanding PostgreSQL online column rename. */
export declare function resolvePending(hostDriver: (args: [request: JsRequest, done: (err: JsError | null, reply: JsReply | null) => void]) => void, req: ResolvePendingRequest): Promise<ApplyReply>

/**
 * The typed request for completing or aborting one outstanding PostgreSQL
 * online-rename contract.
 */
export interface ResolvePendingRequest {
  /**
   * The app id that authored the original rename. It is required to reproduce
   * the engine-stamped contract identities exactly.
   */
  ownerApp: string
  /** The confined project schema containing the renamed table. */
  projectSchema: string
  /** The migrator role used for the approval-gated cleanup DDL. Optional. */
  migratorRole?: string
  /** The pending-contract key returned by apply or status. */
  pendingVersion: string
  /** `"apply"` keeps the new column; `"abort"` keeps the old column. */
  action: string
  /** Explicit approval for the destructive column drop. */
  approved: boolean
  /** Audit label recorded with the cleanup and resolution. */
  appliedBy: string
  /**
   * Ordered policy charter documents (TOML), starting with the root bound and
   * used by the executor's guard.
   */
  charterLayers: Array<string>
}

/** Per-collection runtime options that do not round-trip through catalog state. */
export interface RuntimeOptionsDto {
  /** `schema(...).softDelete()`. */
  softDelete?: boolean
  /** `schema(...).withVersioning()`. */
  versioning?: boolean
  /**
   * `schema(...).strictness(...)` — `"strict"` | `"lenient"` | `"off"`. Default
   * (absent) is `"strict"`.
   */
  strictness?: string
}

/**
 * `status` — the generic `ops::status::status` over the host driver.
 * Migrations cross as a typed `Vec<JsonValue>` (each a `Migration`). Resolves to a
 * typed [`StatusReply`].
 */
export declare function status(hostDriver: (args: [request: JsRequest, done: (err: JsError | null, reply: JsReply | null) => void]) => void, req: StatusRequest): Promise<StatusReply>

/**
 * `statusIr`: lower the supplied pure-JS envelopes through the same guarded
 * Rust path as [`apply_ir`], retain every executable plan step, and reconcile
 * their stable journal identities through the selected dialect backend.
 *
 * This is the status entrypoint for mixed and data-only plans. The legacy
 * [`status`] verb remains available for callers that already hold a flat set of
 * pre-lowered `Migration` values.
 */
export declare function statusIr(hostDriver: (args: [request: JsRequest, done: (err: JsError | null, reply: JsReply | null) => void]) => void, req: StatusIrRequest): Promise<StatusReply>

/**
 * The typed request for the plan-aware `statusIr` verb.
 *
 * Each envelope is lowered through the same guarded Rust path as `applyIr`; the
 * resulting full plan retains DML and backfill identities instead of projecting
 * them to a lossy `Vec<Migration>`.
 */
export interface StatusIrRequest {
  /** The deploying app id stamped during guarded lowering. */
  ownerApp: string
  /** The confined project schema. */
  projectSchema: string
  /** `"postgres" | "mysql"` selects the journal backend. */
  dialect: string
  /** The project's table-ownership registry. */
  registry: Record<string, string>
  /** Ordered authored migration envelopes to reconcile. */
  envelopes: Array<JsonValue>
  /** Required ordered policy charters, identical to the `applyIr` lowering input. */
  charterLayers: Array<string>
}

/** The typed reply for `status` (the projected `MigrationStatus`). */
export interface StatusReply {
  /** The highest net-applied version (`mig_…`), or `None` when nothing is applied. */
  currentVersion?: string
  /** Net-applied versions, in version order. */
  applied: Array<string>
  /** Supplied versions that are NOT net-applied, in apply order. */
  pending: Array<string>
  /** Supplied logical plans whose online rename was explicitly aborted. */
  aborted: Array<string>
  /** Versions whose latest event is a rollback, in version order. */
  rolledBack: Array<string>
  /** Outstanding online-contract obligations, including orphan diagnosis. */
  pendingContracts: Array<PendingContractStatusDto>
  /** Plans blocked by an outstanding dependency contract. */
  blocked: Array<BlockedPlanDto>
  /** Completed or inflight journal identities absent from supplied plans. */
  unexpectedJournal: Array<UnexpectedJournalEntryDto>
  /**
   * Plan-aware detail. Absent on the legacy migration-only `status` verb;
   * present (including as an empty array) on `statusIr`.
   */
  plans?: Array<PlanStatusDto>
}

/** The typed request for the `status` verb. */
export interface StatusRequest {
  /** The project id the `ExecutorConfig` carries. */
  projectId: string
  /** The confined project schema. */
  projectSchema: string
  /** `"postgres" | "mysql"` selects the matching journal backend. */
  dialect: string
  /**
   * The pre-lowered migrations to reconcile against the journal, each a
   * `Migration` as a JS value (empty array for the read/empty-journal flow).
   */
  migrations: Array<JsonValue>
  /**
   * Ordered policy charter documents (TOML), starting with the root bound and
   * used by the executor's guard.
   */
  charterLayers: Array<string>
}

/** One journal identity absent from every supplied plan manifest. */
export interface UnexpectedJournalEntryDto {
  /** Unexpected step identity. */
  version: string
  /** `applied` or `inflight`. */
  state: string
  /** Journal checksum retained for diagnosis. */
  journalChecksum: string
  /** Journaled kind when the entry is completed; absent for inflight markers. */
  journalKind?: string
}
