import { table } from "@zeroship/migrate";
import { createFunction, raw } from "@zeroship/migrate/pg";

export const name = "functions_triggers_comments";

export function up() {
  createFunction({ schema: "zeroship", name: "app_audit_block_tamper", returns: "trigger", language: "plpgsql", body: " BEGIN\n\n\n\n\n\n\n     IF TG_OP = 'DELETE'\n        AND current_setting('zeroship.audit_retention', true) = 'on' THEN\n         RETURN OLD;\n     END IF;\n     RAISE EXCEPTION 'app_audit is append-only'\n         USING ERRCODE = 'insufficient_privilege';\n END" });
  createFunction({ schema: "zeroship", name: "app_oauth_clients_reject_sector_change", returns: "trigger", language: "plpgsql", body: "BEGIN\n  IF NEW.sector_identifier IS DISTINCT FROM OLD.sector_identifier THEN\n    RAISE EXCEPTION 'app_oauth_clients.sector_identifier is immutable after insert'\n      USING ERRCODE = 'check_violation';\n  END IF;\n  RETURN NEW;\nEND;" });
  createFunction({ schema: "zeroship", name: "audit_events_block_tamper", returns: "trigger", language: "plpgsql", body: " BEGIN\n\n\n\n\n\n\n     IF TG_OP = 'DELETE'\n        AND current_setting('zeroship.audit_retention', true) = 'on' THEN\n         RETURN OLD;\n     END IF;\n     RAISE EXCEPTION 'zeroship.audit_events is append-only'\n         USING ERRCODE = 'insufficient_privilege';\n END" });
  createFunction({ schema: "zeroship", name: "authz_decisions_block_tamper", returns: "trigger", language: "plpgsql", body: " BEGIN\n\n\n\n\n\n\n     IF TG_OP = 'DELETE'\n        AND current_setting('zeroship.audit_retention', true) = 'on' THEN\n         RETURN OLD;\n     END IF;\n     RAISE EXCEPTION 'zeroship.authz_decisions is append-only'\n         USING ERRCODE = 'insufficient_privilege';\n END" });
  createFunction({ schema: "zeroship", name: "billing_disputes_controlled_update", returns: "trigger", language: "plpgsql", body: "BEGIN\n    IF TG_OP = 'DELETE' THEN\n        RAISE EXCEPTION 'billing_disputes is append-only (no DELETE) — a dispute is a permanent fact';\n    END IF;\n\n    IF NEW.id <> OLD.id\n       OR NEW.invoice_id <> OLD.invoice_id\n       OR NEW.amount_cents <> OLD.amount_cents\n       OR NEW.currency <> OLD.currency\n       OR NEW.provider_dispute_id <> OLD.provider_dispute_id\n       OR NEW.created_at <> OLD.created_at THEN\n        RAISE EXCEPTION 'billing_disputes frozen columns are immutable (invoice_id/amount_cents/currency/provider_dispute_id) — only status/resolved_at/reason/evidence_due_at may progress';\n    END IF;\n\n\n\n\n\n\n\n\n\n    IF NEW.status <> OLD.status THEN\n        IF NOT (OLD.status = 'open' AND NEW.status IN ('won','lost')) THEN\n            RAISE EXCEPTION 'billing_disputes status may only progress open→won/lost (got %→%) — a terminal dispute is frozen',\n                OLD.status, NEW.status;\n        END IF;\n    END IF;\n    RETURN NEW;\nEND;" });
  createFunction({ schema: "zeroship", name: "billing_reconciliation_findings_controlled_update", returns: "trigger", language: "plpgsql", body: "BEGIN\n    IF TG_OP = 'DELETE' THEN\n        RAISE EXCEPTION 'billing_reconciliation_findings is append-only (no DELETE) — a finding is a permanent audit fact';\n    END IF;\n    IF NEW.id <> OLD.id\n       OR NEW.kind <> OLD.kind\n       OR NEW.entity_id <> OLD.entity_id\n       OR NEW.dedup_key <> OLD.dedup_key\n       OR NEW.detected_at <> OLD.detected_at\n       OR NEW.our_value IS DISTINCT FROM OLD.our_value\n       OR NEW.stripe_value IS DISTINCT FROM OLD.stripe_value THEN\n        RAISE EXCEPTION 'billing_reconciliation_findings frozen columns are immutable — only resolved_at/severity may change';\n    END IF;\n\n    IF OLD.resolved_at IS NOT NULL AND NEW.resolved_at IS DISTINCT FROM OLD.resolved_at THEN\n        RAISE EXCEPTION 'billing_reconciliation_findings.resolved_at is set-once (a resolved finding stays resolved)';\n    END IF;\n    RETURN NEW;\nEND;" });
  createFunction({ schema: "zeroship", name: "connect_checkout_failures_immutable", returns: "trigger", language: "plpgsql", body: "BEGIN\n    RAISE EXCEPTION 'connect_checkout_failures is append-only (no UPDATE/DELETE)';\nEND;" });
  createFunction({ schema: "zeroship", name: "credit_ledger_immutable", returns: "trigger", language: "plpgsql", body: "BEGIN\n    RAISE EXCEPTION 'credit_ledger is append-only (no UPDATE/DELETE) — correct via a new offsetting entry';\nEND;" });
  createFunction({ schema: "zeroship", name: "invoice_lines_immutable", returns: "trigger", language: "plpgsql", body: "DECLARE parent_status zeroship.invoice_status;\nBEGIN\n    SELECT status INTO parent_status FROM zeroship.invoices\n        WHERE id = COALESCE(OLD.invoice_id, NEW.invoice_id);\n    IF parent_status = 'finalized' THEN\n        RAISE EXCEPTION 'invoice_line for invoice % is frozen — parent invoice is finalized',\n            COALESCE(OLD.invoice_id, NEW.invoice_id);\n    END IF;\n    RETURN COALESCE(NEW, OLD);\nEND;" });
  createFunction({ schema: "zeroship", name: "invoice_payments_immutable", returns: "trigger", language: "plpgsql", body: "BEGIN\n    RAISE EXCEPTION 'invoice_payments is append-only (no UPDATE/DELETE) — correct via a new offsetting row';\nEND;" });
  createFunction({ schema: "zeroship", name: "invoices_immutable", returns: "trigger", language: "plpgsql", body: "BEGIN\n    IF TG_OP = 'DELETE' THEN\n        RAISE EXCEPTION 'invoices are append-only (no DELETE)';\n    END IF;\n    IF OLD.status = 'finalized' THEN\n        IF NEW.status = 'void'\n           AND NEW.id = OLD.id AND NEW.creator_id = OLD.creator_id\n           AND NEW.period = OLD.period\n           AND NEW.subtotal_cents = OLD.subtotal_cents\n           AND NEW.credit_cents = OLD.credit_cents\n           AND NEW.tax_cents = OLD.tax_cents\n           AND NEW.total_cents = OLD.total_cents THEN\n            RETURN NEW;\n        END IF;\n        RAISE EXCEPTION 'invoice % is finalized — only the void transition is permitted', OLD.id;\n    END IF;\n    RETURN NEW;\nEND;" });
  createFunction({ schema: "zeroship", name: "payout_failures_immutable", returns: "trigger", language: "plpgsql", body: "BEGIN\n    RAISE EXCEPTION 'payout_failures is append-only (no UPDATE/DELETE)';\nEND;" });
  createFunction({ schema: "zeroship", name: "plan_change_events_immutable", returns: "trigger", language: "plpgsql", body: "BEGIN\n    RAISE EXCEPTION 'plan_change_events is append-only (no UPDATE/DELETE) — the proration timeline is frozen';\nEND;" });
  createFunction({ schema: "zeroship", name: "refunds_immutable", returns: "trigger", language: "plpgsql", body: "BEGIN\n    IF TG_OP = 'DELETE' THEN\n        RAISE EXCEPTION 'refunds are append-only (no DELETE) — correct via a true-up / re-charge';\n    END IF;\n\n    IF NEW.id <> OLD.id\n       OR NEW.invoice_id <> OLD.invoice_id\n       OR NEW.amount_cents <> OLD.amount_cents\n       OR NEW.subtotal_cents <> OLD.subtotal_cents\n       OR NEW.tax_cents <> OLD.tax_cents\n       OR NEW.currency <> OLD.currency\n       OR NEW.destination <> OLD.destination\n       OR NEW.idempotency_key <> OLD.idempotency_key\n       OR NEW.request_fingerprint <> OLD.request_fingerprint THEN\n        RAISE EXCEPTION 'refund % money/identity columns are frozen — only the status lifecycle may progress', OLD.id;\n    END IF;\n\n\n\n    IF NEW.status <> OLD.status THEN\n        IF NOT (\n               (OLD.status = 'pending' AND NEW.status IN ('issued','failed','canceled'))\n            OR (OLD.status = 'issued'  AND NEW.status IN ('failed','canceled'))\n        ) THEN\n            RAISE EXCEPTION 'refund % status may only progress pending→issued/failed/canceled or issued→failed/canceled (got %→%)',\n                OLD.id, OLD.status, NEW.status;\n        END IF;\n    END IF;\n    RETURN NEW;\nEND;" });
  createFunction({ schema: "zeroship", name: "refunds_no_over_refund", returns: "trigger", language: "plpgsql", body: "DECLARE cash BIGINT; sum_cash BIGINT; sum_credit BIGINT;\nBEGIN\n\n    IF NEW.status IN ('failed','canceled') THEN\n        RETURN NEW;\n    END IF;\n    SELECT COALESCE(SUM(amount_cents), 0) INTO cash\n      FROM zeroship.invoice_payments WHERE invoice_id = NEW.invoice_id;\n\n    SELECT COALESCE(SUM(amount_cents) FILTER (WHERE destination = 'cash'),   0),\n           COALESCE(SUM(amount_cents) FILTER (WHERE destination = 'credit'), 0)\n      INTO sum_cash, sum_credit\n      FROM zeroship.refunds\n      WHERE invoice_id = NEW.invoice_id AND id <> NEW.id\n        AND status NOT IN ('failed','canceled');\n    IF NEW.destination = 'cash'   THEN sum_cash   := sum_cash   + NEW.amount_cents; END IF;\n    IF NEW.destination = 'credit' THEN sum_credit := sum_credit + NEW.amount_cents; END IF;\n    IF sum_cash > cash THEN\n        RAISE EXCEPTION 'refund % over-refunds CASH on invoice % (cash refunds % > Σ(invoice_payments) %)',\n            NEW.id, NEW.invoice_id, sum_cash, cash;\n    END IF;\n    IF sum_credit > cash THEN\n        RAISE EXCEPTION 'refund % over-refunds CREDIT-DEST on invoice % (credit refunds % > Σ(invoice_payments) %)',\n            NEW.id, NEW.invoice_id, sum_credit, cash;\n    END IF;\n    IF sum_cash + sum_credit > cash THEN\n        RAISE EXCEPTION 'refund % over-refunds COMBINED on invoice % (% > Σ(invoice_payments) %)',\n            NEW.id, NEW.invoice_id, sum_cash + sum_credit, cash;\n    END IF;\n    RETURN NEW;\nEND;" });
  createFunction({ schema: "zeroship", name: "reject_migrated_migration_audit_mutation", returns: "trigger", language: "plpgsql", body: "BEGIN\n    RAISE EXCEPTION 'migrated_migration_audit is append-only';\nEND;" });
  table("app_audit", { schema: "zeroship" }).createTrigger({ name: "app_audit_block_delete", timing: "before", events: ["delete"], forEach: "row", execute: "app_audit_block_tamper" });
  table("app_audit", { schema: "zeroship" }).createTrigger({ name: "app_audit_block_truncate", timing: "before", events: ["truncate"], forEach: "statement", execute: "app_audit_block_tamper" });
  table("app_audit", { schema: "zeroship" }).createTrigger({ name: "app_audit_block_update", timing: "before", events: ["update"], forEach: "row", execute: "app_audit_block_tamper" });
  // TODO(dsl-v2): createTrigger needs UPDATE OF column-list support
  raw({ sql: "CREATE TRIGGER app_oauth_clients_sector_identifier_immutable BEFORE UPDATE OF sector_identifier ON zeroship.app_oauth_clients FOR EACH ROW EXECUTE FUNCTION zeroship.app_oauth_clients_reject_sector_change()", reason: "this trigger fires on UPDATE OF sector_identifier, which the current trigger DSL cannot express" });
  table("audit_events", { schema: "zeroship" }).createTrigger({ name: "audit_events_block_delete", timing: "before", events: ["delete"], forEach: "row", execute: "audit_events_block_tamper" });
  table("audit_events", { schema: "zeroship" }).createTrigger({ name: "audit_events_block_truncate", timing: "before", events: ["truncate"], forEach: "statement", execute: "audit_events_block_tamper" });
  table("audit_events", { schema: "zeroship" }).createTrigger({ name: "audit_events_block_update", timing: "before", events: ["update"], forEach: "row", execute: "audit_events_block_tamper" });
  table("authz_decisions", { schema: "zeroship" }).createTrigger({ name: "authz_decisions_block_delete", timing: "before", events: ["delete"], forEach: "row", execute: "authz_decisions_block_tamper" });
  table("authz_decisions", { schema: "zeroship" }).createTrigger({ name: "authz_decisions_block_truncate", timing: "before", events: ["truncate"], forEach: "statement", execute: "authz_decisions_block_tamper" });
  table("authz_decisions", { schema: "zeroship" }).createTrigger({ name: "authz_decisions_block_update", timing: "before", events: ["update"], forEach: "row", execute: "authz_decisions_block_tamper" });
  table("billing_disputes", { schema: "zeroship" }).createTrigger({ name: "billing_disputes_controlled_update_trg", timing: "before", events: ["delete", "update"], forEach: "row", execute: "billing_disputes_controlled_update" });
  table("billing_reconciliation_findings", { schema: "zeroship" }).createTrigger({ name: "billing_reconciliation_findings_controlled_update_trg", timing: "before", events: ["delete", "update"], forEach: "row", execute: "billing_reconciliation_findings_controlled_update" });
  table("connect_checkout_failures", { schema: "zeroship" }).createTrigger({ name: "connect_checkout_failures_immutable_trg", timing: "before", events: ["delete", "update"], forEach: "row", execute: "connect_checkout_failures_immutable" });
  table("credit_ledger", { schema: "zeroship" }).createTrigger({ name: "credit_ledger_immutable_trg", timing: "before", events: ["delete", "update"], forEach: "row", execute: "credit_ledger_immutable" });
  table("invoice_lines", { schema: "zeroship" }).createTrigger({ name: "invoice_lines_immutable_trg", timing: "before", events: ["insert", "delete", "update"], forEach: "row", execute: "invoice_lines_immutable" });
  table("invoice_payments", { schema: "zeroship" }).createTrigger({ name: "invoice_payments_immutable_trg", timing: "before", events: ["delete", "update"], forEach: "row", execute: "invoice_payments_immutable" });
  table("invoices", { schema: "zeroship" }).createTrigger({ name: "invoices_immutable_trg", timing: "before", events: ["delete", "update"], forEach: "row", execute: "invoices_immutable" });
  table("migrated_migration_audit", { schema: "zeroship" }).createTrigger({ name: "migrated_migration_audit_append_only", timing: "before", events: ["delete", "update"], forEach: "row", execute: "reject_migrated_migration_audit_mutation" });
  table("payout_failures", { schema: "zeroship" }).createTrigger({ name: "payout_failures_immutable_trg", timing: "before", events: ["delete", "update"], forEach: "row", execute: "payout_failures_immutable" });
  table("plan_change_events", { schema: "zeroship" }).createTrigger({ name: "plan_change_events_immutable_trg", timing: "before", events: ["delete", "update"], forEach: "row", execute: "plan_change_events_immutable" });
  table("refunds", { schema: "zeroship" }).createTrigger({ name: "refunds_immutable_trg", timing: "before", events: ["delete", "update"], forEach: "row", execute: "refunds_immutable" });
  table("refunds", { schema: "zeroship" }).createTrigger({ name: "refunds_no_over_refund_trg", timing: "before", events: ["insert"], forEach: "row", execute: "refunds_no_over_refund" });
  table("app_oauth_clients", { schema: "zeroship" }).column("sector_identifier").comment("Immutable after insert: refresh-token revocation markers persist the derived pairwise subject, so changing the sector would de-align stored family-kill markers from live access-token subjects.");
  table("migrated_app_policies", { schema: "zeroship" }).comment("Creator migration policy versions. App isolation is enforced in the migrated service by authorization plus app_id-scoped queries; no table RLS is installed because the service role can hold BYPASSRLS.");
  table("migrated_migration_audit", { schema: "zeroship" }).comment("Append-only audit history for creator migration submit, approval, pending rejection, and apply outcomes.");
  table("migrated_migrations", { schema: "zeroship" }).comment("Creator migration workflow rows. App isolation is enforced by migrated service authorization plus app_id-scoped primary-key lookups.");
  table("oauth_refresh_tokens", { schema: "zeroship" }).column("sub").comment("Pairwise subject snapshot persisted for refresh-family kill markers. app_oauth_clients.sector_identifier is immutable after insert so this snapshot cannot diverge from newly minted access-token subjects.");
}

export function down() {

}
