import { table } from "@zeroship/migrate";

export const name = "constraints_indexes_fks";

export function up() {
  table("app_oauth_clients", { schema: "zeroship" }).unique("app_oauth_clients_client_id_key").add({ columns: ["client_id"] });
  table("app_usage_history", { schema: "zeroship" }).unique("app_usage_history_app_id_period_key").add({ columns: ["app_id", "period"] });
  table("apps", { schema: "zeroship" }).unique("apps_name_key").add({ columns: ["name"] });
  table("billing_customer_refs", { schema: "zeroship" }).unique("billing_customer_refs_external_id_key").add({ columns: ["external_id"] });
  table("billing_disputes", { schema: "zeroship" }).unique("billing_disputes_provider_dispute_id_key").add({ columns: ["provider_dispute_id"] });
  table("billing_line_provider_refs", { schema: "zeroship" }).unique("billing_line_provider_refs_provider_ref_kind_external_id_key").add({ columns: ["provider", "ref_kind", "external_id"] });
  table("billing_provider_refs", { schema: "zeroship" }).unique("billing_provider_refs_provider_ref_kind_external_id_key").add({ columns: ["provider", "ref_kind", "external_id"] });
  table("billing_reconciliation_findings", { schema: "zeroship" }).unique("billing_reconciliation_findings_dedup_key_key").add({ columns: ["dedup_key"] });
  table("connect_checkout_failures", { schema: "zeroship" }).unique("connect_checkout_failures_provider_payment_intent_id_key").add({ columns: ["provider_payment_intent_id"] });
  table("device_grants", { schema: "zeroship" }).unique("device_grants_user_code_key").add({ columns: ["user_code"] });
  table("federated_identities", { schema: "zeroship" }).unique("federated_identities_provider_subject_key").add({ columns: ["provider", "subject"] });
  table("payout_failures", { schema: "zeroship" }).unique("payout_failures_provider_payout_id_key").add({ columns: ["provider_payout_id"] });
  table("payouts", { schema: "zeroship" }).unique("payouts_event_id_key").add({ columns: ["event_id"] });
  table("provider_dead_letter", { schema: "zeroship" }).unique("provider_dead_letter_provider_event_key").add({ columns: ["provider_id", "event_id"] });
  table("refund_provider_refs", { schema: "zeroship" }).unique("refund_provider_refs_provider_ref_kind_external_id_key").add({ columns: ["provider", "ref_kind", "external_id"] });
  table("refunds", { schema: "zeroship" }).unique("refunds_idempotency_key_key").add({ columns: ["idempotency_key"] });
  table("users", { schema: "zeroship" }).unique("users_email_key").add({ columns: ["email"] });
  table("app_members", { schema: "zeroship" }).index("app_members_user_idx").add({ on: ["user_id"] });
  table("app_net_grants", { schema: "zeroship" }).index("app_net_grants_app_id_idx").add({ on: ["app_id"] });
  table("app_session_anchors", { schema: "zeroship" }).index("app_session_anchors_user_idx").add({ on: ["app_id", "global_user_id"], where: (col) => col("revoked_at").isNull() });
  table("app_user_identities", { schema: "zeroship" }).index("app_user_identities_pairwise_sub_idx").add({ on: ["pairwise_sub"] });
  table("app_user_identities", { schema: "zeroship" }).index("app_user_identities_relay_active_idx").add({ on: ["relay_email"], unique: true, where: (col) => col("relay_email").isNotNull().and(col("revoked_at").isNull()) });
  table("apps", { schema: "zeroship" }).index("apps_plan_id_idx").add({ on: ["plan_id"] });
  table("audit_events", { schema: "zeroship" }).index("auth_audit_event_idx").add({ on: ["event_type", "occurred_at"] });
  table("audit_events", { schema: "zeroship" }).index("auth_audit_user_idx").add({ on: ["actor_user_id", "occurred_at"] });
  table("dpop_jti", { schema: "zeroship" }).index("auth_dpop_jti_inserted_idx").add({ on: ["inserted_at"] });
  table("gateway_sessions", { schema: "zeroship" }).index("auth_gateway_sessions_app_idx").add({ on: ["app_id", "user_id"] });
  table("gateway_sessions", { schema: "zeroship" }).index("auth_gateway_sessions_app_sid_idx").add({ on: ["app_id", "sid"], where: (col) => col("sid").isNotNull().and(col("revoked_at").isNull()) });
  table("gateway_sessions", { schema: "zeroship" }).index("auth_gateway_sessions_idle_idx").add({ on: ["idle_expires_at"], where: (col) => col("revoked_at").isNull() });
  table("magic_completions", { schema: "zeroship" }).index("auth_magic_completions_expires_idx").add({ on: ["expires_at"], where: (col) => col("consumed_at").isNull() });
  table("magic_links", { schema: "zeroship" }).index("auth_magic_email_idx").add({ on: ["email"] });
  table("magic_links", { schema: "zeroship" }).index("auth_magic_user_id_idx").add({ on: ["user_id"] });
  table("rate_limits", { schema: "zeroship" }).index("auth_rate_limits_updated_at_idx").add({ on: ["updated_at"] });
  table("token_revocations", { schema: "zeroship" }).index("auth_token_revocations_revoked_after_idx").add({ on: ["revoked_after"] });
  table("totp_backup_codes", { schema: "zeroship" }).index("auth_totp_backup_codes_user_idx").add({ on: ["user_id"] });
  table("users", { schema: "zeroship" }).index("auth_users_deletion_due_idx").add({ on: ["deletion_scheduled_for"], where: (col) => col("deletion_scheduled_for").isNotNull().and(col("anonymized_at").isNull()) });
  table("authz_decisions", { schema: "zeroship" }).index("authz_decisions_occurred_idx").add({ on: [{ column: "occurred_at", order: "desc" }] });
  table("authz_decisions", { schema: "zeroship" }).index("authz_decisions_user_idx").add({ on: ["actor_user_id"], where: (col) => col("actor_user_id").isNotNull() });
  table("billing_disputes", { schema: "zeroship" }).index("billing_disputes_invoice_idx").add({ on: ["invoice_id"] });
  table("billing_metrics", { schema: "zeroship" }).index("billing_metrics_owner_app_idx").add({ on: ["owner_app"], where: (col) => col("owner_app").isNotNull() });
  table("billing_reconciliation_findings", { schema: "zeroship" }).index("billing_reconciliation_findings_kind_idx").add({ on: ["kind", "detected_at"] });
  table("billing_reconciliation_findings", { schema: "zeroship" }).index("billing_reconciliation_findings_open_idx").add({ on: ["detected_at"], where: (col) => col("resolved_at").isNull() });
  table("connect_checkout_failures", { schema: "zeroship" }).index("connect_checkout_failures_creator_idx").add({ on: ["creator_id", { column: "created_at", order: "desc" }] });
  table("credit_ledger", { schema: "zeroship" }).index("credit_ledger_creator_created_idx").add({ on: ["creator_id", "created_at"] });
  table("credit_ledger", { schema: "zeroship" }).index("credit_ledger_idempotency_key_idx").add({ on: ["idempotency_key"], unique: true, where: (col) => col("idempotency_key").isNotNull() });
  table("credit_ledger", { schema: "zeroship" }).index("credit_ledger_refund_clawback_note_idx").add({ on: ["note"], unique: true, where: (col) => col("kind").cast({ to: "text" }).eq("refund_clawback") });
  table("credit_ledger", { schema: "zeroship" }).index("credit_ledger_refund_to_credit_note_idx").add({ on: ["note"], unique: true, where: (col) => col("kind").cast({ to: "text" }).eq("refund_to_credit") });
  table("device_grants", { schema: "zeroship" }).index("device_grants_client_id_idx").add({ on: ["client_id"], where: (col) => col("client_id").isNotNull() });
  table("device_grants", { schema: "zeroship" }).index("device_grants_expires_at_idx").add({ on: ["expires_at"] });
  table("device_grants", { schema: "zeroship" }).index("device_grants_provider_pending_user_code_idx").add({ on: ["provider", "user_code"], where: (col) => col("status").eq("pending") });
  table("identity_links", { schema: "zeroship" }).index("identity_links_principal_id_idx").add({ on: ["principal_id"] });
  table("app_audit", { schema: "zeroship" }).index("idx_app_audit_app_at").add({ on: ["app_id", { column: "occurred_at", order: "desc" }] });
  table("app_audit", { schema: "zeroship" }).index("idx_app_audit_creator_at").add({ on: ["creator_id", { column: "occurred_at", order: "desc" }] });
  table("billing_notifications", { schema: "zeroship" }).index("idx_billing_notifications_pending").add({ on: ["claimed_at"], where: (col) => col("status").cast({ to: "text" }).eq("pending") });
  table("creator_account_history", { schema: "zeroship" }).index("idx_creator_account_history_creator").add({ on: ["creator_id", { column: "linked_at", order: "desc" }] });
  table("creator_account_history", { schema: "zeroship" }).index("idx_creator_account_history_one_open").add({ on: ["creator_id"], unique: true, where: (col) => col("unlinked_at").isNull() });
  table("creator_billing_status_history", { schema: "zeroship" }).index("idx_creator_billing_status_history_creator_at").add({ on: ["creator_id", { column: "at", order: "desc" }] });
  table("creator_billing_status", { schema: "zeroship" }).index("idx_creator_billing_status_past_due").add({ on: ["past_due_since"], where: (col) => col("state").cast({ to: "text" }).eq("past_due") });
  table("deleted_sandboxes", { schema: "zeroship" }).index("idx_deleted_sandboxes_deleted_at").add({ on: ["deleted_at"] });
  table("hosts", { schema: "zeroship" }).index("idx_hosts_region_status").add({ on: ["region", "status"] });
  table("hosts", { schema: "zeroship" }).index("idx_hosts_status_heartbeat").add({ on: ["status", "last_heartbeat"] });
  table("payouts", { schema: "zeroship" }).index("idx_payouts_creator_time").add({ on: ["creator_id", { column: "occurred_at", order: "desc" }] });
  table("provider_dead_letter", { schema: "zeroship" }).index("idx_provider_dead_letter_provider_created").add({ on: ["provider_id", { column: "created_at", order: "desc" }] });
  table("sandbox_events", { schema: "zeroship" }).index("idx_sandbox_events_ts_brin").add({ on: ["ts"], using: "brin", with: { pagesPerRange: 32 } });
  table("sandbox_events", { schema: "zeroship" }).index("idx_sandbox_events_sandbox_ts").add({ on: ["sandbox_id", "ts"] });
  table("sandbox_events", { schema: "zeroship" }).index("idx_sandbox_events_user_id_ts").add({ on: ["user_id", "ts"] });
  table("sandbox_events", { schema: "zeroship" }).index("idx_sandbox_events_metering")
    .add({ on: ["ts"], where: (col) => col("kind").in(["compute_seconds", "share.used", "preview_egress"]), include: ["sandbox_id", "user_id", "data"] });
  table("sandboxes", { schema: "zeroship" }).index("idx_sandboxes_active_user_project").add({ on: ["user_id", "project_id"], unique: true, where: (col) => col("deleted_at").isNull().and(col("status").in(["starting", "running", "recreating"])) });
  table("sandboxes", { schema: "zeroship" }).index("idx_sandboxes_created_at").add({ on: ["created_at"] });
  table("sandboxes", { schema: "zeroship" }).index("idx_sandboxes_host_id_status").add({ on: ["host_id", "status"], where: (col) => col("deleted_at").isNull() });
  table("sandboxes", { schema: "zeroship" }).index("idx_sandboxes_status_last_used").add({ on: ["status", "last_used_at"], where: (col) => col("deleted_at").isNull() });
  table("sandboxes", { schema: "zeroship" }).index("idx_sandboxes_user_id").add({ on: ["user_id"], where: (col) => col("deleted_at").isNull() });
  table("shares", { schema: "zeroship" }).index("idx_shares_expires_at").add({ on: ["expires_at"], where: (col) => col("deleted_at").isNull().and(col("revoked_at").isNull()) });
  table("shares", { schema: "zeroship" }).index("idx_shares_iss_issued_at").add({ on: ["iss", "issued_at"], where: (col) => col("deleted_at").isNull().and(col("iss").isNotNull()) });
  table("shares", { schema: "zeroship" }).index("idx_shares_sandbox_id_port").add({ on: ["sandbox_id", "port"], where: (col) => col("deleted_at").isNull() });
  table("spend_state_history", { schema: "zeroship" }).index("idx_spend_state_history_app_at").add({ on: ["app_id", { column: "at", order: "desc" }] });
  table("spend_state_history", { schema: "zeroship" }).index("idx_spend_state_history_period").add({ on: ["period"] });
  table("invoice_payments", { schema: "zeroship" }).index("invoice_payments_charge_provider_ref_key").add({ on: ["invoice_id", "provider_ref"], unique: true, where: (col) => col("kind").cast({ to: "text" }).eq("charge") });
  table("invoice_payments", { schema: "zeroship" }).index("invoice_payments_dispute_provider_ref_key").add({ on: ["invoice_id", "provider_ref", "kind"], unique: true, where: (col) => col("kind").cast({ to: "text" }).in(["dispute_debit", "dispute_reversal"]) });
  table("invoice_payments", { schema: "zeroship" }).index("invoice_payments_invoice_idx").add({ on: ["invoice_id"] });
  table("invoices", { schema: "zeroship" }).index("invoices_active_period_claim").add({ on: ["creator_id", "period"], unique: true, where: (col) => col("status").cast({ to: "text" }).ne("void") });
  table("migrated_app_policies", { schema: "zeroship" }).index("migrated_app_policies_app_submitted_idx").add({ on: ["app_id", { column: "submitted_at", order: "desc" }] });
  table("migrated_migration_audit", { schema: "zeroship" }).index("migrated_migration_audit_app_idx").add({ on: ["app_id", "migration_id", "created_at"] });
  table("migrated_migrations", { schema: "zeroship" }).index("migrated_migrations_app_status_idx").add({ on: ["app_id", "status", { column: "submitted_at", order: "desc" }] });
  table("oauth_authorization_codes", { schema: "zeroship" }).index("oauth_authorization_codes_expires_at_idx").add({ on: ["expires_at"] });
  table("oauth_grants", { schema: "zeroship" }).index("oauth_grants_client_idx").add({ on: ["client_id"] });
  table("oauth_grants", { schema: "zeroship" }).index("oauth_grants_user_granted_idx").add({ on: ["user_id", { column: "granted_at", order: "desc" }] });
  table("oauth_refresh_tokens", { schema: "zeroship" }).index("oauth_refresh_tokens_expires_at_idx").add({ on: ["expires_at"] });
  table("oauth_refresh_tokens", { schema: "zeroship" }).index("oauth_refresh_tokens_family_idx").add({ on: ["refresh_family_id", "client_id", "user_id"] });
  table("oauth_refresh_tokens", { schema: "zeroship" }).index("oauth_refresh_tokens_idem_reap_idx").add({ on: ["idem_expires_at"], where: (col) => col("idem_response_enc").isNotNull() });
  table("oauth_refresh_tokens", { schema: "zeroship" }).index("oauth_refresh_tokens_one_active_per_family").add({ on: ["refresh_family_id"], unique: true, where: (col) => col("rotated_at").isNull().and(col("revoked_at").isNull()) });
  table("oauth_refresh_tokens", { schema: "zeroship" }).index("oauth_refresh_tokens_user_idx").add({ on: ["user_id"] });
  table("oidc_session_clients", { schema: "zeroship" }).index("oidc_session_clients_client_idx").add({ on: ["client_id"] });
  table("oidc_session_clients", { schema: "zeroship" }).index("oidc_session_clients_user_idx").add({ on: ["user_id", "idp_session_id"] });
  table("payout_failures", { schema: "zeroship" }).index("payout_failures_creator_idx").add({ on: ["creator_id", { column: "created_at", order: "desc" }] });
  table("pending_disputes", { schema: "zeroship" }).index("pending_disputes_charge_idx").add({ on: ["charge"], where: (col) => col("charge").isNotNull() });
  table("pending_disputes", { schema: "zeroship" }).index("pending_disputes_payment_intent_idx").add({ on: ["payment_intent"], where: (col) => col("payment_intent").isNotNull() });
  table("permission_tokens", { schema: "zeroship" }).index("permission_tokens_owner_active_idx").add({ on: ["owner_id"], where: (col) => col("revoked_at").isNull() });
  table("permission_tokens", { schema: "zeroship" }).index("permission_tokens_policies_gin_idx").add({ on: ["policies"], using: "gin" });
  table("plan_change_events", { schema: "zeroship" }).index("plan_change_events_app_period_idx").add({ on: ["app_id", "period"] });
  table("refunds", { schema: "zeroship" }).index("refunds_invoice_idx").add({ on: ["invoice_id"] });
  table("sandboxes", { schema: "zeroship" }).index("sandboxes_idle_snapshot_idx").add({ on: ["last_used_at"], where: (col) => col("status").eq("running").and(col("idle_snapshot_opted_in")) });
  table("sandboxes", { schema: "zeroship" }).index("sandboxes_status_lessee_idx").add({ on: ["status", "lessee_updated_at"], where: (col) => col("status").in(["snapshotting", "restoring", "restoring_cold"]) });
  table("signing_keys", { schema: "zeroship" }).index("signing_keys_status_idx").add({ on: ["status"] });
  table("usage_aggregates", { schema: "zeroship" }).index("usage_aggregates_period_idx").add({ on: ["period", "app_id"] });
  table("wake_jobs", { schema: "zeroship" }).index("wake_jobs_lessee_idx").add({ on: ["lessee_updated_at"], where: (col) => col("state").notIn(["ok", "failed"]) });
  table("wake_jobs", { schema: "zeroship" }).index("wake_jobs_sandbox_idx").add({ on: ["sandbox_id"] });
  table("wake_jobs", { schema: "zeroship" }).index("wake_jobs_sandbox_pending_uniq").add({ on: ["sandbox_id"], unique: true, where: (col) => col("state").notIn(["ok", "failed"]) });
  table("wake_jobs", { schema: "zeroship" }).index("wake_jobs_state_idx").add({ on: ["state"], where: (col) => col("state").notIn(["ok", "failed"]) });
  table("wake_jobs", { schema: "zeroship" }).index("wake_jobs_updated_at_idx").add({ on: ["updated_at"] });
  table("app_env_expose", { schema: "zeroship" }).foreignKey("app_env_expose_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("app_members", { schema: "zeroship" }).foreignKey("app_members_added_by_fkey").add({ columns: ["added_by"], references: { table: "users", columns: ["id"] } });
  table("app_members", { schema: "zeroship" }).foreignKey("app_members_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("app_members", { schema: "zeroship" }).foreignKey("app_members_user_id_fkey").add({ columns: ["user_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("app_net_grants", { schema: "zeroship" }).foreignKey("app_net_grants_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("app_oauth_clients", { schema: "zeroship" }).foreignKey("app_oauth_clients_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("app_oauth_clients", { schema: "zeroship" }).foreignKey("app_oauth_clients_client_id_fkey").add({ columns: ["client_id"], references: { table: "oauth_clients", columns: ["client_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("app_scope_defs", { schema: "zeroship" }).foreignKey("app_scope_defs_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("app_secrets", { schema: "zeroship" }).foreignKey("app_secrets_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("app_session_anchors", { schema: "zeroship" }).foreignKey("app_session_anchors_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("app_session_anchors", { schema: "zeroship" }).foreignKey("app_session_anchors_client_id_fkey").add({ columns: ["client_id"], references: { table: "oauth_clients", columns: ["client_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("app_session_anchors", { schema: "zeroship" }).foreignKey("app_session_anchors_global_user_id_fkey").add({ columns: ["global_user_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("app_spend_limit", { schema: "zeroship" }).foreignKey("app_spend_limit_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("app_spend_state", { schema: "zeroship" }).foreignKey("app_spend_state_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("app_usage", { schema: "zeroship" }).foreignKey("app_usage_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("app_usage_history", { schema: "zeroship" }).foreignKey("app_usage_history_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("app_user_identities", { schema: "zeroship" }).foreignKey("app_user_identities_app_client_id_fkey").add({ columns: ["app_client_id"], references: { table: "oauth_clients", columns: ["client_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("app_user_identities", { schema: "zeroship" }).foreignKey("app_user_identities_global_user_id_fkey").add({ columns: ["global_user_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("app_vars", { schema: "zeroship" }).foreignKey("app_vars_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("apps", { schema: "zeroship" }).foreignKey("apps_plan_fk").add({ columns: ["plan_id"], references: { table: "plans", columns: ["id"] }, onDelete: "restrict" });
  table("billing_customer_refs", { schema: "zeroship" }).foreignKey("billing_customer_refs_creator_id_fkey").add({ columns: ["creator_id"], references: { table: "creator_billing", columns: ["creator_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("billing_disputes", { schema: "zeroship" }).foreignKey("billing_disputes_invoice_id_fkey").add({ columns: ["invoice_id"], references: { table: "invoices", columns: ["id"] }, onDelete: "restrict" });
  table("billing_line_provider_refs", { schema: "zeroship" }).foreignKey("billing_line_provider_refs_line_fk").add({ columns: ["invoice_id", "app_id", "segment_no"], references: { table: "invoice_lines", columns: ["invoice_id", "app_id", "segment_no"], schema: "zeroship" }, onDelete: "cascade" });
  table("billing_metrics", { schema: "zeroship" }).foreignKey("billing_metrics_owner_app_fkey").add({ columns: ["owner_app"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("billing_notifications", { schema: "zeroship" }).foreignKey("billing_notifications_creator_id_fkey").add({ columns: ["creator_id"], references: { table: "creator_billing", columns: ["creator_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("billing_provider_refs", { schema: "zeroship" }).foreignKey("billing_provider_refs_invoice_id_fkey").add({ columns: ["invoice_id"], references: { table: "invoices", columns: ["id"] }, onDelete: "cascade" });
  table("connect_checkout_failures", { schema: "zeroship" }).foreignKey("connect_checkout_failures_creator_id_fkey").add({ columns: ["creator_id"], references: { table: "creator_accounts", columns: ["creator_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("creator_accounts", { schema: "zeroship" }).foreignKey("creator_accounts_creator_id_fkey").add({ columns: ["creator_id"], references: { table: "users", columns: ["id"] } });
  table("creator_billing", { schema: "zeroship" }).foreignKey("creator_billing_creator_id_fkey").add({ columns: ["creator_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("creator_billing_status", { schema: "zeroship" }).foreignKey("creator_billing_status_creator_id_fkey").add({ columns: ["creator_id"], references: { table: "creator_billing", columns: ["creator_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("creator_billing_status_history", { schema: "zeroship" }).foreignKey("creator_billing_status_history_creator_id_fkey").add({ columns: ["creator_id"], references: { table: "creator_billing", columns: ["creator_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("creator_fee_policy", { schema: "zeroship" }).foreignKey("creator_fee_policy_creator_id_fkey").add({ columns: ["creator_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("credit_ledger", { schema: "zeroship" }).foreignKey("credit_ledger_applied_invoice_id_fkey").add({ columns: ["applied_invoice_id"], references: { table: "invoices", columns: ["id"] }, onDelete: "restrict" });
  table("credit_ledger", { schema: "zeroship" }).foreignKey("credit_ledger_consumed_from_grant_id_fkey").add({ columns: ["consumed_from_grant_id"], references: { table: "credit_ledger", columns: ["id"] }, onDelete: "restrict" });
  table("credit_ledger", { schema: "zeroship" }).foreignKey("credit_ledger_creator_id_fkey").add({ columns: ["creator_id"], references: { table: "creator_billing", columns: ["creator_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("device_grants", { schema: "zeroship" }).foreignKey("device_grants_client_id_fkey").add({ columns: ["client_id"], references: { table: "oauth_clients", columns: ["client_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("device_grants", { schema: "zeroship" }).foreignKey("device_grants_principal_id_fkey").add({ columns: ["principal_id"], references: { table: "users", columns: ["id"] } });
  table("email_verifications", { schema: "zeroship" }).foreignKey("email_verifications_user_id_fkey").add({ columns: ["user_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("federated_identities", { schema: "zeroship" }).foreignKey("federated_identities_user_id_fkey").add({ columns: ["user_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("gateway_sessions", { schema: "zeroship" }).foreignKey("gateway_sessions_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("identity_links", { schema: "zeroship" }).foreignKey("identity_links_principal_id_fkey").add({ columns: ["principal_id"], references: { table: "users", columns: ["id"] } });
  table("idp_sessions", { schema: "zeroship" }).foreignKey("idp_sessions_user_id_fkey").add({ columns: ["user_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("invoice_lines", { schema: "zeroship" }).foreignKey("invoice_lines_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "restrict" });
  table("invoice_lines", { schema: "zeroship" }).foreignKey("invoice_lines_invoice_id_fkey").add({ columns: ["invoice_id"], references: { table: "invoices", columns: ["id"] }, onDelete: "restrict" });
  table("invoice_lines", { schema: "zeroship" }).foreignKey("invoice_lines_plan_id_fkey").add({ columns: ["plan_id"], references: { table: "plans", columns: ["id"] }, onDelete: "restrict" });
  table("invoice_payments", { schema: "zeroship" }).foreignKey("invoice_payments_invoice_id_fkey").add({ columns: ["invoice_id"], references: { table: "invoices", columns: ["id"] }, onDelete: "restrict" });
  table("invoices", { schema: "zeroship" }).foreignKey("invoices_creator_id_fkey").add({ columns: ["creator_id"], references: { table: "creator_billing", columns: ["creator_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("magic_links", { schema: "zeroship" }).foreignKey("magic_links_user_id_fkey").add({ columns: ["user_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("metering_exports", { schema: "zeroship" }).foreignKey("metering_exports_creator_id_fkey").add({ columns: ["creator_id"], references: { table: "creator_billing", columns: ["creator_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("metric_weights", { schema: "zeroship" }).foreignKey("metric_weights_metric_fkey").add({ columns: ["metric"], references: { table: "billing_metrics", columns: ["metric"], schema: "zeroship" }, onDelete: "restrict" });
  table("migrated_app_policies", { schema: "zeroship" }).foreignKey("migrated_app_policies_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("migrated_app_policies", { schema: "zeroship" }).foreignKey("migrated_app_policies_submitted_by_fkey").add({ columns: ["submitted_by"], references: { table: "users", columns: ["id"] }, onDelete: "restrict" });
  table("migrated_migration_audit", { schema: "zeroship" }).foreignKey("migrated_migration_audit_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("migrated_migration_audit", { schema: "zeroship" }).foreignKey("migrated_migration_audit_principal_id_fkey").add({ columns: ["principal_id"], references: { table: "users", columns: ["id"] }, onDelete: "restrict" });
  table("migrated_migrations", { schema: "zeroship" }).foreignKey("migrated_migrations_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("migrated_migrations", { schema: "zeroship" }).foreignKey("migrated_migrations_approved_by_fkey").add({ columns: ["approved_by"], references: { table: "users", columns: ["id"] }, onDelete: "restrict" });
  table("migrated_migrations", { schema: "zeroship" }).foreignKey("migrated_migrations_submitted_by_fkey").add({ columns: ["submitted_by"], references: { table: "users", columns: ["id"] }, onDelete: "restrict" });
  table("oauth_authorization_codes", { schema: "zeroship" }).foreignKey("oauth_authorization_codes_client_id_fkey").add({ columns: ["client_id"], references: { table: "oauth_clients", columns: ["client_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("oauth_authorization_codes", { schema: "zeroship" }).foreignKey("oauth_authorization_codes_user_id_fkey").add({ columns: ["user_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("oauth_clients", { schema: "zeroship" }).foreignKey("oauth_clients_created_by_fkey").add({ columns: ["created_by"], references: { table: "users", columns: ["id"] } });
  table("oauth_grants", { schema: "zeroship" }).foreignKey("oauth_grants_client_id_fkey").add({ columns: ["client_id"], references: { table: "oauth_clients", columns: ["client_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("oauth_grants", { schema: "zeroship" }).foreignKey("oauth_grants_user_id_fkey").add({ columns: ["user_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("oauth_refresh_tokens", { schema: "zeroship" }).foreignKey("oauth_refresh_tokens_client_id_fkey").add({ columns: ["client_id"], references: { table: "oauth_clients", columns: ["client_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("oauth_refresh_tokens", { schema: "zeroship" }).foreignKey("oauth_refresh_tokens_user_id_fkey").add({ columns: ["user_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("oidc_session_clients", { schema: "zeroship" }).foreignKey("oidc_session_clients_client_id_fkey").add({ columns: ["client_id"], references: { table: "oauth_clients", columns: ["client_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("oidc_session_clients", { schema: "zeroship" }).foreignKey("oidc_session_clients_idp_session_id_fkey").add({ columns: ["idp_session_id"], references: { table: "idp_sessions", columns: ["id"] }, onDelete: "cascade" });
  table("oidc_session_clients", { schema: "zeroship" }).foreignKey("oidc_session_clients_user_id_fkey").add({ columns: ["user_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("payout_failures", { schema: "zeroship" }).foreignKey("payout_failures_creator_id_fkey").add({ columns: ["creator_id"], references: { table: "creator_accounts", columns: ["creator_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("payouts", { schema: "zeroship" }).foreignKey("payouts_creator_id_fkey").add({ columns: ["creator_id"], references: { table: "creator_accounts", columns: ["creator_id"], schema: "zeroship" }, onDelete: "restrict" });
  table("permission_tokens", { schema: "zeroship" }).foreignKey("permission_tokens_owner_id_fkey").add({ columns: ["owner_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("plan_change_events", { schema: "zeroship" }).foreignKey("plan_change_events_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("plan_change_events", { schema: "zeroship" }).foreignKey("plan_change_events_from_plan_id_fkey").add({ columns: ["from_plan_id"], references: { table: "plans", columns: ["id"] }, onDelete: "restrict" });
  table("plan_change_events", { schema: "zeroship" }).foreignKey("plan_change_events_to_plan_id_fkey").add({ columns: ["to_plan_id"], references: { table: "plans", columns: ["id"] }, onDelete: "restrict" });
  table("platform_admin_roles", { schema: "zeroship" }).foreignKey("platform_admin_roles_granted_by_fkey").add({ columns: ["granted_by"], references: { table: "users", columns: ["id"] } });
  table("platform_admin_roles", { schema: "zeroship" }).foreignKey("platform_admin_roles_user_id_fkey").add({ columns: ["user_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("platform_policies", { schema: "zeroship" }).foreignKey("platform_policies_updated_by_fkey").add({ columns: ["updated_by"], references: { table: "users", columns: ["id"] } });
  table("principal_grants", { schema: "zeroship" }).foreignKey("principal_grants_principal_id_fkey").add({ columns: ["principal_id"], references: { table: "users", columns: ["id"] } });
  table("refund_provider_refs", { schema: "zeroship" }).foreignKey("refund_provider_refs_refund_id_fkey").add({ columns: ["refund_id"], references: { table: "refunds", columns: ["id"] }, onDelete: "cascade" });
  table("refunds", { schema: "zeroship" }).foreignKey("refunds_invoice_id_fkey").add({ columns: ["invoice_id"], references: { table: "invoices", columns: ["id"] }, onDelete: "restrict" });
  table("sandboxes", { schema: "zeroship" }).foreignKey("sandboxes_host_id_fkey").add({ columns: ["host_id"], references: { table: "hosts", columns: ["host_id"], schema: "zeroship" }, onDelete: "restrict" });
  table("shares", { schema: "zeroship" }).foreignKey("shares_sandbox_id_fkey").add({ columns: ["sandbox_id"], references: { table: "sandboxes", columns: ["sandbox_id"], schema: "zeroship" }, onDelete: "cascade" });
  table("spend_state_history", { schema: "zeroship" }).foreignKey("spend_state_history_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("totp_backup_codes", { schema: "zeroship" }).foreignKey("totp_backup_codes_user_id_fkey").add({ columns: ["user_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("totp_credentials", { schema: "zeroship" }).foreignKey("totp_credentials_user_id_fkey").add({ columns: ["user_id"], references: { table: "users", columns: ["id"] }, onDelete: "cascade" });
  table("usage_aggregates", { schema: "zeroship" }).foreignKey("usage_aggregates_app_id_fkey").add({ columns: ["app_id"], references: { table: "apps", columns: ["id"] }, onDelete: "cascade" });
  table("usage_aggregates", { schema: "zeroship" }).foreignKey("usage_aggregates_metric_fkey").add({ columns: ["metric"], references: { table: "billing_metrics", columns: ["metric"], schema: "zeroship" }, deferrable: true, initiallyDeferred: true });
}

export function down() {

}
