import { raw } from "@zeroship/migrate/pg";

export const name = "control_tables";

export function up() {
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.app_audit (\n    id uuid DEFAULT gen_random_uuid() NOT NULL,\n    app_id uuid,\n    creator_id uuid,\n    actor_user_id uuid,\n    actor_token_id uuid,\n    action text NOT NULL,\n    resource text,\n    source_ip inet,\n    detail jsonb,\n    occurred_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.app_env_expose (\n    app_id uuid NOT NULL,\n    key_name text NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.app_members (\n    app_id uuid NOT NULL,\n    user_id uuid NOT NULL,\n    role text NOT NULL,\n    added_at timestamp with time zone DEFAULT now() NOT NULL,\n    added_by uuid,\n    CONSTRAINT app_members_role_check CHECK ((role = ANY (ARRAY['owner'::text, 'editor'::text, 'viewer'::text])))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.app_net_grants (\n    app_id uuid NOT NULL,\n    host text NOT NULL,\n    port integer NOT NULL,\n    granted_by text NOT NULL,\n    granted_at timestamp with time zone DEFAULT now() NOT NULL,\n    note text,\n    CONSTRAINT app_net_grants_port_check CHECK (((port >= 1) AND (port <= 65535)))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.app_oauth_clients (\n    app_id uuid NOT NULL,\n    client_id text NOT NULL,\n    sector_identifier text NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.app_scope_defs (\n    app_id uuid NOT NULL,\n    scope_id text NOT NULL,\n    label text NOT NULL,\n    description text\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.app_secrets (\n    app_id uuid NOT NULL,\n    key_name text NOT NULL,\n    ciphertext bytea NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.app_usage (\n    app_id uuid NOT NULL,\n    resource text NOT NULL,\n    value bigint DEFAULT 0 NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.app_usage_history (\n    app_id uuid NOT NULL,\n    period text NOT NULL,\n    counters jsonb NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.app_vars (\n    app_id uuid NOT NULL,\n    key_name text NOT NULL,\n    value text NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.apps (\n    id uuid DEFAULT gen_random_uuid() NOT NULL,\n    name text NOT NULL,\n    plan_id text DEFAULT 'free'::text NOT NULL,\n    deploy_hash text,\n    api_key text NOT NULL,\n    api_key_hash text DEFAULT ''::text NOT NULL,\n    env_version bigint DEFAULT 0 NOT NULL,\n    suspended boolean DEFAULT false NOT NULL,\n    audit_locked boolean DEFAULT false NOT NULL,\n    manifest_json text,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL,\n    system boolean DEFAULT false NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.creator_account_history (\n    id uuid DEFAULT gen_random_uuid() NOT NULL,\n    creator_id uuid NOT NULL,\n    stripe_account_id text NOT NULL,\n    linked_at timestamp with time zone DEFAULT now() NOT NULL,\n    unlinked_at timestamp with time zone\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.creator_accounts (\n    creator_id uuid NOT NULL,\n    stripe_account_id text NOT NULL,\n    onboarded_at timestamp with time zone DEFAULT now() NOT NULL,\n    unlinked_at timestamp with time zone,\n    charges_enabled boolean DEFAULT false NOT NULL,\n    payouts_enabled boolean DEFAULT false NOT NULL,\n    details_submitted boolean DEFAULT false NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.migrated_app_policies (\n    app_id uuid NOT NULL,\n    version bigint NOT NULL,\n    raw_toml text NOT NULL,\n    parsed_profile jsonb NOT NULL,\n    effective_profile jsonb NOT NULL,\n    ceiling_id text NOT NULL,\n    ceiling_version bigint NOT NULL,\n    submitted_by uuid NOT NULL,\n    submitted_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT migrated_app_policies_ceiling_version_check CHECK ((ceiling_version > 0)),\n    CONSTRAINT migrated_app_policies_version_check CHECK ((version > 0))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.migrated_migration_audit (\n    audit_id uuid DEFAULT gen_random_uuid() NOT NULL,\n    app_id uuid NOT NULL,\n    migration_id uuid NOT NULL,\n    migration_versions jsonb DEFAULT '[]'::jsonb NOT NULL,\n    action text NOT NULL,\n    outcome text NOT NULL,\n    principal_id uuid NOT NULL,\n    effective_profile jsonb NOT NULL,\n    sealed_profile jsonb,\n    ceiling_id text NOT NULL,\n    ceiling_version bigint NOT NULL,\n    detail jsonb DEFAULT '{}'::jsonb NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT migrated_migration_audit_action_check CHECK ((action = ANY (ARRAY['submit'::text, 'reject_pending'::text, 'approve'::text, 'apply'::text]))),\n    CONSTRAINT migrated_migration_audit_ceiling_version_check CHECK ((ceiling_version > 0))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.migrated_migrations (\n    app_id uuid NOT NULL,\n    migration_id uuid NOT NULL,\n    status text NOT NULL,\n    request_body jsonb NOT NULL,\n    effective_profile jsonb NOT NULL,\n    ceiling_id text NOT NULL,\n    ceiling_version bigint NOT NULL,\n    gated_versions jsonb DEFAULT '[]'::jsonb NOT NULL,\n    submitted_by uuid NOT NULL,\n    submitted_at timestamp with time zone DEFAULT now() NOT NULL,\n    approved_by uuid,\n    approved_at timestamp with time zone,\n    applied_at timestamp with time zone,\n    last_error text,\n    CONSTRAINT migrated_migrations_ceiling_version_check CHECK ((ceiling_version > 0)),\n    CONSTRAINT migrated_migrations_status_check CHECK ((status = ANY (ARRAY['submitted'::text, 'pending_approval'::text, 'approved'::text, 'applied'::text, 'failed'::text])))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.net_policy_catalog (\n    key text NOT NULL,\n    value_json jsonb NOT NULL,\n    updated_by text,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.payouts (\n    id uuid DEFAULT gen_random_uuid() NOT NULL,\n    creator_id uuid NOT NULL,\n    event_id text NOT NULL,\n    event_type text NOT NULL,\n    gross_amount bigint NOT NULL,\n    platform_fee bigint NOT NULL,\n    net_amount bigint NOT NULL,\n    currency text NOT NULL,\n    occurred_at timestamp with time zone NOT NULL,\n    payload_hash bytea,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT control_payouts_currency_shape CHECK ((currency ~ '^[a-z]{3}$'::text)),\n    CONSTRAINT control_payouts_fee_lte_gross CHECK ((platform_fee <= gross_amount)),\n    CONSTRAINT control_payouts_fee_nonnegative CHECK ((platform_fee >= 0)),\n    CONSTRAINT control_payouts_gross_nonnegative CHECK ((gross_amount >= 0)),\n    CONSTRAINT control_payouts_net_matches_amounts CHECK ((net_amount = (gross_amount - platform_fee))),\n    CONSTRAINT control_payouts_net_nonnegative CHECK ((net_amount >= 0))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.permission_tokens (\n    id uuid NOT NULL,\n    owner_id uuid NOT NULL,\n    kind text NOT NULL,\n    client_id text,\n    name text NOT NULL,\n    policies jsonb NOT NULL,\n    policy_hash text NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    expires_at timestamp with time zone,\n    revoked_at timestamp with time zone,\n    last_used_at timestamp with time zone,\n    CONSTRAINT permission_tokens_kind_check CHECK ((kind = ANY (ARRAY['pat'::text, 'oauth_grant'::text])))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.platform_admin_roles (\n    user_id uuid NOT NULL,\n    role text NOT NULL,\n    granted_at timestamp with time zone DEFAULT now() NOT NULL,\n    granted_by uuid,\n    CONSTRAINT platform_admin_roles_role_check CHECK ((role = ANY (ARRAY['admin'::text, 'support'::text, 'billing'::text, 'readonly'::text])))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.platform_policies (\n    id text NOT NULL,\n    cedar_source text NOT NULL,\n    enabled boolean DEFAULT true NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL,\n    updated_by uuid\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
}

export function down() {

}
