import { raw, sequence } from "@zeroship/migrate/pg";

export const name = "auth_oauth_tables";

export function up() {
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.app_session_anchors (\n    id uuid DEFAULT gen_random_uuid() NOT NULL,\n    app_id uuid NOT NULL,\n    client_id text NOT NULL,\n    global_user_id uuid NOT NULL,\n    refresh_token_enc bytea NOT NULL,\n    refresh_family_id text NOT NULL,\n    granted_scopes text[] DEFAULT '{}'::text[] NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    abs_expires_at timestamp with time zone NOT NULL,\n    revoked_at timestamp with time zone\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.app_user_identities (\n    app_client_id text NOT NULL,\n    global_user_id uuid NOT NULL,\n    pairwise_sub text NOT NULL,\n    relay_email text,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    revoked_at timestamp with time zone\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.audit_events (\n    id bigint NOT NULL,\n    occurred_at timestamp with time zone DEFAULT now() NOT NULL,\n    event_type text NOT NULL,\n    outcome text NOT NULL,\n    actor_user_id uuid,\n    client_id text,\n    request_id text,\n    ip inet,\n    user_agent text,\n    auth_method text,\n    detail jsonb\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  sequence("audit_events_id_seq").alter({ schema: "zeroship", ownedBy: { table: "audit_events", column: "id" } });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.authz_decisions (\n    id uuid DEFAULT gen_random_uuid() NOT NULL,\n    occurred_at timestamp with time zone DEFAULT now() NOT NULL,\n    actor_user_id uuid,\n    token_id uuid,\n    action text NOT NULL,\n    resource_type text NOT NULL,\n    resource_id text,\n    decision text NOT NULL,\n    matched_policies text[] DEFAULT '{}'::text[] NOT NULL,\n    request_ip inet,\n    request_id text,\n    CONSTRAINT authz_decisions_decision_check CHECK ((decision = ANY (ARRAY['allow'::text, 'deny'::text])))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.cron_state (\n    key text NOT NULL,\n    last_rotated_at timestamp with time zone DEFAULT now() NOT NULL,\n    notes text\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.device_grants (\n    device_code_hash text NOT NULL,\n    user_code text NOT NULL,\n    status text DEFAULT 'pending'::text NOT NULL,\n    principal_id uuid,\n    platform_access_token_enc bytea,\n    provider text NOT NULL,\n    scope text,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    expires_at timestamp with time zone NOT NULL,\n    last_polled_at timestamp with time zone,\n    auth_credential_version bigint DEFAULT 0 NOT NULL,\n    client_id text,\n    sid text,\n    poll_interval_secs integer DEFAULT 5 NOT NULL,\n    CONSTRAINT device_grants_poll_interval_secs_check CHECK ((poll_interval_secs > 0)),\n    CONSTRAINT device_grants_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'denied'::text])))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.dpop_jti (\n    jti text NOT NULL,\n    inserted_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.email_suppressions (\n    email public.citext NOT NULL,\n    reason text NOT NULL,\n    suppressed_at timestamp with time zone DEFAULT now() NOT NULL,\n    provider_msg text\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.email_verifications (\n    token_hash bytea NOT NULL,\n    user_id uuid NOT NULL,\n    email public.citext NOT NULL,\n    issued_at timestamp with time zone DEFAULT now() NOT NULL,\n    expires_at timestamp with time zone NOT NULL,\n    consumed_at timestamp with time zone\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.federated_identities (\n    id uuid DEFAULT gen_random_uuid() NOT NULL,\n    user_id uuid NOT NULL,\n    provider text NOT NULL,\n    subject text NOT NULL,\n    email_at_link public.citext,\n    raw_profile jsonb,\n    linked_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.gateway_sessions (\n    id uuid DEFAULT gen_random_uuid() NOT NULL,\n    user_id uuid NOT NULL,\n    app_id uuid NOT NULL,\n    email public.citext,\n    name text,\n    avatar_url text,\n    email_verified boolean DEFAULT false NOT NULL,\n    issued_at timestamp with time zone DEFAULT now() NOT NULL,\n    idle_expires_at timestamp with time zone NOT NULL,\n    abs_expires_at timestamp with time zone NOT NULL,\n    revoked_at timestamp with time zone,\n    granted_scopes text[] DEFAULT '{}'::text[] NOT NULL,\n    auth_time timestamp with time zone,\n    amr text[] DEFAULT '{}'::text[] NOT NULL,\n    sid text\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.identity_links (\n    principal_id uuid NOT NULL,\n    provider text NOT NULL,\n    provider_subject text NOT NULL,\n    email text,\n    created_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.idp_sessions (\n    id uuid DEFAULT gen_random_uuid() NOT NULL,\n    user_id uuid NOT NULL,\n    auth_method text NOT NULL,\n    amr text[] NOT NULL,\n    acr text,\n    auth_time timestamp with time zone DEFAULT now() NOT NULL,\n    credential_version bigint DEFAULT 0 NOT NULL,\n    idle_expires_at timestamp with time zone NOT NULL,\n    abs_expires_at timestamp with time zone NOT NULL,\n    revoked_at timestamp with time zone\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.jwk_key_state (\n    set_name text NOT NULL,\n    kid text NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.magic_completions (\n    csrf_nonce text NOT NULL,\n    code text NOT NULL,\n    email public.citext NOT NULL,\n    login_challenge text NOT NULL,\n    attempts smallint DEFAULT 0 NOT NULL,\n    expires_at timestamp with time zone NOT NULL,\n    consumed_pending_at timestamp with time zone,\n    consumed_at timestamp with time zone\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.magic_links (\n    token_hash bytea NOT NULL,\n    email public.citext NOT NULL,\n    csrf_nonce text NOT NULL,\n    purpose text NOT NULL,\n    request_ip inet,\n    request_ua text,\n    issued_at timestamp with time zone DEFAULT now() NOT NULL,\n    expires_at timestamp with time zone NOT NULL,\n    consumed_pending_at timestamp with time zone,\n    consumed_at timestamp with time zone,\n    user_id uuid\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.oauth_authorization_codes (\n    code_hash bytea NOT NULL,\n    client_id text NOT NULL,\n    redirect_uri text NOT NULL,\n    pkce_challenge text NOT NULL,\n    pkce_method text NOT NULL,\n    requested_scopes text[] NOT NULL,\n    granted_scopes text[] NOT NULL,\n    nonce text,\n    user_id uuid NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    expires_at timestamp with time zone NOT NULL,\n    consumed_at timestamp with time zone,\n    auth_credential_version bigint DEFAULT 0 NOT NULL,\n    sid text NOT NULL,\n    CONSTRAINT oauth_authorization_codes_max_ttl CHECK ((expires_at <= (created_at + '00:01:00'::interval))),\n    CONSTRAINT oauth_authorization_codes_pkce_method_check CHECK ((pkce_method = 'S256'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.oauth_clients (\n    client_id text NOT NULL,\n    client_name text NOT NULL,\n    client_uri text,\n    logo_uri text,\n    redirect_uris text[] NOT NULL,\n    scopes text[] NOT NULL,\n    skip_consent boolean DEFAULT false NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    created_by uuid,\n    client_secret_hash text,\n    refresh_allowed boolean DEFAULT false NOT NULL,\n    token_endpoint_auth_method text DEFAULT 'none'::text NOT NULL,\n    brokered boolean DEFAULT false NOT NULL,\n    backchannel_logout_uri text,\n    CONSTRAINT oauth_clients_brokered_requires_secret_basic CHECK (((brokered = false) OR (token_endpoint_auth_method = 'client_secret_basic'::text))),\n    CONSTRAINT oauth_clients_token_endpoint_auth_method_check CHECK ((token_endpoint_auth_method = ANY (ARRAY['none'::text, 'client_secret_basic'::text, 'client_secret_post'::text])))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.oauth_grants (\n    user_id uuid NOT NULL,\n    client_id text NOT NULL,\n    granted_scopes text[] NOT NULL,\n    granted_at timestamp with time zone DEFAULT now() NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL,\n    last_used_at timestamp with time zone\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.oauth_refresh_tokens (\n    token_hash bytea NOT NULL,\n    hash_key_version smallint NOT NULL,\n    refresh_family_id text NOT NULL,\n    replaced_by_token_hash bytea,\n    client_id text NOT NULL,\n    user_id uuid NOT NULL,\n    sub text NOT NULL,\n    granted_scopes text[] NOT NULL,\n    family_granted_scopes text[] NOT NULL,\n    issued_at timestamp with time zone DEFAULT now() NOT NULL,\n    expires_at timestamp with time zone NOT NULL,\n    family_absolute_expires_at timestamp with time zone NOT NULL,\n    consumed_at timestamp with time zone,\n    rotated_at timestamp with time zone,\n    revoked_at timestamp with time zone,\n    last_used_at timestamp with time zone,\n    idem_response_enc bytea,\n    idem_expires_at timestamp with time zone,\n    CONSTRAINT oauth_refresh_tokens_idle_le_ceiling CHECK ((expires_at <= family_absolute_expires_at))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.oidc_session_clients (\n    idp_session_id uuid NOT NULL,\n    user_id uuid NOT NULL,\n    client_id text NOT NULL,\n    sid text NOT NULL,\n    sub text NOT NULL,\n    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,\n    last_seen_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.principal_grants (\n    principal_id uuid NOT NULL,\n    grant_name text NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.rate_limits (\n    bucket_key text NOT NULL,\n    tokens real NOT NULL,\n    updated_at timestamp with time zone NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.signing_keys (\n    kid text NOT NULL,\n    alg text NOT NULL,\n    public_jwk jsonb NOT NULL,\n    status text NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    activated_at timestamp with time zone,\n    retiring_at timestamp with time zone,\n    retired_at timestamp with time zone,\n    CONSTRAINT signing_keys_alg_check CHECK ((alg = 'EdDSA'::text)),\n    CONSTRAINT signing_keys_status_check CHECK ((status = ANY (ARRAY['active'::text, 'next'::text, 'retiring'::text])))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.token_revocations (\n    client_id text NOT NULL,\n    sub text NOT NULL,\n    revoked_after timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.totp_backup_codes (\n    id bigint NOT NULL,\n    user_id uuid NOT NULL,\n    code_hash text NOT NULL,\n    used_at timestamp with time zone,\n    created_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.totp_credentials (\n    user_id uuid NOT NULL,\n    encrypted_secret bytea NOT NULL,\n    confirmed_at timestamp with time zone,\n    created_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.users (\n    id uuid DEFAULT gen_random_uuid() NOT NULL,\n    email public.citext NOT NULL,\n    email_verified_at timestamp with time zone,\n    name text NOT NULL,\n    avatar_url text,\n    password_hash text,\n    credential_version bigint DEFAULT 0 NOT NULL,\n    locked_until timestamp with time zone,\n    disabled_at timestamp with time zone,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL,\n    last_login_at timestamp with time zone,\n    failed_login_count integer DEFAULT 0 NOT NULL,\n    deletion_requested_at timestamp with time zone,\n    deletion_scheduled_for timestamp with time zone,\n    anonymized_at timestamp with time zone\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add a structural operation for this exact platform DDL fragment
  raw({ sql: "ALTER TABLE zeroship.totp_backup_codes ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (\n    SEQUENCE NAME zeroship.totp_backup_codes_id_seq\n    START WITH 1\n    INCREMENT BY 1\n    NO MINVALUE\n    NO MAXVALUE\n    CACHE 1\n)", reason: "this platform DDL object has no exact structural operation in the current v2 surface" });
  // TODO(dsl-v2): add a structural operation for this exact platform DDL fragment
  raw({ sql: "ALTER TABLE ONLY zeroship.audit_events ALTER COLUMN id SET DEFAULT nextval('zeroship.audit_events_id_seq'::regclass)", reason: "this platform DDL object has no exact structural operation in the current v2 surface" });
}

export function down() {

}
