import { raw } from "@zeroship/migrate/pg";

export const name = "sandbox_tables";

export function up() {
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.deleted_sandboxes (\n    sandbox_id text NOT NULL,\n    user_id text NOT NULL,\n    deleted_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT deleted_sandboxes_sandbox_id_check CHECK ((sandbox_id ~ '^sbx_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT deleted_sandboxes_user_id_check CHECK ((user_id ~ '^usr_[0-9A-Za-z]{20,40}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.hosts (\n    host_id text NOT NULL,\n    boot_id text NOT NULL,\n    hostname text NOT NULL,\n    region text NOT NULL,\n    backend text NOT NULL,\n    started_at timestamp with time zone DEFAULT now() NOT NULL,\n    last_heartbeat timestamp with time zone DEFAULT now() NOT NULL,\n    status text DEFAULT 'alive'::text NOT NULL,\n    drain_started_at timestamp with time zone,\n    version text DEFAULT ''::text NOT NULL,\n    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,\n    CONSTRAINT hosts_backend_check CHECK ((backend = ANY (ARRAY['docker'::text, 'k8s'::text, 'nomad-ch'::text]))),\n    CONSTRAINT hosts_boot_id_check CHECK ((boot_id ~ '^[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT hosts_host_id_check CHECK ((host_id ~ '^hst_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT hosts_region_check CHECK ((region ~ '^[a-z][a-z0-9-]{1,63}$'::text)),\n    CONSTRAINT hosts_status_check CHECK ((status = ANY (ARRAY['alive'::text, 'draining'::text, 'dead'::text])))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.sandbox_events (\n    event_id text NOT NULL,\n    sandbox_id text,\n    user_id text NOT NULL,\n    kind text NOT NULL,\n    ts timestamp with time zone DEFAULT now() NOT NULL,\n    data jsonb DEFAULT '{}'::jsonb NOT NULL,\n    CONSTRAINT sandbox_events_data_check CHECK ((pg_column_size(data) <= 8192)),\n    CONSTRAINT sandbox_events_event_id_check CHECK ((event_id ~ '^evt_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_sandbox_id_check CHECK ((sandbox_id ~ '^sbx_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_user_id_check CHECK ((user_id ~ '^usr_[0-9A-Za-z]{20,40}$'::text))\n)\nPARTITION BY RANGE (ts)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.sandbox_events_2026_05 (\n    event_id text NOT NULL,\n    sandbox_id text,\n    user_id text NOT NULL,\n    kind text NOT NULL,\n    ts timestamp with time zone DEFAULT now() NOT NULL,\n    data jsonb DEFAULT '{}'::jsonb NOT NULL,\n    CONSTRAINT sandbox_events_data_check CHECK ((pg_column_size(data) <= 8192)),\n    CONSTRAINT sandbox_events_event_id_check CHECK ((event_id ~ '^evt_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_sandbox_id_check CHECK ((sandbox_id ~ '^sbx_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_user_id_check CHECK ((user_id ~ '^usr_[0-9A-Za-z]{20,40}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.sandbox_events_2026_06 (\n    event_id text NOT NULL,\n    sandbox_id text,\n    user_id text NOT NULL,\n    kind text NOT NULL,\n    ts timestamp with time zone DEFAULT now() NOT NULL,\n    data jsonb DEFAULT '{}'::jsonb NOT NULL,\n    CONSTRAINT sandbox_events_data_check CHECK ((pg_column_size(data) <= 8192)),\n    CONSTRAINT sandbox_events_event_id_check CHECK ((event_id ~ '^evt_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_sandbox_id_check CHECK ((sandbox_id ~ '^sbx_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_user_id_check CHECK ((user_id ~ '^usr_[0-9A-Za-z]{20,40}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.sandbox_events_2026_07 (\n    event_id text NOT NULL,\n    sandbox_id text,\n    user_id text NOT NULL,\n    kind text NOT NULL,\n    ts timestamp with time zone DEFAULT now() NOT NULL,\n    data jsonb DEFAULT '{}'::jsonb NOT NULL,\n    CONSTRAINT sandbox_events_data_check CHECK ((pg_column_size(data) <= 8192)),\n    CONSTRAINT sandbox_events_event_id_check CHECK ((event_id ~ '^evt_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_sandbox_id_check CHECK ((sandbox_id ~ '^sbx_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_user_id_check CHECK ((user_id ~ '^usr_[0-9A-Za-z]{20,40}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.sandbox_events_2026_08 (\n    event_id text NOT NULL,\n    sandbox_id text,\n    user_id text NOT NULL,\n    kind text NOT NULL,\n    ts timestamp with time zone DEFAULT now() NOT NULL,\n    data jsonb DEFAULT '{}'::jsonb NOT NULL,\n    CONSTRAINT sandbox_events_data_check CHECK ((pg_column_size(data) <= 8192)),\n    CONSTRAINT sandbox_events_event_id_check CHECK ((event_id ~ '^evt_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_sandbox_id_check CHECK ((sandbox_id ~ '^sbx_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_user_id_check CHECK ((user_id ~ '^usr_[0-9A-Za-z]{20,40}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.sandbox_events_2026_09 (\n    event_id text NOT NULL,\n    sandbox_id text,\n    user_id text NOT NULL,\n    kind text NOT NULL,\n    ts timestamp with time zone DEFAULT now() NOT NULL,\n    data jsonb DEFAULT '{}'::jsonb NOT NULL,\n    CONSTRAINT sandbox_events_data_check CHECK ((pg_column_size(data) <= 8192)),\n    CONSTRAINT sandbox_events_event_id_check CHECK ((event_id ~ '^evt_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_sandbox_id_check CHECK ((sandbox_id ~ '^sbx_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_user_id_check CHECK ((user_id ~ '^usr_[0-9A-Za-z]{20,40}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.sandbox_events_2026_10 (\n    event_id text NOT NULL,\n    sandbox_id text,\n    user_id text NOT NULL,\n    kind text NOT NULL,\n    ts timestamp with time zone DEFAULT now() NOT NULL,\n    data jsonb DEFAULT '{}'::jsonb NOT NULL,\n    CONSTRAINT sandbox_events_data_check CHECK ((pg_column_size(data) <= 8192)),\n    CONSTRAINT sandbox_events_event_id_check CHECK ((event_id ~ '^evt_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_sandbox_id_check CHECK ((sandbox_id ~ '^sbx_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_user_id_check CHECK ((user_id ~ '^usr_[0-9A-Za-z]{20,40}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.sandbox_events_default (\n    event_id text NOT NULL,\n    sandbox_id text,\n    user_id text NOT NULL,\n    kind text NOT NULL,\n    ts timestamp with time zone DEFAULT now() NOT NULL,\n    data jsonb DEFAULT '{}'::jsonb NOT NULL,\n    CONSTRAINT sandbox_events_data_check CHECK ((pg_column_size(data) <= 8192)),\n    CONSTRAINT sandbox_events_event_id_check CHECK ((event_id ~ '^evt_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_sandbox_id_check CHECK ((sandbox_id ~ '^sbx_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandbox_events_user_id_check CHECK ((user_id ~ '^usr_[0-9A-Za-z]{20,40}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.sandboxes (\n    sandbox_id text NOT NULL,\n    user_id text NOT NULL,\n    project_id text NOT NULL,\n    backend text NOT NULL,\n    vm_index integer,\n    agent_url text,\n    host_id text NOT NULL,\n    generation bigint DEFAULT 0 NOT NULL,\n    status text DEFAULT 'starting'::text NOT NULL,\n    key_fp text NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    started_at timestamp with time zone,\n    stopped_at timestamp with time zone,\n    last_used_at timestamp with time zone DEFAULT now() NOT NULL,\n    deleted_at timestamp with time zone,\n    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,\n    snapshot_artifact_path text,\n    snapshot_taken_at timestamp with time zone,\n    snapshot_ch_version text,\n    snapshot_sha256 bytea,\n    snapshot_aead_dek_id text,\n    snapshot_backing_versions jsonb,\n    snapshot_vm_index smallint,\n    lessee_updated_at timestamp with time zone,\n    last_running_worker_id text,\n    idle_snapshot_opted_in boolean DEFAULT false NOT NULL,\n    idle_snapshot_count_long_poll boolean DEFAULT false NOT NULL,\n    last_drain_failure_at timestamp with time zone,\n    drain_failure_count integer DEFAULT 0 NOT NULL,\n    CONSTRAINT sandboxes_backend_check CHECK ((backend = ANY (ARRAY['docker'::text, 'k8s'::text, 'nomad-ch'::text]))),\n    CONSTRAINT sandboxes_generation_check CHECK ((generation >= 0)),\n    CONSTRAINT sandboxes_key_fp_check CHECK ((key_fp ~ '^[0-9a-f]{32}$'::text)),\n    CONSTRAINT sandboxes_project_id_check CHECK ((project_id ~ '^prj_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandboxes_sandbox_id_check CHECK ((sandbox_id ~ '^sbx_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT sandboxes_snapshot_artifact_consistency CHECK (((status <> ALL (ARRAY['snapshotted'::text, 'snapshotted_suspect'::text])) OR ((snapshot_artifact_path IS NOT NULL) AND (snapshot_sha256 IS NOT NULL) AND (snapshot_ch_version IS NOT NULL)))),\n    CONSTRAINT sandboxes_status_check CHECK ((status = ANY (ARRAY['starting'::text, 'running'::text, 'stopping'::text, 'stopped'::text, 'lost'::text, 'recreating'::text, 'orphan'::text, 'unreachable'::text, 'snapshotting'::text, 'snapshotted'::text, 'snapshotting_aborted'::text, 'snapshotted_suspect'::text, 'restoring'::text, 'restoring_cold'::text]))),\n    CONSTRAINT sandboxes_user_id_check CHECK ((user_id ~ '^usr_[0-9A-Za-z]{20,40}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.shares (\n    token_id text NOT NULL,\n    sandbox_id text NOT NULL,\n    port integer NOT NULL,\n    scope text NOT NULL,\n    secret_version integer NOT NULL,\n    issued_at timestamp with time zone DEFAULT now() NOT NULL,\n    expires_at timestamp with time zone NOT NULL,\n    revoked_at timestamp with time zone,\n    use_count bigint DEFAULT 0 NOT NULL,\n    last_used_at timestamp with time zone,\n    iss text,\n    deleted_at timestamp with time zone,\n    CONSTRAINT shares_check CHECK ((expires_at > issued_at)),\n    CONSTRAINT shares_check1 CHECK (((revoked_at IS NULL) OR (revoked_at >= issued_at))),\n    CONSTRAINT shares_iss_check CHECK (((iss IS NULL) OR (iss ~ '^usr_[0-9A-Za-z]{20,40}$'::text))),\n    CONSTRAINT shares_port_check CHECK (((port >= 1) AND (port <= 65535))),\n    CONSTRAINT shares_scope_check CHECK ((scope = ANY (ARRAY['ro'::text, 'rw'::text]))),\n    CONSTRAINT shares_secret_version_check CHECK ((secret_version >= 1)),\n    CONSTRAINT shares_token_id_check CHECK ((token_id ~ '^tok_[A-Za-z0-9_-]{20,40}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.wake_jobs (\n    wake_id text NOT NULL,\n    sandbox_id text NOT NULL,\n    state text NOT NULL,\n    error_code text,\n    error_message text,\n    started_at timestamp with time zone DEFAULT now() NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL,\n    ready_at timestamp with time zone,\n    agent_url text,\n    lessee text NOT NULL,\n    lessee_updated_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT wake_jobs_agent_url_chk CHECK (((agent_url IS NULL) OR (agent_url ~ '^https?://[a-zA-Z0-9._:/-]+$'::text))),\n    CONSTRAINT wake_jobs_error_code_check CHECK (((error_code IS NULL) OR (error_code = ANY (ARRAY['slot_unavailable'::text, 'source_teardown_timeout'::text, 'restore_failed'::text, 'livez_timeout'::text, 'clock_resync_failed'::text, 'register_failed'::text, 'internal'::text, 'wake_worker_aborted'::text, 'staging_path_missing'::text, 'agent_version_mismatch'::text])))),\n    CONSTRAINT wake_jobs_sandbox_id_check CHECK ((sandbox_id ~ '^sbx_[0-9A-Za-z]{20,40}$'::text)),\n    CONSTRAINT wake_jobs_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'reserving_slot'::text, 'restoring'::text, 'livez_polling'::text, 'clock_resyncing'::text, 'registering'::text, 'ok'::text, 'failed'::text])))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add a structural operation for this exact platform DDL fragment
  raw({ sql: "ALTER TABLE ONLY zeroship.sandbox_events ATTACH PARTITION zeroship.sandbox_events_2026_05 FOR VALUES FROM ('2026-05-01 00:00:00+00') TO ('2026-06-01 00:00:00+00')", reason: "this platform DDL object has no exact structural operation in the current v2 surface" });
  // TODO(dsl-v2): add a structural operation for this exact platform DDL fragment
  raw({ sql: "ALTER TABLE ONLY zeroship.sandbox_events ATTACH PARTITION zeroship.sandbox_events_2026_06 FOR VALUES FROM ('2026-06-01 00:00:00+00') TO ('2026-07-01 00:00:00+00')", reason: "this platform DDL object has no exact structural operation in the current v2 surface" });
  // TODO(dsl-v2): add a structural operation for this exact platform DDL fragment
  raw({ sql: "ALTER TABLE ONLY zeroship.sandbox_events ATTACH PARTITION zeroship.sandbox_events_2026_07 FOR VALUES FROM ('2026-07-01 00:00:00+00') TO ('2026-08-01 00:00:00+00')", reason: "this platform DDL object has no exact structural operation in the current v2 surface" });
  // TODO(dsl-v2): add a structural operation for this exact platform DDL fragment
  raw({ sql: "ALTER TABLE ONLY zeroship.sandbox_events ATTACH PARTITION zeroship.sandbox_events_2026_08 FOR VALUES FROM ('2026-08-01 00:00:00+00') TO ('2026-09-01 00:00:00+00')", reason: "this platform DDL object has no exact structural operation in the current v2 surface" });
  // TODO(dsl-v2): add a structural operation for this exact platform DDL fragment
  raw({ sql: "ALTER TABLE ONLY zeroship.sandbox_events ATTACH PARTITION zeroship.sandbox_events_2026_09 FOR VALUES FROM ('2026-09-01 00:00:00+00') TO ('2026-10-01 00:00:00+00')", reason: "this platform DDL object has no exact structural operation in the current v2 surface" });
  // TODO(dsl-v2): add a structural operation for this exact platform DDL fragment
  raw({ sql: "ALTER TABLE ONLY zeroship.sandbox_events ATTACH PARTITION zeroship.sandbox_events_2026_10 FOR VALUES FROM ('2026-10-01 00:00:00+00') TO ('2026-11-01 00:00:00+00')", reason: "this platform DDL object has no exact structural operation in the current v2 surface" });
  // TODO(dsl-v2): add a structural operation for this exact platform DDL fragment
  raw({ sql: "ALTER TABLE ONLY zeroship.sandbox_events ATTACH PARTITION zeroship.sandbox_events_default DEFAULT", reason: "this platform DDL object has no exact structural operation in the current v2 surface" });
}

export function down() {

}
