import { raw } from "@zeroship/migrate/pg";

export const name = "billing_metering_invoice_tables";

export function up() {
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.app_spend_limit (\n    app_id uuid NOT NULL,\n    spend_limit_cents bigint,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT app_spend_limit_spend_limit_cents_check CHECK (((spend_limit_cents IS NULL) OR (spend_limit_cents >= 0)))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.app_spend_state (\n    app_id uuid NOT NULL,\n    state zeroship.spend_state DEFAULT 'allow'::text NOT NULL,\n    spend_cents bigint DEFAULT 0 NOT NULL,\n    eval_limit_cents bigint DEFAULT 0 NOT NULL,\n    period zeroship.billing_period NOT NULL,\n    evaluated_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT app_spend_state_eval_limit_cents_check CHECK ((eval_limit_cents >= 0)),\n    CONSTRAINT app_spend_state_spend_cents_check CHECK ((spend_cents >= 0))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.billing_customer_refs (\n    creator_id uuid NOT NULL,\n    provider text NOT NULL,\n    external_id text NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.billing_disputes (\n    id text NOT NULL,\n    invoice_id text NOT NULL,\n    amount_cents bigint NOT NULL,\n    currency character(3) DEFAULT 'usd'::bpchar NOT NULL,\n    status zeroship.dispute_status DEFAULT 'open'::text NOT NULL,\n    reason text,\n    evidence_due_at timestamp with time zone,\n    provider_dispute_id text NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    resolved_at timestamp with time zone,\n    CONSTRAINT billing_disputes_amount_cents_check CHECK ((amount_cents > 0)),\n    CONSTRAINT billing_disputes_currency_check CHECK ((currency ~ '^[a-z]{3}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.billing_line_provider_refs (\n    invoice_id text NOT NULL,\n    app_id uuid NOT NULL,\n    provider text NOT NULL,\n    ref_kind text NOT NULL,\n    external_id text NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    segment_no smallint DEFAULT 0 NOT NULL,\n    CONSTRAINT billing_line_provider_refs_segment_no_check CHECK ((segment_no >= 0))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.billing_metrics (\n    metric text NOT NULL,\n    kind zeroship.metric_kind NOT NULL,\n    unit text NOT NULL,\n    archived boolean DEFAULT false NOT NULL,\n    last_seen_at timestamp with time zone,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    owner_app uuid\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.billing_notifications (\n    creator_id uuid NOT NULL,\n    kind zeroship.billing_notification_kind NOT NULL,\n    transition_id text NOT NULL,\n    status zeroship.notification_status DEFAULT 'pending'::text NOT NULL,\n    claimed_at timestamp with time zone DEFAULT now() NOT NULL,\n    sent_at timestamp with time zone\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.billing_provider_refs (\n    invoice_id text NOT NULL,\n    provider text NOT NULL,\n    ref_kind text NOT NULL,\n    external_id text NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.billing_reconciliation_findings (\n    id text NOT NULL,\n    kind zeroship.reconciliation_finding_kind NOT NULL,\n    severity zeroship.reconciliation_finding_severity DEFAULT 'medium'::text NOT NULL,\n    entity_id text NOT NULL,\n    our_value jsonb,\n    stripe_value jsonb,\n    dedup_key text NOT NULL,\n    detected_at timestamp with time zone DEFAULT now() NOT NULL,\n    resolved_at timestamp with time zone\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.connect_checkout_failures (\n    id text NOT NULL,\n    creator_id uuid NOT NULL,\n    provider_payment_intent_id text NOT NULL,\n    stripe_account_id text NOT NULL,\n    amount_cents bigint NOT NULL,\n    currency character(3) DEFAULT 'usd'::bpchar NOT NULL,\n    failure_code text,\n    failure_message text,\n    occurred_at timestamp with time zone NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT connect_checkout_failures_amount_cents_check CHECK ((amount_cents >= 0)),\n    CONSTRAINT connect_checkout_failures_currency_check CHECK ((currency ~ '^[a-z]{3}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.creator_billing (\n    creator_id uuid NOT NULL,\n    default_pm_set boolean DEFAULT false NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.creator_billing_status (\n    creator_id uuid NOT NULL,\n    state zeroship.account_state DEFAULT 'active'::text NOT NULL,\n    past_due_since timestamp with time zone,\n    suspended_at timestamp with time zone,\n    last_payment_failure_at timestamp with time zone,\n    failed_invoice_id text,\n    last_event_at timestamp with time zone,\n    last_recovered_at timestamp with time zone,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.creator_billing_status_history (\n    id text NOT NULL,\n    creator_id uuid NOT NULL,\n    from_state zeroship.account_state NOT NULL,\n    to_state zeroship.account_state NOT NULL,\n    reason text,\n    at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.creator_fee_policy (\n    creator_id uuid NOT NULL,\n    kind text NOT NULL,\n    amount_cents bigint,\n    percent_bps integer,\n    cap_cents bigint,\n    floor_cents bigint,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT creator_fee_policy_cap_nonneg CHECK (((cap_cents IS NULL) OR (cap_cents >= 0))),\n    CONSTRAINT creator_fee_policy_floor_le_cap CHECK (((floor_cents IS NULL) OR (cap_cents IS NULL) OR (floor_cents <= cap_cents))),\n    CONSTRAINT creator_fee_policy_floor_nonneg CHECK (((floor_cents IS NULL) OR (floor_cents >= 0))),\n    CONSTRAINT creator_fee_policy_kind_check CHECK ((kind = ANY (ARRAY['fixed'::text, 'percent'::text]))),\n    CONSTRAINT creator_fee_policy_shape CHECK ((((kind = 'fixed'::text) AND (amount_cents IS NOT NULL) AND (amount_cents >= 0)) OR ((kind = 'percent'::text) AND (percent_bps IS NOT NULL) AND ((percent_bps >= 0) AND (percent_bps <= 10000)))))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.credit_ledger (\n    id text NOT NULL,\n    creator_id uuid NOT NULL,\n    kind zeroship.credit_entry_kind NOT NULL,\n    amount_cents bigint NOT NULL,\n    currency character(3) DEFAULT 'usd'::bpchar NOT NULL,\n    applied_invoice_id text,\n    consumed_from_grant_id text,\n    expires_at timestamp with time zone,\n    note text,\n    idempotency_key text,\n    request_fingerprint text,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT credit_ledger_amount_cents_check CHECK ((amount_cents <> 0)),\n    CONSTRAINT credit_ledger_currency_check CHECK ((currency ~ '^[a-z]{3}$'::text)),\n    CONSTRAINT credit_ledger_grant_ref CHECK (((((kind)::text = ANY (ARRAY['consumed'::text, 'void_reversal'::text, 'refund_clawback'::text])) AND (consumed_from_grant_id IS NOT NULL)) OR (((kind)::text <> ALL (ARRAY['consumed'::text, 'void_reversal'::text, 'refund_clawback'::text])) AND (consumed_from_grant_id IS NULL)))),\n    CONSTRAINT credit_ledger_kind_sign CHECK (((((kind)::text = ANY (ARRAY['consumed'::text, 'refund_clawback'::text])) AND (amount_cents < 0)) OR (((kind)::text <> ALL (ARRAY['consumed'::text, 'refund_clawback'::text])) AND (amount_cents > 0))))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.invoice_lines (\n    invoice_id text NOT NULL,\n    app_id uuid NOT NULL,\n    included_units bigint NOT NULL,\n    fx_pico_cents_per_unit bigint NOT NULL,\n    base_fee_cents bigint DEFAULT 0 NOT NULL,\n    amount_cents bigint NOT NULL,\n    usage_snapshot jsonb NOT NULL,\n    weights_snapshot jsonb NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    segment_no smallint DEFAULT 0 NOT NULL,\n    plan_id text NOT NULL,\n    CONSTRAINT invoice_lines_amount_cents_check CHECK ((amount_cents >= 0)),\n    CONSTRAINT invoice_lines_base_fee_cents_check CHECK ((base_fee_cents >= 0)),\n    CONSTRAINT invoice_lines_fx_pico_cents_per_unit_check CHECK ((fx_pico_cents_per_unit >= 1000)),\n    CONSTRAINT invoice_lines_included_units_check CHECK ((included_units >= 0)),\n    CONSTRAINT invoice_lines_segment_no_check CHECK ((segment_no >= 0))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.invoice_payments (\n    id text NOT NULL,\n    invoice_id text NOT NULL,\n    amount_cents bigint NOT NULL,\n    currency character(3) DEFAULT 'usd'::bpchar NOT NULL,\n    kind zeroship.invoice_payment_kind NOT NULL,\n    provider_ref text,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT invoice_payments_amount_cents_check CHECK ((amount_cents <> 0)),\n    CONSTRAINT invoice_payments_currency_check CHECK ((currency ~ '^[a-z]{3}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.invoices (\n    id text NOT NULL,\n    creator_id uuid NOT NULL,\n    period zeroship.billing_period NOT NULL,\n    status zeroship.invoice_status DEFAULT 'draft'::text NOT NULL,\n    currency character(3) DEFAULT 'usd'::bpchar NOT NULL,\n    subtotal_cents bigint DEFAULT 0 NOT NULL,\n    credit_cents bigint DEFAULT 0 NOT NULL,\n    tax_cents bigint DEFAULT 0 NOT NULL,\n    total_cents bigint DEFAULT 0 NOT NULL,\n    finalized_at timestamp with time zone,\n    voided_at timestamp with time zone,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT invoice_total_balances CHECK ((total_cents = ((subtotal_cents - credit_cents) + tax_cents))),\n    CONSTRAINT invoices_credit_cents_check CHECK ((credit_cents >= 0)),\n    CONSTRAINT invoices_currency_check CHECK ((currency ~ '^[a-z]{3}$'::text)),\n    CONSTRAINT invoices_subtotal_cents_check CHECK ((subtotal_cents >= 0)),\n    CONSTRAINT invoices_tax_cents_check CHECK ((tax_cents >= 0)),\n    CONSTRAINT invoices_total_cents_check CHECK ((total_cents >= 0))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.metering_exports (\n    creator_id uuid NOT NULL,\n    period zeroship.billing_period NOT NULL,\n    exported_units bigint DEFAULT 0 NOT NULL,\n    consecutive_failures integer DEFAULT 0 NOT NULL,\n    last_error text,\n    last_attempt_at timestamp with time zone,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT metering_exports_consecutive_failures_check CHECK ((consecutive_failures >= 0)),\n    CONSTRAINT metering_exports_exported_units_check CHECK ((exported_units >= 0))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.metric_weights (\n    metric text NOT NULL,\n    units_per_op bigint NOT NULL,\n    per_units bigint NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT metric_weights_per_units_check CHECK ((per_units > 0)),\n    CONSTRAINT metric_weights_units_per_op_check CHECK ((units_per_op >= 0))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.payout_failures (\n    id text NOT NULL,\n    creator_id uuid NOT NULL,\n    provider_payout_id text NOT NULL,\n    stripe_account_id text NOT NULL,\n    amount_cents bigint NOT NULL,\n    currency character(3) DEFAULT 'usd'::bpchar NOT NULL,\n    failure_code text,\n    failure_message text,\n    occurred_at timestamp with time zone NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT payout_failures_amount_cents_check CHECK ((amount_cents >= 0)),\n    CONSTRAINT payout_failures_currency_check CHECK ((currency ~ '^[a-z]{3}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.pending_disputes (\n    provider_dispute_id text NOT NULL,\n    payment_intent text,\n    charge text,\n    amount_cents bigint NOT NULL,\n    currency character(3) DEFAULT 'usd'::bpchar NOT NULL,\n    reason text,\n    evidence_due_at timestamp with time zone,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT pending_disputes_amount_cents_check CHECK ((amount_cents > 0)),\n    CONSTRAINT pending_disputes_check CHECK (((payment_intent IS NOT NULL) OR (charge IS NOT NULL))),\n    CONSTRAINT pending_disputes_currency_check CHECK ((currency ~ '^[a-z]{3}$'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.plan_change_events (\n    id text NOT NULL,\n    app_id uuid NOT NULL,\n    period zeroship.billing_period NOT NULL,\n    from_plan_id text,\n    to_plan_id text NOT NULL,\n    effective_at timestamp with time zone DEFAULT now() NOT NULL,\n    usage_at_change jsonb DEFAULT '{}'::jsonb NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.plans (\n    id text NOT NULL,\n    name text NOT NULL,\n    base_fee_cents bigint DEFAULT 0 NOT NULL,\n    included_units bigint DEFAULT 0 NOT NULL,\n    fx_pico_cents_per_unit bigint,\n    spend_limit_default_cents bigint DEFAULT 0 NOT NULL,\n    assignable_by_creator boolean DEFAULT false NOT NULL,\n    runtime_limits_json jsonb NOT NULL,\n    archived boolean DEFAULT false NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL,\n    net_policy_limits_json jsonb DEFAULT '{\"max_sockets\": 4, \"egress_ceiling_bytes\": 10485760}'::jsonb NOT NULL,\n    CONSTRAINT plans_base_fee_cents_check CHECK ((base_fee_cents >= 0)),\n    CONSTRAINT plans_fx_pico_cents_per_unit_check CHECK (((fx_pico_cents_per_unit IS NULL) OR (fx_pico_cents_per_unit >= 1000))),\n    CONSTRAINT plans_included_units_check CHECK ((included_units >= 0)),\n    CONSTRAINT plans_spend_limit_default_cents_check CHECK ((spend_limit_default_cents >= 0))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.pricing_config (\n    id text DEFAULT 'global'::text NOT NULL,\n    fx_pico_cents_per_unit bigint NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT pricing_config_fx_pico_cents_per_unit_check CHECK ((fx_pico_cents_per_unit >= 1000)),\n    CONSTRAINT pricing_config_id_check CHECK ((id = 'global'::text))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.refund_provider_refs (\n    refund_id text NOT NULL,\n    provider text NOT NULL,\n    ref_kind text NOT NULL,\n    external_id text NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.refunds (\n    id text NOT NULL,\n    invoice_id text NOT NULL,\n    amount_cents bigint NOT NULL,\n    subtotal_cents bigint NOT NULL,\n    tax_cents bigint DEFAULT 0 NOT NULL,\n    currency character(3) DEFAULT 'usd'::bpchar NOT NULL,\n    destination zeroship.refund_destination NOT NULL,\n    reason text,\n    idempotency_key text NOT NULL,\n    request_fingerprint text NOT NULL,\n    status zeroship.refund_status DEFAULT 'pending'::text NOT NULL,\n    created_at timestamp with time zone DEFAULT now() NOT NULL,\n    issued_at timestamp with time zone,\n    failed_at timestamp with time zone,\n    CONSTRAINT refund_amount_split CHECK ((amount_cents = (subtotal_cents + tax_cents))),\n    CONSTRAINT refunds_amount_cents_check CHECK ((amount_cents > 0)),\n    CONSTRAINT refunds_currency_check CHECK ((currency ~ '^[a-z]{3}$'::text)),\n    CONSTRAINT refunds_subtotal_cents_check CHECK ((subtotal_cents >= 0)),\n    CONSTRAINT refunds_tax_cents_check CHECK ((tax_cents >= 0))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.spend_state_history (\n    id text NOT NULL,\n    app_id uuid NOT NULL,\n    period zeroship.billing_period NOT NULL,\n    from_state zeroship.spend_state NOT NULL,\n    to_state zeroship.spend_state NOT NULL,\n    spend_cents bigint NOT NULL,\n    limit_cents bigint,\n    at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT spend_state_history_limit_cents_check CHECK (((limit_cents IS NULL) OR (limit_cents >= 0))),\n    CONSTRAINT spend_state_history_spend_cents_check CHECK ((spend_cents >= 0))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.stripe_events_seen (\n    event_id text NOT NULL,\n    event_type text NOT NULL,\n    seen_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.usage_aggregates (\n    app_id uuid NOT NULL,\n    period zeroship.billing_period NOT NULL,\n    metric text NOT NULL,\n    total bigint DEFAULT 0 NOT NULL,\n    updated_at timestamp with time zone DEFAULT now() NOT NULL,\n    CONSTRAINT usage_aggregates_total_check CHECK ((total >= 0))\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
  // TODO(dsl-v2): add an exact/platform table creation mode that does not inject app runtime system fields or the synthetic id primary key
  raw({ sql: "CREATE TABLE zeroship.usage_reports_seen (\n    worker_id text NOT NULL,\n    sequence bigint NOT NULL,\n    period zeroship.billing_period,\n    seen_at timestamp with time zone DEFAULT now() NOT NULL\n)", reason: "table().create currently routes through the app collection snapshot and injects runtime system fields, so it cannot reproduce an exact platform table" });
}

export function down() {

}
