// Addon loader — resolve + load the prebuilt N-API `.node` from
// `crates/zero-migrate-node` and type its exposed surface.
//
// The addon is the V8-free Rust core (`host-pg` + bundled rusqlite, no compio, no
// io_uring, cross-platform). It exposes:
//  - sync, DB-free: `irVersion()`, `loadVerify(...)`
//  - async, host-driven (fire-and-resolve over a `hostDriver` TSFN): `applyIr(...)`,
//    `apply(...)`, `status(...)`, `history(...)`
//
// The host-driver callback contract is `hostDriver([request, done]) => void` —
// napi delivers `(request, done)` as a SINGLE array arg. See `driver-pg.ts`.

import { createRequire } from "node:module";

// The addon's wire DTOs + verb signatures are GENERATED by napi-rs from the Rust
// `#[napi]` source (`crates/zero-migrate-node/src/wire.rs` + `bridge.rs`) into
// `crates/zero-migrate-node/index.d.ts` — the SINGLE source of truth. We import
// them here (a type-only import — no runtime dependency on the crate;
// the `.node` is still loaded via `createRequire`) and re-export the driver cell DTOs
// so `driver-pg.ts`/`driver-mysql2.ts` consume them instead of hand-copying.
import type {
  JsCell as GenJsCell,
  JsRow as GenJsRow,
  JsRequest as GenJsRequest,
  JsReply as GenJsReply,
  JsError as GenJsError,
  ApplyIrSqliteRequest,
  ApplyRequest,
  StatusRequest,
  StatusIrRequest,
  ResolvePendingRequest,
  RollbackRequest,
  RollbackTargetDto,
  HistoryRequest,
  ApplyReply,
  RollbackReply,
  StatusReply,
  HistoryReply,
  LoadVerifyReply,
  PreviewSqlSource,
  BuildInfo,
} from "zero-migrate-node";

export type {
  ApplyIrSqliteRequest,
  ApplyRequest,
  StatusRequest,
  StatusIrRequest,
  ResolvePendingRequest,
  RollbackRequest,
  RollbackTargetDto,
  HistoryRequest,
  ApplyReply,
  RollbackReply,
  StatusReply,
  HistoryReply,
  LoadVerifyReply,
  PreviewSqlSource,
};

/** The neutral driver cell DTOs — the single source of truth from the generated
 *  addon `index.d.ts`. Re-exported so the host drivers import (not re-declare) them. */
export type JsCell = GenJsCell;
export type JsRow = GenJsRow;
export type JsRequest = GenJsRequest;
export type JsReply = GenJsReply;
export type JsError = GenJsError;

/** The `hostDriver([request, done]) => void` callback the async entrypoints drive.
 *  Shaped exactly by the generated `JsRequest`/`JsReply`/`JsError` DTOs. */
export type AddonHostDriver = (
  args: [request: JsRequest, done: (err: JsError | null, reply: JsReply | null) => void],
) => void;

/** The addon's exposed surface — the TYPED verb boundary: every
 *  verb takes + returns a generated `#[napi(object)]` DTO, NO JSON strings. */
export interface MigrateAddon {
  /** The IR-format version this addon was built against — the single source of
   *  truth across the boundary. */
  irVersion(): number;

  /** The identity of the loaded binary: crate version, IR floor, and a sha256 over
   *  the workspace source it was built from. `irVersion()` answers the format floor
   *  alone; this answers WHICH artifact is in memory, which is what a stale prebuilt
   *  `.node` gets wrong while every other call still succeeds. */
  buildInfo(): BuildInfo;

  /** Sync, DB-free load + verify of an IR envelope document. Returns a typed
   *  `LoadVerifyReply` (`registry` crosses typed, not a JSON string). */
  loadVerify(
    envelopeJson: string,
    deployingApp: string,
    dialect: string,
    registry: Record<string, string>,
    projectSchema: string,
  ): LoadVerifyReply;

  /** Sync, DB-free rendering of authored IR envelope JSON for operator review. */
  previewSql(source: PreviewSqlSource): string[];

  /** HOST-AUTHORING apply: take a typed `ApplyRequest` (the IR envelope
   *  as a JS value), LOWER it in Rust (stamp `owner_app` + fold
   *  `Checksum::of_ir`), then drive `executor::apply` over the host driver. Resolves
   *  to a typed `ApplyReply`. */
  applyIr(hostDriver: AddonHostDriver, req: ApplyRequest): Promise<ApplyReply>;

  /** SQLite apply through the addon's bundled in-process rusqlite backend. */
  applyIrSqlite(
    appPath: string,
    journalPath: string,
    req: ApplyIrSqliteRequest,
  ): Promise<ApplyReply>;

  /** `status` over the host driver. Resolves to a typed `StatusReply`. */
  status(hostDriver: AddonHostDriver, req: StatusRequest): Promise<StatusReply>;

  /** Plan-aware status over authored IR envelopes. The addon lowers complete
   *  plans in Rust, retaining DML and backfill step identities. */
  statusIr(hostDriver: AddonHostDriver, req: StatusIrRequest): Promise<StatusReply>;

  /** Read-only plan-aware status through the bundled in-process SQLite backend. */
  statusIrSqlite(
    appPath: string,
    journalPath: string,
    req: StatusIrRequest,
  ): Promise<StatusReply>;

  /** Unwind applied migrations over the host driver, reconstructing each `down`
   *  from its authored envelope. Resolves to a typed `RollbackReply`. */
  rollback(hostDriver: AddonHostDriver, req: RollbackRequest): Promise<RollbackReply>;

  /** Rollback through the addon's bundled in-process rusqlite backend. */
  rollbackSqlite(
    appPath: string,
    journalPath: string,
    req: RollbackRequest,
  ): Promise<RollbackReply>;

  /** Complete or abort one outstanding PostgreSQL online rename. */
  resolvePending(
    hostDriver: AddonHostDriver,
    req: ResolvePendingRequest,
  ): Promise<ApplyReply>;

  /** `history` over the host driver. Resolves to a typed `HistoryReply`. */
  history(hostDriver: AddonHostDriver, req: HistoryRequest): Promise<HistoryReply>;
}

let cached: MigrateAddon | null = null;

/**
 * Load the native addon. Resolution order:
 *  1. `ZERO_MIGRATE_ADDON_PATH` env override: an explicit `.node` path, used in
 *     dev / CI to point at a freshly-`napi build`'d artifact without a publish.
 *  2. the `zero-migrate-node` package: its generated loader (`index.js`) picks the
 *     correct prebuilt binary for `process.platform`/`arch`/libc, whether that is a
 *     sibling `.node` (monorepo dev) or one of the `zero-migrate-node-<triple>`
 *     optionalDependencies (published install).
 *
 * `zero-migrate-node` is a real `dependency` of this package, so the platform
 * resolution and the "npm optional-deps bug" guidance all live in its generated
 * loader; we never re-implement triple math here.
 *
 * @throws if neither the override nor `zero-migrate-node` yields a usable addon.
 */
export function loadAddon(): MigrateAddon {
  if (cached) return cached;
  const require = createRequire(import.meta.url);
  const override = process.env.ZERO_MIGRATE_ADDON_PATH;
  const target = override ?? "zero-migrate-node";
  let mod: MigrateAddon;
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    mod = require(target) as MigrateAddon;
  } catch (e) {
    throw new Error(
      `zero-migrate-cli: could not load the native addon from ${JSON.stringify(target)}: ` +
        `${(e as Error).message}\n` +
        (override
          ? "The ZERO_MIGRATE_ADDON_PATH override does not point at a loadable .node."
          : "Install the platform binary (it ships as an optionalDependency of " +
            "zero-migrate-node), or set ZERO_MIGRATE_ADDON_PATH to a `napi build` output."),
    );
  }
  if (!mod || typeof mod.irVersion !== "function") {
    throw new Error(
      `zero-migrate-cli: the native addon loaded from ${JSON.stringify(target)} is missing ` +
        "irVersion(): it is not a zero-migrate-node build.",
    );
  }
  cached = mod;
  return mod;
}

/** The addon's IR-format version — the single source of truth. */
export function currentIrVersion(): number {
  return loadAddon().irVersion();
}
