#!/usr/bin/env node
//
// Emit the TypeScript view of policies/confined-system-shape.inject.toml.
//
// WHY THIS EXISTS. The confined [[inject]] rule is the shape of every creator
// table on the platform, and it used to be written out by hand in six places.
// Rust consumers now take the fragment directly -
// `concat!(include_str!("<grants>"), include_str!("<fragment>"))` - so for them
// there is nothing to generate and nothing that can drift. TypeScript has no
// include_str!, and `sdks/vite-plugin` is a PUBLISHED package that runs on a
// creator's machine where this repo does not exist, so it cannot read the file
// at runtime either. The bytes have to be carried into a module, and something
// has to put them there.
//
// WHY THE OUTPUT IS COMMITTED rather than gitignored and built. Generating into
// an untracked file would make `tsc`, `tsx` and every editor depend on this
// script having run first. That failure IS loud - measured 2026-08-20, absent
// output gives `error TS2307: Cannot find module './confined-system-shape.
// generated.js'` (tsc exit 2) and `ERR_MODULE_NOT_FOUND` under tsx - but loud is
// not the same as informative: neither message names the step you were supposed
// to run. AGENTS.md spends twenty lines on exactly that shape of error, because
// a loud TS2307 from the zero-migrate-node addon still cost a real deploy twenty
// minutes. Committing the output keeps the build order flat and moves the whole
// question onto a drift check, which is what `schema/codegen.mjs` (the sibling
// generator, project-v1.json -> project-config/generated.ts) already does.
//
// THE DRIFT CHECK is `--check`, run by tests/inject_policy_mirror_gate.sh. It
// regenerates in memory and compares BYTE FOR BYTE, so unlike the text-mirroring
// gate this replaces it also catches a comment or a blank line going stale.
//
// Usage:
//   node policies/codegen.mjs           write the generated file
//   node policies/codegen.mjs --check   exit 1 if it differs from the fragment

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");

const FRAGMENT = join(ROOT, "policies", "confined-system-shape.inject.toml");
const TARGET = join(
  ROOT,
  "sdks",
  "vite-plugin",
  "src",
  "gen-types",
  "confined-system-shape.generated.ts",
);

const fragment = readFileSync(FRAGMENT, "utf8");

// The fragment is embedded as a TEMPLATE LITERAL so the generated file stays
// readable - a committed file gets read, and JSON.stringify would turn the rule
// into one unreadable line. That only works while the fragment contains no
// backtick, no `${` and no backslash, which is also true of the .toml it has to
// remain. Refuse rather than emit something that compiles to different bytes.
for (const [needle, what] of [
  ["`", "a backtick"],
  ["${", "a template-literal substitution"],
  ["\\", "a backslash"],
]) {
  if (fragment.includes(needle)) {
    console.error(
      `policies/codegen.mjs: the fragment contains ${what}, which does not survive\n` +
        "  embedding as a template literal. Reword the comment (the TOML rule itself\n" +
        "  needs none of these characters), or change this script to emit an escaped\n" +
        "  string and accept that the generated file becomes unreadable.",
    );
    process.exit(2);
  }
}

// Anti-vacuity: an empty or truncated read would generate a ceiling that injects
// nothing, and every consumer would still compile.
if (!/^\[\[inject\]\]$/m.test(fragment) || !/^author_primary_key\s*=/m.test(fragment)) {
  console.error(
    `policies/codegen.mjs: ${relative(ROOT, FRAGMENT)} carries no [[inject]] rule.\n` +
      "  Generating from it would emit a ceiling that injects nothing, which every\n" +
      "  consumer would accept in silence.",
  );
  process.exit(2);
}

const source = `/**
 * GENERATED by policies/codegen.mjs from
 * policies/confined-system-shape.inject.toml -- DO NOT EDIT.
 *
 * Regenerate with \`node policies/codegen.mjs\`;
 * \`tests/inject_policy_mirror_gate.sh\` fails when this file drifts from the
 * fragment.
 *
 * This is the TypeScript view of the ONE copy of the platform system-table
 * shape. The Rust consumers (the deployed server ceiling, the dev SQLite
 * ceiling, and the two adapter fixtures) \`include_str!\` the fragment itself and
 * need no generated form. Read the fragment, not this file, for what the rule
 * means and why it is shared.
 */

export const CONFINED_SYSTEM_SHAPE_INJECT_TOML = \`${fragment}\`;
`;

const check = process.argv.includes("--check");
const rel = relative(ROOT, TARGET);

if (!check) {
  writeFileSync(TARGET, source, "utf8");
  console.log(`  wrote   ${rel}`);
  process.exit(0);
}

let committed;
try {
  committed = readFileSync(TARGET, "utf8");
} catch {
  console.error(`  MISSING ${rel}`);
  console.error(
    "policies/codegen.mjs --check: the generated file is absent. Run " +
      "`node policies/codegen.mjs` and commit the result.",
  );
  process.exit(1);
}

if (committed !== source) {
  console.error(`  DRIFT   ${rel}`);
  console.error(
    "policies/codegen.mjs --check: the generated file drifted from " +
      "policies/confined-system-shape.inject.toml. Run `node policies/codegen.mjs` " +
      "and commit the result.",
  );
  process.exit(1);
}

console.log(`  ok      ${rel}`);
