#!/usr/bin/env node
// Embed the migration policy for the published build-time toolchain.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const FRAGMENT = join(ROOT, "policies/confined-system-shape.inject.toml");
const TARGET_TOML = join(ROOT, "packages/vite-plugin/src/gen-types/confined-system-shape.generated.ts");
const fragment = readFileSync(FRAGMENT, "utf8");
if (!/^\[\[inject\]\]$/m.test(fragment) || !/^author_primary_key\s*=/m.test(fragment)
    || ["`", "${", "\\"].some((token) => fragment.includes(token))) {
  throw new Error("policy fragment is missing its rule or cannot be embedded as a template literal");
}

const tomlSource = `/**
 * GENERATED by policies/codegen.mjs from
 * policies/confined-system-shape.inject.toml -- DO NOT EDIT.
 *
 * Regenerate with \`pnpm gen-types\`; \`pnpm gen-types:check\` fails when this
 * file drifts from the fragment.
 *
 * This is the TypeScript view of the authored platform system-table shape.
 * Rust consumers \`include_str!\` the fragment itself and need no generated
 * form. Read the fragment for what the rule means and why it is shared.
 */

export const CONFINED_SYSTEM_SHAPE_INJECT_TOML = \`${fragment}\`;
`;

if (process.argv.includes("--check")) {
  if (readFileSync(TARGET_TOML, "utf8") !== tomlSource) {
    console.error(`DRIFT ${relative(ROOT, TARGET_TOML)}; run node policies/codegen.mjs`);
    process.exit(1);
  }
  console.log(`OK ${relative(ROOT, TARGET_TOML)}`);
} else {
  mkdirSync(dirname(TARGET_TOML), { recursive: true });
  writeFileSync(TARGET_TOML, tomlSource);
}
