import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { isDeepStrictEqual } from "node:util";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";
import { genArtifacts } from "../../zeroship-migrate-node/index.js";
import { buildEnvelope } from "../../../packages/zero-migrate/dist/internal/recorder.js";
import { currentIrVersion, previewSql } from "../../../packages/zero-migrate-cli/dist/index.js";
import { managerIdentityColumns, workflowManagerSchema } from "./schema.ts";

export function compileSchema(schema = workflowManagerSchema) {
  const outputs = [];
  const sqlByDialect = {};
  let runtime;
  for (const dialect of ["postgres", "sqlite"]) {
    const namespace = dialect === "postgres" ? "workflow_manager" : "main";
    const envelope = buildEnvelope({
      name: "workflow_manager",
      schema: () => schema(namespace),
    }, { irVersion: currentIrVersion() });
    if (!envelope.ops.length) throw new Error("workflow manager schema recorder is empty");
    const charter = `policy_version = 1
[[grant]]
key = "schema.create_table"
value = true
scope = { include = ["${namespace}"] }
[[grant]]
key = "schema.cross_schema"
value = true
scope = { include = ["${namespace}"] }
[[grant]]
key = "sql.raw"
value = true
scope = { include = ["${namespace}"] }
`;
    const args = { dialect, projectSchema: namespace, charterLayers: [charter] };
    const artifacts = genArtifacts({ ...args, envelopes: [envelope] });
    if (!artifacts.ok) throw new Error(artifacts.error);
    const descriptor = JSON.parse(artifacts.runtimeJson);
    if (!isDeepStrictEqual(Object.keys(descriptor.collections).sort(), Object.keys(managerIdentityColumns).sort())) {
      throw new Error("workflow manager descriptor has unexpected collections");
    }
    for (const collection of Object.values(descriptor.collections)) {
      const primaryKey = Object.entries(collection.fields)
        .filter(([, field]) => field.primaryKey)
        .map(([name]) => name);
      if (!isDeepStrictEqual(primaryKey, ["id"])) {
        throw new Error("workflow manager tables require id as their sole primary key");
      }
    }
    if (runtime && !isDeepStrictEqual(runtime, descriptor)) {
      throw new Error("workflow manager metadata differs between database dialects");
    }
    runtime = descriptor;
    const statements = previewSql({
      ...args,
      envelopes: [JSON.stringify(envelope)],
      defaultSchema: namespace,
      ownerApp: "workflow_manager",
    });
    const emitted = statements.join("\n");
    if (emitted.includes("[runtime-resolved]")) {
      throw new Error("workflow manager schema must lower completely");
    }
    // Preview annotations are diagnostics; the artifact retains emitted SQL.
    const sql = emitted.split("\n").filter(line => !line.startsWith("--")).join("\n").trim();
    if (!sql) throw new Error("workflow manager schema emitted no SQL");
    sqlByDialect[dialect] = sql;
  }
  const fingerprint = createHash("sha256").update(JSON.stringify(sqlByDialect)).digest("hex");
  for (const [dialect, sql] of Object.entries(sqlByDialect)) {
    const namespace = dialect === "postgres" ? "workflow_manager" : "main";
    outputs.push({
      name: `${dialect}.sql`,
      content: `-- Generated by schema/generate.mjs through the migration compiler.\n${sql}\nINSERT INTO ${namespace}.schema_version (id, fingerprint) VALUES ('manager', '${fingerprint}');\n`,
    });
  }
  outputs.push({ name: "schema.runtime.json", content: JSON.stringify(runtime, null, 2) + "\n" });
  outputs.push({ name: "fingerprint.txt", content: `${fingerprint}\n` });
  outputs.push({ name: "identity-columns.json", content: JSON.stringify(managerIdentityColumns, null, 2) + "\n" });
  return outputs;
}

export async function writeArtifacts(outputs, { directory = new URL("./", import.meta.url), check = false } = {}) {
  if (!outputs.length) throw new Error("workflow manager artifacts are empty");
  for (const { name, content } of outputs) {
    const path = new URL(name, directory);
    if (check) {
      if (await readFile(path, "utf8") !== content) {
        throw new Error(`stale workflow manager schema: ${name}`);
      }
    } else {
      await writeFile(path, content);
    }
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.some(arg => arg !== "--check")) throw new Error("usage: node schema/generate.mjs [--check]");
  // Complete compilation of every dialect before changing generated artifacts.
  await writeArtifacts(compileSchema(), { check: args.includes("--check") });
}
