-- Generated by schema/generate.mjs through the migration compiler.
CREATE TABLE "workflow_manager"."schema_version" ("id" text PRIMARY KEY NOT NULL, "fingerprint" text NOT NULL);

CREATE TABLE "workflow_manager"."queue_scopes" ("id" text PRIMARY KEY NOT NULL, "lock_version" bigint NOT NULL DEFAULT 0);

CREATE TABLE "workflow_manager"."deployment_holds" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "deployment_id" text NOT NULL, "holder_id" text NOT NULL, "deploy_hash" text, "generation" bigint NOT NULL, "state" text NOT NULL, CONSTRAINT "deployment_hold_scope" FOREIGN KEY ("app_id") REFERENCES "workflow_manager"."queue_scopes" (id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "deployment_hold_scope_idx" ON "workflow_manager"."deployment_holds" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "deployment_holds_scope_key" ON "workflow_manager"."deployment_holds" ("app_id", "deployment_id");

CREATE INDEX IF NOT EXISTS "deployment_holds_pending_idx" ON "workflow_manager"."deployment_holds" ("state", "app_id", "deployment_id");

CREATE TABLE "workflow_manager"."workers" ("id" text PRIMARY KEY NOT NULL, "capacity" bigint NOT NULL, "state" text NOT NULL, "expires_at" bigint NOT NULL, "lock_version" bigint NOT NULL DEFAULT 0);

CREATE TABLE "workflow_manager"."assignments" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "worker_id" text NOT NULL, "revision" bigint NOT NULL, "expires_at" bigint NOT NULL, "released" boolean NOT NULL, "wake_revision" bigint, "next_due_at" bigint, CONSTRAINT "assignment_scope" FOREIGN KEY ("app_id") REFERENCES "workflow_manager"."queue_scopes" (id) ON DELETE RESTRICT, CONSTRAINT "assignment_worker" FOREIGN KEY ("worker_id") REFERENCES "workflow_manager"."workers" (id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "assignment_scope_idx" ON "workflow_manager"."assignments" ("app_id");

CREATE INDEX IF NOT EXISTS "assignment_worker_idx" ON "workflow_manager"."assignments" ("worker_id");

CREATE UNIQUE INDEX IF NOT EXISTS "assignments_scope_key" ON "workflow_manager"."assignments" ("app_id", "worker_id");

CREATE INDEX IF NOT EXISTS "assignments_worker_idx" ON "workflow_manager"."assignments" ("worker_id", "app_id");

CREATE INDEX IF NOT EXISTS "assignments_expiry_idx" ON "workflow_manager"."assignments" ("expires_at", "app_id");

CREATE TABLE "workflow_manager"."placement_receipts" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "request_id" text NOT NULL, "operation" text NOT NULL, "worker_id" text NOT NULL, "expected_revision" bigint, "wake_revision" bigint, "result_revision" bigint NOT NULL, "result_expires_at" bigint NOT NULL, CONSTRAINT "receipt_scope" FOREIGN KEY ("app_id") REFERENCES "workflow_manager"."queue_scopes" (id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "receipt_scope_idx" ON "workflow_manager"."placement_receipts" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "placement_receipts_scope_key" ON "workflow_manager"."placement_receipts" ("app_id", "request_id");

CREATE TABLE "workflow_manager"."management" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "request_id" text NOT NULL, "run_id" text NOT NULL, "actor" text NOT NULL, "operation" text NOT NULL, "restart_name" text, "restart_occurrence" bigint, "restart_deploy" text, "created_at" bigint NOT NULL, "outcome" text, "run_state" text, "ack_worker_id" text, "ack_revision" bigint, CONSTRAINT "management_scope" FOREIGN KEY ("app_id") REFERENCES "workflow_manager"."queue_scopes" (id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "management_scope_idx" ON "workflow_manager"."management" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "management_scope_key" ON "workflow_manager"."management" ("app_id", "request_id");

CREATE INDEX IF NOT EXISTS "management_pending_idx" ON "workflow_manager"."management" ("app_id", "outcome", "created_at", "request_id");

CREATE TABLE "workflow_manager"."jobs" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "deployment_id" text NOT NULL, "operation" text NOT NULL, "spec_digest" text NOT NULL, "available_at" bigint NOT NULL, "state" text NOT NULL, "attempt" bigint NOT NULL DEFAULT 0, "worker_id" text, "assignment_revision" bigint, "lease_deadline" bigint, "outcome" text, "settlement_digest" text, "created_at" bigint NOT NULL, CONSTRAINT "jobs_app_id_fkey" FOREIGN KEY ("app_id") REFERENCES "workflow_manager"."queue_scopes" (id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "jobs_app_id_fkey_idx" ON "workflow_manager"."jobs" ("app_id");

CREATE INDEX IF NOT EXISTS "jobs_available_idx" ON "workflow_manager"."jobs" ("app_id", "state", "available_at", "id");

CREATE INDEX IF NOT EXISTS "jobs_lease_idx" ON "workflow_manager"."jobs" ("app_id", "state", "lease_deadline", "id");

CREATE UNIQUE INDEX IF NOT EXISTS "jobs_scope_key" ON "workflow_manager"."jobs" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "jobs_deployment_idx" ON "workflow_manager"."jobs" ("app_id", "deployment_id", "state");

CREATE TABLE "workflow_manager"."schedule_deployments" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "definition" text NOT NULL, "interpretation" text NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "schedule_deployment_scope" FOREIGN KEY ("app_id") REFERENCES "workflow_manager"."queue_scopes" (id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "schedule_deployment_scope_idx" ON "workflow_manager"."schedule_deployments" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_deployments_scope_key" ON "workflow_manager"."schedule_deployments" ("app_id", "id");

CREATE TABLE "workflow_manager"."schedule_activations" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "deployment_id" text NOT NULL, "revision" bigint NOT NULL, "activated_at" bigint NOT NULL, CONSTRAINT "schedule_activation_deploy" FOREIGN KEY ("app_id", "deployment_id") REFERENCES "workflow_manager"."schedule_deployments" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "schedule_activation_job" FOREIGN KEY ("app_id", "id") REFERENCES "workflow_manager"."jobs" ("app_id", id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "schedule_activation_deploy_idx" ON "workflow_manager"."schedule_activations" ("app_id", "deployment_id");

CREATE INDEX IF NOT EXISTS "schedule_activation_job_idx" ON "workflow_manager"."schedule_activations" ("app_id", "id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_activations_scope_key" ON "workflow_manager"."schedule_activations" ("app_id", "revision");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_activations_identity_key" ON "workflow_manager"."schedule_activations" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "schedule_activations_deployment_idx" ON "workflow_manager"."schedule_activations" ("app_id", "deployment_id", "id");

CREATE TABLE "workflow_manager"."schedule_scopes" ("id" text PRIMARY KEY NOT NULL, "revision" bigint NOT NULL, "activation_id" text NOT NULL, CONSTRAINT "schedule_scope_activation" FOREIGN KEY ("id", "activation_id") REFERENCES "workflow_manager"."schedule_activations" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "schedule_scope_app" FOREIGN KEY ("id") REFERENCES "workflow_manager"."queue_scopes" (id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "schedule_scope_activation_idx" ON "workflow_manager"."schedule_scopes" ("id", "activation_id");

CREATE TABLE "workflow_manager"."schedules" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "name" text NOT NULL, "activation_id" text NOT NULL, "revision" bigint NOT NULL, "definition" text NOT NULL, "next_at" bigint, "anchor_at" bigint NOT NULL, "catch_up_until" bigint, "catch_up_remaining" bigint, CONSTRAINT "schedule_activation" FOREIGN KEY ("app_id", "activation_id") REFERENCES "workflow_manager"."schedule_activations" ("app_id", id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "schedule_activation_idx" ON "workflow_manager"."schedules" ("app_id", "activation_id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedules_scope_key" ON "workflow_manager"."schedules" ("app_id", "name");

CREATE UNIQUE INDEX IF NOT EXISTS "schedules_identity_key" ON "workflow_manager"."schedules" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "schedules_due_idx" ON "workflow_manager"."schedules" ("next_at", "id");

CREATE INDEX IF NOT EXISTS "schedules_activation_idx" ON "workflow_manager"."schedules" ("app_id", "activation_id");

CREATE TABLE "workflow_manager"."schedule_occurrences" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "schedule_id" text NOT NULL, "revision" bigint NOT NULL, "scheduled_at" bigint NOT NULL, "run_id" text NOT NULL, "job_id" text NOT NULL, "activation_id" text NOT NULL, CONSTRAINT "occurrence_activation" FOREIGN KEY ("app_id", "activation_id") REFERENCES "workflow_manager"."schedule_activations" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "occurrence_job" FOREIGN KEY ("app_id", "job_id") REFERENCES "workflow_manager"."jobs" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "occurrence_schedule" FOREIGN KEY ("app_id", "schedule_id") REFERENCES "workflow_manager"."schedules" ("app_id", id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "occurrence_activation_idx" ON "workflow_manager"."schedule_occurrences" ("app_id", "activation_id");

CREATE INDEX IF NOT EXISTS "occurrence_job_idx" ON "workflow_manager"."schedule_occurrences" ("app_id", "job_id");

CREATE INDEX IF NOT EXISTS "occurrence_schedule_idx" ON "workflow_manager"."schedule_occurrences" ("app_id", "schedule_id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_occurrences_scope_key" ON "workflow_manager"."schedule_occurrences" ("app_id", "schedule_id", "revision", "scheduled_at");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_occurrences_job_key" ON "workflow_manager"."schedule_occurrences" ("app_id", "job_id");

CREATE TABLE "workflow_manager"."recovery_scopes" ("id" text PRIMARY KEY NOT NULL, "deployment_id" text NOT NULL, "activation_revision" bigint NOT NULL, "next_due_at" bigint NOT NULL, "pending_job_id" text, CONSTRAINT "recovery_job" FOREIGN KEY ("pending_job_id") REFERENCES "workflow_manager"."jobs" (id) ON DELETE RESTRICT, CONSTRAINT "recovery_scope" FOREIGN KEY ("id") REFERENCES "workflow_manager"."queue_scopes" (id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "recovery_job_idx" ON "workflow_manager"."recovery_scopes" ("pending_job_id");

CREATE INDEX IF NOT EXISTS "recovery_scopes_due_idx" ON "workflow_manager"."recovery_scopes" ("next_due_at", "id");

ALTER TABLE "workflow_manager"."schema_version" ALTER COLUMN "id" TYPE text COLLATE "C";

ALTER TABLE "workflow_manager"."queue_scopes" ALTER COLUMN "id" TYPE text COLLATE "C";

ALTER TABLE "workflow_manager"."deployment_holds" ALTER COLUMN "id" TYPE text COLLATE "C", ALTER COLUMN "app_id" TYPE text COLLATE "C", ALTER COLUMN "deployment_id" TYPE text COLLATE "C", ALTER COLUMN "holder_id" TYPE text COLLATE "C";

ALTER TABLE "workflow_manager"."workers" ALTER COLUMN "id" TYPE text COLLATE "C";

ALTER TABLE "workflow_manager"."assignments" ALTER COLUMN "id" TYPE text COLLATE "C", ALTER COLUMN "app_id" TYPE text COLLATE "C", ALTER COLUMN "worker_id" TYPE text COLLATE "C";

ALTER TABLE "workflow_manager"."placement_receipts" ALTER COLUMN "id" TYPE text COLLATE "C", ALTER COLUMN "app_id" TYPE text COLLATE "C", ALTER COLUMN "request_id" TYPE text COLLATE "C", ALTER COLUMN "worker_id" TYPE text COLLATE "C";

ALTER TABLE "workflow_manager"."management" ALTER COLUMN "id" TYPE text COLLATE "C", ALTER COLUMN "app_id" TYPE text COLLATE "C", ALTER COLUMN "request_id" TYPE text COLLATE "C", ALTER COLUMN "run_id" TYPE text COLLATE "C", ALTER COLUMN "ack_worker_id" TYPE text COLLATE "C";

ALTER TABLE "workflow_manager"."jobs" ALTER COLUMN "id" TYPE text COLLATE "C", ALTER COLUMN "app_id" TYPE text COLLATE "C", ALTER COLUMN "deployment_id" TYPE text COLLATE "C", ALTER COLUMN "worker_id" TYPE text COLLATE "C";

ALTER TABLE "workflow_manager"."recovery_scopes" ALTER COLUMN "id" TYPE text COLLATE "C", ALTER COLUMN "deployment_id" TYPE text COLLATE "C", ALTER COLUMN "pending_job_id" TYPE text COLLATE "C";

ALTER TABLE "workflow_manager"."schedule_deployments" ALTER COLUMN "id" TYPE text COLLATE "C", ALTER COLUMN "app_id" TYPE text COLLATE "C";

ALTER TABLE "workflow_manager"."schedule_activations" ALTER COLUMN "id" TYPE text COLLATE "C", ALTER COLUMN "app_id" TYPE text COLLATE "C", ALTER COLUMN "deployment_id" TYPE text COLLATE "C";

ALTER TABLE "workflow_manager"."schedule_scopes" ALTER COLUMN "id" TYPE text COLLATE "C", ALTER COLUMN "activation_id" TYPE text COLLATE "C";

ALTER TABLE "workflow_manager"."schedules" ALTER COLUMN "id" TYPE text COLLATE "C", ALTER COLUMN "app_id" TYPE text COLLATE "C", ALTER COLUMN "name" TYPE text COLLATE "C", ALTER COLUMN "activation_id" TYPE text COLLATE "C";

ALTER TABLE "workflow_manager"."schedule_occurrences" ALTER COLUMN "id" TYPE text COLLATE "C", ALTER COLUMN "app_id" TYPE text COLLATE "C", ALTER COLUMN "schedule_id" TYPE text COLLATE "C", ALTER COLUMN "run_id" TYPE text COLLATE "C", ALTER COLUMN "job_id" TYPE text COLLATE "C", ALTER COLUMN "activation_id" TYPE text COLLATE "C";
INSERT INTO workflow_manager.schema_version (id, fingerprint) VALUES ('manager', '63eb4ec5f38df09a87d698a26555d96fd1696338c8d915e0536e1978e1d3f556');
