-- Generated by schema/generate.mjs through the migration compiler.
CREATE TABLE "workflow_manager"."queue_scopes" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "lock_version" bigint NOT NULL DEFAULT 0);

CREATE UNIQUE INDEX IF NOT EXISTS "queue_scopes_app_id_key" ON "workflow_manager"."queue_scopes" ("app_id");

CREATE TABLE "workflow_manager"."jobs" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "deployment_id" text NOT NULL, "operation" text NOT NULL, "spec_digest" text NOT NULL, "available_at" bigint NOT NULL, "state" text NOT NULL, "attempt" bigint NOT NULL DEFAULT 0, "worker_id" text, "assignment_revision" bigint, "lease_deadline" bigint, "outcome" text, "settlement_digest" text, "created_at" bigint NOT NULL, CONSTRAINT "jobs_app_id_fkey" FOREIGN KEY ("app_id") REFERENCES "workflow_manager"."queue_scopes" ("app_id") ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "jobs_app_id_fkey_idx" ON "workflow_manager"."jobs" ("app_id");

CREATE INDEX IF NOT EXISTS "jobs_available_idx" ON "workflow_manager"."jobs" ("app_id", "state", "available_at", "id");

CREATE INDEX IF NOT EXISTS "jobs_lease_idx" ON "workflow_manager"."jobs" ("app_id", "state", "lease_deadline", "id");

ALTER TABLE "workflow_manager"."queue_scopes" ALTER COLUMN "id" TYPE text COLLATE "C", ALTER COLUMN "app_id" TYPE text COLLATE "C";

ALTER TABLE "workflow_manager"."jobs" ALTER COLUMN "id" TYPE text COLLATE "C", ALTER COLUMN "app_id" TYPE text COLLATE "C", ALTER COLUMN "deployment_id" TYPE text COLLATE "C", ALTER COLUMN "worker_id" TYPE text COLLATE "C";
