-- Generated by schema/generate.mjs through the migration compiler.
CREATE TABLE "schema_version" ("id" TEXT PRIMARY KEY NOT NULL, "fingerprint" TEXT NOT NULL);

CREATE TABLE "queue_scopes" ("id" TEXT PRIMARY KEY NOT NULL, "lock_version" INTEGER NOT NULL DEFAULT 0, "dispatch_cursor" INTEGER NOT NULL DEFAULT 0);

CREATE TABLE "deployment_holds" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "deployment_id" TEXT NOT NULL, "holder_id" TEXT NOT NULL, "deploy_hash" TEXT, "generation" INTEGER NOT NULL, "state" TEXT NOT NULL, "held_at" INTEGER, "journal_state" TEXT NOT NULL DEFAULT 'pending', "journal_job_id" TEXT, "journal_published_at" INTEGER, CONSTRAINT "deployment_hold_scope" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "deployment_hold_scope_idx" ON "deployment_holds" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "deployment_holds_scope_key" ON "deployment_holds" ("app_id", "deployment_id");

CREATE INDEX IF NOT EXISTS "deployment_holds_pending_idx" ON "deployment_holds" ("state", "app_id", "deployment_id");

CREATE INDEX IF NOT EXISTS "deployment_holds_journal_idx" ON "deployment_holds" ("journal_state", "state", "app_id", "deployment_id");

CREATE TABLE "workers" ("id" TEXT PRIMARY KEY NOT NULL, "capacity" INTEGER NOT NULL DEFAULT 1, "state" TEXT NOT NULL DEFAULT 'ready', "expires_at" INTEGER NOT NULL DEFAULT 0, "lock_version" INTEGER NOT NULL DEFAULT 0, "execution_zone_id" TEXT);

CREATE INDEX IF NOT EXISTS "workers_zone_idx" ON "workers" ("execution_zone_id", "state", "expires_at", "id");

CREATE TABLE "assignments" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "worker_id" TEXT NOT NULL, "revision" INTEGER NOT NULL, "expires_at" INTEGER NOT NULL, "released" INTEGER NOT NULL, "refused" INTEGER NOT NULL, CONSTRAINT "assignment_scope" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT, CONSTRAINT "assignment_worker" FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "assignment_scope_idx" ON "assignments" ("app_id");

CREATE INDEX IF NOT EXISTS "assignment_worker_idx" ON "assignments" ("worker_id");

CREATE UNIQUE INDEX IF NOT EXISTS "assignments_scope_key" ON "assignments" ("app_id", "worker_id");

CREATE INDEX IF NOT EXISTS "assignments_worker_idx" ON "assignments" ("worker_id", "app_id");

CREATE INDEX IF NOT EXISTS "assignments_expiry_idx" ON "assignments" ("expires_at", "app_id");

CREATE TABLE "placement_receipts" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "request_id" TEXT NOT NULL, "operation" TEXT NOT NULL, "worker_id" TEXT NOT NULL, "expected_revision" INTEGER, "reason" TEXT, "result_revision" INTEGER NOT NULL, "result_expires_at" INTEGER NOT NULL, CONSTRAINT "receipt_scope" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "receipt_scope_idx" ON "placement_receipts" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "placement_receipts_scope_key" ON "placement_receipts" ("app_id", "request_id");

CREATE TABLE "jobs" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "deployment_id" TEXT, "operation" TEXT NOT NULL, "operation_kind" TEXT NOT NULL, "management_request_id" TEXT, "run_id" TEXT, "spec_digest" TEXT NOT NULL, "available_at" INTEGER NOT NULL, "dispatch_order" INTEGER NOT NULL, "state" TEXT NOT NULL, "attempt" INTEGER NOT NULL DEFAULT 0, "execution_attempts" INTEGER NOT NULL DEFAULT 0, "executed_attempt" INTEGER, "worker_id" TEXT, "assignment_revision" INTEGER, "lease_deadline" INTEGER, "outcome" TEXT, "settlement_digest" TEXT, "created_at" INTEGER NOT NULL, CONSTRAINT "jobs_app_id_fkey" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "jobs_app_id_fkey_idx" ON "jobs" ("app_id");

CREATE INDEX IF NOT EXISTS "jobs_available_idx" ON "jobs" ("app_id", "state", "available_at", "id");

CREATE INDEX IF NOT EXISTS "jobs_lease_idx" ON "jobs" ("app_id", "state", "lease_deadline", "id");

CREATE UNIQUE INDEX IF NOT EXISTS "jobs_scope_key" ON "jobs" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "jobs_deployment_idx" ON "jobs" ("app_id", "deployment_id", "state");

CREATE UNIQUE INDEX IF NOT EXISTS "jobs_dispatch_key" ON "jobs" ("app_id", "dispatch_order");

CREATE INDEX IF NOT EXISTS "jobs_dispatch_idx" ON "jobs" ("app_id", "state", "dispatch_order");

CREATE UNIQUE INDEX IF NOT EXISTS "jobs_management_request_key" ON "jobs" ("app_id", "management_request_id");

CREATE INDEX IF NOT EXISTS "jobs_operation_idx" ON "jobs" ("app_id", "operation_kind", "state", "id");

CREATE TABLE "management_scopes" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "run_id" TEXT NOT NULL, "accepted_revision" INTEGER NOT NULL, "settled_revision" INTEGER NOT NULL, CONSTRAINT "management_order_app" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "management_order_app_idx" ON "management_scopes" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "management_scopes_scope_key" ON "management_scopes" ("app_id", "run_id");

CREATE TABLE "management" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "request_id" TEXT NOT NULL, "run_id" TEXT NOT NULL, "revision" INTEGER NOT NULL, "actor" TEXT NOT NULL, "request" TEXT NOT NULL, "request_digest" TEXT NOT NULL, "blocks_execution" INTEGER NOT NULL, "created_at" INTEGER NOT NULL, "outcome" TEXT, CONSTRAINT "management_job" FOREIGN KEY (app_id, id) REFERENCES jobs(app_id, id) ON DELETE RESTRICT, CONSTRAINT "management_order" FOREIGN KEY (app_id, run_id) REFERENCES management_scopes(app_id, run_id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "management_job_idx" ON "management" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "management_order_idx" ON "management" ("app_id", "run_id");

CREATE UNIQUE INDEX IF NOT EXISTS "management_scope_key" ON "management" ("app_id", "request_id");

CREATE UNIQUE INDEX IF NOT EXISTS "management_revision_key" ON "management" ("app_id", "run_id", "revision");

CREATE INDEX IF NOT EXISTS "management_pending_idx" ON "management" ("app_id", "outcome", "id");

CREATE INDEX IF NOT EXISTS "management_barrier_idx" ON "management" ("app_id", "run_id", "outcome", "blocks_execution", "revision");

CREATE TABLE "schedule_deployments" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "definition" TEXT NOT NULL, "interpretation" TEXT NOT NULL, "created_at" INTEGER NOT NULL, CONSTRAINT "schedule_deployment_scope" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "schedule_deployment_scope_idx" ON "schedule_deployments" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_deployments_scope_key" ON "schedule_deployments" ("app_id", "id");

CREATE TABLE "schedule_activations" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "deployment_id" TEXT NOT NULL, "revision" INTEGER NOT NULL, "activated_at" INTEGER NOT NULL, CONSTRAINT "schedule_activation_deploy" FOREIGN KEY (app_id, deployment_id) REFERENCES schedule_deployments(app_id, id) ON DELETE RESTRICT, CONSTRAINT "schedule_activation_job" FOREIGN KEY (app_id, id) REFERENCES jobs(app_id, id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "schedule_activation_deploy_idx" ON "schedule_activations" ("app_id", "deployment_id");

CREATE INDEX IF NOT EXISTS "schedule_activation_job_idx" ON "schedule_activations" ("app_id", "id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_activations_scope_key" ON "schedule_activations" ("app_id", "revision");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_activations_identity_key" ON "schedule_activations" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "schedule_activations_deployment_idx" ON "schedule_activations" ("app_id", "deployment_id", "id");

CREATE TABLE "schedule_disables" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "revision" INTEGER NOT NULL, "created_at" INTEGER NOT NULL, CONSTRAINT "schedule_disable_scope" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "schedule_disable_scope_idx" ON "schedule_disables" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_disables_scope_key" ON "schedule_disables" ("app_id", "revision");

CREATE TABLE "schedule_scopes" ("id" TEXT PRIMARY KEY NOT NULL, "revision" INTEGER NOT NULL, "enabled" INTEGER NOT NULL, "activation_id" TEXT, CONSTRAINT "schedule_scope_activation" FOREIGN KEY (id, activation_id) REFERENCES schedule_activations(app_id, id) ON DELETE RESTRICT, CONSTRAINT "schedule_scope_app" FOREIGN KEY (id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "schedule_scope_activation_idx" ON "schedule_scopes" ("id", "activation_id");

CREATE TABLE "schedules" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "name" TEXT NOT NULL, "activation_id" TEXT NOT NULL, "revision" INTEGER NOT NULL, "definition" TEXT NOT NULL, "next_at" INTEGER, "anchor_at" INTEGER NOT NULL, "catch_up_until" INTEGER, "catch_up_remaining" INTEGER, CONSTRAINT "schedule_activation" FOREIGN KEY (app_id, activation_id) REFERENCES schedule_activations(app_id, id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "schedule_activation_idx" ON "schedules" ("app_id", "activation_id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedules_scope_key" ON "schedules" ("app_id", "name");

CREATE UNIQUE INDEX IF NOT EXISTS "schedules_identity_key" ON "schedules" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "schedules_due_idx" ON "schedules" ("next_at", "id");

CREATE INDEX IF NOT EXISTS "schedules_activation_idx" ON "schedules" ("app_id", "activation_id");

CREATE TABLE "schedule_occurrences" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "schedule_id" TEXT NOT NULL, "revision" INTEGER NOT NULL, "scheduled_at" INTEGER NOT NULL, "run_id" TEXT NOT NULL, "job_id" TEXT NOT NULL, "activation_id" TEXT NOT NULL, CONSTRAINT "occurrence_activation" FOREIGN KEY (app_id, activation_id) REFERENCES schedule_activations(app_id, id) ON DELETE RESTRICT, CONSTRAINT "occurrence_job" FOREIGN KEY (app_id, job_id) REFERENCES jobs(app_id, id) ON DELETE RESTRICT, CONSTRAINT "occurrence_schedule" FOREIGN KEY (app_id, schedule_id) REFERENCES schedules(app_id, id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "occurrence_activation_idx" ON "schedule_occurrences" ("app_id", "activation_id");

CREATE INDEX IF NOT EXISTS "occurrence_job_idx" ON "schedule_occurrences" ("app_id", "job_id");

CREATE INDEX IF NOT EXISTS "occurrence_schedule_idx" ON "schedule_occurrences" ("app_id", "schedule_id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_occurrences_scope_key" ON "schedule_occurrences" ("app_id", "schedule_id", "revision", "scheduled_at");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_occurrences_job_key" ON "schedule_occurrences" ("app_id", "job_id");

CREATE TABLE "recovery_scopes" ("id" TEXT PRIMARY KEY NOT NULL, "deployment_id" TEXT NOT NULL, "activation_revision" INTEGER NOT NULL, "ingress_epoch" INTEGER NOT NULL, "state" TEXT NOT NULL, "closing_watermark" INTEGER, "close_job_id" TEXT, "active_at" INTEGER NOT NULL, "close_after" INTEGER, "close_attempts" INTEGER NOT NULL DEFAULT 0, CONSTRAINT "recovery_close_job" FOREIGN KEY (id, close_job_id) REFERENCES jobs(app_id, id) ON DELETE RESTRICT, CONSTRAINT "recovery_scope" FOREIGN KEY (id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "recovery_close_job_idx" ON "recovery_scopes" ("id", "close_job_id");

CREATE TABLE "recovery_duties" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "kind" TEXT NOT NULL, "next_due_at" INTEGER NOT NULL, "pending_job_id" TEXT, CONSTRAINT "recovery_duty_job" FOREIGN KEY (app_id, pending_job_id) REFERENCES jobs(app_id, id) ON DELETE RESTRICT, CONSTRAINT "recovery_duty_scope" FOREIGN KEY (app_id) REFERENCES recovery_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "recovery_duty_job_idx" ON "recovery_duties" ("app_id", "pending_job_id");

CREATE INDEX IF NOT EXISTS "recovery_duty_scope_idx" ON "recovery_duties" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "recovery_duties_scope_key" ON "recovery_duties" ("app_id", "kind");

CREATE INDEX IF NOT EXISTS "recovery_duties_due_idx" ON "recovery_duties" ("kind", "next_due_at", "app_id");

CREATE TABLE "capacity_demands" ("id" TEXT PRIMARY KEY NOT NULL, "execution_zone_id" TEXT NOT NULL, "recorded_at" INTEGER NOT NULL, CONSTRAINT "capacity_demand_scope" FOREIGN KEY (id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "capacity_demands_zone_idx" ON "capacity_demands" ("execution_zone_id", "id");

CREATE TABLE "capacity_targets" ("id" TEXT PRIMARY KEY NOT NULL, "revision" INTEGER NOT NULL DEFAULT 0, "desired" INTEGER NOT NULL DEFAULT 0, "state" TEXT NOT NULL DEFAULT 'steady', "refusal" TEXT, "observed" INTEGER, "attempt" INTEGER NOT NULL DEFAULT 0, "attempt_deadline" INTEGER, "retry_at" INTEGER, "below_since" INTEGER, "lock_version" INTEGER NOT NULL DEFAULT 0);

SELECT 1;
INSERT INTO main.schema_version (id, fingerprint) VALUES ('manager', '05468ea25777be6c1a636b6c4f841801aed1888d6918cf92e9349fd0318b3c95');
