-- Generated by schema/generate.mjs through the migration compiler.
CREATE TABLE "schema_version" ("id" TEXT PRIMARY KEY NOT NULL, "fingerprint" TEXT NOT NULL);

CREATE TABLE "queue_scopes" ("id" TEXT PRIMARY KEY NOT NULL, "lock_version" INTEGER NOT NULL DEFAULT 0, "dispatch_cursor" INTEGER NOT NULL DEFAULT 0);

CREATE TABLE "deployment_holds" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "deployment_id" TEXT NOT NULL, "holder_id" TEXT NOT NULL, "deploy_hash" TEXT, "generation" INTEGER NOT NULL, "state" TEXT NOT NULL, CONSTRAINT "deployment_hold_scope" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "deployment_hold_scope_idx" ON "deployment_holds" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "deployment_holds_scope_key" ON "deployment_holds" ("app_id", "deployment_id");

CREATE INDEX IF NOT EXISTS "deployment_holds_pending_idx" ON "deployment_holds" ("state", "app_id", "deployment_id");

CREATE TABLE "workers" ("id" TEXT PRIMARY KEY NOT NULL, "capacity" INTEGER NOT NULL DEFAULT 1, "state" TEXT NOT NULL DEFAULT 'ready', "expires_at" INTEGER NOT NULL DEFAULT 0, "lock_version" INTEGER NOT NULL DEFAULT 0);

CREATE TABLE "assignments" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "worker_id" TEXT NOT NULL, "revision" INTEGER NOT NULL, "expires_at" INTEGER NOT NULL, "released" INTEGER NOT NULL, "wake_revision" INTEGER, "next_due_at" INTEGER, CONSTRAINT "assignment_scope" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT, CONSTRAINT "assignment_worker" FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "assignment_scope_idx" ON "assignments" ("app_id");

CREATE INDEX IF NOT EXISTS "assignment_worker_idx" ON "assignments" ("worker_id");

CREATE UNIQUE INDEX IF NOT EXISTS "assignments_scope_key" ON "assignments" ("app_id", "worker_id");

CREATE INDEX IF NOT EXISTS "assignments_worker_idx" ON "assignments" ("worker_id", "app_id");

CREATE INDEX IF NOT EXISTS "assignments_expiry_idx" ON "assignments" ("expires_at", "app_id");

CREATE TABLE "placement_receipts" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "request_id" TEXT NOT NULL, "operation" TEXT NOT NULL, "worker_id" TEXT NOT NULL, "expected_revision" INTEGER, "wake_revision" INTEGER, "result_revision" INTEGER NOT NULL, "result_expires_at" INTEGER NOT NULL, CONSTRAINT "receipt_scope" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "receipt_scope_idx" ON "placement_receipts" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "placement_receipts_scope_key" ON "placement_receipts" ("app_id", "request_id");

CREATE TABLE "management" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "request_id" TEXT NOT NULL, "run_id" TEXT NOT NULL, "actor" TEXT NOT NULL, "operation" TEXT NOT NULL, "restart_name" TEXT, "restart_occurrence" INTEGER, "restart_deploy" TEXT, "created_at" INTEGER NOT NULL, "outcome" TEXT, "run_state" TEXT, "ack_worker_id" TEXT, "ack_revision" INTEGER, CONSTRAINT "management_scope" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "management_scope_idx" ON "management" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "management_scope_key" ON "management" ("app_id", "request_id");

CREATE INDEX IF NOT EXISTS "management_pending_idx" ON "management" ("app_id", "outcome", "created_at", "request_id");

CREATE TABLE "jobs" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "deployment_id" TEXT NOT NULL, "operation" TEXT NOT NULL, "spec_digest" TEXT NOT NULL, "available_at" INTEGER NOT NULL, "dispatch_order" INTEGER NOT NULL, "state" TEXT NOT NULL, "attempt" INTEGER NOT NULL DEFAULT 0, "worker_id" TEXT, "assignment_revision" INTEGER, "lease_deadline" INTEGER, "outcome" TEXT, "settlement_digest" TEXT, "created_at" INTEGER NOT NULL, CONSTRAINT "jobs_app_id_fkey" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "jobs_app_id_fkey_idx" ON "jobs" ("app_id");

CREATE INDEX IF NOT EXISTS "jobs_available_idx" ON "jobs" ("app_id", "state", "available_at", "id");

CREATE INDEX IF NOT EXISTS "jobs_lease_idx" ON "jobs" ("app_id", "state", "lease_deadline", "id");

CREATE UNIQUE INDEX IF NOT EXISTS "jobs_scope_key" ON "jobs" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "jobs_deployment_idx" ON "jobs" ("app_id", "deployment_id", "state");

CREATE UNIQUE INDEX IF NOT EXISTS "jobs_dispatch_key" ON "jobs" ("app_id", "dispatch_order");

CREATE INDEX IF NOT EXISTS "jobs_dispatch_idx" ON "jobs" ("app_id", "state", "dispatch_order");

CREATE TABLE "schedule_deployments" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "definition" TEXT NOT NULL, "interpretation" TEXT NOT NULL, "created_at" INTEGER NOT NULL, CONSTRAINT "schedule_deployment_scope" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "schedule_deployment_scope_idx" ON "schedule_deployments" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_deployments_scope_key" ON "schedule_deployments" ("app_id", "id");

CREATE TABLE "schedule_activations" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "deployment_id" TEXT NOT NULL, "revision" INTEGER NOT NULL, "activated_at" INTEGER NOT NULL, CONSTRAINT "schedule_activation_deploy" FOREIGN KEY (app_id, deployment_id) REFERENCES schedule_deployments(app_id, id) ON DELETE RESTRICT, CONSTRAINT "schedule_activation_job" FOREIGN KEY (app_id, id) REFERENCES jobs(app_id, id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "schedule_activation_deploy_idx" ON "schedule_activations" ("app_id", "deployment_id");

CREATE INDEX IF NOT EXISTS "schedule_activation_job_idx" ON "schedule_activations" ("app_id", "id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_activations_scope_key" ON "schedule_activations" ("app_id", "revision");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_activations_identity_key" ON "schedule_activations" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "schedule_activations_deployment_idx" ON "schedule_activations" ("app_id", "deployment_id", "id");

CREATE TABLE "schedule_disables" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "revision" INTEGER NOT NULL, "created_at" INTEGER NOT NULL, CONSTRAINT "schedule_disable_scope" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "schedule_disable_scope_idx" ON "schedule_disables" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_disables_scope_key" ON "schedule_disables" ("app_id", "revision");

CREATE TABLE "schedule_scopes" ("id" TEXT PRIMARY KEY NOT NULL, "revision" INTEGER NOT NULL, "enabled" INTEGER NOT NULL, "activation_id" TEXT, CONSTRAINT "schedule_scope_activation" FOREIGN KEY (id, activation_id) REFERENCES schedule_activations(app_id, id) ON DELETE RESTRICT, CONSTRAINT "schedule_scope_app" FOREIGN KEY (id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "schedule_scope_activation_idx" ON "schedule_scopes" ("id", "activation_id");

CREATE TABLE "schedules" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "name" TEXT NOT NULL, "activation_id" TEXT NOT NULL, "revision" INTEGER NOT NULL, "definition" TEXT NOT NULL, "next_at" INTEGER, "anchor_at" INTEGER NOT NULL, "catch_up_until" INTEGER, "catch_up_remaining" INTEGER, CONSTRAINT "schedule_activation" FOREIGN KEY (app_id, activation_id) REFERENCES schedule_activations(app_id, id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "schedule_activation_idx" ON "schedules" ("app_id", "activation_id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedules_scope_key" ON "schedules" ("app_id", "name");

CREATE UNIQUE INDEX IF NOT EXISTS "schedules_identity_key" ON "schedules" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "schedules_due_idx" ON "schedules" ("next_at", "id");

CREATE INDEX IF NOT EXISTS "schedules_activation_idx" ON "schedules" ("app_id", "activation_id");

CREATE TABLE "schedule_occurrences" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "schedule_id" TEXT NOT NULL, "revision" INTEGER NOT NULL, "scheduled_at" INTEGER NOT NULL, "run_id" TEXT NOT NULL, "job_id" TEXT NOT NULL, "activation_id" TEXT NOT NULL, CONSTRAINT "occurrence_activation" FOREIGN KEY (app_id, activation_id) REFERENCES schedule_activations(app_id, id) ON DELETE RESTRICT, CONSTRAINT "occurrence_job" FOREIGN KEY (app_id, job_id) REFERENCES jobs(app_id, id) ON DELETE RESTRICT, CONSTRAINT "occurrence_schedule" FOREIGN KEY (app_id, schedule_id) REFERENCES schedules(app_id, id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "occurrence_activation_idx" ON "schedule_occurrences" ("app_id", "activation_id");

CREATE INDEX IF NOT EXISTS "occurrence_job_idx" ON "schedule_occurrences" ("app_id", "job_id");

CREATE INDEX IF NOT EXISTS "occurrence_schedule_idx" ON "schedule_occurrences" ("app_id", "schedule_id");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_occurrences_scope_key" ON "schedule_occurrences" ("app_id", "schedule_id", "revision", "scheduled_at");

CREATE UNIQUE INDEX IF NOT EXISTS "schedule_occurrences_job_key" ON "schedule_occurrences" ("app_id", "job_id");

CREATE TABLE "recovery_scopes" ("id" TEXT PRIMARY KEY NOT NULL, "deployment_id" TEXT NOT NULL, "activation_revision" INTEGER NOT NULL, "next_due_at" INTEGER NOT NULL, "pending_job_id" TEXT, CONSTRAINT "recovery_job" FOREIGN KEY (pending_job_id) REFERENCES jobs(id) ON DELETE RESTRICT, CONSTRAINT "recovery_scope" FOREIGN KEY (id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "recovery_job_idx" ON "recovery_scopes" ("pending_job_id");

CREATE INDEX IF NOT EXISTS "recovery_scopes_due_idx" ON "recovery_scopes" ("next_due_at", "id");

SELECT 1;
INSERT INTO main.schema_version (id, fingerprint) VALUES ('manager', '0895c557b5d3ef9c718a55bb0677e83d06df62a80b727fe2a745f685c0d3438a');
