-- Generated by schema/generate.mjs through the migration compiler.
CREATE TABLE "schema_version" ("id" TEXT PRIMARY KEY NOT NULL, "fingerprint" TEXT NOT NULL);

CREATE TABLE "queue_scopes" ("id" TEXT PRIMARY KEY NOT NULL, "lock_version" INTEGER NOT NULL DEFAULT 0);

CREATE TABLE "workers" ("id" TEXT PRIMARY KEY NOT NULL, "capacity" INTEGER NOT NULL, "state" TEXT NOT NULL, "expires_at" INTEGER NOT NULL, "lock_version" INTEGER NOT NULL DEFAULT 0);

CREATE TABLE "assignments" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "worker_id" TEXT NOT NULL, "revision" INTEGER NOT NULL, "expires_at" INTEGER NOT NULL, "released" INTEGER NOT NULL, "wake_revision" INTEGER, "next_due_at" INTEGER, CONSTRAINT "assignment_scope" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT, CONSTRAINT "assignment_worker" FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "assignment_scope_idx" ON "assignments" ("app_id");

CREATE INDEX IF NOT EXISTS "assignment_worker_idx" ON "assignments" ("worker_id");

CREATE UNIQUE INDEX IF NOT EXISTS "assignments_scope_key" ON "assignments" ("app_id", "worker_id");

CREATE INDEX IF NOT EXISTS "assignments_worker_idx" ON "assignments" ("worker_id", "app_id");

CREATE INDEX IF NOT EXISTS "assignments_expiry_idx" ON "assignments" ("expires_at", "app_id");

CREATE TABLE "placement_receipts" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "request_id" TEXT NOT NULL, "operation" TEXT NOT NULL, "worker_id" TEXT NOT NULL, "expected_revision" INTEGER, "wake_revision" INTEGER, "result_revision" INTEGER NOT NULL, "result_expires_at" INTEGER NOT NULL, CONSTRAINT "receipt_scope" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "receipt_scope_idx" ON "placement_receipts" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "placement_receipts_scope_key" ON "placement_receipts" ("app_id", "request_id");

CREATE TABLE "management" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "request_id" TEXT NOT NULL, "run_id" TEXT NOT NULL, "actor" TEXT NOT NULL, "operation" TEXT NOT NULL, "restart_name" TEXT, "restart_occurrence" INTEGER, "restart_deploy" TEXT, "created_at" INTEGER NOT NULL, "outcome" TEXT, "run_state" TEXT, "ack_worker_id" TEXT, "ack_revision" INTEGER, CONSTRAINT "management_scope" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "management_scope_idx" ON "management" ("app_id");

CREATE UNIQUE INDEX IF NOT EXISTS "management_scope_key" ON "management" ("app_id", "request_id");

CREATE INDEX IF NOT EXISTS "management_pending_idx" ON "management" ("app_id", "outcome", "created_at", "request_id");

CREATE TABLE "jobs" ("id" TEXT PRIMARY KEY NOT NULL, "app_id" TEXT NOT NULL, "deployment_id" TEXT NOT NULL, "operation" TEXT NOT NULL, "spec_digest" TEXT NOT NULL, "available_at" INTEGER NOT NULL, "state" TEXT NOT NULL, "attempt" INTEGER NOT NULL DEFAULT 0, "worker_id" TEXT, "assignment_revision" INTEGER, "lease_deadline" INTEGER, "outcome" TEXT, "settlement_digest" TEXT, "created_at" INTEGER NOT NULL, CONSTRAINT "jobs_app_id_fkey" FOREIGN KEY (app_id) REFERENCES queue_scopes(id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "jobs_app_id_fkey_idx" ON "jobs" ("app_id");

CREATE INDEX IF NOT EXISTS "jobs_available_idx" ON "jobs" ("app_id", "state", "available_at", "id");

CREATE INDEX IF NOT EXISTS "jobs_lease_idx" ON "jobs" ("app_id", "state", "lease_deadline", "id");

SELECT 1;
INSERT INTO main.schema_version (id, fingerprint) VALUES ('manager', 'da1a9579a7e8535b894cce0b7be241cfd148e918e713108c63b08e5ed2a6344e');
