import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { isDeepStrictEqual } from "node:util";
import { genArtifacts } from "../../../crates/zeroship-migrate-node/index.js";
import { workflowSchema } from "./schema.ts";
import { bindOwnedNames } from "./names.mjs";
import { buildEnvelope } from "../../../packages/zero-migrate/dist/internal/recorder.js";
import { currentIrVersion, previewSql } from "../../../packages/zero-migrate-cli/dist/index.js";

const check = process.argv.includes("--check");
const fingerprints = {};
const outputs = [];
let runtimeDescriptor;
for (const dialect of ["postgres", "sqlite"]) {
  const namespace = dialect === "postgres" ? "__zeroship_workflow_schema" : "main";
  let identifiers;
  const envelope = buildEnvelope({ name: "workflow_journal", schema: () => { identifiers = workflowSchema(namespace); } }, { irVersion: currentIrVersion() });
  if (!envelope.ops.length) throw new Error("workflow schema recorder is empty");
  const charter = `policy_version = 1
[[grant]]
key = "schema.create_table"
value = true
scope = { include = ["${namespace}"] }
[[grant]]
key = "schema.cross_schema"
value = true
scope = { include = ["${namespace}"] }
[[grant]]
key = "sql.raw"
value = true
scope = { include = ["${namespace}"] }
`;
  const statements = previewSql({ envelopes: [JSON.stringify(envelope)], dialect, defaultSchema: namespace, ownerApp: "workflow", charterLayers: [charter] });
  const artifacts = genArtifacts({ envelopes: [envelope], dialect, projectSchema: namespace, charterLayers: [charter] });
  if (!artifacts.ok) throw new Error(artifacts.error);
  const descriptor = JSON.parse(artifacts.runtimeJson);
  if (!Object.keys(descriptor.collections).length) throw new Error("workflow descriptor is empty");
  descriptor.collections = Object.fromEntries(Object.entries(descriptor.collections).map(([name, collection]) => {
    if (!identifiers.identifiers.has(name)) throw new Error(`unexpected workflow collection ${name}`);
    const indexes = collection.indexes.map(index => {
      if (!identifiers.identifiers.has(index.name)) throw new Error(`unexpected workflow index ${index.name}`);
      return { ...index, name: `__zeroship_workflow_${index.name}` };
    });
    return [`__zeroship_workflow_${name}`, { ...collection, indexes }];
  }));
  if (runtimeDescriptor && !isDeepStrictEqual(runtimeDescriptor, descriptor)) {
    throw new Error("workflow model metadata differs between database dialects");
  }
  runtimeDescriptor = descriptor;
  const emitted = statements.join("\n");
  if (emitted.includes("[runtime-resolved]")) throw new Error("workflow schema must lower completely");
  // Preview annotations contain measured tallies; shipped SQL retains statements.
  const sql = bindOwnedNames(emitted.split("\n").filter(line => !line.startsWith("--")).join("\n").trim(), identifiers);
  const fingerprint = createHash("sha256").update(sql).digest("hex");
  fingerprints[dialect] = fingerprint;
  const content = `-- Generated by schema/generate.mjs through the migration compiler.\n${sql}\nINSERT INTO "${namespace}".__zeroship_workflow_schema_version (id, fingerprint) VALUES ('workflow', '${fingerprint}');\n`;
  const path = new URL(`./${dialect}.sql`, import.meta.url);
  outputs.push({ path, content });
}

outputs.push({ path: new URL("./fingerprints.json", import.meta.url), content: JSON.stringify(fingerprints, null, 2) + "\n" });
outputs.push({ path: new URL("./schema.runtime.json", import.meta.url), content: JSON.stringify(runtimeDescriptor, null, 2) + "\n" });
// Finish compiling every dialect before changing any generated artifact.
for (const { path, content } of outputs) {
  if (check) {
    if (await readFile(path, "utf8") !== content) throw new Error(`stale workflow schema ${path.pathname}; run node crates/zeroship-workflow-schema/schema/generate.mjs`);
  } else {
    await writeFile(path, content);
  }
}
