-- Generated by schema/generate.mjs through the migration compiler.
CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_schema_version" ("id" text PRIMARY KEY NOT NULL, "version" bigint NOT NULL, "fingerprint" text NOT NULL);

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "signal_epoch" bigint NOT NULL DEFAULT 0, "last_polled_at" bigint NOT NULL DEFAULT 0, "subscription_sequence" bigint NOT NULL DEFAULT 0, "signal_sequence" bigint NOT NULL DEFAULT 0, "closed_epoch" bigint NOT NULL DEFAULT 0, "collection_revision" bigint NOT NULL DEFAULT 1, "collection_after_id" text COLLATE "C", "collection_upper_id" text COLLATE "C", "collection_observed_at" bigint, "reconciliation_revision" bigint NOT NULL DEFAULT 1, "reconciliation_phase" text NOT NULL DEFAULT 'publications', "reconciliation_after_id" text COLLATE "C", "reconciliation_upper_id" text COLLATE "C");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_app_state_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_deploys" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "hash" text NOT NULL, "manifest" text NOT NULL, "created_at" bigint NOT NULL, "active" bigint NOT NULL, "state" text NOT NULL, "availability_epoch" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_deploys_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_deploy_hash_identity" ON "__zeroship_workflow_schema"."__zeroship_workflow_deploys" ("app_id", "hash");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_deploys_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_deploys" ("app_id", "id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_deployment_holds" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "deploy_id" text COLLATE "C" NOT NULL, "deploy_hash" text, "holder_id" text NOT NULL, "generation" bigint NOT NULL, "state" text NOT NULL, CONSTRAINT "__zeroship_workflow_deployment_holds_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_deployment_holds_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_deployment_holds" ("app_id", "deploy_id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_deployment_holds_pending_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_deployment_holds" ("app_id", "state", "deploy_id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_schedules" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "name" text COLLATE "C" NOT NULL, CONSTRAINT "__zeroship_workflow_schedules_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_schedule_name" ON "__zeroship_workflow_schema"."__zeroship_workflow_schedules" ("app_id", "name");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_schedules_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_schedules" ("app_id", "id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_runs" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "workflow_name" text NOT NULL, "deploy_id" text NOT NULL, "generation" bigint NOT NULL, "state" text NOT NULL, "control" text NOT NULL, "due_at" bigint, "task_id" text, "lease_epoch" bigint NOT NULL, "frontier_revision" bigint NOT NULL DEFAULT 1, "key" text, "parent_id" text, "parent_generation" bigint, "parent_ordinal" bigint, "cascade" bigint NOT NULL, "depth" bigint NOT NULL, "created_at" bigint NOT NULL, "terminal_at" bigint, "signal_epoch" bigint NOT NULL, "compensation_target" text, "schedule_id" text, CONSTRAINT "__zeroship_workflow_run_deploy" FOREIGN KEY ("app_id", "deploy_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_deploys" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_run_schedule" FOREIGN KEY ("app_id", "schedule_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_schedules" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_runs_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_live_workflow_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_runs" ("app_id", "workflow_name", "key");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_run_deploy_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_runs" ("app_id", "deploy_id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_run_schedule_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_runs" ("app_id", "schedule_id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_runs_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_runs" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_run_parent_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_runs" ("app_id", "parent_id");

ALTER TABLE "__zeroship_workflow_schema"."__zeroship_workflow_runs" ADD CONSTRAINT "__zeroship_workflow_run_parent" FOREIGN KEY ("app_id", "parent_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_runs" ("app_id", id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_runs_due_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_runs" ("due_at", "app_id", "id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_runs_parent_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_runs" ("app_id", "parent_id", "parent_generation", "cascade", "id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_generations" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "run_id" text NOT NULL, "generation" bigint NOT NULL, "deploy_id" text NOT NULL, "input" text NOT NULL, "input_ref" text, "output" text, "output_ref" text, "error" text, "state" text NOT NULL, "started_at" bigint NOT NULL, "terminal_at" bigint, CONSTRAINT "__zeroship_workflow_generation_deploy" FOREIGN KEY ("app_id", "deploy_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_deploys" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_generations_run" FOREIGN KEY ("app_id", "run_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_runs" ("app_id", id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_generation_deploy_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_generations" ("app_id", "deploy_id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_generation_identity" ON "__zeroship_workflow_schema"."__zeroship_workflow_generations" ("app_id", "id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_generations_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_generations" ("app_id", "run_id", "generation");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_continuation_heads" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "current_generation_id" text NOT NULL, "revision" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_continuation_head_generation" FOREIGN KEY ("app_id", "current_generation_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_generations" ("app_id", id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_continuation_head_generation_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_continuation_heads" ("app_id", "current_generation_id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_continuation_heads_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_continuation_heads" ("app_id", "id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_continuation_members" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "head_id" text NOT NULL, "revision" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_continuation_member_generation" FOREIGN KEY ("app_id", "id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_generations" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_continuation_member_head" FOREIGN KEY ("app_id", "head_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_continuation_heads" ("app_id", id) ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_continuation_member_revision" ON "__zeroship_workflow_schema"."__zeroship_workflow_continuation_members" ("app_id", "head_id", "revision");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_continuation_members_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_continuation_members" ("app_id", "id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_steps" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "run_id" text NOT NULL, "generation" bigint NOT NULL, "ordinal" bigint NOT NULL, "name" text NOT NULL, "occurrence" bigint NOT NULL, "origin_generation" bigint NOT NULL, "kind" text NOT NULL, "state" text NOT NULL, "record" text NOT NULL, "child_member_id" text, "child_result_member_id" text, "compensation_attempts" bigint NOT NULL DEFAULT 0, "compensation_due_at" bigint, "compensation_error" text, "compensation_retry_ms" bigint NOT NULL DEFAULT 1000, CONSTRAINT "__zeroship_workflow_step_child_member" FOREIGN KEY ("app_id", "child_member_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_continuation_members" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_step_child_result_member" FOREIGN KEY ("app_id", "child_result_member_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_continuation_members" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_steps_generation" FOREIGN KEY ("app_id", "run_id", "generation") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_generations" ("app_id", "run_id", "generation") ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_step_child_member_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_steps" ("app_id", "child_member_id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_step_child_result_member_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_steps" ("app_id", "child_result_member_id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_step_name_occurrence" ON "__zeroship_workflow_schema"."__zeroship_workflow_steps" ("app_id", "run_id", "generation", "name", "occurrence");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_steps_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_steps" ("app_id", "run_id", "generation", "ordinal");

ALTER TABLE "__zeroship_workflow_schema"."__zeroship_workflow_steps" ADD CONSTRAINT "__zeroship_workflow_step_child_linkage" CHECK (((("kind" = 'child') AND ("child_member_id" IS NOT NULL)) OR ((("kind" <> 'child') AND ("child_member_id" IS NULL)) AND ("child_result_member_id" IS NULL))));

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_job_receipts" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "run_id" text COLLATE "C", "specification" text NOT NULL, "outcome" text, "created_at" bigint NOT NULL, "completed_at" bigint, CONSTRAINT "__zeroship_workflow_job_receipts_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_job_receipts_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_job_receipts" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_job_receipts_run_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_job_receipts" ("app_id", "run_id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_collection_pages" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "plan" text NOT NULL, "next_index" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_collection_page_receipt" FOREIGN KEY ("app_id", "id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_job_receipts" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_collection_pages_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_collection_pages_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_collection_pages" ("app_id", "id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_reconciliation_pages" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "plan" text NOT NULL, "next_index" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_reconciliation_page_receipt" FOREIGN KEY ("app_id", "id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_job_receipts" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_reconciliation_pages_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_reconciliation_pages_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_reconciliation_pages" ("app_id", "id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_activations" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "deploy_id" text COLLATE "C" NOT NULL, "revision" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_activation_deploy" FOREIGN KEY ("app_id", "deploy_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_deploys" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_activation_receipt" FOREIGN KEY ("app_id", "id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_job_receipts" ("app_id", id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_activation_deploy_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_activations" ("app_id", "deploy_id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_activation_identity" ON "__zeroship_workflow_schema"."__zeroship_workflow_activations" ("app_id", "id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_activations_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_activations" ("app_id", "revision");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_activation_scopes" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "activation_id" text COLLATE "C" NOT NULL, "revision" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_activation_scope_app" FOREIGN KEY ("id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_activation_scope_receipt" FOREIGN KEY ("id", "activation_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_activations" ("app_id", id) ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_activation_scope_receipt_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_activation_scopes" ("id", "activation_id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_tasks" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "run_id" text NOT NULL, "generation" bigint NOT NULL, "worker" text NOT NULL, "epoch" bigint NOT NULL, "token_hash" text NOT NULL, "deadline" bigint NOT NULL, "state" text NOT NULL, "completion_digest" text, "receipt" text, "frontier_revision" bigint NOT NULL DEFAULT 1, "job_id" text COLLATE "C", "delivery_attempt" bigint, "assignment_revision" bigint, "created_at" bigint NOT NULL, "finished_at" bigint, CONSTRAINT "__zeroship_workflow_task_job" FOREIGN KEY ("app_id", "job_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_job_receipts" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_tasks_generation" FOREIGN KEY ("app_id", "run_id", "generation") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_generations" ("app_id", "run_id", "generation") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_task_fence_identity" ON "__zeroship_workflow_schema"."__zeroship_workflow_tasks" ("app_id", "run_id", "generation", "epoch");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_task_job_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_tasks" ("app_id", "job_id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_task_scope_identity" ON "__zeroship_workflow_schema"."__zeroship_workflow_tasks" ("app_id", "run_id", "generation", "id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_tasks_admission_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_tasks" ("app_id", "state", "deadline");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_waits" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "run_id" text NOT NULL, "generation" bigint NOT NULL, "ordinal" bigint NOT NULL, "kind" text NOT NULL, "signal_type" text, "topic" text, "max_signal_age" bigint, "due_at" bigint, CONSTRAINT "__zeroship_workflow_wait_step" FOREIGN KEY ("app_id", "run_id", "generation", "ordinal") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_steps" ("app_id", "run_id", "generation", "ordinal") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_waits_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_waits" ("app_id", "run_id", "generation", "ordinal");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_topics" ("id" text PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "topic" text COLLATE "C" NOT NULL, "signal_epoch" bigint NOT NULL, "accepted_sequence" bigint NOT NULL DEFAULT 0, "completed_sequence" bigint NOT NULL DEFAULT 0, CONSTRAINT "__zeroship_workflow_topics_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_topics_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_topics" ("app_id", "topic");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_broadcasts" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "topic" text COLLATE "C" NOT NULL, "signal_type" text NOT NULL, "payload" text NOT NULL, "created_at" bigint NOT NULL, "cursor" bigint NOT NULL, "cutoff_sequence" bigint NOT NULL, "origin" text NOT NULL, "finished" bigint NOT NULL, "sequence" bigint NOT NULL, "revision" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_broadcast_topic" FOREIGN KEY ("app_id", "topic") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_topics" ("app_id", "topic") ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_broadcasts_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_broadcast_order" ON "__zeroship_workflow_schema"."__zeroship_workflow_broadcasts" ("app_id", "topic", "sequence");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_broadcasts_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_broadcasts" ("app_id", "id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_signals" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "run_id" text NOT NULL, "signal_type" text NOT NULL, "payload" text NOT NULL, "created_at" bigint NOT NULL, "delivery_sequence" bigint NOT NULL, "consumed_generation" bigint, "consumed_ordinal" bigint, "broadcast_id" text, "origin" text NOT NULL DEFAULT 'app', "delivery" text NOT NULL DEFAULT 'direct', "topic" text, "target_generation" bigint, "target_ordinal" bigint, CONSTRAINT "__zeroship_workflow_signal_broadcast" FOREIGN KEY ("app_id", "broadcast_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_broadcasts" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_signal_consumption" FOREIGN KEY ("app_id", "run_id", "consumed_generation", "consumed_ordinal") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_steps" ("app_id", "run_id", "generation", "ordinal") ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_signal_target" FOREIGN KEY ("app_id", "run_id", "target_generation", "target_ordinal") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_steps" ("app_id", "run_id", "generation", "ordinal") ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_signals_run" FOREIGN KEY ("app_id", "run_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_runs" ("app_id", id) ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_broadcast_delivery" ON "__zeroship_workflow_schema"."__zeroship_workflow_signals" ("app_id", "broadcast_id", "run_id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_signal_consumption_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_signals" ("app_id", "run_id", "consumed_generation", "consumed_ordinal");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_signal_delivery_order" ON "__zeroship_workflow_schema"."__zeroship_workflow_signals" ("app_id", "delivery_sequence");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_signal_target_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_signals" ("app_id", "run_id", "target_generation", "target_ordinal");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_signals_run_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_signals" ("app_id", "run_id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_signals_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_signals" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_signals_mailbox_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_signals" ("app_id", "run_id", "signal_type", "consumed_generation", "delivery_sequence");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_subscriptions" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "run_id" text NOT NULL, "generation" bigint NOT NULL, "ordinal" bigint NOT NULL, "topic" text NOT NULL, "created_at" bigint NOT NULL, "sequence" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_subscription_step" FOREIGN KEY ("app_id", "run_id", "generation", "ordinal") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_steps" ("app_id", "run_id", "generation", "ordinal") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_subscription_identity" ON "__zeroship_workflow_schema"."__zeroship_workflow_subscriptions" ("app_id", "id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_subscription_sequence_unique" ON "__zeroship_workflow_schema"."__zeroship_workflow_subscriptions" ("app_id", "sequence");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_subscriptions_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_subscriptions" ("app_id", "run_id", "generation", "ordinal");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_subscriptions_topic_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_subscriptions" ("app_id", "topic", "id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_requests" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "request_id" text NOT NULL, "operation" text NOT NULL, "digest" text NOT NULL, "result" text NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_requests_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_requests_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_requests" ("app_id", "request_id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_management_receipts" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "run_id" text COLLATE "C" NOT NULL, "request_id" text COLLATE "C" NOT NULL, "revision" bigint NOT NULL, "outcome" text NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_management_job_receipt" FOREIGN KEY ("app_id", "id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_job_receipts" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_management_receipts_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_management_job_receipt_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_management_receipts" ("app_id", "id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_management_receipts_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_management_receipts" ("app_id", "request_id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_management_revision_identity" ON "__zeroship_workflow_schema"."__zeroship_workflow_management_receipts" ("app_id", "run_id", "revision");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_occurrences" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "schedule_id" text COLLATE "C" NOT NULL, "revision" bigint NOT NULL, "at" bigint NOT NULL, "job_id" text COLLATE "C" NOT NULL, "run_id" text COLLATE "C", CONSTRAINT "__zeroship_workflow_occurrence_job" FOREIGN KEY ("app_id", "job_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_job_receipts" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_occurrence_run" FOREIGN KEY ("app_id", "run_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_runs" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_occurrence_schedule" FOREIGN KEY ("app_id", "schedule_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_schedules" ("app_id", id) ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_occurrence_job_identity" ON "__zeroship_workflow_schema"."__zeroship_workflow_occurrences" ("app_id", "job_id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_occurrence_run_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_occurrences" ("app_id", "run_id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_occurrences_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_occurrences" ("app_id", "schedule_id", "revision", "at");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_payloads" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "run_id" text NOT NULL, "generation" bigint NOT NULL, "task_id" text NOT NULL, "request_id" text NOT NULL, "hash" text NOT NULL, "size" bigint NOT NULL, "content_type" text, "state" text NOT NULL, "created_at" bigint NOT NULL, "expires_at" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_payload_task" FOREIGN KEY ("app_id", "run_id", "generation", "task_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_tasks" ("app_id", "run_id", "generation", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_payloads_generation" FOREIGN KEY ("app_id", "run_id", "generation") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_generations" ("app_id", "run_id", "generation") ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_payload_task_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_payloads" ("app_id", "run_id", "generation", "task_id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_payloads_generation_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_payloads" ("app_id", "run_id", "generation");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_payloads_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_payloads" ("app_id", "id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_payload_upload_request" ON "__zeroship_workflow_schema"."__zeroship_workflow_payloads" ("app_id", "task_id", "request_id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_payloads_expiry_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_payloads" ("state", "expires_at");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_payload_refs" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "run_id" text NOT NULL, "generation" bigint NOT NULL, "slot" text NOT NULL, "ordinal" bigint NOT NULL, "payload_id" text NOT NULL, CONSTRAINT "__zeroship_workflow_payload_ref" FOREIGN KEY ("app_id", "payload_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_payloads" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_payload_refs_generation" FOREIGN KEY ("app_id", "run_id", "generation") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_generations" ("app_id", "run_id", "generation") ON DELETE RESTRICT);

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_payload_ref_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_payload_refs" ("app_id", "payload_id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_payload_refs_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_payload_refs" ("app_id", "run_id", "generation", "slot", "ordinal");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_outbox" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "kind" text NOT NULL, "payload" text NOT NULL, "created_at" bigint NOT NULL, "delivered_at" bigint, CONSTRAINT "__zeroship_workflow_outbox_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_outbox_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_outbox" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_outbox_delivery_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_outbox" ("delivered_at", "created_at");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_job_publications" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "specification" text NOT NULL, "created_at" bigint NOT NULL, "confirmed_at" bigint, CONSTRAINT "__zeroship_workflow_job_publications_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_job_publications_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_job_publications" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_job_publications_pending_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_job_publications" ("app_id", "confirmed_at", "id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_advance_publications" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "deploy_id" text COLLATE "C" NOT NULL, "run_id" text COLLATE "C" NOT NULL, "generation" bigint NOT NULL, "frontier_revision" bigint NOT NULL, "available_at" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_advance_publication_intent" FOREIGN KEY ("app_id", "id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_job_publications" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_advance_publications_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_advance_publication_frontier" ON "__zeroship_workflow_schema"."__zeroship_workflow_advance_publications" ("app_id", "run_id", "generation", "frontier_revision", "available_at");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_advance_publications_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_advance_publications" ("app_id", "id");

CREATE INDEX IF NOT EXISTS "__zeroship_workflow_advance_publications_deployment_idx" ON "__zeroship_workflow_schema"."__zeroship_workflow_advance_publications" ("app_id", "deploy_id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_fanout_publications" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "broadcast_id" text COLLATE "C" NOT NULL, "revision" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_fanout_publication_intent" FOREIGN KEY ("app_id", "id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_job_publications" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_fanout_publications_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_fanout_publication_broadcast" ON "__zeroship_workflow_schema"."__zeroship_workflow_fanout_publications" ("app_id", "broadcast_id", "revision");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_fanout_publications_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_fanout_publications" ("app_id", "id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_propagation_publications" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "propagation_id" text NOT NULL, "revision" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_propagation_publication_intent" FOREIGN KEY ("app_id", "id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_job_publications" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_propagation_publications_app" FOREIGN KEY ("app_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_app_state" ("app_id") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_propagation_publication_obligation" ON "__zeroship_workflow_schema"."__zeroship_workflow_propagation_publications" ("app_id", "propagation_id", "revision");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_propagation_publications_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_propagation_publications" ("app_id", "id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_fanout_pages" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "broadcast_id" text COLLATE "C" NOT NULL, "revision" bigint NOT NULL, "result" text NOT NULL, CONSTRAINT "__zeroship_workflow_fanout_page_broadcast" FOREIGN KEY ("app_id", "broadcast_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_broadcasts" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_fanout_page_publication" FOREIGN KEY ("app_id", "id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_job_publications" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_fanout_page_receipt" FOREIGN KEY ("app_id", "id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_job_receipts" ("app_id", id) ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_fanout_page_revision" ON "__zeroship_workflow_schema"."__zeroship_workflow_fanout_pages" ("app_id", "broadcast_id", "revision");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_fanout_pages_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_fanout_pages" ("app_id", "id");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_propagations" ("id" text PRIMARY KEY NOT NULL, "app_id" text NOT NULL, "run_id" text NOT NULL, "generation" bigint NOT NULL, "kind" text NOT NULL, "cursor" text, "revision" bigint NOT NULL, "finished" bigint NOT NULL, "created_at" bigint NOT NULL, CONSTRAINT "__zeroship_workflow_propagations_generation" FOREIGN KEY ("app_id", "run_id", "generation") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_generations" ("app_id", "run_id", "generation") ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_propagation_identity" ON "__zeroship_workflow_schema"."__zeroship_workflow_propagations" ("app_id", "id");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_propagations_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_propagations" ("app_id", "run_id", "generation", "kind");

CREATE TABLE "__zeroship_workflow_schema"."__zeroship_workflow_propagation_pages" ("id" text COLLATE "C" PRIMARY KEY NOT NULL, "app_id" text COLLATE "C" NOT NULL, "propagation_id" text NOT NULL, "revision" bigint NOT NULL, "result" text NOT NULL, CONSTRAINT "__zeroship_workflow_propagation_page_obligation" FOREIGN KEY ("app_id", "propagation_id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_propagations" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_propagation_page_publication" FOREIGN KEY ("app_id", "id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_job_publications" ("app_id", id) ON DELETE RESTRICT, CONSTRAINT "__zeroship_workflow_propagation_page_receipt" FOREIGN KEY ("app_id", "id") REFERENCES "__zeroship_workflow_schema"."__zeroship_workflow_job_receipts" ("app_id", id) ON DELETE RESTRICT);

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_propagation_page_revision" ON "__zeroship_workflow_schema"."__zeroship_workflow_propagation_pages" ("app_id", "propagation_id", "revision");

CREATE UNIQUE INDEX IF NOT EXISTS "__zeroship_workflow_propagation_pages_scope_key" ON "__zeroship_workflow_schema"."__zeroship_workflow_propagation_pages" ("app_id", "id");
INSERT INTO "__zeroship_workflow_schema".__zeroship_workflow_schema_version (id, version, fingerprint) VALUES ('workflow', 1, '067e70fe01ded0834566813e972b508009d46453110553f96ae72e361523b3ef');
