//! PostgreSQL DDL emission, moved verbatim from the engine.

use zero_migrate_backend::ddl::{
    default_clause, fk_local_columns, fk_policy_tail, fk_referenced_columns, fk_target_table,
    generated_clause, inline_checks_clause, inline_pk_for_column, render_index_order_suffix,
    should_render_table_pk, CreateTableRequest, DdlEmitter,
};
use zero_migrate_backend::schema::SchemaRenderer;
use zero_migrate_backend::snapshot::{
    ColumnSnapshot, ConstraintSnapshot, IndexElementSnapshot, IndexSnapshot,
};
use zero_migrate_ir::dialect::DialectId;
use zero_migrate_ir::ir::{
    IndexStorageParams, PartitionBoundValue, PartitionBounds, PartitionSpec,
};

// This module's vendor identity, read from the crate's ONE declaration of it.
use crate::DIALECT;

fn quote_ident(ident: &str) -> String {
    crate::schema::RENDERER.quote_ident(ident)
}

pub(super) fn emitter(project_schema: &str) -> Box<dyn DdlEmitter> {
    Box::new(PgEmitter {
        project_schema: project_schema.to_string(),
    })
}

fn pg_identity_clause(c: &ColumnSnapshot) -> String {
    match c.identity {
        Some(identity) if identity.always => " GENERATED ALWAYS AS IDENTITY".to_string(),
        Some(_) => " GENERATED BY DEFAULT AS IDENTITY".to_string(),
        None => String::new(),
    }
}

fn primary_key_clause(inline_pk: bool) -> &'static str {
    if inline_pk {
        " PRIMARY KEY"
    } else {
        ""
    }
}

fn null_clause(c: &ColumnSnapshot) -> &'static str {
    if c.nullable {
        ""
    } else {
        " NOT NULL"
    }
}

fn render_index_elements_pg(idx: &IndexSnapshot, opclass_suffix: &str) -> String {
    let elements = if idx.elements.is_empty() {
        idx.columns
            .iter()
            .map(|c| IndexElementSnapshot::column(c.clone()))
            .collect::<Vec<_>>()
    } else {
        idx.elements.clone()
    };
    elements
        .iter()
        .map(|element| match element {
            IndexElementSnapshot::Column {
                name,
                order,
                opclass,
                collation,
            } => {
                // PG index-element grammar: `column [COLLATE "c"] [opclass] [ASC|DESC]`.
                // A per-element opclass overrides the index-level `opclass_suffix`
                // (the ANN metric opclass); COLLATE precedes the operator class.
                let collate = collation
                    .as_deref()
                    .map(|c| format!(" COLLATE {}", quote_ident(c)))
                    .unwrap_or_default();
                let opclass = opclass
                    .as_deref()
                    .map(|oc| format!(" {oc}"))
                    .unwrap_or_else(|| opclass_suffix.to_string());
                format!(
                    "{}{collate}{opclass}{}",
                    quote_ident(name),
                    render_index_order_suffix(*order)
                )
            }
            IndexElementSnapshot::Expr(expr) => format!("({expr})"),
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_ident_list_pg(cols: &[String]) -> String {
    cols.iter()
        .map(|c| quote_ident(c))
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_partition_spec_pg(spec: &PartitionSpec) -> String {
    let (kind, columns) = match spec {
        PartitionSpec::Range { columns, .. } => ("RANGE", columns),
        PartitionSpec::List { columns, .. } => ("LIST", columns),
        PartitionSpec::Hash { columns, .. } => ("HASH", columns),
    };
    format!(" PARTITION BY {kind} ({})", render_ident_list_pg(columns))
}

fn normalize_timestamptz_bound_literal(value: &str) -> String {
    let mut out = value.to_string();
    if out.len() >= 20
        && out.as_bytes().get(4) == Some(&b'-')
        && out.as_bytes().get(7) == Some(&b'-')
        && out
            .as_bytes()
            .get(10)
            .is_some_and(|b| *b == b'T' || *b == b' ')
    {
        out = out.replace('T', " ");
        if let Some(stripped) = out.strip_suffix('Z') {
            out = format!("{stripped}+00");
        }
        if let Some(stripped) = out.strip_suffix("+00:00") {
            out = format!("{stripped}+00");
        }
        if let Some(stripped) = out.strip_suffix(".000+00") {
            out = format!("{stripped}+00");
        }
    }
    out
}

fn render_partition_bound_value_pg(value: &PartitionBoundValue) -> String {
    match value {
        PartitionBoundValue::String { value } => {
            let normalized = normalize_timestamptz_bound_literal(value);
            format!("'{}'", normalized.replace('\'', "''"))
        }
        PartitionBoundValue::Int { value } => value.get().to_string(),
        PartitionBoundValue::MinValue => "MINVALUE".to_string(),
        PartitionBoundValue::MaxValue => "MAXVALUE".to_string(),
    }
}

fn render_partition_bound_values_pg(values: &[PartitionBoundValue]) -> String {
    values
        .iter()
        .map(render_partition_bound_value_pg)
        .collect::<Vec<_>>()
        .join(", ")
}

fn render_partition_bounds_pg(bounds: &PartitionBounds) -> String {
    match bounds {
        PartitionBounds::Range { from, to } => format!(
            "FOR VALUES FROM ({}) TO ({})",
            render_partition_bound_values_pg(from),
            render_partition_bound_values_pg(to),
        ),
        PartitionBounds::List { values } => {
            format!(
                "FOR VALUES IN ({})",
                render_partition_bound_values_pg(values)
            )
        }
        PartitionBounds::Hash { modulus, remainder } => {
            format!("FOR VALUES WITH (MODULUS {modulus}, REMAINDER {remainder})")
        }
        PartitionBounds::Default => "DEFAULT".to_string(),
    }
}

fn render_index_include_pg(include: &[String]) -> String {
    if include.is_empty() {
        String::new()
    } else {
        format!(" INCLUDE ({})", render_ident_list_pg(include))
    }
}

fn render_index_storage_params_pg(params: &IndexStorageParams) -> String {
    let mut entries = Vec::new();
    if let Some(pages_per_range) = params.pages_per_range {
        entries.push(format!("pages_per_range='{pages_per_range}'"));
    }
    if let Some(fillfactor) = params.fillfactor {
        entries.push(format!("fillfactor='{fillfactor}'"));
    }
    if entries.is_empty() {
        String::new()
    } else {
        format!(" WITH ({})", entries.join(", "))
    }
}

fn fk_ddl_local_cols(cols: &[String]) -> String {
    cols.iter()
        .map(|c| quote_ident(c))
        .collect::<Vec<_>>()
        .join(", ")
}

fn fk_ddl_referenced_cols(cols: &[String]) -> String {
    cols.iter()
        .map(|c| {
            if c == "id" {
                "id".to_string()
            } else {
                quote_ident(c)
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Postgres DDL emitter — schema-qualified, access-method / `WITH`-aware, with
/// trailing `COMMENT ON COLUMN` sentinels. Holds the project schema for
/// qualification. Byte-identical to the former PG arm of each render method.
struct PgEmitter {
    project_schema: String,
}

impl PgEmitter {
    /// Render `<schema>.<object>`, both parts quoted. (Was `DeclarativeAuthor::qualified`.)
    fn qualified(&self, object: &str) -> String {
        format!(
            "{}.{}",
            quote_ident(&self.project_schema),
            quote_ident(object)
        )
    }

    /// Render a `CONSTRAINT … FOREIGN KEY (…) REFERENCES <schema>.<tgt> (…)
    /// [<policy>]` clause for inline `CREATE TABLE` / `ALTER … ADD CONSTRAINT` use.
    /// (Was the non-MySQL branch of `DeclarativeAuthor::fk_clause`, moved VERBATIM.)
    ///
    /// The `ON UPDATE` / `ON DELETE` / `DEFERRABLE` policy tail is carried in the
    /// constraint `definition` (built by `fk_definition_for_dialect` in the dialect
    /// canonical spelling) and appended verbatim, so the applied constraint
    /// introspects back to the identical definition and the FK round-trips clean.
    fn fk_clause(&self, fk: &ConstraintSnapshot) -> String {
        let cols = fk_local_columns(&fk.definition);
        let target = fk_target_table(&fk.definition).unwrap_or_default();
        let ref_cols = fk_referenced_columns(&fk.definition);
        let policy = fk_policy_tail(&fk.definition);
        format!(
            "CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({}){}",
            quote_ident(&fk.name),
            fk_ddl_local_cols(&cols),
            self.qualified(&target),
            fk_ddl_referenced_cols(&ref_cols),
            policy,
        )
    }

    /// The PG `COMMENT ON COLUMN` sentinel statement, or `None`. (Was
    /// `DeclarativeAuthor::comment_stmt`, moved VERBATIM.)
    fn comment_stmt(&self, table: &str, c: &ColumnSnapshot) -> Option<String> {
        let sentinel = c.comment_sentinel.as_deref()?;
        let escaped = sentinel.replace('\'', "''");
        Some(format!(
            "COMMENT ON COLUMN {}.{} IS '{}'",
            self.qualified(table),
            quote_ident(&c.name),
            escaped,
        ))
    }
}

impl DdlEmitter for PgEmitter {
    fn dialect(&self) -> DialectId {
        DIALECT
    }

    fn fk_clause(&self, fk: &ConstraintSnapshot) -> String {
        PgEmitter::fk_clause(self, fk)
    }

    fn alter_table_ref(&self, table: &str) -> String {
        self.qualified(table)
    }

    fn drop_foreign_key_up(&self, table: &str, name: &str) -> Option<String> {
        Some(format!(
            "ALTER TABLE {} DROP CONSTRAINT {}",
            self.qualified(table),
            quote_ident(name),
        ))
    }

    /// The `USING <col>::<type>` cast is emitted so a compatible widening (e.g.
    /// `integer` → `double precision`) applies without a manual cast; an
    /// incompatible change still fails loudly at apply (never silently).
    ///
    /// A GENERATED column takes NO `USING`, and this is the server's rule rather
    /// than a preference. MEASURED on PostgreSQL 18.4: the cast this statement used
    /// to attach unconditionally is answered with `cannot specify USING when
    /// altering type of generated column` — for `int → bigint` as much as for
    /// anything else, so the clause made even the otherwise-legal widening
    /// undeployable. WITHOUT it the same `ALTER` is ACCEPTED and
    /// `pg_attribute.attgenerated` survives: the server recomputes the expression
    /// under the new type, which is exactly why it will not take a cast of the old
    /// value. `cast_value` is core's answer to that question.
    fn alter_column_type_up(
        &self,
        table: &str,
        column: &str,
        ty: &str,
        cast_value: bool,
    ) -> Option<String> {
        let using = if cast_value {
            format!(" USING {}::{}", quote_ident(column), ty)
        } else {
            String::new()
        };
        Some(format!(
            "ALTER TABLE {} ALTER COLUMN {} TYPE {}{}",
            self.qualified(table),
            quote_ident(column),
            ty,
            using,
        ))
    }

    fn alter_column_nullability(
        &self,
        table: &str,
        column: &str,
        nullable: bool,
    ) -> Option<(String, String)> {
        let (verb, reverse) = if nullable {
            ("DROP NOT NULL", "SET NOT NULL")
        } else {
            ("SET NOT NULL", "DROP NOT NULL")
        };
        Some((
            format!(
                "ALTER TABLE {} ALTER COLUMN {} {}",
                self.qualified(table),
                quote_ident(column),
                verb
            ),
            format!(
                "ALTER TABLE {} ALTER COLUMN {} {}",
                self.qualified(table),
                quote_ident(column),
                reverse
            ),
        ))
    }

    fn alter_column_default(
        &self,
        table: &str,
        column: &str,
        default_sql: Option<&str>,
    ) -> Option<String> {
        let (table_ref, col_ref) = (self.qualified(table), quote_ident(column));
        let action = match default_sql {
            Some(default_sql) => format!("SET DEFAULT {default_sql}"),
            None => "DROP DEFAULT".to_string(),
        };
        Some(format!(
            "ALTER TABLE {table_ref} ALTER COLUMN {col_ref} {action}"
        ))
    }

    fn indexes_inlined_by_create(&self, _req: &CreateTableRequest<'_>) -> Vec<String> {
        Vec::new()
    }

    fn create_table(&self, req: &CreateTableRequest<'_>) -> Vec<String> {
        let (table, t) = (req.table, req.snapshot);
        let mut parts: Vec<String> = Vec::new();
        for c in &t.columns {
            let inline_pk = inline_pk_for_column(&crate::fold::POLICY, table, t, &c.name);
            let ty = crate::schema::RENDERER.column_type(c, inline_pk);
            let pk = primary_key_clause(inline_pk);
            let null = null_clause(c);
            let identity = pg_identity_clause(c);
            let generated = generated_clause(c.generated.as_ref());
            // emit the DEFAULT clause (emission-only metadata), including the
            // legacy `__fts` generated-column sentinel path.
            let default = default_clause(c.default.as_deref());
            let checks = inline_checks_clause(c);
            // the inline `/* zero-migrate:enc:… */` sentinel rides between
            // the type and the constraints, exactly as the shared kernel's
            // `field_to_column_for_dialect` bakes it, so a `generate`d encrypted
            // column is byte-identical to a `registerModel`-created one.
            let enc = c
                .encryption_sentinel
                .as_deref()
                .map(|s| format!(" {s}"))
                .unwrap_or_default();
            parts.push(format!(
                "{} {}{}{}{}{}{}{}{}",
                quote_ident(&c.name),
                ty,
                enc,
                identity,
                generated,
                pk,
                null,
                default,
                checks,
            ));
        }
        for fk in req.inline_fks {
            parts.push(self.fk_clause(fk));
        }
        // inline CHECK constraints (literal-pin, min/max, enum) as
        // table-level `CONSTRAINT <name> CHECK (...)` clauses. The definition is
        // the emitted DDL clause built by `field_check_constraints`.
        //
        // a `createTable({ uniques })` table-level UNIQUE
        // (folded into the snapshot as a `UNIQUE` `ConstraintSnapshot` by
        // `render::lower::create_table_descriptor`'s spec-fold) is inlined here as a
        // `CONSTRAINT <name> <definition>` clause, the SAME shape a stand-alone
        // `addConstraint(unique)` renders (`UNIQUE (cols)`), so a table built with
        // a named unique round-trips against the live catalog. CHECK is inlined the
        // same way; both are emission-only bodies the differ does not re-diff.
        for c in &t.constraints {
            if should_render_table_pk(&crate::fold::POLICY, table, t, c)
                || c.kind == "CHECK"
                || c.kind == "UNIQUE"
                || c.kind == "EXCLUDE"
            {
                parts.push(format!(
                    "CONSTRAINT {} {}",
                    quote_ident(&c.name),
                    c.definition
                ));
            }
        }
        let partition = t
            .partition_by
            .as_ref()
            .map(render_partition_spec_pg)
            .unwrap_or_default();
        let create = format!(
            "CREATE TABLE {} ({}){}",
            self.qualified(table),
            parts.join(", "),
            partition,
        );
        let mut statements: Vec<String> = vec![create];
        // append `COMMENT ON COLUMN … '<sentinel>'` for every
        // column carrying a comment sentinel (`zero-migrate:mask:…` on a masked sibling,
        // `zero-migrate:enc:…` on an encrypted column), so the runtime sentinel is part of
        // the same migration as the table create (an interrupted apply never
        // leaves a column without its sentinel). The comment body is built by
        // the shared codecs; we only quote it into the statement here. Each
        // COMMENT is its OWN structural statement (a guard-per-statement unit),
        // not a textual `;\n` split of the joined `up`.
        for c in &t.columns {
            if let Some(stmt) = self.comment_stmt(table, c) {
                statements.push(stmt);
            }
        }
        statements
    }

    fn add_column(&self, table: &str, c: &ColumnSnapshot) -> (Vec<String>, Option<String>) {
        let inline_pk = false;
        let null = null_clause(c);
        let generated = generated_clause(c.generated.as_ref());
        let default = default_clause(c.default.as_deref());
        let identity = pg_identity_clause(c);
        let checks = inline_checks_clause(c);
        let enc = c
            .encryption_sentinel
            .as_deref()
            .map(|s| format!(" {s}"))
            .unwrap_or_default();
        let table_ref = self.qualified(table);
        let add = format!(
            "ALTER TABLE {} ADD COLUMN {} {}{}{}{}{}{}{}",
            table_ref,
            quote_ident(&c.name),
            crate::schema::RENDERER.column_type(c, inline_pk),
            enc,
            identity,
            generated,
            null,
            default,
            checks,
        );
        let mut up: Vec<String> = vec![add];
        // (PG only) — a column added via ADD COLUMN carries its comment
        // sentinel (`zero-migrate:mask:…` for a masked sibling, `zero-migrate:enc:…` for an
        // encrypted column) in the same migration (atomic with the column), as its
        // OWN structural statement.
        if let Some(stmt) = self.comment_stmt(table, c) {
            up.push(stmt);
        }
        let down = format!(
            "ALTER TABLE {} DROP COLUMN {}",
            table_ref,
            quote_ident(&c.name)
        );
        (up, Some(down))
    }

    fn create_index(&self, table: &str, idx: &IndexSnapshot) -> (String, String) {
        let unique = if idx.unique { "UNIQUE " } else { "" };
        // - `USING <method>` for a non-btree index (GIN over the `__fts`
        // tsvector, ivfflat/hnsw over a vector column). A btree index omits the
        // clause (PG's default), so existing btree indexes are byte-unchanged.
        let using = if idx.access_method == "btree" {
            String::new()
        } else {
            format!(" USING {}", idx.access_method)
        };
        // Per-column operator class for an ANN index (`"col" vector_cosine_ops`).
        let opclass_suffix = idx
            .opclass
            .as_deref()
            .map(|oc| format!(" {oc}"))
            .unwrap_or_default();
        let col_list = render_index_elements_pg(idx, &opclass_suffix);
        let include_clause = render_index_include_pg(&idx.include);
        // PG 15+ `NULLS NOT DISTINCT` sits after INCLUDE and before WITH, and is
        // only meaningful on a UNIQUE index. Absent ⇒ byte-identical to before.
        let nulls_not_distinct_clause = if idx.nulls_not_distinct {
            " NULLS NOT DISTINCT"
        } else {
            ""
        };
        let with_clause = if let Some(params) = &idx.with {
            render_index_storage_params_pg(params)
        } else if idx.access_method == "ivfflat" {
            " WITH (lists = 100)".to_string()
        } else {
            String::new()
        };
        let only = if idx.only { "ONLY " } else { "" };
        (
            format!(
                "CREATE {unique}INDEX IF NOT EXISTS {} ON {only}{}{using} ({col_list}){}{}{}{}",
                quote_ident(&idx.name),
                self.qualified(table),
                include_clause,
                nulls_not_distinct_clause,
                with_clause,
                idx.predicate
                    .as_deref()
                    .map(|p| format!(" WHERE {p}"))
                    .unwrap_or_default(),
            ),
            format!("DROP INDEX IF EXISTS {}", self.qualified(&idx.name)),
        )
    }

    fn drop_table_up(&self, table: &str) -> String {
        format!("DROP TABLE {}", self.qualified(table))
    }

    fn rename_table(&self, table: &str, to: &str) -> (String, String) {
        // The SOURCE table is schema-qualified; the TARGET is a BARE name (PG
        // rejects a schema-qualified RENAME TARGET — the table stays in its schema).
        (
            format!(
                "ALTER TABLE {} RENAME TO {}",
                self.qualified(table),
                quote_ident(to)
            ),
            // Inverse rename: the table now lives under `to`, rename it back.
            format!(
                "ALTER TABLE {} RENAME TO {}",
                self.qualified(to),
                quote_ident(table)
            ),
        )
    }

    fn drop_column_up(&self, table: &str, col: &str) -> String {
        format!(
            "ALTER TABLE {} DROP COLUMN {}",
            self.qualified(table),
            quote_ident(col)
        )
    }

    fn drop_index_up(&self, _table: Option<&str>, idx_name: &str) -> String {
        format!("DROP INDEX {}", self.qualified(idx_name))
    }

    fn create_partition(
        &self,
        name: &str,
        of: &str,
        bounds: &PartitionBounds,
    ) -> Option<(String, String)> {
        let up = format!(
            "CREATE TABLE {} PARTITION OF {} {}",
            self.qualified(name),
            self.qualified(of),
            render_partition_bounds_pg(bounds),
        );
        let down = format!("DROP TABLE {}", self.qualified(name));
        Some((up, down))
    }

    fn attach_partition(
        &self,
        parent: &str,
        name: &str,
        bound: &PartitionBounds,
    ) -> Option<(String, String)> {
        let up = format!(
            "ALTER TABLE {} ATTACH PARTITION {} {}",
            self.qualified(parent),
            self.qualified(name),
            render_partition_bounds_pg(bound),
        );
        let down = format!(
            "ALTER TABLE {} DETACH PARTITION {}",
            self.qualified(parent),
            self.qualified(name),
        );
        Some((up, down))
    }

    fn detach_partition(&self, parent: &str, name: &str, concurrently: bool) -> Option<String> {
        let concurrently = if concurrently { " CONCURRENTLY" } else { "" };
        let up = format!(
            "ALTER TABLE {} DETACH PARTITION {}{}",
            self.qualified(parent),
            self.qualified(name),
            concurrently,
        );
        Some(up)
    }

    fn drop_partition(&self, name: &str, cascade: bool) -> Option<String> {
        let cascade = if cascade { " CASCADE" } else { "" };
        let up = format!("DROP TABLE {}{}", self.qualified(name), cascade);
        Some(up)
    }
}
